// Code generated by gen-tags. DO NOT EDIT.

package tags

// AFCPMainTags contains tag definitions from Image::ExifTool::AFCP
var AFCPMainTags = TagTable{
	ModuleName: "AFCP",
	Tags: map[string]TagDef{
		"IPTC": {
			ID:          "IPTC",
		},
		"TEXT": {
			ID:          "TEXT",
			Name:        "Text",
		},
	},
}
