// Code generated by gen-tags. DO NOT EDIT.

package tags

// AIFFCommentTags contains tag definitions from Image::ExifTool::AIFF
var AIFFCommentTags = TagTable{
	ModuleName: "AIFF",
	Tags: map[string]TagDef{
		"0": {
			ID:          "0",
		},
		"1": {
			ID:          "1",
			Name:        "MarkerID",
		},
	},
}
