// Code generated by gen-tags. DO NOT EDIT.

package tags

// AIFFCompositeTags contains tag definitions from Image::ExifTool::AIFF
var AIFFCompositeTags = TagTable{
	ModuleName: "AIFF",
	Tags: map[string]TagDef{
	},
}
