// Code generated by gen-tags. DO NOT EDIT.

package tags

// APENewHeaderTags contains tag definitions from Image::ExifTool::APE
var APENewHeaderTags = TagTable{
	ModuleName: "APE",
	Tags: map[string]TagDef{
		"8": {
			ID:          "8",
			Name:        "BitsPerSample",
		},
		"9": {
			ID:          "9",
			Name:        "Channels",
		},
		"10": {
			ID:          "10",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int16u",
		},
		"0": {
			ID:          "0",
			Name:        "CompressionLevel",
		},
		"2": {
			ID:          "2",
		},
		"4": {
			ID:          "4",
		},
		"6": {
			ID:          "6",
		},
	},
}
