// Code generated by gen-tags. DO NOT EDIT.

package tags

// APECompositeTags contains tag definitions from Image::ExifTool::APE
var APECompositeTags = TagTable{
	ModuleName: "APE",
	Tags: map[string]TagDef{
	},
}
