// Code generated by gen-tags. DO NOT EDIT.

package tags

// APEMainTags contains tag definitions from Image::ExifTool::APE
var APEMainTags = TagTable{
	ModuleName: "APE",
	Tags: map[string]TagDef{
		"Title": {
			ID:          "Title",
		},
		"Track": {
			ID:          "Track",
		},
		"Year": {
			ID:          "Year",
		},
		"Tool Version": {
			ID:          "Tool Version",
		},
		"Tool Name": {
			ID:          "Tool Name",
		},
		"Album": {
			ID:          "Album",
		},
		"Artist": {
			ID:          "Artist",
		},
		"Genre": {
			ID:          "Genre",
		},
	},
}
