// Code generated by gen-tags. DO NOT EDIT.

package tags

// ArabicArabicTags contains tag definitions from 
var ArabicArabicTags = TagTable{
	ModuleName: "Arabic",
	Tags: map[string]TagDef{
		"0xDD": {
			ID:          "0xDD",
		},
		"0xF2": {
			ID:          "0xF2",
		},
		"0xF8": {
			ID:          "0xF8",
		},
		"0x88": {
			ID:          "0x88",
		},
		"0xC0": {
			ID:          "0xC0",
		},
		"0xD4": {
			ID:          "0xD4",
		},
		"0xEC": {
			ID:          "0xEC",
		},
		"0xFF": {
			ID:          "0xFF",
		},
		"0x80": {
			ID:          "0x80",
		},
		"0x84": {
			ID:          "0x84",
		},
		"0x9C": {
			ID:          "0x9C",
		},
		"0xA1": {
			ID:          "0xA1",
		},
		"0xC4": {
			ID:          "0xC4",
		},
		"0xD0": {
			ID:          "0xD0",
		},
		"0x8C": {
			ID:          "0x8C",
		},
		"0x90": {
			ID:          "0x90",
		},
		"0x98": {
			ID:          "0x98",
		},
		"0xC8": {
			ID:          "0xC8",
		},
		"0xE3": {
			ID:          "0xE3",
		},
		"0x94": {
			ID:          "0x94",
		},
		"0xCC": {
			ID:          "0xCC",
		},
		"0xD9": {
			ID:          "0xD9",
		},
	},
}
