// Code generated by gen-tags. DO NOT EDIT.

package tags

// ASFPictureTags contains tag definitions from Image::ExifTool::ASF
var ASFPictureTags = TagTable{
	ModuleName: "ASF",
	Tags: map[string]TagDef{
		"1": {
			ID:          "1",
			Name:        "PictureMIMEType",
		},
		"2": {
			ID:          "2",
			Name:        "PictureDescription",
		},
	},
}
