// Code generated by gen-tags. DO NOT EDIT.

package tags

// ASFCodecListTags contains tag definitions from Image::ExifTool::ASF
var ASFCodecListTags = TagTable{
	ModuleName: "ASF",
	Tags: map[string]TagDef{
		"VideoCodecDescription": {
			ID:          "VideoCodecDescription",
		},
		"AudioCodecName": {
			ID:          "AudioCodecName",
		},
		"AudioCodecDescription": {
			ID:          "AudioCodecDescription",
		},
		"OtherCodecName": {
			ID:          "OtherCodecName",
		},
		"OtherCodecDescription": {
			ID:          "OtherCodecDescription",
		},
		"VideoCodecName": {
			ID:          "VideoCodecName",
		},
	},
}
