// Code generated by gen-tags. DO NOT EDIT.

package tags

// ASFStreamPropertiesTags contains tag definitions from Image::ExifTool::ASF
var ASFStreamPropertiesTags = TagTable{
	ModuleName: "ASF",
	Tags: map[string]TagDef{
	},
}
