// Code generated by gen-tags. DO NOT EDIT.

package tags

// ASFContentBrandingTags contains tag definitions from Image::ExifTool::ASF
var ASFContentBrandingTags = TagTable{
	ModuleName: "ASF",
	Tags: map[string]TagDef{
		"1": {
			ID:          "1",
		},
		"2": {
			ID:          "2",
			Name:        "BannerImageURL",
		},
		"3": {
			ID:          "3",
			Name:        "CopyrightURL",
		},
	},
}
