// Code generated by gen-tags. DO NOT EDIT.

package tags

// ASFExtendedDescrTags contains tag definitions from Image::ExifTool::ASF
var ASFExtendedDescrTags = TagTable{
	ModuleName: "ASF",
	Tags: map[string]TagDef{
		"UniqueFileIdentifier": {
			ID:          "UniqueFileIdentifier",
		},
		"DRM_DRMHeader_KeyID": {
			ID:          "DRM_DRMHeader_KeyID",
		},
		"AudioFileURL": {
			ID:          "AudioFileURL",
		},
		"MediaIsFinale": {
			ID:          "MediaIsFinale",
		},
		"VideoClosedCaptioning": {
			ID:          "VideoClosedCaptioning",
		},
		"MediaClassPrimaryID": {
			ID:          "MediaClassPrimaryID",
		},
		"Can_Skip_Forward": {
			ID:          "Can_Skip_Forward",
		},
		"HasImage": {
			ID:          "HasImage",
		},
		"Is_Trusted": {
			ID:          "Is_Trusted",
		},
		"NSC_Phone": {
			ID:          "NSC_Phone",
		},
		"Signature_Name": {
			ID:          "Signature_Name",
		},
		"ISRC": {
			ID:          "ISRC",
		},
		"ParentalRatingReason": {
			ID:          "ParentalRatingReason",
		},
		"DRM_ContentID": {
			ID:          "DRM_ContentID",
		},
		"DRM_LASignatureRootCert": {
			ID:          "DRM_LASignatureRootCert",
		},
		"DRM_V1LicenseAcqURL": {
			ID:          "DRM_V1LicenseAcqURL",
		},
		"Stridable": {
			ID:          "Stridable",
		},
		"AlbumCoverURL": {
			ID:          "AlbumCoverURL",
		},
		"SubscriptionContentID": {
			ID:          "SubscriptionContentID",
		},
		"WMCollectionGroupID": {
			ID:          "WMCollectionGroupID",
		},
		"NSC_Description": {
			ID:          "NSC_Description",
		},
		"PeakBitrate": {
			ID:          "PeakBitrate",
		},
		"Provider": {
			ID:          "Provider",
		},
		"ProviderStyle": {
			ID:          "ProviderStyle",
		},
		"ModifiedBy": {
			ID:          "ModifiedBy",
		},
		"Can_Skip_Backward": {
			ID:          "Can_Skip_Backward",
		},
		"HasAttachedImages": {
			ID:          "HasAttachedImages",
		},
		"AlbumArtist": {
			ID:          "AlbumArtist",
		},
		"AlbumTitle": {
			ID:          "AlbumTitle",
		},
		"Author": {
			ID:          "Author",
		},
		"DVDID": {
			ID:          "DVDID",
		},
		"MediaOriginalChannel": {
			ID:          "MediaOriginalChannel",
		},
		"MediaStationCallSign": {
			ID:          "MediaStationCallSign",
		},
		"OriginalArtist": {
			ID:          "OriginalArtist",
		},
		"StreamTypeInfo": {
			ID:          "StreamTypeInfo",
		},
		"UserWebURL": {
			ID:          "UserWebURL",
		},
		"AspectRatioX": {
			ID:          "AspectRatioX",
		},
		"AspectRatioY": {
			ID:          "AspectRatioY",
		},
		"MediaClassSecondaryID": {
			ID:          "MediaClassSecondaryID",
		},
		"RadioStationName": {
			ID:          "RadioStationName",
		},
		"SubTitle": {
			ID:          "SubTitle",
			Name:        "Subtitle",
		},
		"ASFSecurityObjectsSize": {
			ID:          "ASFSecurityObjectsSize",
		},
		"ContentGroupDescription": {
			ID:          "ContentGroupDescription",
		},
		"DRM": {
			ID:          "DRM",
		},
		"MediaIsPremiere": {
			ID:          "MediaIsPremiere",
		},
		"Text": {
			ID:          "Text",
		},
		"WMContentID": {
			ID:          "WMContentID",
		},
		"Seekable": {
			ID:          "Seekable",
		},
		"BannerImageType": {
			ID:          "BannerImageType",
		},
		"NSC_Address": {
			ID:          "NSC_Address",
		},
		"VBRPeak": {
			ID:          "VBRPeak",
		},
		"MediaIsRepeat": {
			ID:          "MediaIsRepeat",
		},
		"Track": {
			ID:          "Track",
		},
		"Bitrate": {
			ID:          "Bitrate",
		},
		"NumberOfFrames": {
			ID:          "NumberOfFrames",
		},
		"Writer": {
			ID:          "Writer",
		},
		"Rating": {
			ID:          "Rating",
		},
		"Copyright": {
			ID:          "Copyright",
		},
		"CopyrightURL": {
			ID:          "CopyrightURL",
		},
		"Title": {
			ID:          "Title",
		},
		"TrackNumber": {
			ID:          "TrackNumber",
		},
		"VideoWidth": {
			ID:          "VideoWidth",
		},
		"HasArbitraryDataStream": {
			ID:          "HasArbitraryDataStream",
		},
		"HasFileTransferStream": {
			ID:          "HasFileTransferStream",
		},
		"InitialKey": {
			ID:          "InitialKey",
		},
		"MediaIsSAP": {
			ID:          "MediaIsSAP",
		},
		"OriginalFilename": {
			ID:          "OriginalFilename",
			Name:        "OriginalFileName",
		},
		"DRM_DRMHeader_IndividualizedVersion": {
			ID:          "DRM_DRMHeader_IndividualizedVersion",
		},
		"MediaStationName": {
			ID:          "MediaStationName",
		},
		"OriginalAlbumTitle": {
			ID:          "OriginalAlbumTitle",
		},
		"ToolName": {
			ID:          "ToolName",
		},
		"DRM_DRMHeader_SubscriptionContentID": {
			ID:          "DRM_DRMHeader_SubscriptionContentID",
		},
		"HasAudio": {
			ID:          "HasAudio",
		},
		"PeakValue": {
			ID:          "PeakValue",
		},
		"MediaIsLive": {
			ID:          "MediaIsLive",
		},
		"Producer": {
			ID:          "Producer",
		},
		"BannerImageURL": {
			ID:          "BannerImageURL",
		},
		"DRM_DRMHeader_LicenseAcqURL": {
			ID:          "DRM_DRMHeader_LicenseAcqURL",
		},
		"AuthorURL": {
			ID:          "AuthorURL",
		},
		"Composer": {
			ID:          "Composer",
		},
		"OriginalLyricist": {
			ID:          "OriginalLyricist",
		},
		"SubTitleDescription": {
			ID:          "SubTitleDescription",
			Name:        "SubtitleDescription",
		},
		"WMCollectionID": {
			ID:          "WMCollectionID",
		},
		"ParentalRating": {
			ID:          "ParentalRating",
		},
		"RadioStationOwner": {
			ID:          "RadioStationOwner",
		},
		"VideoFrameRate": {
			ID:          "VideoFrameRate",
		},
		"ASFLeakyBucketPairs": {
			ID:          "ASFLeakyBucketPairs",
		},
		"BannerImageData": {
			ID:          "BannerImageData",
		},
		"CurrentBitrate": {
			ID:          "CurrentBitrate",
		},
		"Duration": {
			ID:          "Duration",
		},
		"FileSize": {
			ID:          "FileSize",
		},
		"IsVBR": {
			ID:          "IsVBR",
		},
		"MediaIsStereo": {
			ID:          "MediaIsStereo",
		},
		"MediaIsTape": {
			ID:          "MediaIsTape",
		},
		"BufferAverage": {
			ID:          "BufferAverage",
		},
		"DRM_DRMHeader_ContentDistributor": {
			ID:          "DRM_DRMHeader_ContentDistributor",
		},
		"Lyrics_Synchronised": {
			ID:          "Lyrics_Synchronised",
		},
		"ProtectionType": {
			ID:          "ProtectionType",
		},
		"Year": {
			ID:          "Year",
		},
		"DRM_LicenseAcqURL": {
			ID:          "DRM_LicenseAcqURL",
		},
		"NSC_Email": {
			ID:          "NSC_Email",
		},
		"ASFPacketCount": {
			ID:          "ASFPacketCount",
		},
		"Conductor": {
			ID:          "Conductor",
		},
		"ProviderCopyright": {
			ID:          "ProviderCopyright",
		},
		"NSC_Name": {
			ID:          "NSC_Name",
		},
		"OptimalBitrate": {
			ID:          "OptimalBitrate",
		},
		"Genre": {
			ID:          "Genre",
		},
		"Publisher": {
			ID:          "Publisher",
		},
		"WMADRCPeakReference": {
			ID:          "WMADRCPeakReference",
		},
		"HasScript": {
			ID:          "HasScript",
		},
		"HasVideo": {
			ID:          "HasVideo",
		},
		"GenreID": {
			ID:          "GenreID",
		},
		"WMADRCPeakTarget": {
			ID:          "WMADRCPeakTarget",
		},
		"AudioSourceURL": {
			ID:          "AudioSourceURL",
		},
		"ContainerFormat": {
			ID:          "ContainerFormat",
		},
		"ContentDistributor": {
			ID:          "ContentDistributor",
		},
		"Lyrics": {
			ID:          "Lyrics",
		},
		"Description": {
			ID:          "Description",
		},
		"DRM_KeyID": {
			ID:          "DRM_KeyID",
		},
		"DRM_LASignatureCert": {
			ID:          "DRM_LASignatureCert",
		},
		"DRM_LASignatureLicSrvCert": {
			ID:          "DRM_LASignatureLicSrvCert",
		},
		"BeatsPerMinute": {
			ID:          "BeatsPerMinute",
		},
		"EncodingTime": {
			ID:          "EncodingTime",
		},
		"MCDI": {
			ID:          "MCDI",
		},
		"MediaCredits": {
			ID:          "MediaCredits",
		},
		"OriginalReleaseYear": {
			ID:          "OriginalReleaseYear",
		},
		"VideoHeight": {
			ID:          "VideoHeight",
		},
		"DRM_IndividualizedVersion": {
			ID:          "DRM_IndividualizedVersion",
		},
		"Language": {
			ID:          "Language",
		},
		"Period": {
			ID:          "Period",
		},
		"AverageLevel": {
			ID:          "AverageLevel",
		},
		"Broadcast": {
			ID:          "Broadcast",
		},
		"Category": {
			ID:          "Category",
		},
		"MediaIsSubtitled": {
			ID:          "MediaIsSubtitled",
		},
		"PlaylistDelay": {
			ID:          "PlaylistDelay",
		},
		"ToolVersion": {
			ID:          "ToolVersion",
		},
		"DRM_DRMHeader": {
			ID:          "DRM_DRMHeader",
		},
		"EncodingSettings": {
			ID:          "EncodingSettings",
		},
		"MediaNetworkAffiliation": {
			ID:          "MediaNetworkAffiliation",
		},
		"Is_Protected": {
			ID:          "Is_Protected",
		},
		"Codec": {
			ID:          "Codec",
		},
		"MediaIsDelay": {
			ID:          "MediaIsDelay",
		},
		"PromotionURL": {
			ID:          "PromotionURL",
		},
		"ProviderRating": {
			ID:          "ProviderRating",
		},
		"WMADRCAverageReference": {
			ID:          "WMADRCAverageReference",
		},
		"Mood": {
			ID:          "Mood",
		},
		"DRM_LASignaturePrivKey": {
			ID:          "DRM_LASignaturePrivKey",
		},
		"EncodedBy": {
			ID:          "EncodedBy",
		},
		"SharedUserRating": {
			ID:          "SharedUserRating",
		},
		"WMADRCAverageTarget": {
			ID:          "WMADRCAverageTarget",
		},
		"DRM_DRMHeader_ContentID": {
			ID:          "DRM_DRMHeader_ContentID",
		},
		"Director": {
			ID:          "Director",
		},
		"PartOfSet": {
			ID:          "PartOfSet",
		},
	},
}
