// Code generated by gen-tags. DO NOT EDIT.

package tags

// AudibletsegTags contains tag definitions from Image::ExifTool::Audible
var AudibletsegTags = TagTable{
	ModuleName: "Audible",
	Tags: map[string]TagDef{
	},
}
