// Code generated by gen-tags. DO NOT EDIT.

package tags

// BMPExtraTags contains tag definitions from Image::ExifTool::BMP
var BMPExtraTags = TagTable{
	ModuleName: "BMP",
	Tags: map[string]TagDef{
		"LinkedProfileName": {
			ID:          "LinkedProfileName",
		},
		"ICC_Profile": {
			ID:          "ICC_Profile",
		},
	},
}
