// Code generated by gen-tags. DO NOT EDIT.

package tags

// BMPOS2Tags contains tag definitions from Image::ExifTool::BMP
var BMPOS2Tags = TagTable{
	ModuleName: "BMP",
	Tags: map[string]TagDef{
		"4": {
			ID:          "4",
		},
		"6": {
			ID:          "6",
		},
		"8": {
			ID:          "8",
		},
		"10": {
			ID:          "10",
		},
	},
}
