// Code generated by gen-tags. DO NOT EDIT.

package tags

// CanonVRDMainTags contains tag definitions from Image::ExifTool::CanonVRD
var CanonVRDMainTags = TagTable{
	ModuleName: "CanonVRD",
	Tags: map[string]TagDef{
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
	},
}
