// Code generated by gen-tags. DO NOT EDIT.

package tags

// CanonCustomFunctionsD30Tags contains tag definitions from Image::ExifTool::CanonCustom
var CanonCustomFunctionsD30Tags = TagTable{
	ModuleName: "CanonCustom",
	Tags: map[string]TagDef{
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"WRITABLE": {
			ID:          "WRITABLE",
			Name:        "int8u",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
	},
}
