// Code generated by gen-tags. DO NOT EDIT.

package tags

// CanonCDI1Tags contains tag definitions from Image::ExifTool::Canon
var CanonCDI1Tags = TagTable{
	ModuleName: "Canon",
	Tags: map[string]TagDef{
		"IAD1": {
			ID:          "IAD1",
		},
	},
}
