// Code generated by gen-tags. DO NOT EDIT.

package tags

// CanonRawRawJpgInfoTags contains tag definitions from Image::ExifTool::CanonRaw
var CanonRawRawJpgInfoTags = TagTable{
	ModuleName: "CanonRaw",
	Tags: map[string]TagDef{
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"WRITABLE": {
			ID:          "WRITABLE",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int16u",
		},
		"3": {
			ID:          "3",
		},
		"4": {
			ID:          "4",
		},
	},
}
