// Code generated by gen-tags. DO NOT EDIT.

package tags

// CanonCameraInfo5DTags contains tag definitions from Image::ExifTool::Canon
var CanonCameraInfo5DTags = TagTable{
	ModuleName: "Canon",
	Tags: map[string]TagDef{
		"0xFA": {
			ID:          "0xFA",
			Name:        "SaturationStandard",
		},
		"0x101": {
			ID:          "0x101",
			Name:        "SaturationUserDef2",
		},
		"0x102": {
			ID:          "0x102",
			Name:        "SaturationUserDef3",
		},
		"0x28": {
			ID:          "0x28",
		},
		"0xF9": {
			ID:          "0xF9",
			Name:        "SharpnessUserDef3",
		},
		"0xFB": {
			ID:          "0xFB",
			Name:        "SaturationPortrait",
		},
		"0x103": {
			ID:          "0x103",
			Name:        "ColorToneStandard",
		},
		"0x03": {
			ID:          "0x03",
		},
		"0x04": {
			ID:          "0x04",
		},
		"0xE8": {
			ID:          "0xE8",
			Name:        "ContrastStandard",
		},
		"0xE9": {
			ID:          "0xE9",
			Name:        "ContrastPortrait",
		},
		"0xED": {
			ID:          "0xED",
			Name:        "ContrastMonochrome",
		},
		"0xF7": {
			ID:          "0xF7",
			Name:        "SharpnessUserDef1",
		},
		"0x100": {
			ID:          "0x100",
			Name:        "SaturationUserDef1",
		},
		"0x107": {
			ID:          "0x107",
			Name:        "ColorToneFaithful",
		},
		"0x06": {
			ID:          "0x06",
		},
		"0x1B": {
			ID:          "0x1B",
		},
		"0xEE": {
			ID:          "0xEE",
			Name:        "ContrastUserDef1",
		},
		"0xEF": {
			ID:          "0xEF",
			Name:        "ContrastUserDef2",
		},
		"0xFE": {
			ID:          "0xFE",
			Name:        "SaturationFaithful",
		},
		"0x10A": {
			ID:          "0x10A",
			Name:        "ColorToneUserDef2",
		},
		"PRIORITY": {
			ID:          "PRIORITY",
		},
		"0xF4": {
			ID:          "0xF4",
			Name:        "SharpnessNeutral",
		},
		"0xFC": {
			ID:          "0xFC",
			Name:        "SaturationLandscape",
		},
		"0xFD": {
			ID:          "0xFD",
			Name:        "SaturationNeutral",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int8s",
		},
		"0xEA": {
			ID:          "0xEA",
			Name:        "ContrastLandscape",
		},
		"0xF1": {
			ID:          "0xF1",
			Name:        "SharpnessStandard",
		},
		"0x105": {
			ID:          "0x105",
			Name:        "ColorToneLandscape",
		},
		"0xEB": {
			ID:          "0xEB",
			Name:        "ContrastNeutral",
		},
		"0xF2": {
			ID:          "0xF2",
			Name:        "SharpnessPortrait",
		},
		"0xF3": {
			ID:          "0xF3",
			Name:        "SharpnessLandscape",
		},
		"0xF6": {
			ID:          "0xF6",
			Name:        "SharpnessMonochrome",
		},
		"0x106": {
			ID:          "0x106",
			Name:        "ColorToneNeutral",
		},
		"0x10B": {
			ID:          "0x10B",
			Name:        "ColorToneUserDef3",
		},
		"0x17": {
			ID:          "0x17",
		},
		"0x93": {
			ID:          "0x93",
		},
		"0x104": {
			ID:          "0x104",
			Name:        "ColorTonePortrait",
		},
		"0x109": {
			ID:          "0x109",
			Name:        "ColorToneUserDef1",
		},
		"0x95": {
			ID:          "0x95",
		},
		"0xEC": {
			ID:          "0xEC",
			Name:        "ContrastFaithful",
		},
		"0xF0": {
			ID:          "0xF0",
			Name:        "ContrastUserDef3",
		},
		"0xF5": {
			ID:          "0xF5",
			Name:        "SharpnessFaithful",
		},
		"0xF8": {
			ID:          "0xF8",
			Name:        "SharpnessUserDef2",
		},
	},
}
