// Code generated by gen-tags. DO NOT EDIT.

package tags

// CanonCameraInfo750DTags contains tag definitions from Image::ExifTool::Canon
var CanonCameraInfo750DTags = TagTable{
	ModuleName: "Canon",
	Tags: map[string]TagDef{
		"0x188": {
			ID:          "0x188",
		},
		"PRIORITY": {
			ID:          "PRIORITY",
		},
		"0x04": {
			ID:          "0x04",
		},
		"0x186": {
			ID:          "0x186",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int8u",
		},
		"0x03": {
			ID:          "0x03",
		},
		"0x06": {
			ID:          "0x06",
		},
		"0x1B": {
			ID:          "0x1B",
		},
		"0x23": {
			ID:          "0x23",
		},
	},
}
