// Code generated by gen-tags. DO NOT EDIT.

package tags

// CanonColorData12Tags contains tag definitions from Image::ExifTool::Canon
var CanonColorData12Tags = TagTable{
	ModuleName: "Canon",
	Tags: map[string]TagDef{
		"0xA0": {
			ID:          "0xA0",
		},
		"0xFA": {
			ID:          "0xFA",
		},
		"0x73": {
			ID:          "0x73",
		},
		"0x90": {
			ID:          "0x90",
		},
		"0x9B": {
			ID:          "0x9B",
		},
		"0xAE": {
			ID:          "0xAE",
		},
		"0xD2": {
			ID:          "0xD2",
		},
		"0xE5": {
			ID:          "0xE5",
		},
		"0xB9": {
			ID:          "0xB9",
		},
		"0xC2": {
			ID:          "0xC2",
		},
		"0xDB": {
			ID:          "0xDB",
		},
		"0xFE": {
			ID:          "0xFE",
		},
		"0x112": {
			ID:          "0x112",
		},
		"0x91": {
			ID:          "0x91",
		},
		"0x95": {
			ID:          "0x95",
		},
		"0xB3": {
			ID:          "0xB3",
		},
		"0xD1": {
			ID:          "0xD1",
		},
		"0xFF": {
			ID:          "0xFF",
		},
		"0x6E": {
			ID:          "0x6E",
		},
		"0xC3": {
			ID:          "0xC3",
		},
		"0xC8": {
			ID:          "0xC8",
		},
		"0xD7": {
			ID:          "0xD7",
		},
		"0x127": {
			ID:          "0x127",
		},
		"0x12B": {
			ID:          "0x12B",
		},
		"0x8B": {
			ID:          "0x8B",
			Name:        "ColorTempFlash",
		},
		"0x9A": {
			ID:          "0x9A",
		},
		"0xC7": {
			ID:          "0xC7",
		},
		"0x113": {
			ID:          "0x113",
		},
		"0x82": {
			ID:          "0x82",
		},
		"IS_SUBDIR": {
			ID:          "IS_SUBDIR",
		},
		"0x69": {
			ID:          "0x69",
		},
		"0xA5": {
			ID:          "0xA5",
		},
		"0xE1": {
			ID:          "0xE1",
		},
		"0xE6": {
			ID:          "0xE6",
		},
		"0x109": {
			ID:          "0x109",
		},
		"0x117": {
			ID:          "0x117",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int16s",
		},
		"0x78": {
			ID:          "0x78",
		},
		"0xB8": {
			ID:          "0xB8",
		},
		"0xEF": {
			ID:          "0xEF",
		},
		"0xF0": {
			ID:          "0xF0",
		},
		"0xF4": {
			ID:          "0xF4",
		},
		"0x11D": {
			ID:          "0x11D",
		},
		"0xBE": {
			ID:          "0xBE",
		},
		"0xD6": {
			ID:          "0xD6",
		},
		"0x11C": {
			ID:          "0x11C",
		},
		"0x81": {
			ID:          "0x81",
			Name:        "ColorTempTungsten",
		},
		"0x9F": {
			ID:          "0x9F",
		},
		"0xA9": {
			ID:          "0xA9",
		},
		"0xDC": {
			ID:          "0xDC",
		},
		"0xEA": {
			ID:          "0xEA",
		},
		"0x108": {
			ID:          "0x108",
		},
		"0x122": {
			ID:          "0x122",
		},
		"0x87": {
			ID:          "0x87",
		},
		"0x8C": {
			ID:          "0x8C",
		},
		"0x96": {
			ID:          "0x96",
		},
		"0xEB": {
			ID:          "0xEB",
		},
		"0xA4": {
			ID:          "0xA4",
		},
		"0xAF": {
			ID:          "0xAF",
		},
		"0xB4": {
			ID:          "0xB4",
		},
		"0xCD": {
			ID:          "0xCD",
		},
		"0x72": {
			ID:          "0x72",
			Name:        "ColorTempDaylight",
		},
		"0x77": {
			ID:          "0x77",
			Name:        "ColorTempShade",
		},
		"0x7C": {
			ID:          "0x7C",
			Name:        "ColorTempCloudy",
		},
		"0xF5": {
			ID:          "0xF5",
		},
		"0x103": {
			ID:          "0x103",
		},
		"0xCC": {
			ID:          "0xCC",
		},
		"0xE0": {
			ID:          "0xE0",
		},
		"0x10D": {
			ID:          "0x10D",
		},
		"0x126": {
			ID:          "0x126",
		},
		"0x7D": {
			ID:          "0x7D",
		},
		"0xBD": {
			ID:          "0xBD",
		},
		"0xF9": {
			ID:          "0xF9",
		},
		"0x104": {
			ID:          "0x104",
		},
		"0x121": {
			ID:          "0x121",
		},
		"DATAMEMBER": {
			ID:          "DATAMEMBER",
		},
		"0xAA": {
			ID:          "0xAA",
		},
		"0x10E": {
			ID:          "0x10E",
		},
		"0x118": {
			ID:          "0x118",
		},
		"0x6D": {
			ID:          "0x6D",
		},
		"0x86": {
			ID:          "0x86",
		},
	},
}
