// Code generated by gen-tags. DO NOT EDIT.

package tags

// CanonCameraInfo5DmkIITags contains tag definitions from Image::ExifTool::Canon
var CanonCameraInfo5DmkIITags = TagTable{
	ModuleName: "Canon",
	Tags: map[string]TagDef{
		"0x1E": {
			ID:          "0x1E",
		},
		"0xE8": {
			ID:          "0xE8",
		},
		"PRIORITY": {
			ID:          "PRIORITY",
		},
		"DATAMEMBER": {
			ID:          "DATAMEMBER",
		},
		"IS_SUBDIR": {
			ID:          "IS_SUBDIR",
		},
		"0x03": {
			ID:          "0x03",
		},
		"0x04": {
			ID:          "0x04",
		},
		"0x06": {
			ID:          "0x06",
		},
		"0x1B": {
			ID:          "0x1B",
		},
		"0x19": {
			ID:          "0x19",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int8u",
		},
	},
}
