// Code generated by gen-tags. DO NOT EDIT.

package tags

// CanonCameraInfo450DTags contains tag definitions from Image::ExifTool::Canon
var CanonCameraInfo450DTags = TagTable{
	ModuleName: "Canon",
	Tags: map[string]TagDef{
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int8u",
		},
		"PRIORITY": {
			ID:          "PRIORITY",
		},
		"0x03": {
			ID:          "0x03",
		},
		"0x04": {
			ID:          "0x04",
		},
		"0x06": {
			ID:          "0x06",
		},
		"IS_SUBDIR": {
			ID:          "IS_SUBDIR",
		},
		"0x18": {
			ID:          "0x18",
		},
		"0x1B": {
			ID:          "0x1B",
		},
		"0x1D": {
			ID:          "0x1D",
		},
	},
}
