// Code generated by gen-tags. DO NOT EDIT.

package tags

// CanoncanonModelIDTags contains tag definitions from Image::ExifTool::Canon
var CanoncanonModelIDTags = TagTable{
	ModuleName: "Canon",
	Tags: map[string]TagDef{
		"0x4030000": {
			ID:          "0x4030000",
			Name:        "PowerShot ELPH 190 IS / IXUS 180 / IXY 190",
		},
		"0x4040001": {
			ID:          "0x4040001",
		},
		"0x1080000": {
			ID:          "0x1080000",
			Name:        "PowerShot A10",
		},
		"0x1960000": {
			ID:          "0x1960000",
			Name:        "PowerShot A540",
		},
		"0x2560000": {
			ID:          "0x2560000",
			Name:        "PowerShot D10",
		},
		"0x2920000": {
			ID:          "0x2920000",
			Name:        "PowerShot G12",
		},
		"0x80000169": {
			ID:          "0x80000169",
			Name:        "EOS-1D Mark III",
		},
		"0x1040000": {
			ID:          "0x1040000",
			Name:        "PowerShot S300 / Digital IXUS 300 / IXY Digital 300",
		},
		"0x3250000": {
			ID:          "0x3250000",
			Name:        "PowerShot ELPH 520 HS / IXUS 500 HS / IXY 3",
		},
		"0x3590000": {
			ID:          "0x3590000",
			Name:        "PowerShot S200 (new)",
		},
		"0x3660000": {
			ID:          "0x3660000",
			Name:        "PowerShot SX700 HS",
		},
		"0x2720000": {
			ID:          "0x2720000",
			Name:        "PowerShot S90",
		},
		"0x3880000": {
			ID:          "0x3880000",
			Name:        "PowerShot ELPH 350 HS / IXUS 275 HS / IXY 640",
		},
		"0x80000241": {
			ID:          "0x80000241",
			Name:        "WFT-E2",
		},
		"0x2150000": {
			ID:          "0x2150000",
			Name:        "PowerShot SD750 / Digital IXUS 75 / IXY Digital 90",
		},
		"0x2370000": {
			ID:          "0x2370000",
			Name:        "PowerShot SD770 IS / Digital IXUS 85 IS / IXY Digital 25 IS",
		},
		"0x80000349": {
			ID:          "0x80000349",
		},
		"0x1880000": {
			ID:          "0x1880000",
			Name:        "PowerShot A420",
		},
		"0x3010000": {
			ID:          "0x3010000",
			Name:        "PowerShot Pro90 IS",
		},
		"0x808": {
			ID:          "0x808",
			Name:        "PowerShot G7 X Mark III",
		},
		"0x80000297": {
			ID:          "0x80000297",
			Name:        "WFT-E2 II",
		},
		"0x80000464": {
			ID:          "0x80000464",
		},
		"0x2420000": {
			ID:          "0x2420000",
			Name:        "PowerShot A470",
		},
		"0x1170000": {
			ID:          "0x1170000",
			Name:        "PowerShot A200",
		},
		"0x1210000": {
			ID:          "0x1210000",
			Name:        "PowerShot S45",
		},
		"0x1270000": {
			ID:          "0x1270000",
			Name:        "PowerShot S400 / Digital IXUS 400 / IXY Digital 400",
		},
		"0x1370000": {
			ID:          "0x1370000",
			Name:        "PowerShot Pro1",
		},
		"0x3210000": {
			ID:          "0x3210000",
			Name:        "PowerShot A4000 IS",
		},
		"0x3280000": {
			ID:          "0x3280000",
			Name:        "PowerShot A2300",
		},
		"0x80000421": {
			ID:          "0x80000421",
		},
		"0x1470000": {
			ID:          "0x1470000",
			Name:        "PowerShot A310",
		},
		"0x1900000": {
			ID:          "0x1900000",
			Name:        "PowerShot SD550 / Digital IXUS 750 / IXY Digital 700",
		},
		"0x80000350": {
			ID:          "0x80000350",
		},
		"0x80000382": {
			ID:          "0x80000382",
			Name:        "EOS 5DS",
		},
		"0x80000436": {
			ID:          "0x80000436",
		},
		"0x80000468": {
			ID:          "0x80000468",
		},
		"0x3240000": {
			ID:          "0x3240000",
			Name:        "PowerShot ELPH 530 HS / IXUS 510 HS / IXY 1",
		},
		"0x1060000": {
			ID:          "0x1060000",
			Name:        "PowerShot A20",
		},
		"0x4007D87F": {
			ID:          "0x4007D87F",
			Name:        "FS100",
		},
		"0x4007D987": {
			ID:          "0x4007D987",
			Name:        "DC410/DC411/DC420",
		},
		"0x1550000": {
			ID:          "0x1550000",
			Name:        "PowerShot SD200 / Digital IXUS 30 / IXY Digital 40",
		},
		"0x2300000": {
			ID:          "0x2300000",
			Name:        "PowerShot SD950 IS / Digital IXUS 960 IS / IXY Digital 2000 IS",
		},
		"0x2530000": {
			ID:          "0x2530000",
			Name:        "PowerShot SD990 IS / Digital IXUS 980 IS / IXY Digital 3000 IS",
		},
		"0x2550000": {
			ID:          "0x2550000",
			Name:        "PowerShot E1",
		},
		"0x3820000": {
			ID:          "0x3820000",
			Name:        "PowerShot SX710 HS",
		},
		"0x3850000": {
			ID:          "0x3850000",
			Name:        "PowerShot G3 X",
		},
		"0x3950000": {
			ID:          "0x3950000",
			Name:        "PowerShot G5 X",
		},
		"0x4007D880": {
			ID:          "0x4007D880",
		},
		"0x2520000": {
			ID:          "0x2520000",
			Name:        "PowerShot SX110 IS",
		},
		"0x2590000": {
			ID:          "0x2590000",
			Name:        "PowerShot A480",
		},
		"0x3330000": {
			ID:          "0x3330000",
		},
		"0x3350000": {
			ID:          "0x3350000",
			Name:        "PowerShot SX160 IS",
		},
		"0x4007DA92": {
			ID:          "0x4007DA92",
			Name:        "FS31/FS36/FS37/FS300/FS305/FS306/FS307",
		},
		"0x2540000": {
			ID:          "0x2540000",
			Name:        "PowerShot SD880 IS / Digital IXUS 870 IS / IXY Digital 920 IS",
		},
		"0x4007E1C3": {
			ID:          "0x4007E1C3",
			Name:        "EOS C200",
		},
		"0x80000481": {
			ID:          "0x80000481",
		},
		"0x2000000": {
			ID:          "0x2000000",
			Name:        "PowerShot SD800 IS / Digital IXUS 850 IS / IXY Digital 900 IS",
		},
		"0x3230000": {
			ID:          "0x3230000",
			Name:        "PowerShot SX240 HS",
		},
		"0x3320000": {
			ID:          "0x3320000",
		},
		"0x4180000": {
			ID:          "0x4180000",
		},
		"0x4007D77D": {
			ID:          "0x4007D77D",
			Name:        "MD255/ZR950",
		},
		"0x4007D87E": {
			ID:          "0x4007D87E",
			Name:        "DC301/DC310/DC311/DC320/DC330",
		},
		"0x4007D98A": {
			ID:          "0x4007D98A",
		},
		"0x80000428": {
			ID:          "0x80000428",
		},
		"0x1110000": {
			ID:          "0x1110000",
			Name:        "PowerShot S40",
		},
		"0x1530000": {
			ID:          "0x1530000",
			Name:        "PowerShot A95",
		},
		"0x3090000": {
			ID:          "0x3090000",
			Name:        "PowerShot SX150 IS",
		},
		"0x1760000": {
			ID:          "0x1760000",
			Name:        "PowerShot S80",
		},
		"0x2140000": {
			ID:          "0x2140000",
			Name:        "PowerShot A560",
		},
		"0x2980000": {
			ID:          "0x2980000",
			Name:        "PowerShot A3300 IS",
		},
		"0x3020000": {
			ID:          "0x3020000",
			Name:        "PowerShot ELPH 100 HS / IXUS 115 HS / IXY 210F",
		},
		"0x2570000": {
			ID:          "0x2570000",
			Name:        "PowerShot SD960 IS / Digital IXUS 110 IS / IXY Digital 510 IS",
		},
		"0x3140000": {
			ID:          "0x3140000",
		},
		"0x3750000": {
			ID:          "0x3750000",
		},
		"0x3890000": {
			ID:          "0x3890000",
			Name:        "PowerShot ELPH 170 IS / IXUS 170",
		},
		"0x80000175": {
			ID:          "0x80000175",
			Name:        "EOS 20D",
		},
		"0x80000408": {
			ID:          "0x80000408",
			Name:        "EOS 77D / 9000D",
		},
		"0x1780000": {
			ID:          "0x1780000",
			Name:        "PowerShot A620",
		},
		"0x1870000": {
			ID:          "0x1870000",
			Name:        "PowerShot SD400 / Digital IXUS 50 / IXY Digital 55",
		},
		"0x3070000": {
			ID:          "0x3070000",
			Name:        "PowerShot SX220 HS",
		},
		"0x80000234": {
			ID:          "0x80000234",
			Name:        "EOS 30D",
		},
		"0x80000355": {
			ID:          "0x80000355",
			Name:        "EOS M2",
		},
		"0x1410000": {
			ID:          "0x1410000",
			Name:        "PowerShot S500 / Digital IXUS 500 / IXY Digital 500",
		},
		"0x3430000": {
			ID:          "0x3430000",
			Name:        "PowerShot A2600",
		},
		"0x3710000": {
			ID:          "0x3710000",
			Name:        "PowerShot ELPH 150 IS / IXUS 155 / IXY 140",
		},
		"0x3990000": {
			ID:          "0x3990000",
			Name:        "PowerShot ELPH 360 HS / IXUS 285 HS / IXY 650",
		},
		"0x80000270": {
			ID:          "0x80000270",
			Name:        "EOS Rebel T2i / 550D / Kiss X4",
		},
		"0x1120000": {
			ID:          "0x1120000",
			Name:        "PowerShot S30",
		},
		"0x2310000": {
			ID:          "0x2310000",
			Name:        "PowerShot SD870 IS / Digital IXUS 860 IS / IXY Digital 910 IS",
		},
		"0x3930000": {
			ID:          "0x3930000",
			Name:        "PowerShot G9 X",
		},
		"0x804": {
			ID:          "0x804",
			Name:        "PowerShot G5 X Mark II",
		},
		"0x80000271": {
			ID:          "0x80000271",
			Name:        "WFT-E4",
		},
		"0x80000289": {
			ID:          "0x80000289",
		},
		"0x1800000": {
			ID:          "0x1800000",
			Name:        "PowerShot SD630 / Digital IXUS 65 / IXY Digital 80",
		},
		"0x2120000": {
			ID:          "0x2120000",
			Name:        "PowerShot SD850 IS / Digital IXUS 950 IS / IXY Digital 810 IS",
		},
		"0x2840000": {
			ID:          "0x2840000",
			Name:        "PowerShot SD1400 IS / IXUS 130 / IXY 400F",
		},
		"0x3510000": {
			ID:          "0x3510000",
			Name:        "PowerShot A2500",
		},
		"0x80000465": {
			ID:          "0x80000465",
		},
		"0x2620000": {
			ID:          "0x2620000",
			Name:        "PowerShot SD780 IS / Digital IXUS 100 IS / IXY Digital 210 IS",
		},
		"0x1390000": {
			ID:          "0x1390000",
			Name:        "PowerShot S60",
		},
		"0x1420000": {
			ID:          "0x1420000",
			Name:        "PowerShot A75",
		},
		"0x3380000": {
			ID:          "0x3380000",
			Name:        "PowerShot N",
		},
		"0x4150000": {
			ID:          "0x4150000",
			Name:        "PowerShot ELPH 185 / IXUS 185 / IXY 200",
		},
		"0x4007D778": {
			ID:          "0x4007D778",
		},
		"0x1010000": {
			ID:          "0x1010000",
			Name:        "PowerShot A30",
		},
		"0x1668000": {
			ID:          "0x1668000",
			Name:        "EOS D60",
		},
		"0x2100000": {
			ID:          "0x2100000",
			Name:        "PowerShot A460",
		},
		"0x2890000": {
			ID:          "0x2890000",
			Name:        "PowerShot SD4500 IS / IXUS 1000 HS / IXY 50S",
		},
		"0x3790000": {
			ID:          "0x3790000",
			Name:        "PowerShot N2",
		},
		"0x3800000": {
			ID:          "0x3800000",
			Name:        "PowerShot SX530 HS",
		},
		"0x4020000": {
			ID:          "0x4020000",
			Name:        "PowerShot SX420 IS",
		},
		"0x80000298": {
			ID:          "0x80000298",
			Name:        "WFT-E4 II",
		},
		"0x1100000": {
			ID:          "0x1100000",
			Name:        "PowerShot G2",
		},
		"0x2160000": {
			ID:          "0x2160000",
			Name:        "PowerShot SD1000 / Digital IXUS 70 / IXY Digital 10",
		},
		"0x3650000": {
			ID:          "0x3650000",
			Name:        "PowerShot D30",
		},
		"0x3910000": {
			ID:          "0x3910000",
			Name:        "PowerShot SX410 IS",
		},
		"0x80000288": {
			ID:          "0x80000288",
			Name:        "EOS Rebel T3 / 1100D / Kiss X50",
		},
		"0x2010000": {
			ID:          "0x2010000",
			Name:        "PowerShot SD40 / Digital IXUS i7 / IXY Digital L4",
		},
		"0x3830000": {
			ID:          "0x3830000",
			Name:        "PowerShot SX610 HS",
		},
		"0x4050000": {
			ID:          "0x4050000",
			Name:        "PowerShot SX720 HS",
		},
		"0x4007D675": {
			ID:          "0x4007D675",
			Name:        "HV10",
		},
		"0x80000325": {
			ID:          "0x80000325",
			Name:        "EOS 70D",
		},
		"0x80000401": {
			ID:          "0x80000401",
			Name:        "EOS 5DS R",
		},
		"0x2320000": {
			ID:          "0x2320000",
			Name:        "PowerShot SD890 IS / Digital IXUS 970 IS / IXY Digital 820 IS",
		},
		"0x1980000": {
			ID:          "0x1980000",
			Name:        "PowerShot G7",
		},
		"0x1520000": {
			ID:          "0x1520000",
			Name:        "PowerShot S410 / Digital IXUS 430 / IXY Digital 450",
		},
		"0x3540000": {
			ID:          "0x3540000",
			Name:        "PowerShot G16",
		},
		"0x3860000": {
			ID:          "0x3860000",
			Name:        "PowerShot ELPH 165 HS / IXUS 165 / IXY 160",
		},
		"0x4007D673": {
			ID:          "0x4007D673",
			Name:        "DC19/DC21/DC22",
		},
		"0x80000250": {
			ID:          "0x80000250",
			Name:        "EOS 7D",
		},
		"0x80000273": {
			ID:          "0x80000273",
			Name:        "WFT-E5",
		},
		"0x1260000": {
			ID:          "0x1260000",
			Name:        "PowerShot A60",
		},
		"0x1640000": {
			ID:          "0x1640000",
			Name:        "PowerShot S2 IS",
		},
		"0x3120000": {
			ID:          "0x3120000",
			Name:        "PowerShot ELPH 310 HS / IXUS 230 HS / IXY 600F",
		},
		"0x3440000": {
			ID:          "0x3440000",
		},
		"0x3470000": {
			ID:          "0x3470000",
			Name:        "PowerShot ELPH 115/120 IS / IXUS 132/135 / IXY 90F/100F",
		},
		"0x80000254": {
			ID:          "0x80000254",
			Name:        "EOS Rebel XS / 1000D / Kiss F",
		},
		"0x2710000": {
			ID:          "0x2710000",
			Name:        "PowerShot SX120 IS",
		},
		"0x3190000": {
			ID:          "0x3190000",
			Name:        "PowerShot ELPH 110 HS / IXUS 125 HS / IXY 220F",
		},
		"0x3270000": {
			ID:          "0x3270000",
			Name:        "PowerShot A2400 IS",
		},
		"0x4007D926": {
			ID:          "0x4007D926",
		},
		"0x80000168": {
			ID:          "0x80000168",
			Name:        "EOS 10D",
		},
		"0x80000435": {
			ID:          "0x80000435",
		},
		"0x1250000": {
			ID:          "0x1250000",
			Name:        "PowerShot A70",
		},
		"0x2510000": {
			ID:          "0x2510000",
			Name:        "PowerShot A2000 IS",
		},
		"0x2830000": {
			ID:          "0x2830000",
			Name:        "PowerShot A3000 IS",
		},
		"0x3100000": {
			ID:          "0x3100000",
			Name:        "PowerShot ELPH 510 HS / IXUS 1100 HS / IXY 51S",
		},
		"0x3160000": {
			ID:          "0x3160000",
			Name:        "PowerShot A1300",
		},
		"0x3600000": {
			ID:          "0x3600000",
		},
		"0x80000393": {
			ID:          "0x80000393",
			Name:        "EOS Rebel T6i / 750D / Kiss X8i",
		},
		"0x1140000": {
			ID:          "0x1140000",
			Name:        "EOS D30",
		},
		"0x1990000": {
			ID:          "0x1990000",
			Name:        "PowerShot A530",
		},
		"0x2820000": {
			ID:          "0x2820000",
		},
		"0x1890000": {
			ID:          "0x1890000",
			Name:        "PowerShot SD900 / Digital IXUS 900 Ti / IXY Digital 1000",
		},
		"0x2290000": {
			ID:          "0x2290000",
			Name:        "PowerShot SX100 IS",
		},
		"0x2810000": {
			ID:          "0x2810000",
			Name:        "PowerShot A490",
		},
		"0x4007D676": {
			ID:          "0x4007D676",
			Name:        "MD130/MD140/MD150/MD160/ZR850",
		},
		"0x80000232": {
			ID:          "0x80000232",
			Name:        "EOS-1D Mark II N",
		},
		"0x1150000": {
			ID:          "0x1150000",
			Name:        "PowerShot A100",
		},
		"0x2240000": {
			ID:          "0x2240000",
			Name:        "PowerShot A650 IS",
		},
		"0x2640000": {
			ID:          "0x2640000",
			Name:        "PowerShot SD1200 IS / Digital IXUS 95 IS / IXY Digital 110 IS",
		},
		"0x3940000": {
			ID:          "0x3940000",
		},
		"0x1090000": {
			ID:          "0x1090000",
			Name:        "PowerShot S110 / Digital IXUS v / IXY Digital 200",
		},
		"0x1750000": {
			ID:          "0x1750000",
			Name:        "PowerShot A410",
		},
		"0x2700000": {
			ID:          "0x2700000",
			Name:        "PowerShot G11",
		},
		"0x3410000": {
			ID:          "0x3410000",
			Name:        "PowerShot SX270 HS",
		},
		"0x6040000": {
			ID:          "0x6040000",
			Name:        "PowerShot S100 / Digital IXUS / IXY Digital",
		},
		"0x80000176": {
			ID:          "0x80000176",
			Name:        "EOS Digital Rebel XSi / 450D / Kiss X2",
		},
		"0x80000252": {
			ID:          "0x80000252",
			Name:        "EOS Rebel T1i / 500D / Kiss X3",
		},
		"0x80000326": {
			ID:          "0x80000326",
			Name:        "EOS Rebel T5i / 700D / Kiss X7i",
		},
		"0x1740000": {
			ID:          "0x1740000",
			Name:        "PowerShot A430",
		},
		"0x3060000": {
			ID:          "0x3060000",
			Name:        "PowerShot A1200",
		},
		"0x3550000": {
			ID:          "0x3550000",
			Name:        "PowerShot S120",
		},
		"0x3670000": {
			ID:          "0x3670000",
			Name:        "PowerShot SX600 HS",
		},
		"0x3970000": {
			ID:          "0x3970000",
			Name:        "PowerShot G7 X Mark II",
		},
		"0x4007DA90": {
			ID:          "0x4007DA90",
		},
		"0x80000347": {
			ID:          "0x80000347",
			Name:        "EOS Rebel T6s / 760D / 8000D",
		},
		"0x80000467": {
			ID:          "0x80000467",
			Name:        "PowerShot ZOOM",
		},
		"0x1940000": {
			ID:          "0x1940000",
			Name:        "PowerShot SD700 IS / Digital IXUS 800 IS / IXY Digital 800 IS",
		},
		"0x2230000": {
			ID:          "0x2230000",
			Name:        "PowerShot G9",
		},
		"0x3460000": {
			ID:          "0x3460000",
			Name:        "PowerShot ELPH 130 IS / IXUS 140 / IXY 110F",
		},
		"0x4007DDA9": {
			ID:          "0x4007DDA9",
		},
		"0x4007DFB4": {
			ID:          "0x4007DFB4",
			Name:        "XC10",
		},
		"0x80000219": {
			ID:          "0x80000219",
			Name:        "WFT-E1",
		},
		"0x1180000": {
			ID:          "0x1180000",
			Name:        "PowerShot S330 / Digital IXUS 330 / IXY Digital 300a",
		},
		"0x3610000": {
			ID:          "0x3610000",
			Name:        "PowerShot N100",
		},
		"0x3770000": {
			ID:          "0x3770000",
			Name:        "PowerShot SX400 IS",
		},
		"0x4007D674": {
			ID:          "0x4007D674",
			Name:        "XH A1",
		},
		"0x4007D988": {
			ID:          "0x4007D988",
		},
		"0x4007DCA0": {
			ID:          "0x4007DCA0",
			Name:        "EOS C300",
		},
		"0x80000495": {
			ID:          "0x80000495",
		},
		"0x1360000": {
			ID:          "0x1360000",
			Name:        "PowerShot S1 IS",
		},
		"0x1230000": {
			ID:          "0x1230000",
			Name:        "PowerShot SD100 / Digital IXUS II / IXY Digital 30",
		},
		"0x2850000": {
			ID:          "0x2850000",
			Name:        "PowerShot SD1300 IS / IXUS 105 / IXY 200F",
		},
		"0x2870000": {
			ID:          "0x2870000",
			Name:        "PowerShot SX210 IS",
		},
		"0x2990000": {
			ID:          "0x2990000",
			Name:        "PowerShot A3200 IS",
		},
		"0x3000000": {
			ID:          "0x3000000",
			Name:        "PowerShot ELPH 500 HS / IXUS 310 HS / IXY 31S",
		},
		"0x3110000": {
			ID:          "0x3110000",
			Name:        "PowerShot S100 (new)",
		},
		"0x3260000": {
			ID:          "0x3260000",
			Name:        "PowerShot A3400 IS",
		},
		"0x4040000": {
			ID:          "0x4040000",
			Name:        "PowerShot G1",
		},
		"0x2610000": {
			ID:          "0x2610000",
			Name:        "PowerShot SD970 IS / Digital IXUS 990 IS / IXY Digital 830 IS",
		},
		"0x1570000": {
			ID:          "0x1570000",
			Name:        "PowerShot A510",
		},
		"0x2360000": {
			ID:          "0x2360000",
			Name:        "PowerShot SD790 IS / Digital IXUS 90 IS / IXY Digital 95 IS",
		},
		"0x3450000": {
			ID:          "0x3450000",
			Name:        "PowerShot A1400",
		},
		"0x4170000": {
			ID:          "0x4170000",
			Name:        "PowerShot SX730 HS",
		},
		"0x812": {
			ID:          "0x812",
		},
		"0x4007D81C": {
			ID:          "0x4007D81C",
			Name:        "HF11",
		},
		"0x3760000": {
			ID:          "0x3760000",
		},
		"0x1810000": {
			ID:          "0x1810000",
			Name:        "PowerShot SD450 / Digital IXUS 55 / IXY Digital 60",
		},
		"0x2950000": {
			ID:          "0x2950000",
			Name:        "PowerShot S95",
		},
		"0x3420000": {
			ID:          "0x3420000",
			Name:        "PowerShot A3500 IS",
		},
		"0x4007D77A": {
			ID:          "0x4007D77A",
			Name:        "HG10",
		},
		"0x80000287": {
			ID:          "0x80000287",
			Name:        "EOS 60D",
		},
		"0x80000328": {
			ID:          "0x80000328",
		},
		"0x80000433": {
			ID:          "0x80000433",
			Name:        "EOS RP",
		},
		"0x2180000": {
			ID:          "0x2180000",
			Name:        "PowerShot A550",
		},
		"0x1130000": {
			ID:          "0x1130000",
			Name:        "PowerShot A40",
		},
		"0x1380000": {
			ID:          "0x1380000",
			Name:        "PowerShot S70",
		},
		"0x1660000": {
			ID:          "0x1660000",
			Name:        "PowerShot SD500 / Digital IXUS 700 / IXY Digital 600",
		},
		"0x80000001": {
			ID:          "0x80000001",
			Name:        "EOS-1D",
		},
		"0x80000236": {
			ID:          "0x80000236",
			Name:        "EOS Digital Rebel XTi / 400D / Kiss Digital X",
		},
		"0x80000327": {
			ID:          "0x80000327",
			Name:        "EOS Rebel T5 / 1200D / Kiss X70 / Hi",
		},
		"0x80000331": {
			ID:          "0x80000331",
			Name:        "EOS M",
		},
		"0x2470000": {
			ID:          "0x2470000",
			Name:        "PowerShot SX10 IS",
		},
		"0x1400000": {
			ID:          "0x1400000",
			Name:        "PowerShot G6",
		},
		"0x1540000": {
			ID:          "0x1540000",
			Name:        "PowerShot SD300 / Digital IXUS 40 / IXY Digital 50",
		},
		"0x1590000": {
			ID:          "0x1590000",
			Name:        "PowerShot SD20 / Digital IXUS i5 / IXY Digital L2",
		},
		"0x1820000": {
			ID:          "0x1820000",
			Name:        "PowerShot TX1",
		},
		"0x3010001": {
			ID:          "0x3010001",
			Name:        "PowerShot A800",
		},
		"0x3050000": {
			ID:          "0x3050000",
			Name:        "PowerShot A2200",
		},
		"0x4007D87C": {
			ID:          "0x4007D87C",
			Name:        "XH A1S",
		},
		"0x3870000": {
			ID:          "0x3870000",
			Name:        "PowerShot ELPH 160 / IXUS 160",
		},
		"0x4007D882": {
			ID:          "0x4007D882",
		},
		"0x4007D925": {
			ID:          "0x4007D925",
		},
		"0x80000286": {
			ID:          "0x80000286",
			Name:        "EOS Rebel T3i / 600D / Kiss X5",
		},
		"0x80000302": {
			ID:          "0x80000302",
		},
		"0x1650000": {
			ID:          "0x1650000",
			Name:        "PowerShot SD430 / Digital IXUS Wireless / IXY Digital Wireless",
		},
		"0x2630000": {
			ID:          "0x2630000",
			Name:        "PowerShot A1100 IS",
		},
		"0x3030000": {
			ID:          "0x3030000",
			Name:        "PowerShot SX230 HS",
		},
		"0x3740000": {
			ID:          "0x3740000",
		},
		"0x80000487": {
			ID:          "0x80000487",
		},
		"0x80000496": {
			ID:          "0x80000496",
		},
		"0x2130000": {
			ID:          "0x2130000",
			Name:        "PowerShot A570 IS",
		},
		"0x2460000": {
			ID:          "0x2460000",
			Name:        "PowerShot SX1 IS",
		},
		"0x2600000": {
			ID:          "0x2600000",
			Name:        "PowerShot SX200 IS",
		},
		"0x3560000": {
			ID:          "0x3560000",
			Name:        "PowerShot SX170 IS",
		},
		"0x80000404": {
			ID:          "0x80000404",
			Name:        "EOS Rebel T6 / 1300D / Kiss X80",
		},
		"0x1190000": {
			ID:          "0x1190000",
			Name:        "PowerShot G3",
		},
		"0x1240000": {
			ID:          "0x1240000",
			Name:        "PowerShot S230 / Digital IXUS v3 / IXY Digital 320",
		},
		"0x3360000": {
			ID:          "0x3360000",
			Name:        "PowerShot S110 (new)",
		},
		"0x3390000": {
			ID:          "0x3390000",
		},
		"0x80000437": {
			ID:          "0x80000437",
		},
		"0x80000480": {
			ID:          "0x80000480",
		},
		"0x2430000": {
			ID:          "0x2430000",
			Name:        "PowerShot SD1100 IS / Digital IXUS 80 IS / IXY Digital 20 IS",
		},
		"0x3040000": {
			ID:          "0x3040000",
			Name:        "PowerShot ELPH 300 HS / IXUS 220 HS / IXY 410F",
		},
		"0x3780000": {
			ID:          "0x3780000",
		},
		"0x4007D878": {
			ID:          "0x4007D878",
			Name:        "HV30",
		},
		"0x1920000": {
			ID:          "0x1920000",
			Name:        "PowerShot A700",
		},
		"0x2770000": {
			ID:          "0x2770000",
			Name:        "PowerShot SD940 IS / Digital IXUS 120 IS / IXY Digital 220 IS",
		},
		"0x3170000": {
			ID:          "0x3170000",
			Name:        "PowerShot A810",
		},
		"0x811": {
			ID:          "0x811",
		},
		"0x80000406": {
			ID:          "0x80000406",
		},
		"0x80000424": {
			ID:          "0x80000424",
		},
		"0x1950000": {
			ID:          "0x1950000",
			Name:        "PowerShot S3 IS",
		},
		"0x2030000": {
			ID:          "0x2030000",
			Name:        "PowerShot A640",
		},
		"0x3080000": {
			ID:          "0x3080000",
			Name:        "PowerShot G1 X",
		},
		"0x3200000": {
			ID:          "0x3200000",
			Name:        "PowerShot D20",
		},
		"0x80000170": {
			ID:          "0x80000170",
			Name:        "EOS Digital Rebel / 300D / Kiss Digital",
		},
		"0x80000188": {
			ID:          "0x80000188",
			Name:        "EOS-1Ds Mark II",
		},
		"0x80000422": {
			ID:          "0x80000422",
		},
		"0x80000432": {
			ID:          "0x80000432",
		},
		"0x1970000": {
			ID:          "0x1970000",
			Name:        "PowerShot SD600 / Digital IXUS 60 / IXY Digital 70",
		},
		"0x2760000": {
			ID:          "0x2760000",
			Name:        "PowerShot SD980 IS / Digital IXUS 200 IS / IXY Digital 930 IS",
		},
		"0x2940000": {
			ID:          "0x2940000",
			Name:        "PowerShot SX130 IS",
		},
		"0x3370000": {
			ID:          "0x3370000",
			Name:        "PowerShot SX500 IS",
		},
		"0x3640000": {
			ID:          "0x3640000",
			Name:        "PowerShot G1 X Mark II",
		},
		"0x3680000": {
			ID:          "0x3680000",
			Name:        "PowerShot ELPH 140 IS / IXUS 150 / IXY 130",
		},
		"0x3690000": {
			ID:          "0x3690000",
			Name:        "PowerShot ELPH 135 / IXUS 145 / IXY 120",
		},
		"0x3700000": {
			ID:          "0x3700000",
			Name:        "PowerShot ELPH 340 HS / IXUS 265 HS / IXY 630",
		},
		"0x2090000": {
			ID:          "0x2090000",
			Name:        "PowerShot S5 IS",
		},
		"0x3340000": {
			ID:          "0x3340000",
		},
		"0x4010000": {
			ID:          "0x4010000",
			Name:        "PowerShot SX540 HS",
		},
		"0x4007DA8F": {
			ID:          "0x4007DA8F",
		},
		"0x80000189": {
			ID:          "0x80000189",
			Name:        "EOS Digital Rebel XT / 350D / Kiss Digital N",
		},
		"0x1490000": {
			ID:          "0x1490000",
			Name:        "PowerShot A85",
		},
		"0x1790000": {
			ID:          "0x1790000",
			Name:        "PowerShot A610",
		},
		"0x3840000": {
			ID:          "0x3840000",
			Name:        "EOS M10",
		},
		"0x4100000": {
			ID:          "0x4100000",
			Name:        "PowerShot G9 X Mark II",
		},
		"0x805": {
			ID:          "0x805",
			Name:        "PowerShot SX70 HS",
		},
		"0x80000346": {
			ID:          "0x80000346",
			Name:        "EOS Rebel SL1 / 100D / Kiss X7",
		},
		"0x80000520": {
			ID:          "0x80000520",
		},
		"0x3220000": {
			ID:          "0x3220000",
			Name:        "PowerShot SX260 HS",
		},
		"0x80000281": {
			ID:          "0x80000281",
			Name:        "EOS-1D Mark IV",
		},
		"0x80000450": {
			ID:          "0x80000450",
		},
		"0x2380000": {
			ID:          "0x2380000",
			Name:        "PowerShot A590 IS",
		},
		"0x2490000": {
			ID:          "0x2490000",
			Name:        "PowerShot G10",
		},
		"0x1560000": {
			ID:          "0x1560000",
			Name:        "PowerShot A520",
		},
		"0x1700000": {
			ID:          "0x1700000",
			Name:        "PowerShot SD30 / Digital IXUS i Zoom / IXY Digital L3",
		},
		"0x2930000": {
			ID:          "0x2930000",
			Name:        "PowerShot SX30 IS",
		},
		"0x4007D978": {
			ID:          "0x4007D978",
		},
		"0x80000190": {
			ID:          "0x80000190",
			Name:        "EOS 40D",
		},
		"0x80000246": {
			ID:          "0x80000246",
			Name:        "WFT-E3",
		},
		"0x1340000": {
			ID:          "0x1340000",
			Name:        "PowerShot A80",
		},
		"0x1440000": {
			ID:          "0x1440000",
			Name:        "PowerShot SD110 / Digital IXUS IIs / IXY Digital 30a",
		},
		"0x4007DA8E": {
			ID:          "0x4007DA8E",
		},
		"0x80000560": {
			ID:          "0x80000560",
		},
		"0x2390000": {
			ID:          "0x2390000",
			Name:        "PowerShot A580",
		},
		"0x80000174": {
			ID:          "0x80000174",
			Name:        "EOS-1D Mark II",
		},
		"0x80000491": {
			ID:          "0x80000491",
		},
		"0x2190000": {
			ID:          "0x2190000",
			Name:        "PowerShot A450",
		},
		"0x1290000": {
			ID:          "0x1290000",
			Name:        "PowerShot G5",
		},
		"0x1350000": {
			ID:          "0x1350000",
			Name:        "PowerShot SD10 / Digital IXUS i / IXY Digital L",
		},
		"0x3980000": {
			ID:          "0x3980000",
		},
		"0x801": {
			ID:          "0x801",
			Name:        "PowerShot SX740 HS",
		},
		"0x1160000": {
			ID:          "0x1160000",
			Name:        "PowerShot S200 / Digital IXUS v2 / IXY Digital 200a",
		},
		"0x1310000": {
			ID:          "0x1310000",
			Name:        "PowerShot S50",
		},
		"0x2800000": {
			ID:          "0x2800000",
			Name:        "PowerShot A495",
		},
		"0x3490000": {
			ID:          "0x3490000",
			Name:        "PowerShot ELPH 330 HS / IXUS 255 HS / IXY 610F",
		},
		"0x3580000": {
			ID:          "0x3580000",
			Name:        "PowerShot SX510 HS",
		},
		"0x80000269": {
			ID:          "0x80000269",
			Name:        "EOS-1D X",
		},
		"0x412": {
			ID:          "0x412",
		},
		"0x4007D77B": {
			ID:          "0x4007D77B",
		},
		"0x80000261": {
			ID:          "0x80000261",
			Name:        "EOS 50D",
		},
		"0x80000301": {
			ID:          "0x80000301",
			Name:        "EOS Rebel T4i / 650D / Kiss X6i",
		},
		"0x1300000": {
			ID:          "0x1300000",
			Name:        "PowerShot A300",
		},
		"0x2880000": {
			ID:          "0x2880000",
			Name:        "PowerShot SD4000 IS / IXUS 300 HS / IXY 30S",
		},
		"0x4007D779": {
			ID:          "0x4007D779",
		},
		"0x80000218": {
			ID:          "0x80000218",
			Name:        "EOS 5D Mark II",
		},
		"0x1450000": {
			ID:          "0x1450000",
			Name:        "PowerShot A400",
		},
		"0x2040000": {
			ID:          "0x2040000",
			Name:        "PowerShot A630",
		},
		"0x2580000": {
			ID:          "0x2580000",
			Name:        "PowerShot A2100 IS",
		},
		"0x3180000": {
			ID:          "0x3180000",
			Name:        "PowerShot ELPH 320 HS / IXUS 240 HS / IXY 420F",
		},
		"0x4007D989": {
			ID:          "0x4007D989",
		},
		"0x80000498": {
			ID:          "0x80000498",
		},
		"0x3400000": {
			ID:          "0x3400000",
			Name:        "PowerShot SX280 HS",
		},
		"0x80000215": {
			ID:          "0x80000215",
			Name:        "EOS-1Ds Mark III",
		},
		"0x80000405": {
			ID:          "0x80000405",
			Name:        "EOS Rebel T7i / 800D / Kiss X9i",
		},
		"0x80000417": {
			ID:          "0x80000417",
		},
		"0x2750000": {
			ID:          "0x2750000",
			Name:        "PowerShot SX20 IS",
		},
		"0x80000213": {
			ID:          "0x80000213",
			Name:        "EOS 5D",
		},
		"0x3130000": {
			ID:          "0x3130000",
			Name:        "PowerShot SX40 HS",
		},
		"0x4160000": {
			ID:          "0x4160000",
			Name:        "PowerShot SX430 IS",
		},
		"0x2020000": {
			ID:          "0x2020000",
			Name:        "PowerShot A710 IS",
		},
		"0x2260000": {
			ID:          "0x2260000",
			Name:        "PowerShot A720 IS",
		},
		"0x2480000": {
			ID:          "0x2480000",
			Name:        "PowerShot A1000 IS",
		},
		"0x2860000": {
			ID:          "0x2860000",
			Name:        "PowerShot SD3500 IS / IXUS 210 / IXY 10S",
		},
		"0x4060000": {
			ID:          "0x4060000",
			Name:        "PowerShot SX620 HS",
		},
		"0x80000453": {
			ID:          "0x80000453",
		},
		"0x4070000": {
			ID:          "0x4070000",
			Name:        "EOS M6",
		},
		"0x4007D777": {
			ID:          "0x4007D777",
		},
		"0x80000167": {
			ID:          "0x80000167",
			Name:        "EOS-1DS",
		},
		"0x80000285": {
			ID:          "0x80000285",
			Name:        "EOS 5D Mark III",
		},
		"0x80000324": {
			ID:          "0x80000324",
		},
	},
}
