// Code generated by gen-tags. DO NOT EDIT.

package tags

// CanonColorData3Tags contains tag definitions from Image::ExifTool::Canon
var CanonColorData3Tags = TagTable{
	ModuleName: "Canon",
	Tags: map[string]TagDef{
		"0x3F": {
			ID:          "0x3F",
		},
		"0x61": {
			ID:          "0x61",
			Name:        "ColorTempTungsten",
		},
		"0x6B": {
			ID:          "0x6B",
			Name:        "ColorTempKelvin",
		},
		"0x7A": {
			ID:          "0x7A",
			Name:        "ColorTempPC2",
		},
		"IS_SUBDIR": {
			ID:          "IS_SUBDIR",
		},
		"0x48": {
			ID:          "0x48",
			Name:        "ColorTempAuto",
		},
		"0x52": {
			ID:          "0x52",
			Name:        "ColorTempDaylight",
		},
		"0x58": {
			ID:          "0x58",
		},
		"0x66": {
			ID:          "0x66",
			Name:        "ColorTempFluorescent",
		},
		"0x76": {
			ID:          "0x76",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int16s",
		},
		"0x53": {
			ID:          "0x53",
		},
		"0x5D": {
			ID:          "0x5D",
		},
		"0x6C": {
			ID:          "0x6C",
		},
		"0x57": {
			ID:          "0x57",
			Name:        "ColorTempShade",
		},
		"0x7B": {
			ID:          "0x7B",
		},
		"0x44": {
			ID:          "0x44",
		},
		"0x4D": {
			ID:          "0x4D",
			Name:        "ColorTempMeasured",
		},
		"0x5C": {
			ID:          "0x5C",
			Name:        "ColorTempCloudy",
		},
		"0x62": {
			ID:          "0x62",
		},
		"0x80": {
			ID:          "0x80",
		},
		"0x84": {
			ID:          "0x84",
			Name:        "ColorTempCustom",
		},
		"0x49": {
			ID:          "0x49",
		},
		"0x67": {
			ID:          "0x67",
		},
		"0x70": {
			ID:          "0x70",
			Name:        "ColorTempFlash",
		},
		"0x75": {
			ID:          "0x75",
			Name:        "ColorTempPC1",
		},
		"0x43": {
			ID:          "0x43",
			Name:        "ColorTempAsShot",
		},
		"0x4E": {
			ID:          "0x4E",
		},
		"0x71": {
			ID:          "0x71",
		},
		"0x7F": {
			ID:          "0x7F",
			Name:        "ColorTempPC3",
		},
	},
}
