// Code generated by gen-tags. DO NOT EDIT.

package tags

// CanonRawWhiteSampleTags contains tag definitions from Image::ExifTool::CanonRaw
var CanonRawWhiteSampleTags = TagTable{
	ModuleName: "CanonRaw",
	Tags: map[string]TagDef{
		"1": {
			ID:          "1",
			Name:        "WhiteSampleWidth",
		},
		"2": {
			ID:          "2",
			Name:        "WhiteSampleHeight",
		},
		"3": {
			ID:          "3",
			Name:        "WhiteSampleLeftBorder",
		},
		"4": {
			ID:          "4",
			Name:        "WhiteSampleTopBorder",
		},
		"5": {
			ID:          "5",
			Name:        "WhiteSampleBits",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int16u",
		},
	},
}
