// Code generated by gen-tags. DO NOT EDIT.

package tags

// CanonPSInfo2Tags contains tag definitions from Image::ExifTool::Canon
var CanonPSInfo2Tags = TagTable{
	ModuleName: "Canon",
	Tags: map[string]TagDef{
		"0x04": {
			ID:          "0x04",
		},
		"0x38": {
			ID:          "0x38",
		},
		"0x5C": {
			ID:          "0x5C",
		},
		"0x84": {
			ID:          "0x84",
		},
		"0xAC": {
			ID:          "0xAC",
		},
		"0xCC": {
			ID:          "0xCC",
		},
		"0x3C": {
			ID:          "0x3C",
		},
		"0x44": {
			ID:          "0x44",
		},
		"0xC8": {
			ID:          "0xC8",
		},
		"0xE0": {
			ID:          "0xE0",
		},
		"0x08": {
			ID:          "0x08",
		},
		"0x10": {
			ID:          "0x10",
		},
		"0x14": {
			ID:          "0x14",
		},
		"0x18": {
			ID:          "0x18",
		},
		"0x20": {
			ID:          "0x20",
		},
		"0x24": {
			ID:          "0x24",
		},
		"0x34": {
			ID:          "0x34",
		},
		"0x54": {
			ID:          "0x54",
		},
		"0x40": {
			ID:          "0x40",
		},
		"0x58": {
			ID:          "0x58",
		},
		"0x60": {
			ID:          "0x60",
		},
		"0x94": {
			ID:          "0x94",
		},
		"0x9C": {
			ID:          "0x9C",
		},
		"0xA8": {
			ID:          "0xA8",
		},
		"0xB4": {
			ID:          "0xB4",
		},
		"0xDC": {
			ID:          "0xDC",
		},
		"0x30": {
			ID:          "0x30",
		},
		"0x48": {
			ID:          "0x48",
		},
		"0x70": {
			ID:          "0x70",
		},
		"0x78": {
			ID:          "0x78",
		},
		"0x7C": {
			ID:          "0x7C",
		},
		"0xB0": {
			ID:          "0xB0",
		},
		"0xE4": {
			ID:          "0xE4",
		},
		"PRIORITY": {
			ID:          "PRIORITY",
		},
		"0x00": {
			ID:          "0x00",
		},
		"0x2C": {
			ID:          "0x2C",
		},
		"0x64": {
			ID:          "0x64",
		},
		"0x68": {
			ID:          "0x68",
		},
		"0x74": {
			ID:          "0x74",
		},
		"0xC4": {
			ID:          "0xC4",
		},
		"0x1C": {
			ID:          "0x1C",
		},
		"0x28": {
			ID:          "0x28",
		},
		"0x50": {
			ID:          "0x50",
		},
		"0x6C": {
			ID:          "0x6C",
		},
		"0x90": {
			ID:          "0x90",
		},
		"0xC0": {
			ID:          "0xC0",
		},
		"0xD8": {
			ID:          "0xD8",
		},
		"0x0C": {
			ID:          "0x0C",
		},
		"0x4C": {
			ID:          "0x4C",
		},
		"0x80": {
			ID:          "0x80",
		},
		"0x98": {
			ID:          "0x98",
		},
	},
}
