// Code generated by gen-tags. DO NOT EDIT.

package tags

// CanonFaceDetect2Tags contains tag definitions from Image::ExifTool::Canon
var CanonFaceDetect2Tags = TagTable{
	ModuleName: "Canon",
	Tags: map[string]TagDef{
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int8u",
		},
		"0x01": {
			ID:          "0x01",
			Name:        "FaceWidth",
		},
		"0x02": {
			ID:          "0x02",
			Name:        "FacesDetected",
		},
	},
}
