// Code generated by gen-tags. DO NOT EDIT.

package tags

// CanonLensInfoTags contains tag definitions from Image::ExifTool::Canon
var CanonLensInfoTags = TagTable{
	ModuleName: "Canon",
	Tags: map[string]TagDef{
	},
}
