// Code generated by gen-tags. DO NOT EDIT.

package tags

// CanonCameraInfoR6Tags contains tag definitions from Image::ExifTool::Canon
var CanonCameraInfoR6Tags = TagTable{
	ModuleName: "Canon",
	Tags: map[string]TagDef{
		"PRIORITY": {
			ID:          "PRIORITY",
		},
	},
}
