// Code generated by gen-tags. DO NOT EDIT.

package tags

// CanonVignettingCorrTags contains tag definitions from Image::ExifTool::Canon
var CanonVignettingCorrTags = TagTable{
	ModuleName: "Canon",
	Tags: map[string]TagDef{
		"9": {
			ID:          "9",
			Name:        "DistortionCorrectionValue",
		},
		"12": {
			ID:          "12",
			Name:        "OriginalImageHeight",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int16s",
		},
		"6": {
			ID:          "6",
			Name:        "PeripheralLightingValue",
		},
	},
}
