// Code generated by gen-tags. DO NOT EDIT.

package tags

// CanonAFInfoTags contains tag definitions from Image::ExifTool::Canon
var CanonAFInfoTags = TagTable{
	ModuleName: "Canon",
	Tags: map[string]TagDef{
		"5": {
			ID:          "5",
			Name:        "AFImageHeight",
		},
		"6": {
			ID:          "6",
			Name:        "AFAreaWidth",
		},
		"7": {
			ID:          "7",
			Name:        "AFAreaHeight",
		},
		"12": {
			ID:          "12",
			Name:        "PrimaryAFPoint",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int16u",
		},
	},
}
