// Code generated by gen-tags. DO NOT EDIT.

package tags

// CanonVRDEdit4Tags contains tag definitions from Image::ExifTool::CanonVRD
var CanonVRDEdit4Tags = TagTable{
	ModuleName: "CanonVRD",
	Tags: map[string]TagDef{
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
	},
}
