// Code generated by gen-tags. DO NOT EDIT.

package tags

// CanonFlagsTags contains tag definitions from Image::ExifTool::Canon
var CanonFlagsTags = TagTable{
	ModuleName: "Canon",
	Tags: map[string]TagDef{
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int16s",
		},
		"1": {
			ID:          "1",
			Name:        "ModifiedParamFlag",
		},
	},
}
