// Code generated by gen-tags. DO NOT EDIT.

package tags

// CanonVignettingCorr2Tags contains tag definitions from Image::ExifTool::Canon
var CanonVignettingCorr2Tags = TagTable{
	ModuleName: "Canon",
	Tags: map[string]TagDef{
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int32s",
		},
	},
}
