// Code generated by gen-tags. DO NOT EDIT.

package tags

// CanonuuidTags contains tag definitions from Image::ExifTool::Canon
var CanonuuidTags = TagTable{
	ModuleName: "Canon",
	Tags: map[string]TagDef{
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
			Name:        "Image::ExifTool::QuickTime::WriteQuickTime",
		},
	},
}
