// Code generated by gen-tags. DO NOT EDIT.

package tags

// CanonColorData2Tags contains tag definitions from Image::ExifTool::Canon
var CanonColorData2Tags = TagTable{
	ModuleName: "Canon",
	Tags: map[string]TagDef{
		"0x35": {
			ID:          "0x35",
			Name:        "ColorTempCloudy",
		},
		"0x5D": {
			ID:          "0x5D",
		},
		"0x67": {
			ID:          "0x67",
		},
		"0x72": {
			ID:          "0x72",
		},
		"0x7C": {
			ID:          "0x7C",
		},
		"0x4E": {
			ID:          "0x4E",
		},
		"0x76": {
			ID:          "0x76",
		},
		"0x68": {
			ID:          "0x68",
		},
		"0x86": {
			ID:          "0x86",
		},
		"0x8A": {
			ID:          "0x8A",
		},
		"0x4A": {
			ID:          "0x4A",
		},
		"0x54": {
			ID:          "0x54",
		},
		"0x30": {
			ID:          "0x30",
			Name:        "ColorTempShade",
		},
		"0x40": {
			ID:          "0x40",
		},
		"0x59": {
			ID:          "0x59",
		},
		"0x7B": {
			ID:          "0x7B",
		},
		"0x8B": {
			ID:          "0x8B",
		},
		"0x9A": {
			ID:          "0x9A",
		},
		"0x3A": {
			ID:          "0x3A",
			Name:        "ColorTempTungsten",
		},
		"0x3F": {
			ID:          "0x3F",
			Name:        "ColorTempFluorescent",
		},
		"0x49": {
			ID:          "0x49",
			Name:        "ColorTempFlash",
		},
		"0x8F": {
			ID:          "0x8F",
		},
		"0xA3": {
			ID:          "0xA3",
		},
		"0x1C": {
			ID:          "0x1C",
			Name:        "ColorTempAuto",
		},
		"0x27": {
			ID:          "0x27",
		},
		"0x4F": {
			ID:          "0x4F",
		},
		"0x77": {
			ID:          "0x77",
		},
		"0x94": {
			ID:          "0x94",
			Name:        "ColorTempPC1",
		},
		"0x3B": {
			ID:          "0x3B",
		},
		"0x85": {
			ID:          "0x85",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int16s",
		},
		"0x95": {
			ID:          "0x95",
		},
		"0x2B": {
			ID:          "0x2B",
			Name:        "ColorTempDaylight",
		},
		"0x2C": {
			ID:          "0x2C",
		},
		"0x31": {
			ID:          "0x31",
		},
		"0x58": {
			ID:          "0x58",
		},
		"0x9F": {
			ID:          "0x9F",
		},
		"0x45": {
			ID:          "0x45",
		},
		"0x80": {
			ID:          "0x80",
		},
		"0x26": {
			ID:          "0x26",
			Name:        "ColorTempAsShot",
		},
		"0x6C": {
			ID:          "0x6C",
		},
		"0x71": {
			ID:          "0x71",
		},
		"0x81": {
			ID:          "0x81",
		},
		"0x18": {
			ID:          "0x18",
		},
		"0x1D": {
			ID:          "0x1D",
		},
		"0x99": {
			ID:          "0x99",
			Name:        "ColorTempPC2",
		},
		"0x22": {
			ID:          "0x22",
		},
		"0x44": {
			ID:          "0x44",
			Name:        "ColorTempKelvin",
		},
		"0x53": {
			ID:          "0x53",
		},
		"0x63": {
			ID:          "0x63",
		},
		"0x6D": {
			ID:          "0x6D",
		},
		"0x90": {
			ID:          "0x90",
		},
		"0x5E": {
			ID:          "0x5E",
		},
		"IS_SUBDIR": {
			ID:          "IS_SUBDIR",
		},
		"0x21": {
			ID:          "0x21",
		},
		"0x36": {
			ID:          "0x36",
		},
		"0x62": {
			ID:          "0x62",
		},
		"0x9E": {
			ID:          "0x9E",
			Name:        "ColorTempPC3",
		},
	},
}
