// Code generated by gen-tags. DO NOT EDIT.

package tags

// CanonVRDVer1Tags contains tag definitions from Image::ExifTool::CanonVRD
var CanonVRDVer1Tags = TagTable{
	ModuleName: "CanonVRD",
	Tags: map[string]TagDef{
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"WRITABLE": {
			ID:          "WRITABLE",
		},
		"PERMANENT": {
			ID:          "PERMANENT",
		},
		"DATAMEMBER": {
			ID:          "DATAMEMBER",
		},
	},
}
