// Code generated by gen-tags. DO NOT EDIT.

package tags

// CanonCameraInfoUnknown32Tags contains tag definitions from Image::ExifTool::Canon
var CanonCameraInfoUnknown32Tags = TagTable{
	ModuleName: "Canon",
	Tags: map[string]TagDef{
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int32s",
		},
		"PRIORITY": {
			ID:          "PRIORITY",
		},
	},
}
