// Code generated by gen-tags. DO NOT EDIT.

package tags

// CanonCameraInfoPowerShot2Tags contains tag definitions from Image::ExifTool::Canon
var CanonCameraInfoPowerShot2Tags = TagTable{
	ModuleName: "Canon",
	Tags: map[string]TagDef{
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int32s",
		},
		"PRIORITY": {
			ID:          "PRIORITY",
		},
		"0x18": {
			ID:          "0x18",
			Name:        "Rotation",
		},
	},
}
