// Code generated by gen-tags. DO NOT EDIT.

package tags

// CanonCMP1Tags contains tag definitions from Image::ExifTool::Canon
var CanonCMP1Tags = TagTable{
	ModuleName: "Canon",
	Tags: map[string]TagDef{
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int16u",
		},
		"PRIORITY": {
			ID:          "PRIORITY",
		},
		"8": {
			ID:          "8",
		},
		"10": {
			ID:          "10",
		},
	},
}
