// Code generated by gen-tags. DO NOT EDIT.

package tags

// CanonCustomPersonalFuncsTags contains tag definitions from Image::ExifTool::CanonCustom
var CanonCustomPersonalFuncsTags = TagTable{
	ModuleName: "CanonCustom",
	Tags: map[string]TagDef{
		"3": {
			ID:          "3",
		},
		"18": {
			ID:          "18",
		},
		"29": {
			ID:          "29",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"9": {
			ID:          "9",
		},
		"26": {
			ID:          "26",
		},
		"28": {
			ID:          "28",
		},
		"32": {
			ID:          "32",
		},
		"11": {
			ID:          "11",
		},
		"19": {
			ID:          "19",
		},
		"20": {
			ID:          "20",
		},
		"21": {
			ID:          "21",
		},
		"25": {
			ID:          "25",
		},
		"17": {
			ID:          "17",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int16u",
		},
		"2": {
			ID:          "2",
		},
		"7": {
			ID:          "7",
		},
		"22": {
			ID:          "22",
		},
		"24": {
			ID:          "24",
		},
		"31": {
			ID:          "31",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"WRITABLE": {
			ID:          "WRITABLE",
		},
		"4": {
			ID:          "4",
		},
		"5": {
			ID:          "5",
		},
		"14": {
			ID:          "14",
		},
		"15": {
			ID:          "15",
		},
		"1": {
			ID:          "1",
		},
		"6": {
			ID:          "6",
		},
		"10": {
			ID:          "10",
		},
		"8": {
			ID:          "8",
		},
		"16": {
			ID:          "16",
		},
		"27": {
			ID:          "27",
		},
		"30": {
			ID:          "30",
		},
	},
}
