// Code generated by gen-tags. DO NOT EDIT.

package tags

// CanonMeasuredColorTags contains tag definitions from Image::ExifTool::Canon
var CanonMeasuredColorTags = TagTable{
	ModuleName: "Canon",
	Tags: map[string]TagDef{
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int16u",
		},
	},
}
