// Code generated by gen-tags. DO NOT EDIT.

package tags

// CanonCameraInfo1DmkIVTags contains tag definitions from Image::ExifTool::Canon
var CanonCameraInfo1DmkIVTags = TagTable{
	ModuleName: "Canon",
	Tags: map[string]TagDef{
		"0x04": {
			ID:          "0x04",
		},
		"0x06": {
			ID:          "0x06",
		},
		"0x19": {
			ID:          "0x19",
		},
		"0x1E": {
			ID:          "0x1E",
		},
		"0x151": {
			ID:          "0x151",
		},
		"PRIORITY": {
			ID:          "PRIORITY",
		},
		"DATAMEMBER": {
			ID:          "DATAMEMBER",
		},
		"IS_SUBDIR": {
			ID:          "IS_SUBDIR",
		},
		"0x03": {
			ID:          "0x03",
		},
	},
}
