// Code generated by gen-tags. DO NOT EDIT.

package tags

// CanonRawcrwTagFormatTags contains tag definitions from Image::ExifTool::CanonRaw
var CanonRawcrwTagFormatTags = TagTable{
	ModuleName: "CanonRaw",
	Tags: map[string]TagDef{
		"0x00": {
			ID:          "0x00",
			Name:        "int8u",
		},
		"0x08": {
			ID:          "0x08",
			Name:        "string",
		},
		"0x10": {
			ID:          "0x10",
			Name:        "int16u",
		},
		"0x18": {
			ID:          "0x18",
			Name:        "int32u",
		},
	},
}
