// Code generated by gen-tags. DO NOT EDIT.

package tags

// CanonCameraSettingsTags contains tag definitions from Image::ExifTool::Canon
var CanonCameraSettingsTags = TagTable{
	ModuleName: "Canon",
	Tags: map[string]TagDef{
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int16s",
		},
		"DATAMEMBER": {
			ID:          "DATAMEMBER",
		},
		"36": {
			ID:          "36",
		},
		"37": {
			ID:          "37",
		},
	},
}
