// Code generated by gen-tags. DO NOT EDIT.

package tags

// CanonCameraInfo1DXTags contains tag definitions from Image::ExifTool::Canon
var CanonCameraInfo1DXTags = TagTable{
	ModuleName: "Canon",
	Tags: map[string]TagDef{
		"0x03": {
			ID:          "0x03",
		},
		"0x23": {
			ID:          "0x23",
		},
		"0x1A9": {
			ID:          "0x1A9",
		},
		"0x04": {
			ID:          "0x04",
		},
		"0x06": {
			ID:          "0x06",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int8u",
		},
		"PRIORITY": {
			ID:          "PRIORITY",
		},
		"DATAMEMBER": {
			ID:          "DATAMEMBER",
		},
		"IS_SUBDIR": {
			ID:          "IS_SUBDIR",
		},
	},
}
