// Code generated by gen-tags. DO NOT EDIT.

package tags

// CanonCNOPTags contains tag definitions from Image::ExifTool::Canon
var CanonCNOPTags = TagTable{
	ModuleName: "Canon",
	Tags: map[string]TagDef{
	},
}
