// Code generated by gen-tags. DO NOT EDIT.

package tags

// CanonCameraInfoPowerShotTags contains tag definitions from Image::ExifTool::Canon
var CanonCameraInfoPowerShotTags = TagTable{
	ModuleName: "Canon",
	Tags: map[string]TagDef{
		"0x17": {
			ID:          "0x17",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int32s",
		},
		"PRIORITY": {
			ID:          "PRIORITY",
		},
	},
}
