// Code generated by gen-tags. DO NOT EDIT.

package tags

// CanonCameraInfoG5XIITags contains tag definitions from Image::ExifTool::Canon
var CanonCameraInfoG5XIITags = TagTable{
	ModuleName: "Canon",
	Tags: map[string]TagDef{
		"PRIORITY": {
			ID:          "PRIORITY",
		},
	},
}
