// Code generated by gen-tags. DO NOT EDIT.

package tags

// CasioAVITags contains tag definitions from Image::ExifTool::Casio
var CasioAVITags = TagTable{
	ModuleName: "Casio",
	Tags: map[string]TagDef{
	},
}
