// Code generated by gen-tags. DO NOT EDIT.

package tags

// CasioFaceInfo2Tags contains tag definitions from Image::ExifTool::Casio
var CasioFaceInfo2Tags = TagTable{
	ModuleName: "Casio",
	Tags: map[string]TagDef{
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"WRITABLE": {
			ID:          "WRITABLE",
		},
		"DATAMEMBER": {
			ID:          "DATAMEMBER",
		},
	},
}
