// Code generated by gen-tags. DO NOT EDIT.

package tags

// CBORMainTags contains tag definitions from Image::ExifTool::CBOR
var CBORMainTags = TagTable{
	ModuleName: "CBOR",
	Tags: map[string]TagDef{
		"authorName": {
			ID:          "authorName",
		},
		"thumbnailHash": {
			ID:          "thumbnailHash",
		},
		"dc:format": {
			ID:          "dc:format",
			Name:        "Format",
		},
		"authorIdentifier": {
			ID:          "authorIdentifier",
		},
		"documentID": {
			ID:          "documentID",
		},
		"instanceID": {
			ID:          "instanceID",
		},
		"thumbnailUrl": {
			ID:          "thumbnailUrl",
		},
		"relationship": {
			ID:          "relationship",
		},
		"dc:title": {
			ID:          "dc:title",
			Name:        "Title",
		},
	},
}
