// Code generated by gen-tags. DO NOT EDIT.

package tags

// csTranslateTags contains tag definitions from Image::ExifTool::Lang::cs
var csTranslateTags = TagTable{
	ModuleName: "cs",
	Tags: map[string]TagDef{
		"Opto-ElectricConvFactor": {
			ID:          "Opto-ElectricConvFactor",
			Name:        "Optoel. konverzní faktor (OECF)",
		},
		"Title": {
			ID:          "Title",
			Name:        "Název",
		},
		"XPComment": {
			ID:          "XPComment",
			Name:        "Komentář",
		},
		"CellLength": {
			ID:          "CellLength",
			Name:        "Délka buňky",
		},
		"GPSDateStamp": {
			ID:          "GPSDateStamp",
			Name:        "GPS Datum",
		},
		"InkNames": {
			ID:          "InkNames",
			Name:        "Název náplně",
		},
		"PreviewImage": {
			ID:          "PreviewImage",
			Name:        "Náhled",
		},
		"RelatedImageHeight": {
			ID:          "RelatedImageHeight",
			Name:        "Výška obrázku",
		},
		"TransferFunction": {
			ID:          "TransferFunction",
			Name:        "Transfer funkce",
		},
		"SubSecTimeOriginal": {
			ID:          "SubSecTimeOriginal",
			Name:        "DateTimeOriginal 1/100 sekund",
		},
		"Brightness": {
			ID:          "Brightness",
			Name:        "Jas",
		},
		"ExifToolVersion": {
			ID:          "ExifToolVersion",
			Name:        "ExifTool verze",
		},
		"Index": {
			ID:          "Index",
			Name:        "Nápověda",
		},
		"SpatialFrequencyResponse": {
			ID:          "SpatialFrequencyResponse",
			Name:        "Spatial frequency response",
		},
		"Urgency": {
			ID:          "Urgency",
			Name:        "Naléhavost",
		},
		"YCbCrSubSampling": {
			ID:          "YCbCrSubSampling",
			Name:        "Vzorkovací poměr Y k C",
		},
		"Category": {
			ID:          "Category",
			Name:        "Kategorie",
		},
		"ColorMap": {
			ID:          "ColorMap",
			Name:        "Barevná mapa",
		},
		"FaxRecvTime": {
			ID:          "FaxRecvTime",
			Name:        "Čas příjmu faxu",
		},
		"CellWidth": {
			ID:          "CellWidth",
			Name:        "Šířka buňky",
		},
		"Keyword": {
			ID:          "Keyword",
			Name:        "Klíčová slova",
		},
		"ExpandFilm": {
			ID:          "ExpandFilm",
			Name:        "Ext. film",
		},
		"SVGVersion": {
			ID:          "SVGVersion",
			Name:        "SVG verze",
		},
		"Aperture": {
			ID:          "Aperture",
			Name:        "Clona",
		},
		"ExpandLens": {
			ID:          "ExpandLens",
			Name:        "Ext. objektiv",
		},
		"GPSMapDatum": {
			ID:          "GPSMapDatum",
			Name:        "Geodetická data",
		},
		"T6Options": {
			ID:          "T6Options",
			Name:        "Volby T6",
		},
		"XMP": {
			ID:          "XMP",
			Name:        "XMP metadata",
		},
		"ImageDescription": {
			ID:          "ImageDescription",
			Name:        "Popis obrázku",
		},
		"Lens": {
			ID:          "Lens",
			Name:        "Objektiv",
		},
		"XPKeywords": {
			ID:          "XPKeywords",
			Name:        "Klíčová slova",
		},
		"DateCreated": {
			ID:          "DateCreated",
			Name:        "Datum vytvoření",
		},
		"FlashpixVersion": {
			ID:          "FlashpixVersion",
			Name:        "Podporovaná verze Flashpix",
		},
		"InteropVersion": {
			ID:          "InteropVersion",
			Name:        "Verze kompatibility",
		},
		"GPSDestDistance": {
			ID:          "GPSDestDistance",
			Name:        "Vzdálenost k cíli",
		},
		"Instructions": {
			ID:          "Instructions",
			Name:        "Pokyny",
		},
		"SamplesPerPixel": {
			ID:          "SamplesPerPixel",
			Name:        "Počet složek",
		},
		"ExifOffset": {
			ID:          "ExifOffset",
			Name:        "Ukazatel Exif IFD",
		},
		"GIFVersion": {
			ID:          "GIFVersion",
			Name:        "GIF verze",
		},
		"GPSVersionID": {
			ID:          "GPSVersionID",
			Name:        "Verze GPS TAGu",
		},
		"RelatedSoundFile": {
			ID:          "RelatedSoundFile",
			Name:        "Audio soubor",
		},
		"VRDVersion": {
			ID:          "VRDVersion",
			Name:        "VRD verze",
		},
		"FocalLength": {
			ID:          "FocalLength",
			Name:        "Ohnisková vzdálenost",
		},
		"IPTC-NAA": {
			ID:          "IPTC-NAA",
			Name:        "IPTC-NAA metadata",
		},
		"ShutterSpeedValue": {
			ID:          "ShutterSpeedValue",
			Name:        "Čas závěrky",
		},
		"MakerNote": {
			ID:          "MakerNote",
			Name:        "Privátní data výrobce",
		},
		"RelatedImageWidth": {
			ID:          "RelatedImageWidth",
			Name:        "Šířka obrázku",
		},
		"DigitalZoomRatio": {
			ID:          "DigitalZoomRatio",
			Name:        "Digitální zoom",
		},
		"ShutterSpeed": {
			ID:          "ShutterSpeed",
			Name:        "Expoziční čas",
		},
		"FocalLengthIn35mmFormat": {
			ID:          "FocalLengthIn35mmFormat",
			Name:        "Přepočtená ohnisková vzdálenost (35mm)",
		},
		"GPSDateTime": {
			ID:          "GPSDateTime",
			Name:        "GPS čas (atomový čas)",
		},
		"XPAuthor": {
			ID:          "XPAuthor",
			Name:        "Autor",
		},
		"FrameRate": {
			ID:          "FrameRate",
			Name:        "Snímkovací frekvence",
		},
		"GPSDestBearing": {
			ID:          "GPSDestBearing",
			Name:        "Azimut cíle",
		},
		"Rating": {
			ID:          "Rating",
			Name:        "Hodnocení",
		},
		"Subject": {
			ID:          "Subject",
			Name:        "Popis",
		},
		"WhitePoint": {
			ID:          "WhitePoint",
			Name:        "Chromatičnost bílého bodu",
		},
		"GPSDOP": {
			ID:          "GPSDOP",
			Name:        "Přesnost měření",
		},
		"SubSecTimeDigitized": {
			ID:          "SubSecTimeDigitized",
			Name:        "DateTimeDigitized 1/100 sekund",
		},
		"SubjectArea": {
			ID:          "SubjectArea",
			Name:        "Pozice hlavního objektu",
		},
		"TileOffsets": {
			ID:          "TileOffsets",
			Name:        "Offset prvku",
		},
		"ApertureValue": {
			ID:          "ApertureValue",
			Name:        "Clona",
		},
		"CompressedBitsPerPixel": {
			ID:          "CompressedBitsPerPixel",
			Name:        "Komprimační mod",
		},
		"Location": {
			ID:          "Location",
			Name:        "Lokalita",
		},
		"ModifyDate": {
			ID:          "ModifyDate",
			Name:        "Datum a čas změny souboru",
		},
		"CopyrightNotice": {
			ID:          "CopyrightNotice",
			Name:        "Oznámení o autorských právech",
		},
		"HalftoneHints": {
			ID:          "HalftoneHints",
			Name:        "Půltóny",
		},
		"SubSecModifyDate": {
			ID:          "SubSecModifyDate",
			Name:        "Datum a čas změny souboru",
		},
		"XPSubject": {
			ID:          "XPSubject",
			Name:        "Popis",
		},
		"CaptionWriter": {
			ID:          "CaptionWriter",
			Name:        "Autor popisku",
		},
		"DocumentName": {
			ID:          "DocumentName",
			Name:        "Jméno dokumentu",
		},
		"Model2": {
			ID:          "Model2",
			Name:        "Typ zařízení (2)",
		},
		"SelfTimerMode": {
			ID:          "SelfTimerMode",
			Name:        "Samospoušť",
		},
		"CFARepeatPatternDim": {
			ID:          "CFARepeatPatternDim",
			Name:        "Velikost berevné matice CFA",
		},
		"StripOffsets": {
			ID:          "StripOffsets",
			Name:        "Pozice obrazových dat",
		},
		"SubSecDateTimeOriginal": {
			ID:          "SubSecDateTimeOriginal",
			Name:        "Datum a čas vzniku originálních dat",
		},
		"ThumbnailImageSize": {
			ID:          "ThumbnailImageSize",
			Name:        "Velkost náhledu",
		},
		"UserComment": {
			ID:          "UserComment",
			Name:        "Komentář",
		},
		"ExposureTime2": {
			ID:          "ExposureTime2",
			Name:        "Expoziční čas 2",
		},
		"GPSAltitude": {
			ID:          "GPSAltitude",
			Name:        "Nadmořská výška",
		},
		"RatingPercent": {
			ID:          "RatingPercent",
			Name:        "Hodnocení v procentech",
		},
		"CreationDate": {
			ID:          "CreationDate",
			Name:        "Datum vytvoření",
		},
		"MaxAperture": {
			ID:          "MaxAperture",
			Name:        "Maximální clona+C1233 objektivu",
		},
		"RowsPerStrip": {
			ID:          "RowsPerStrip",
			Name:        "Počet řádek v části",
		},
		"ThumbnailImage": {
			ID:          "ThumbnailImage",
			Name:        "Náhled",
		},
		"Credit": {
			ID:          "Credit",
			Name:        "Kredit",
		},
		"GPSImgDirection": {
			ID:          "GPSImgDirection",
			Name:        "Orientace obrázku",
		},
		"MaxApertureValue": {
			ID:          "MaxApertureValue",
			Name:        "Max clona objektivu",
		},
		"DriveMode": {
			ID:          "DriveMode",
			Name:        "Režim spouště",
		},
		"PageNumber": {
			ID:          "PageNumber",
			Name:        "Číslo stránky",
		},
		"TileByteCounts": {
			ID:          "TileByteCounts",
			Name:        "Počet bytů prvku",
		},
		"JFIFVersion": {
			ID:          "JFIFVersion",
			Name:        "JFIF verze",
		},
		"FileType": {
			ID:          "FileType",
			Name:        "Typ",
		},
		"Model": {
			ID:          "Model",
			Name:        "Typ fotoaparátu",
		},
		"RelatedImageFileFormat": {
			ID:          "RelatedImageFileFormat",
			Name:        "Obrazový formát",
		},
		"YPosition": {
			ID:          "YPosition",
			Name:        "Y-pozice",
		},
		"Copyright": {
			ID:          "Copyright",
			Name:        "Držitel práv",
		},
		"Directory": {
			ID:          "Directory",
			Name:        "Umístění souboru",
		},
		"FlashExposureComp": {
			ID:          "FlashExposureComp",
			Name:        "Kompenzace blesku",
		},
		"FreeByteCounts": {
			ID:          "FreeByteCounts",
			Name:        "Počet volných bytů",
		},
		"SubjectLocation": {
			ID:          "SubjectLocation",
			Name:        "Pozice hlavního objektu",
		},
		"APEVersion": {
			ID:          "APEVersion",
			Name:        "APE verze",
		},
		"ConsecutiveBadFaxLines": {
			ID:          "ConsecutiveBadFaxLines",
			Name:        "Sekvence vadných faxových řádků",
		},
		"FocalLength35efl": {
			ID:          "FocalLength35efl",
			Name:        "Ohnisková vzdálenost",
		},
		"HostComputer": {
			ID:          "HostComputer",
			Name:        "Host",
		},
		"ShadingCompensation": {
			ID:          "ShadingCompensation",
			Name:        "Kompenzace stínování",
		},
		"CFAPattern": {
			ID:          "CFAPattern",
			Name:        "CFA matrice",
		},
		"GrayResponseCurve": {
			ID:          "GrayResponseCurve",
			Name:        "Šedá referenční křivka",
		},
		"Make": {
			ID:          "Make",
			Name:        "Výrobce",
		},
		"RAFVersion": {
			ID:          "RAFVersion",
			Name:        "RAF verze",
		},
		"Categories": {
			ID:          "Categories",
			Name:        "Kategorie",
		},
		"MakerNotes": {
			ID:          "MakerNotes",
			Name:        "Poznámka výrobce",
		},
		"OldSubfileType": {
			ID:          "OldSubfileType",
			Name:        "Typ podsekce",
		},
		"PhotoshopAnnotations": {
			ID:          "PhotoshopAnnotations",
			Name:        "Poznámky Photoshop",
		},
		"TileWidth": {
			ID:          "TileWidth",
			Name:        "Šířka prvku",
		},
		"Thresholding": {
			ID:          "Thresholding",
			Name:        "Práh",
		},
		"TileLength": {
			ID:          "TileLength",
			Name:        "Délka prvku",
		},
		"BrightnessValue": {
			ID:          "BrightnessValue",
			Name:        "Jas",
		},
		"CFAPattern2": {
			ID:          "CFAPattern2",
			Name:        "CFA matice 2",
		},
		"FNumber": {
			ID:          "FNumber",
			Name:        "F hodnota",
		},
		"LensInfo": {
			ID:          "LensInfo",
			Name:        "Informace o optice",
		},
		"ReferenceBlackWhite": {
			ID:          "ReferenceBlackWhite",
			Name:        "Černý a bílý referenční bod",
		},
		"SubSecCreateDate": {
			ID:          "SubSecCreateDate",
			Name:        "Datum a čas generování digitálních dat",
		},
		"ExposureIndex": {
			ID:          "ExposureIndex",
			Name:        "Index expozice",
		},
		"Source": {
			ID:          "Source",
			Name:        "Zdroj",
		},
		"TransmissionReference": {
			ID:          "TransmissionReference",
			Name:        "Reference přenosu",
		},
		"ExifImageWidth": {
			ID:          "ExifImageWidth",
			Name:        "Šířka",
		},
		"ExpandSoftware": {
			ID:          "ExpandSoftware",
			Name:        "Ext. Software",
		},
		"FocalPlaneYResolution": {
			ID:          "FocalPlaneYResolution",
			Name:        "Vertikální rozlišení senzoru",
		},
		"Headline": {
			ID:          "Headline",
			Name:        "Titulek",
		},
		"ImageHistory": {
			ID:          "ImageHistory",
			Name:        "Historie obrázku",
		},
		"MIEVersion": {
			ID:          "MIEVersion",
			Name:        "MIE verze",
		},
		"YResolution": {
			ID:          "YResolution",
			Name:        "Rozlišení obrázku na výšku",
		},
		"ColorTemperature": {
			ID:          "ColorTemperature",
			Name:        "Teplota barev",
		},
		"Country-PrimaryLocationName": {
			ID:          "Country-PrimaryLocationName",
			Name:        "Země",
		},
		"GPSProcessingMethod": {
			ID:          "GPSProcessingMethod",
			Name:        "Název procesní metody GPS",
		},
		"GPSLongitude": {
			ID:          "GPSLongitude",
			Name:        "Zeměpisná délka",
		},
		"ISO": {
			ID:          "ISO",
			Name:        "Citlivost ISO",
		},
		"BatteryLevel": {
			ID:          "BatteryLevel",
			Name:        "Stav baterie",
		},
		"ExpandFlashLamp": {
			ID:          "ExpandFlashLamp",
			Name:        "Ext. světlo blesku",
		},
		"GPSLatitude": {
			ID:          "GPSLatitude",
			Name:        "Zeměpisná šířka",
		},
		"ImageSourceData": {
			ID:          "ImageSourceData",
			Name:        "Zdrojová data obrázku",
		},
		"Lightness": {
			ID:          "Lightness",
			Name:        "Jas",
		},
		"GPSInfo": {
			ID:          "GPSInfo",
			Name:        "IFD ukazatel v GPS informacích",
		},
		"Version": {
			ID:          "Version",
			Name:        "Verze",
		},
		"BadFaxLines": {
			ID:          "BadFaxLines",
			Name:        "Špatné faxové řádky",
		},
		"ExpandScanner": {
			ID:          "ExpandScanner",
			Name:        "Ext. skener",
		},
		"Software": {
			ID:          "Software",
			Name:        "Použitý software",
		},
		"Filename": {
			ID:          "Filename",
			Name:        "Jméno",
		},
		"FocalPlaneXResolution": {
			ID:          "FocalPlaneXResolution",
			Name:        "Horizontální rozlišení senzoru",
		},
		"GPSAreaInformation": {
			ID:          "GPSAreaInformation",
			Name:        "Název GPS oblasti",
		},
		"LeafData": {
			ID:          "LeafData",
			Name:        "Leaf data",
		},
		"Noise": {
			ID:          "Noise",
			Name:        "Šum",
		},
		"ComponentsConfiguration": {
			ID:          "ComponentsConfiguration",
			Name:        "Určení složek",
		},
		"DateTimeOriginal": {
			ID:          "DateTimeOriginal",
			Name:        "Datum a čas vzniku originálních dat",
		},
		"ExposureTime": {
			ID:          "ExposureTime",
			Name:        "Expoziční čas",
		},
		"ImageNumber": {
			ID:          "ImageNumber",
			Name:        "Číslo obrázku",
		},
		"InteropOffset": {
			ID:          "InteropOffset",
			Name:        "Značka součinnosti",
		},
		"Province-State": {
			ID:          "Province-State",
			Name:        "Stát/provincie",
		},
		"Artist": {
			ID:          "Artist",
			Name:        "Autor",
		},
		"AuthorsPosition": {
			ID:          "AuthorsPosition",
			Name:        "Pozice autora",
		},
		"ExifVersion": {
			ID:          "ExifVersion",
			Name:        "Exif verze",
		},
		"FreeOffsets": {
			ID:          "FreeOffsets",
			Name:        "Volná datová pozice",
		},
		"SubfileType": {
			ID:          "SubfileType",
			Name:        "Nový typ podsekce",
		},
		"SubjectDistance": {
			ID:          "SubjectDistance",
			Name:        "Vzdálenost objektu",
		},
		"TargetPrinter": {
			ID:          "TargetPrinter",
			Name:        "Cílová tiskárna",
		},
		"By-line": {
			ID:          "By-line",
			Name:        "Autor",
		},
		"ImageHeight": {
			ID:          "ImageHeight",
			Name:        "Výška",
		},
		"MinSampleValue": {
			ID:          "MinSampleValue",
			Name:        "Min. hodnota vzorku",
		},
		"PEFVersion": {
			ID:          "PEFVersion",
			Name:        "PEF verze",
		},
		"SPIFFVersion": {
			ID:          "SPIFFVersion",
			Name:        "SPIFF verze",
		},
		"Annotations": {
			ID:          "Annotations",
			Name:        "Poznámky Photoshop",
		},
		"City": {
			ID:          "City",
			Name:        "Město",
		},
		"ColorResponseUnit": {
			ID:          "ColorResponseUnit",
			Name:        "Odpovídající barevná jednotka",
		},
		"FileModifyDate": {
			ID:          "FileModifyDate",
			Name:        "Datum úpravy",
		},
		"FileSize": {
			ID:          "FileSize",
			Name:        "Velikost",
		},
		"Hue": {
			ID:          "Hue",
			Name:        "Odstín",
		},
		"StripByteCounts": {
			ID:          "StripByteCounts",
			Name:        "Bytů na komprimovanou část",
		},
		"FaxRecvParams": {
			ID:          "FaxRecvParams",
			Name:        "Parametry příjemce faxu",
		},
		"GPSDestLatitude": {
			ID:          "GPSDestLatitude",
			Name:        "Zeměpisná šířka cíle",
		},
		"GPSSatellites": {
			ID:          "GPSSatellites",
			Name:        "GPS satelity využité při měření",
		},
		"ColorFilter": {
			ID:          "ColorFilter",
			Name:        "Barevný filtr",
		},
		"GPSTimeStamp": {
			ID:          "GPSTimeStamp",
			Name:        "GPS čas (atomový čas)",
		},
		"DjVuVersion": {
			ID:          "DjVuVersion",
			Name:        "DjVu verze",
		},
		"FileFormat": {
			ID:          "FileFormat",
			Name:        "Formát",
		},
		"GPSTrack": {
			ID:          "GPSTrack",
			Name:        "Směr pohybu",
		},
		"State": {
			ID:          "State",
			Name:        "Stát",
		},
		"Writer-Editor": {
			ID:          "Writer-Editor",
			Name:        "Autor popisku",
		},
		"YCbCrCoefficients": {
			ID:          "YCbCrCoefficients",
			Name:        "Koeficienty transformační YCbCr matrice",
		},
		"Caption-Abstract": {
			ID:          "Caption-Abstract",
			Name:        "Popisek",
		},
		"DeviceSettingDescription": {
			ID:          "DeviceSettingDescription",
			Name:        "Popis nastavení zařízení",
		},
		"ICCProfile": {
			ID:          "ICCProfile",
			Name:        "ICC-Profil",
		},
		"ImageUniqueID": {
			ID:          "ImageUniqueID",
			Name:        "Jedinečné ID obrázku",
		},
		"Padding": {
			ID:          "Padding",
			Name:        "Náhradní znaky",
		},
		"SerialNumber": {
			ID:          "SerialNumber",
			Name:        "ID fotoaparátu",
		},
		"DateTime": {
			ID:          "DateTime",
			Name:        "Datum a čas změny souboru",
		},
		"SpectralSensitivity": {
			ID:          "SpectralSensitivity",
			Name:        "Spektrální citlivost",
		},
		"XPTitle": {
			ID:          "XPTitle",
			Name:        "Název",
		},
		"XResolution": {
			ID:          "XResolution",
			Name:        "Rozlišení obrázku na šířku",
		},
		"DotRange": {
			ID:          "DotRange",
			Name:        "Bodová rozteč",
		},
		"MaxSampleValue": {
			ID:          "MaxSampleValue",
			Name:        "Max. hodnota vzorku",
		},
		"XPosition": {
			ID:          "XPosition",
			Name:        "X-pozice",
		},
		"GPSSpeed": {
			ID:          "GPSSpeed",
			Name:        "Rychlost GPS přijímače",
		},
		"PrimaryChromaticities": {
			ID:          "PrimaryChromaticities",
			Name:        "Chromatičnost primárních barev",
		},
		"SubSecTime": {
			ID:          "SubSecTime",
			Name:        "DateTime 1/100 sekundy",
		},
		"ExpandFilterLens": {
			ID:          "ExpandFilterLens",
			Name:        "Ext. filtr objektivu",
		},
		"InkSet": {
			ID:          "InkSet",
			Name:        "Inkoustová sada",
		},
		"ExifImageHeight": {
			ID:          "ExifImageHeight",
			Name:        "Výška",
		},
		"FileName": {
			ID:          "FileName",
			Name:        "Jméno",
		},
		"CreateDate": {
			ID:          "CreateDate",
			Name:        "Datum a čas generování digitálních dat",
		},
		"FrameSize": {
			ID:          "FrameSize",
			Name:        "Velikost snímku",
		},
		"ImageWidth": {
			ID:          "ImageWidth",
			Name:        "Šířka",
		},
		"CleanFaxData": {
			ID:          "CleanFaxData",
			Name:        "Čistá fax data",
		},
		"Country": {
			ID:          "Country",
			Name:        "Země",
		},
		"BitsPerSample": {
			ID:          "BitsPerSample",
			Name:        "Počet bitů na složku",
		},
		"NumberofInks": {
			ID:          "NumberofInks",
			Name:        "Číslo náplně",
		},
		"T4Options": {
			ID:          "T4Options",
			Name:        "Plné bity",
		},
		"Comment": {
			ID:          "Comment",
			Name:        "Komentář",
		},
		"Description": {
			ID:          "Description",
			Name:        "Popis",
		},
		"GPSDestLongitude": {
			ID:          "GPSDestLongitude",
			Name:        "Zeměpisná délka cíle",
		},
		"Keywords": {
			ID:          "Keywords",
			Name:        "Klíčová slova",
		},
		"SupplementalCategories": {
			ID:          "SupplementalCategories",
			Name:        "Doplňkové kategorie",
		},
		"Author": {
			ID:          "Author",
			Name:        "Autor",
		},
		"ExposureCompensation": {
			ID:          "ExposureCompensation",
			Name:        "Korekce expozice",
		},
		"ImageSize": {
			ID:          "ImageSize",
			Name:        "Velikost snímku",
		},
		"FaxSubAddress": {
			ID:          "FaxSubAddress",
			Name:        "Sub adresa faxu",
		},
		"FlashEnergy": {
			ID:          "FlashEnergy",
			Name:        "Síla záblesku",
		},
		"Gradation": {
			ID:          "Gradation",
			Name:        "Pusobivy",
		},
		"PageName": {
			ID:          "PageName",
			Name:        "Jméno stránky",
		},
	},
}
