// Code generated by gen-tags. DO NOT EDIT.

package tags

// DarwinCoreMainTags contains tag definitions from Image::ExifTool::DarwinCore
var DarwinCoreMainTags = TagTable{
	ModuleName: "DarwinCore",
	Tags: map[string]TagDef{
		"OccurrenceOccurrenceRemarks": {
			ID:          "OccurrenceOccurrenceRemarks",
		},
		"EventEventTime": {
			ID:          "EventEventTime",
		},
		"OrganismOrganismScope": {
			ID:          "OrganismOrganismScope",
		},
		"PreservedSpecimen": {
			ID:          "PreservedSpecimen",
		},
		"WRITABLE": {
			ID:          "WRITABLE",
			Name:        "string",
		},
		"TaxonTaxonRemarks": {
			ID:          "TaxonTaxonRemarks",
		},
		"NAMESPACE": {
			ID:          "NAMESPACE",
			Name:        "dwc",
		},
		"EventEventID": {
			ID:          "EventEventID",
		},
		"LivingSpecimen": {
			ID:          "LivingSpecimen",
		},
		"OrganismOrganismName": {
			ID:          "OrganismOrganismName",
		},
		"OrganismOrganismRemarks": {
			ID:          "OrganismOrganismRemarks",
		},
		"TaxonTaxonConceptID": {
			ID:          "TaxonTaxonConceptID",
		},
		"TaxonTaxonID": {
			ID:          "TaxonTaxonID",
		},
		"GROUPS": {
			ID:          "GROUPS",
		},
		"EventEventRemarks": {
			ID:          "EventEventRemarks",
		},
		"GeologicalContextFormation": {
			ID:          "GeologicalContextFormation",
		},
		"GeologicalContextGroup": {
			ID:          "GeologicalContextGroup",
		},
		"MachineObservation": {
			ID:          "MachineObservation",
		},
		"OrganismOrganismID": {
			ID:          "OrganismOrganismID",
		},
		"TaxonTaxonRank": {
			ID:          "TaxonTaxonRank",
		},
		"EventEventDate": {
			ID:          "EventEventDate",
		},
		"FossilSpecimen": {
			ID:          "FossilSpecimen",
		},
		"GeologicalContextBed": {
			ID:          "GeologicalContextBed",
		},
		"OccurrenceOccurrenceStatus": {
			ID:          "OccurrenceOccurrenceStatus",
		},
		"GeologicalContextMember": {
			ID:          "GeologicalContextMember",
		},
		"HumanObservation": {
			ID:          "HumanObservation",
		},
		"MaterialSample": {
			ID:          "MaterialSample",
		},
		"MaterialSampleMaterialSampleID": {
			ID:          "MaterialSampleMaterialSampleID",
		},
		"OccurrenceOccurrenceDetails": {
			ID:          "OccurrenceOccurrenceDetails",
		},
		"OccurrenceOccurrenceID": {
			ID:          "OccurrenceOccurrenceID",
		},
	},
}
