// Code generated by gen-tags. DO NOT EDIT.

package tags

// DJIProtobufTags contains tag definitions from Image::ExifTool::DJI
var DJIProtobufTags = TagTable{
	ModuleName: "DJI",
	Tags: map[string]TagDef{
		"dvtm_Mini4_Pro_3-2-32-1": {
			ID:          "dvtm_Mini4_Pro_3-2-32-1",
		},
		"dvtm_ac203_3-2-6-1": {
			ID:          "dvtm_ac203_3-2-6-1",
		},
		"dvtm_ac204_3-2-10-2": {
			ID:          "dvtm_ac204_3-2-10-2",
		},
		"dvtm_ac204_3-2-10-4": {
			ID:          "dvtm_ac204_3-2-10-4",
		},
		"dvtm_wm265e_3-2-2-1": {
			ID:          "dvtm_wm265e_3-2-2-1",
		},
		"dvtm_wm265e_3-3-4-2": {
			ID:          "dvtm_wm265e_3-3-4-2",
		},
		"dvtm_ac203_1-1-5": {
			ID:          "dvtm_ac203_1-1-5",
		},
		"dvtm_ac203_3-2-10-3": {
			ID:          "dvtm_ac203_3-2-10-3",
		},
		"dvtm_AVATA2_3-2-6-1": {
			ID:          "dvtm_AVATA2_3-2-6-1",
		},
		"dvtm_AVATA2_3-4-5-1": {
			ID:          "dvtm_AVATA2_3-4-5-1",
		},
		"dvtm_Mini4_Pro_1-1-10": {
			ID:          "dvtm_Mini4_Pro_1-1-10",
			Name:        "Model",
		},
		"dvtm_Mini4_Pro_3-3-5-1": {
			ID:          "dvtm_Mini4_Pro_3-3-5-1",
		},
		"dvtm_ac204_3-2-6-1": {
			ID:          "dvtm_ac204_3-2-6-1",
		},
		"dvtm_AVATA2_1-1-10": {
			ID:          "dvtm_AVATA2_1-1-10",
			Name:        "Model",
		},
		"dvtm_AVATA2_3-2-2-1": {
			ID:          "dvtm_AVATA2_3-2-2-1",
		},
		"dvtm_pm320_3-2-2-1": {
			ID:          "dvtm_pm320_3-2-2-1",
		},
		"dvtm_pm320_3-3-4-2": {
			ID:          "dvtm_pm320_3-3-4-2",
		},
		"dvtm_pm320_3-3-5-1": {
			ID:          "dvtm_pm320_3-3-5-1",
		},
		"dvtm_pm320_1-1-10": {
			ID:          "dvtm_pm320_1-1-10",
			Name:        "Model",
		},
		"dvtm_ac203_1-1-10": {
			ID:          "dvtm_ac203_1-1-10",
			Name:        "Model",
		},
		"dvtm_AVATA2_1-1-5": {
			ID:          "dvtm_AVATA2_1-1-5",
		},
		"dvtm_wm265e_3-3-5-1": {
			ID:          "dvtm_wm265e_3-3-5-1",
		},
		"dvtm_pm320_3-2-6-1": {
			ID:          "dvtm_pm320_3-2-6-1",
		},
		"dvtm_Mini4_Pro_3-2-7-1": {
			ID:          "dvtm_Mini4_Pro_3-2-7-1",
		},
		"dvtm_ac203_3-2-2-1": {
			ID:          "dvtm_ac203_3-2-2-1",
		},
		"dvtm_AVATA2_2-2-3-1": {
			ID:          "dvtm_AVATA2_2-2-3-1",
		},
		"dvtm_AVATA2_3-4-4-2": {
			ID:          "dvtm_AVATA2_3-4-4-2",
		},
		"dvtm_wm265e_1-1-5": {
			ID:          "dvtm_wm265e_1-1-5",
		},
		"dvtm_pm320_1-1-5": {
			ID:          "dvtm_pm320_1-1-5",
		},
		"dvtm_ac203_3-2-10-2": {
			ID:          "dvtm_ac203_3-2-10-2",
		},
		"dvtm_wm265e_3-2-6-1": {
			ID:          "dvtm_wm265e_3-2-6-1",
		},
		"dvtm_Mini4_Pro_3-3-4-2": {
			ID:          "dvtm_Mini4_Pro_3-3-4-2",
		},
		"dvtm_ac203_3-2-10-4": {
			ID:          "dvtm_ac203_3-2-10-4",
		},
		"dvtm_ac204_1-1-5": {
			ID:          "dvtm_ac204_1-1-5",
		},
		"dvtm_ac204_1-1-10": {
			ID:          "dvtm_ac204_1-1-10",
			Name:        "Model",
		},
		"dvtm_ac204_3-2-10-3": {
			ID:          "dvtm_ac204_3-2-10-3",
		},
		"dvtm_wm265e_1-1-10": {
			ID:          "dvtm_wm265e_1-1-10",
			Name:        "Model",
		},
		"dvtm_Mini4_Pro_1-1-5": {
			ID:          "dvtm_Mini4_Pro_1-1-5",
		},
	},
}
