// Code generated by gen-tags. DO NOT EDIT.

package tags

// DJIDroneInfoTags contains tag definitions from Image::ExifTool::DJI
var DJIDroneInfoTags = TagTable{
	ModuleName: "DJI",
	Tags: map[string]TagDef{
		"3": {
			ID:          "3",
		},
		"1": {
			ID:          "1",
		},
		"2": {
			ID:          "2",
		},
	},
}
