// Code generated by gen-tags. DO NOT EDIT.

package tags

// DJIMainTags contains tag definitions from Image::ExifTool::DJI
var DJIMainTags = TagTable{
	ModuleName: "DJI",
	Tags: map[string]TagDef{
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"0x03": {
			ID:          "0x03",
		},
		"0x05": {
			ID:          "0x05",
		},
		"0x07": {
			ID:          "0x07",
		},
		"0x08": {
			ID:          "0x08",
		},
		"0x01": {
			ID:          "0x01",
		},
		"0x04": {
			ID:          "0x04",
		},
		"0x06": {
			ID:          "0x06",
		},
		"0x09": {
			ID:          "0x09",
		},
		"0x0A": {
			ID:          "0x0A",
		},
		"0x0B": {
			ID:          "0x0B",
		},
	},
}
