// Code generated by gen-tags. DO NOT EDIT.

package tags

// DJIGlamourTags contains tag definitions from Image::ExifTool::DJI
var DJIGlamourTags = TagTable{
	ModuleName: "DJI",
	Tags: map[string]TagDef{
		"whitening": {
			ID:          "whitening",
			Name:        "Whitening",
		},
		"mouth_beautify": {
			ID:          "mouth_beautify",
			Name:        "MouthModify",
		},
		"blush": {
			ID:          "blush",
			Name:        "Blush",
		},
		"teeth_whitening": {
			ID:          "teeth_whitening",
			Name:        "TeethWhitening",
		},
		"leg_longer": {
			ID:          "leg_longer",
			Name:        "LegLonger",
		},
		"dark_circle": {
			ID:          "dark_circle",
			Name:        "DarkCircle",
		},
		"acne_spot_removal": {
			ID:          "acne_spot_removal",
			Name:        "AcneSpotRemoval",
		},
		"face_slimming": {
			ID:          "face_slimming",
			Name:        "FaceSlimming",
		},
		"nose_slimming": {
			ID:          "nose_slimming",
			Name:        "NoseSlimming",
		},
		"lipstick": {
			ID:          "lipstick",
			Name:        "Lipstick",
		},
		"eye_enlarge": {
			ID:          "eye_enlarge",
			Name:        "EyeEnlarge",
		},
		"head_shrinking": {
			ID:          "head_shrinking",
			Name:        "HeadShrinking",
		},
		"eyebrows": {
			ID:          "eyebrows",
			Name:        "Eyebrows",
		},
		"beauty_enable": {
			ID:          "beauty_enable",
			Name:        "BeautyEnable",
		},
		"smoother": {
			ID:          "smoother",
			Name:        "Smoother",
		},
	},
}
