// Code generated by gen-tags. DO NOT EDIT.

package tags

// DJIGPSInfoTags contains tag definitions from Image::ExifTool::DJI
var DJIGPSInfoTags = TagTable{
	ModuleName: "DJI",
	Tags: map[string]TagDef{
	},
}
