// Code generated by gen-tags. DO NOT EDIT.

package tags

// DJIThermalParams3Tags contains tag definitions from Image::ExifTool::DJI
var DJIThermalParams3Tags = TagTable{
	ModuleName: "DJI",
	Tags: map[string]TagDef{
		"0x04": {
			ID:          "0x04",
		},
		"0x06": {
			ID:          "0x06",
		},
		"0x08": {
			ID:          "0x08",
		},
		"0x0A": {
			ID:          "0x0A",
		},
	},
}
