// Code generated by gen-tags. DO NOT EDIT.

package tags

// DNGImageSeqTags contains tag definitions from Image::ExifTool::DNG
var DNGImageSeqTags = TagTable{
	ModuleName: "DNG",
	Tags: map[string]TagDef{
		"7": {
			ID:          "7",
		},
		"11": {
			ID:          "11",
		},
		"0": {
			ID:          "0",
		},
		"1": {
			ID:          "1",
		},
		"2": {
			ID:          "2",
		},
		"3": {
			ID:          "3",
		},
	},
}
