// Code generated by gen-tags. DO NOT EDIT.

package tags

// DVMainTags contains tag definitions from Image::ExifTool::DV
var DVMainTags = TagTable{
	ModuleName: "DV",
	Tags: map[string]TagDef{
		"TotalBitrate": {
			ID:          "TotalBitrate",
		},
		"VideoFormat": {
			ID:          "VideoFormat",
		},
		"VideoScanType": {
			ID:          "VideoScanType",
		},
		"AspectRatio": {
			ID:          "AspectRatio",
		},
		"Colorimetry": {
			ID:          "Colorimetry",
		},
		"AudioSampleRate": {
			ID:          "AudioSampleRate",
		},
		"ImageWidth": {
			ID:          "ImageWidth",
		},
		"ImageHeight": {
			ID:          "ImageHeight",
		},
		"Duration": {
			ID:          "Duration",
		},
		"FrameRate": {
			ID:          "FrameRate",
		},
		"AudioChannels": {
			ID:          "AudioChannels",
		},
		"AudioBitsPerSample": {
			ID:          "AudioBitsPerSample",
		},
	},
}
