// Code generated by gen-tags. DO NOT EDIT.

package tags

// EXEMiscTags contains tag definitions from Image::ExifTool::EXE
var EXEMiscTags = TagTable{
	ModuleName: "EXE",
	Tags: map[string]TagDef{
		"12": {
			ID:          "12",
			Name:        "EXEFileName",
		},
	},
}
