// Code generated by gen-tags. DO NOT EDIT.

package tags

// EXEdirInfoTags contains tag definitions from Image::ExifTool::EXE
var EXEdirInfoTags = TagTable{
	ModuleName: "EXE",
	Tags: map[string]TagDef{
	},
}
