// Code generated by gen-tags. DO NOT EDIT.

package tags

// EXEPEFTags contains tag definitions from Image::ExifTool::EXE
var EXEPEFTags = TagTable{
	ModuleName: "EXE",
	Tags: map[string]TagDef{
		"3": {
			ID:          "3",
			Name:        "PEFVersion",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int32u",
		},
	},
}
