// Code generated by gen-tags. DO NOT EDIT.

package tags

// EXECHMTags contains tag definitions from Image::ExifTool::EXE
var EXECHMTags = TagTable{
	ModuleName: "EXE",
	Tags: map[string]TagDef{
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int32u",
		},
		"1": {
			ID:          "1",
		},
	},
}
