// Code generated by gen-tags. DO NOT EDIT.

package tags

// ExifMainTags contains tag definitions from Image::ExifTool::Exif
var ExifMainTags = TagTable{
	ModuleName: "Exif",
	Tags: map[string]TagDef{
		"0x8214": {
			ID:          "0x8214",
		},
		"0x8215": {
			ID:          "0x8215",
		},
		"0x82A6": {
			ID:          "0x82A6",
		},
		"0xA420": {
			ID:          "0xA420",
		},
		"0xA43B": {
			ID:          "0xA43B",
		},
		"0xAFC5": {
			ID:          "0xAFC5",
		},
		"0x158": {
			ID:          "0x158",
		},
		"0x5013": {
			ID:          "0x5013",
		},
		"0x5028": {
			ID:          "0x5028",
		},
		"0x85D7": {
			ID:          "0x85D7",
		},
		"0x920D": {
			ID:          "0x920D",
		},
		"0x923F": {
			ID:          "0x923F",
		},
		"0xA433": {
			ID:          "0xA433",
		},
		"0xC429": {
			ID:          "0xC429",
		},
		"WRITE_GROUP": {
			ID:          "WRITE_GROUP",
		},
		"0x203": {
			ID:          "0x203",
			Name:        "JPEGRestartInterval",
		},
		"0x5090": {
			ID:          "0x5090",
		},
		"0x5101": {
			ID:          "0x5101",
		},
		"0x80B9": {
			ID:          "0x80B9",
		},
		"0x80E4": {
			ID:          "0x80E4",
		},
		"0x827D": {
			ID:          "0x827D",
		},
		"0xA211": {
			ID:          "0xA211",
			Name:        "ImageNumber",
		},
		"0x500B": {
			ID:          "0x500B",
		},
		"0x5030": {
			ID:          "0x5030",
		},
		"0x821A": {
			ID:          "0x821A",
		},
		"0x85B8": {
			ID:          "0x85B8",
		},
		"0xA216": {
			ID:          "0xA216",
		},
		"0xA481": {
			ID:          "0xA481",
		},
		"0xAFC4": {
			ID:          "0xAFC4",
		},
		"0xBC81": {
			ID:          "0xBC81",
		},
		"0x22F": {
			ID:          "0x22F",
			Name:        "StripRowCounts",
		},
		"0x5012": {
			ID:          "0x5012",
		},
		"0x82A8": {
			ID:          "0x82A8",
		},
		"0x847E": {
			ID:          "0x847E",
		},
		"0x5091": {
			ID:          "0x5091",
		},
		"0x5102": {
			ID:          "0x5102",
		},
		"0x80BC": {
			ID:          "0x80BC",
		},
		"0x500F": {
			ID:          "0x500F",
		},
		"0x5001": {
			ID:          "0x5001",
		},
		"0x14E": {
			ID:          "0x14E",
		},
		"0x5009": {
			ID:          "0x5009",
		},
		"0x500A": {
			ID:          "0x500A",
		},
		"0x3E7": {
			ID:          "0x3E7",
		},
		"0x5004": {
			ID:          "0x5004",
		},
		"0x5019": {
			ID:          "0x5019",
		},
		"0x5032": {
			ID:          "0x5032",
		},
		"0x5111": {
			ID:          "0x5111",
		},
		"0x82AC": {
			ID:          "0x82AC",
		},
		"0x8829": {
			ID:          "0x8829",
		},
		"0xA212": {
			ID:          "0xA212",
			Name:        "SecurityClassification",
		},
		"0x150": {
			ID:          "0x150",
		},
		"0x500D": {
			ID:          "0x500D",
		},
		"0x5016": {
			ID:          "0x5016",
		},
		"0x5017": {
			ID:          "0x5017",
		},
		"0x503A": {
			ID:          "0x503A",
		},
		"0x5104": {
			ID:          "0x5104",
		},
		"0x80E3": {
			ID:          "0x80E3",
		},
		"0x84E6": {
			ID:          "0x84E6",
		},
		"0x156": {
			ID:          "0x156",
			Name:        "TransferRange",
		},
		"0x1B2": {
			ID:          "0x1B2",
		},
		"0x84E2": {
			ID:          "0x84E2",
		},
		"0x84EC": {
			ID:          "0x84EC",
		},
		"0x84ED": {
			ID:          "0x84ED",
		},
		"0x885D": {
			ID:          "0x885D",
		},
		"0x885E": {
			ID:          "0x885E",
		},
		"0xAFC1": {
			ID:          "0xAFC1",
		},
		"0x80E5": {
			ID:          "0x80E5",
		},
		"0x80E6": {
			ID:          "0x80E6",
		},
		"0x5002": {
			ID:          "0x5002",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"0x920E": {
			ID:          "0x920E",
		},
		"0xAFC3": {
			ID:          "0xAFC3",
		},
		"0xBC80": {
			ID:          "0xBC80",
		},
		"0x5014": {
			ID:          "0x5014",
		},
		"0x5020": {
			ID:          "0x5020",
		},
		"0x5023": {
			ID:          "0x5023",
		},
		"0x502F": {
			ID:          "0x502F",
		},
		"0x8216": {
			ID:          "0x8216",
		},
		"0x1B3": {
			ID:          "0x1B3",
		},
		"0x82A7": {
			ID:          "0x82A7",
		},
		"0x920F": {
			ID:          "0x920F",
		},
		"0x5035": {
			ID:          "0x5035",
		},
		"0x5037": {
			ID:          "0x5037",
		},
		"0x80A4": {
			ID:          "0x80A4",
		},
		"0x8218": {
			ID:          "0x8218",
		},
		"0x835E": {
			ID:          "0x835E",
		},
		"0xAFC0": {
			ID:          "0xAFC0",
		},
		"0x502D": {
			ID:          "0x502D",
			Name:        "ThumbnailResolutionX",
		},
		"0x82A9": {
			ID:          "0x82A9",
		},
		"0x847F": {
			ID:          "0x847F",
		},
		"0x84EB": {
			ID:          "0x84EB",
		},
		"0xBC83": {
			ID:          "0xBC83",
		},
		"0xA500": {
			ID:          "0xA500",
		},
		"0x82AA": {
			ID:          "0x82AA",
		},
		"0x87BE": {
			ID:          "0x87BE",
		},
		"0xC44F": {
			ID:          "0xC44F",
		},
		"0x5100": {
			ID:          "0x5100",
		},
		"0x932F": {
			ID:          "0x932F",
			Name:        "MSDocumentText",
		},
		"0xA439": {
			ID:          "0xA439",
		},
		"0x1B1": {
			ID:          "0x1B1",
		},
		"0x5038": {
			ID:          "0x5038",
		},
		"0x8217": {
			ID:          "0x8217",
		},
		"0x920C": {
			ID:          "0x920C",
		},
		"0xA20D": {
			ID:          "0xA20D",
			Name:        "Noise",
		},
		"0x80A5": {
			ID:          "0x80A5",
		},
		"0x8219": {
			ID:          "0x8219",
		},
		"0xAFC2": {
			ID:          "0xAFC2",
		},
		"0xB4C3": {
			ID:          "0xB4C3",
		},
		"0x5036": {
			ID:          "0x5036",
		},
		"0x5103": {
			ID:          "0x5103",
		},
		"0x9215": {
			ID:          "0x9215",
		},
		"0xA434": {
			ID:          "0xA434",
		},
		"0x155": {
			ID:          "0x155",
			Name:        "SMaxSampleValue",
		},
		"0x205": {
			ID:          "0x205",
			Name:        "JPEGLosslessPredictors",
		},
		"0x502B": {
			ID:          "0x502B",
		},
		"0x5039": {
			ID:          "0x5039",
		},
		"0x82AB": {
			ID:          "0x82AB",
		},
		"0x835C": {
			ID:          "0x835C",
		},
		"0xA437": {
			ID:          "0xA437",
		},
		"0x501A": {
			ID:          "0x501A",
		},
		"0x159": {
			ID:          "0x159",
		},
		"0x206": {
			ID:          "0x206",
			Name:        "JPEGPointTransforms",
		},
		"0x12C": {
			ID:          "0x12C",
		},
		"0x5025": {
			ID:          "0x5025",
		},
		"0x5026": {
			ID:          "0x5026",
		},
		"0x8481": {
			ID:          "0x8481",
		},
		"0x84E1": {
			ID:          "0x84E1",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"0x5006": {
			ID:          "0x5006",
		},
		"0x5007": {
			ID:          "0x5007",
		},
		"0x500C": {
			ID:          "0x500C",
		},
		"0x5011": {
			ID:          "0x5011",
		},
		"0x5024": {
			ID:          "0x5024",
		},
		"0x5027": {
			ID:          "0x5027",
		},
		"0xA43A": {
			ID:          "0xA43A",
		},
		"0x80A3": {
			ID:          "0x80A3",
		},
		"0x885C": {
			ID:          "0x885C",
		},
		"0xA43C": {
			ID:          "0xA43C",
		},
		"0xC427": {
			ID:          "0xC427",
		},
		"0xC428": {
			ID:          "0xC428",
		},
		"0x5034": {
			ID:          "0x5034",
		},
		"0x80BA": {
			ID:          "0x80BA",
		},
		"0x194": {
			ID:          "0x194",
		},
		"0x5003": {
			ID:          "0x5003",
		},
		"0x5005": {
			ID:          "0x5005",
		},
		"0x500E": {
			ID:          "0x500E",
		},
		"0x5010": {
			ID:          "0x5010",
		},
		"0x84E4": {
			ID:          "0x84E4",
		},
		"0x157": {
			ID:          "0x157",
		},
		"0x146": {
			ID:          "0x146",
		},
		"0x148": {
			ID:          "0x148",
		},
		"0x14D": {
			ID:          "0x14D",
		},
		"0x5008": {
			ID:          "0x5008",
		},
		"0x502E": {
			ID:          "0x502E",
			Name:        "ThumbnailResolutionY",
		},
		"0x8335": {
			ID:          "0x8335",
		},
		"0x835D": {
			ID:          "0x835D",
		},
		"SET_GROUP1": {
			ID:          "SET_GROUP1",
		},
		"0x5022": {
			ID:          "0x5022",
		},
		"0x5031": {
			ID:          "0x5031",
		},
		"0x8336": {
			ID:          "0x8336",
		},
		"0x927C": {
			ID:          "0x927C",
		},
		"0xA213": {
			ID:          "0xA213",
			Name:        "ImageHistory",
		},
		"0xA435": {
			ID:          "0xA435",
		},
		"0xBC82": {
			ID:          "0xBC82",
		},
		"0x80BB": {
			ID:          "0x80BB",
		},
		"0x154": {
			ID:          "0x154",
			Name:        "SMinSampleValue",
		},
		"0x5015": {
			ID:          "0x5015",
		},
		"0x501B": {
			ID:          "0x501B",
		},
		"0x5021": {
			ID:          "0x5021",
		},
		"0x502C": {
			ID:          "0x502C",
		},
		"0x84E9": {
			ID:          "0x84E9",
		},
		"0x84EF": {
			ID:          "0x84EF",
		},
		"0x5018": {
			ID:          "0x5018",
		},
		"0x503B": {
			ID:          "0x503B",
		},
		"0x5110": {
			ID:          "0x5110",
		},
		"0x5112": {
			ID:          "0x5112",
		},
		"0x800D": {
			ID:          "0x800D",
		},
		"0x8782": {
			ID:          "0x8782",
		},
		"0x8871": {
			ID:          "0x8871",
		},
		"0x9216": {
			ID:          "0x9216",
		},
		"0x195": {
			ID:          "0x195",
		},
		"0x5113": {
			ID:          "0x5113",
		},
		"0x84E0": {
			ID:          "0x84E0",
		},
		"0x84F0": {
			ID:          "0x84F0",
		},
		"0x923A": {
			ID:          "0x923A",
		},
		"0xA215": {
			ID:          "0xA215",
		},
		"0xC42A": {
			ID:          "0xC42A",
		},
		"0x5029": {
			ID:          "0x5029",
		},
		"0x5033": {
			ID:          "0x5033",
		},
		"0x835F": {
			ID:          "0x835F",
		},
		"0x84EA": {
			ID:          "0x84EA",
		},
		"0x87AC": {
			ID:          "0x87AC",
			Name:        "ImageLayer",
		},
		"0x923B": {
			ID:          "0x923B",
		},
		"0x923C": {
			ID:          "0x923C",
		},
		"0xA436": {
			ID:          "0xA436",
		},
		"0x502A": {
			ID:          "0x502A",
		},
		"0x84E5": {
			ID:          "0x84E5",
		},
		"0xA438": {
			ID:          "0xA438",
		},
		"0xA480": {
			ID:          "0xA480",
		},
	},
}
