// Code generated by gen-tags. DO NOT EDIT.

package tags

// ExifsubfileTypeTags contains tag definitions from Image::ExifTool::Exif
var ExifsubfileTypeTags = TagTable{
	ModuleName: "Exif",
	Tags: map[string]TagDef{
		"2": {
			ID:          "2",
			Name:        "Single page of multi-page image",
		},
		"3": {
			ID:          "3",
			Name:        "Single page of multi-page reduced-resolution image",
		},
		"4": {
			ID:          "4",
			Name:        "Transparency mask",
		},
		"8": {
			ID:          "8",
		},
		"9": {
			ID:          "9",
		},
		"0x10001": {
			ID:          "0x10001",
		},
		"5": {
			ID:          "5",
			Name:        "Transparency mask of reduced-resolution image",
		},
		"6": {
			ID:          "6",
			Name:        "Transparency mask of multi-page image",
		},
		"7": {
			ID:          "7",
			Name:        "Transparency mask of reduced-resolution multi-page image",
		},
		"16": {
			ID:          "16",
		},
		"0x10004": {
			ID:          "0x10004",
		},
		"0xFFFFFFFF": {
			ID:          "0xFFFFFFFF",
		},
		"0": {
			ID:          "0",
			Name:        "Full-resolution image",
		},
		"1": {
			ID:          "1",
			Name:        "Reduced-resolution image",
		},
	},
}
