// Code generated by gen-tags. DO NOT EDIT.

package tags

// ExifflashTags contains tag definitions from Image::ExifTool::Exif
var ExifflashTags = TagTable{
	ModuleName: "Exif",
	Tags: map[string]TagDef{
		"0x09": {
			ID:          "0x09",
			Name:        "On, Fired",
		},
		"0x1F": {
			ID:          "0x1F",
			Name:        "Auto, Fired, Return detected",
		},
		"0x45": {
			ID:          "0x45",
			Name:        "Fired, Red-eye reduction, Return not detected",
		},
		"0x49": {
			ID:          "0x49",
			Name:        "On, Red-eye reduction",
		},
		"0x59": {
			ID:          "0x59",
			Name:        "Auto, Fired, Red-eye reduction",
		},
		"0x5D": {
			ID:          "0x5D",
			Name:        "Auto, Fired, Red-eye reduction, Return not detected",
		},
		"0x01": {
			ID:          "0x01",
			Name:        "Fired",
		},
		"0x1D": {
			ID:          "0x1D",
			Name:        "Auto, Fired, Return not detected",
		},
		"0x30": {
			ID:          "0x30",
			Name:        "Off, No flash function",
		},
		"0x41": {
			ID:          "0x41",
			Name:        "Fired, Red-eye reduction",
		},
		"0x47": {
			ID:          "0x47",
			Name:        "Fired, Red-eye reduction, Return detected",
		},
		"0x4F": {
			ID:          "0x4F",
			Name:        "On, Red-eye reduction, Return detected",
		},
		"0x50": {
			ID:          "0x50",
			Name:        "Off, Red-eye reduction",
		},
		"0x5F": {
			ID:          "0x5F",
			Name:        "Auto, Fired, Red-eye reduction, Return detected",
		},
		"0x00": {
			ID:          "0x00",
			Name:        "No Flash",
		},
		"0x05": {
			ID:          "0x05",
			Name:        "Fired, Return not detected",
		},
		"0x14": {
			ID:          "0x14",
			Name:        "Off, Did not fire, Return not detected",
		},
		"0x19": {
			ID:          "0x19",
			Name:        "Auto, Fired",
		},
		"0x08": {
			ID:          "0x08",
		},
		"0x0D": {
			ID:          "0x0D",
			Name:        "On, Return not detected",
		},
		"0x0F": {
			ID:          "0x0F",
			Name:        "On, Return detected",
		},
		"0x10": {
			ID:          "0x10",
			Name:        "Off, Did not fire",
		},
		"0x18": {
			ID:          "0x18",
			Name:        "Auto, Did not fire",
		},
		"0x20": {
			ID:          "0x20",
			Name:        "No flash function",
		},
		"0x4D": {
			ID:          "0x4D",
			Name:        "On, Red-eye reduction, Return not detected",
		},
		"0x58": {
			ID:          "0x58",
			Name:        "Auto, Did not fire, Red-eye reduction",
		},
		"0x07": {
			ID:          "0x07",
			Name:        "Fired, Return detected",
		},
	},
}
