// Code generated by gen-tags. DO NOT EDIT.

package tags

// ExifprintParameterTags contains tag definitions from Image::ExifTool::Exif
var ExifprintParameterTags = TagTable{
	ModuleName: "Exif",
	Tags: map[string]TagDef{
	},
}
