// Code generated by gen-tags. DO NOT EDIT.

package tags

// ExifintFormatTags contains tag definitions from Image::ExifTool::Exif
var ExifintFormatTags = TagTable{
	ModuleName: "Exif",
	Tags: map[string]TagDef{
		"int32u": {
			ID:          "int32u",
		},
		"int8s": {
			ID:          "int8s",
		},
		"ifd": {
			ID:          "ifd",
		},
		"ifd64": {
			ID:          "ifd64",
		},
		"int8u": {
			ID:          "int8u",
		},
		"int16u": {
			ID:          "int16u",
		},
		"int16s": {
			ID:          "int16s",
		},
		"int32s": {
			ID:          "int32s",
		},
		"int64u": {
			ID:          "int64u",
		},
		"int64s": {
			ID:          "int64s",
		},
	},
}
