// Code generated by gen-tags. DO NOT EDIT.

package tags

// FLACPictureTags contains tag definitions from Image::ExifTool::FLAC
var FLACPictureTags = TagTable{
	ModuleName: "FLAC",
	Tags: map[string]TagDef{
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int32u",
		},
		"3": {
			ID:          "3",
			Name:        "PictureWidth",
		},
		"4": {
			ID:          "4",
			Name:        "PictureHeight",
		},
		"5": {
			ID:          "5",
			Name:        "PictureBitsPerPixel",
		},
		"6": {
			ID:          "6",
			Name:        "PictureIndexedColors",
		},
		"7": {
			ID:          "7",
			Name:        "PictureLength",
		},
	},
}
