// Code generated by gen-tags. DO NOT EDIT.

package tags

// FLACCompositeTags contains tag definitions from Image::ExifTool::FLAC
var FLACCompositeTags = TagTable{
	ModuleName: "FLAC",
	Tags: map[string]TagDef{
	},
}
