// Code generated by gen-tags. DO NOT EDIT.

package tags

// FlashPixTransformTags contains tag definitions from Image::ExifTool::FlashPix
var FlashPixTransformTags = TagTable{
	ModuleName: "FlashPix",
	Tags: map[string]TagDef{
		"0x00010000": {
			ID:          "0x00010000",
			Name:        "TransformNodeID",
		},
		"0x00010002": {
			ID:          "0x00010002",
			Name:        "LockedPropertyList",
		},
		"0x00010006": {
			ID:          "0x00010006",
		},
		"0x10000000": {
			ID:          "0x10000000",
			Name:        "ResultAspectRatio",
		},
		"0x00010003": {
			ID:          "0x00010003",
			Name:        "TransformTitle",
		},
		"0x10000004": {
			ID:          "0x10000004",
			Name:        "ColorTwistMatrix",
		},
		"0x10000005": {
			ID:          "0x10000005",
			Name:        "ContrastAdjustment",
		},
		"0x00010005": {
			ID:          "0x00010005",
			Name:        "RevisionNumber",
		},
		"0x00010008": {
			ID:          "0x00010008",
			Name:        "CreatingApplication",
		},
		"0x00010101": {
			ID:          "0x00010101",
			Name:        "OutputDataObjectList",
		},
		"0x10000001": {
			ID:          "0x10000001",
			Name:        "RectangleOfInterest",
		},
		"0x10000002": {
			ID:          "0x10000002",
			Name:        "Filtering",
		},
		"0x00010001": {
			ID:          "0x00010001",
			Name:        "OperationClassID",
		},
		"0x00010004": {
			ID:          "0x00010004",
			Name:        "LastModifier",
		},
		"0x00010007": {
			ID:          "0x00010007",
		},
		"0x00010100": {
			ID:          "0x00010100",
			Name:        "InputDataObjectList",
		},
		"0x00010102": {
			ID:          "0x00010102",
			Name:        "OperationNumber",
		},
		"0x10000003": {
			ID:          "0x10000003",
			Name:        "SpatialOrientation",
		},
	},
}
