// Code generated by gen-tags. DO NOT EDIT.

package tags

// FlashPixOperationTags contains tag definitions from Image::ExifTool::FlashPix
var FlashPixOperationTags = TagTable{
	ModuleName: "FlashPix",
	Tags: map[string]TagDef{
		"0x00010000": {
			ID:          "0x00010000",
			Name:        "OperationID",
		},
	},
}
