// Code generated by gen-tags. DO NOT EDIT.

package tags

// FlashMetaTags contains tag definitions from Image::ExifTool::Flash
var FlashMetaTags = TagTable{
	ModuleName: "Flash",
	Tags: map[string]TagDef{
		"hasMetadata": {
			ID:          "hasMetadata",
			Name:        "HasMetadata",
		},
		"height": {
			ID:          "height",
			Name:        "ImageHeight",
		},
		"videocodecid": {
			ID:          "videocodecid",
			Name:        "VideoCodecID",
		},
		"audiodelay": {
			ID:          "audiodelay",
		},
		"purl": {
			ID:          "purl",
		},
		"pmsg": {
			ID:          "pmsg",
		},
		"videosize": {
			ID:          "videosize",
			Name:        "VideoSize",
		},
		"bytelength": {
			ID:          "bytelength",
		},
		"canseekontime": {
			ID:          "canseekontime",
		},
		"lastkeyframetimestamp": {
			ID:          "lastkeyframetimestamp",
			Name:        "LastKeyFrameTime",
		},
		"audiocodecid": {
			ID:          "audiocodecid",
		},
		"keyframesTimes": {
			ID:          "keyframesTimes",
			Name:        "KeyFramesTimes",
		},
		"lasttimestamp": {
			ID:          "lasttimestamp",
			Name:        "LastTimeStamp",
		},
		"width": {
			ID:          "width",
			Name:        "ImageWidth",
		},
		"datasize": {
			ID:          "datasize",
			Name:        "DataSize",
		},
		"hasAudio": {
			ID:          "hasAudio",
		},
		"hasKeyframes": {
			ID:          "hasKeyframes",
			Name:        "HasKeyFrames",
		},
		"sourcedata": {
			ID:          "sourcedata",
		},
		"audiosize": {
			ID:          "audiosize",
		},
		"createdby": {
			ID:          "createdby",
		},
		"hasVideo": {
			ID:          "hasVideo",
			Name:        "HasVideo",
		},
		"httphostheader": {
			ID:          "httphostheader",
		},
		"metadatacreator": {
			ID:          "metadatacreator",
			Name:        "MetadataCreator",
		},
		"keyframesFilepositions": {
			ID:          "keyframesFilepositions",
			Name:        "KeyFramePositions",
		},
		"audiosamplesize": {
			ID:          "audiosamplesize",
		},
		"canSeekToEnd": {
			ID:          "canSeekToEnd",
			Name:        "CanSeekToEnd",
		},
		"hasCuePoints": {
			ID:          "hasCuePoints",
			Name:        "HasCuePoints",
		},
		"stereo": {
			ID:          "stereo",
		},
		"totalduration": {
			ID:          "totalduration",
			Name:        "TotalDuration",
		},
		"audiosamplerate": {
			ID:          "audiosamplerate",
		},
		"filesize": {
			ID:          "filesize",
			Name:        "FileSizeBytes",
		},
	},
}
