// Code generated by gen-tags. DO NOT EDIT.

package tags

// FlashPixMainTags contains tag definitions from Image::ExifTool::FlashPix
var FlashPixMainTags = TagTable{
	ModuleName: "FlashPix",
	Tags: map[string]TagDef{
	},
}
