// Code generated by gen-tags. DO NOT EDIT.

package tags

// FlashPixDocumentInfoTags contains tag definitions from Image::ExifTool::FlashPix
var FlashPixDocumentInfoTags = TagTable{
	ModuleName: "FlashPix",
	Tags: map[string]TagDef{
		"0x05": {
			ID:          "0x05",
			Name:        "Lines",
		},
		"0x06": {
			ID:          "0x06",
			Name:        "Paragraphs",
		},
		"0x07": {
			ID:          "0x07",
			Name:        "Slides",
		},
		"0x0C": {
			ID:          "0x0C",
			Name:        "HeadingPairs",
		},
		"0x0E": {
			ID:          "0x0E",
			Name:        "Manager",
		},
		"0x1A": {
			ID:          "0x1A",
		},
		"0x02": {
			ID:          "0x02",
			Name:        "Category",
		},
		"0x0F": {
			ID:          "0x0F",
			Name:        "Company",
		},
		"0x1B": {
			ID:          "0x1B",
		},
		"0x04": {
			ID:          "0x04",
			Name:        "Bytes",
		},
		"0x11": {
			ID:          "0x11",
			Name:        "CharCountWithSpaces",
		},
		"0x1C": {
			ID:          "0x1C",
		},
		"0x1D": {
			ID:          "0x1D",
		},
		"0x03": {
			ID:          "0x03",
			Name:        "PresentationTarget",
		},
		"0x08": {
			ID:          "0x08",
			Name:        "Notes",
		},
		"0x09": {
			ID:          "0x09",
			Name:        "HiddenSlides",
		},
		"0x0A": {
			ID:          "0x0A",
			Name:        "MMClips",
		},
	},
}
