// Code generated by gen-tags. DO NOT EDIT.

package tags

// FlashPixPreviewInfoTags contains tag definitions from Image::ExifTool::FlashPix
var FlashPixPreviewInfoTags = TagTable{
	ModuleName: "FlashPix",
	Tags: map[string]TagDef{
	},
}
