// Code generated by gen-tags. DO NOT EDIT.

package tags

// FlashPixDocTableTags contains tag definitions from Image::ExifTool::FlashPix
var FlashPixDocTableTags = TagTable{
	ModuleName: "FlashPix",
	Tags: map[string]TagDef{
		"DOP": {
			ID:          "DOP",
		},
		"TableOffsets": {
			ID:          "TableOffsets",
		},
	},
}
