// Code generated by gen-tags. DO NOT EDIT.

package tags

// FlashVideoTags contains tag definitions from Image::ExifTool::Flash
var FlashVideoTags = TagTable{
	ModuleName: "Flash",
	Tags: map[string]TagDef{
	},
}
