// Code generated by gen-tags. DO NOT EDIT.

package tags

// FlashCuePointTags contains tag definitions from Image::ExifTool::Flash
var FlashCuePointTags = TagTable{
	ModuleName: "Flash",
	Tags: map[string]TagDef{
		"type": {
			ID:          "type",
			Name:        "Type",
		},
		"time": {
			ID:          "time",
			Name:        "Time",
		},
		"name": {
			ID:          "name",
			Name:        "Name",
		},
	},
}
