// Code generated by gen-tags. DO NOT EDIT.

package tags

// FlashFLVTags contains tag definitions from Image::ExifTool::Flash
var FlashFLVTags = TagTable{
	ModuleName: "Flash",
	Tags: map[string]TagDef{
	},
}
