// Code generated by gen-tags. DO NOT EDIT.

package tags

// FlashPixExtensionsTags contains tag definitions from Image::ExifTool::FlashPix
var FlashPixExtensionsTags = TagTable{
	ModuleName: "FlashPix",
	Tags: map[string]TagDef{
		"0x0001": {
			ID:          "0x0001",
			Name:        "ExtensionName",
		},
		"0x0004": {
			ID:          "0x0004",
		},
		"0x0005": {
			ID:          "0x0005",
		},
		"0x1000": {
			ID:          "0x1000",
			Name:        "Storage-StreamPathname",
		},
		"0x2000": {
			ID:          "0x2000",
			Name:        "FlashPixStreamPathname",
		},
		"0x2001": {
			ID:          "0x2001",
			Name:        "FlashPixStreamFieldOffset",
		},
		"0x0002": {
			ID:          "0x0002",
			Name:        "ExtensionClassID",
		},
		"0x0006": {
			ID:          "0x0006",
			Name:        "CreatingApplication",
		},
		"0x0007": {
			ID:          "0x0007",
			Name:        "ExtensionDescription",
		},
		"0x3000": {
			ID:          "0x3000",
			Name:        "PropertySetPathname",
		},
		"0x3001": {
			ID:          "0x3001",
			Name:        "PropertySetIDCodes",
		},
		"0x3002": {
			ID:          "0x3002",
			Name:        "PropertyVectorElements",
		},
		"0x4000": {
			ID:          "0x4000",
			Name:        "SubimageResolutions",
		},
		"0x10000000": {
			ID:          "0x10000000",
			Name:        "UsedExtensionNumbers",
		},
	},
}
