// Code generated by gen-tags. DO NOT EDIT.

package tags

// FLIFMainTags contains tag definitions from Image::ExifTool::FLIF
var FLIFMainTags = TagTable{
	ModuleName: "FLIF",
	Tags: map[string]TagDef{
		"2": {
			ID:          "2",
			Name:        "ImageWidth",
		},
		"3": {
			ID:          "3",
			Name:        "ImageHeight",
		},
		"4": {
			ID:          "4",
			Name:        "AnimationFrames",
		},
	},
}
