// Code generated by gen-tags. DO NOT EDIT.

package tags

// FLIRMainTags contains tag definitions from Image::ExifTool::FLIR
var FLIRMainTags = TagTable{
	ModuleName: "FLIR",
	Tags: map[string]TagDef{
		"WRITABLE": {
			ID:          "WRITABLE",
		},
		"PRIORITY": {
			ID:          "PRIORITY",
		},
		"0x02": {
			ID:          "0x02",
		},
		"0x04": {
			ID:          "0x04",
		},
		"0x05": {
			ID:          "0x05",
		},
		"0x06": {
			ID:          "0x06",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
	},
}
