// Code generated by gen-tags. DO NOT EDIT.

package tags

// FLIRAFF1Tags contains tag definitions from Image::ExifTool::FLIR
var FLIRAFF1Tags = TagTable{
	ModuleName: "FLIR",
	Tags: map[string]TagDef{
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int16u",
		},
		"0x01": {
			ID:          "0x01",
		},
		"0x02": {
			ID:          "0x02",
		},
	},
}
