// Code generated by gen-tags. DO NOT EDIT.

package tags

// FLIRHeaderTags contains tag definitions from Image::ExifTool::FLIR
var FLIRHeaderTags = TagTable{
	ModuleName: "FLIR",
	Tags: map[string]TagDef{
		"4": {
			ID:          "4",
		},
	},
}
