// Code generated by gen-tags. DO NOT EDIT.

package tags

// FLIRMeasInfoTags contains tag definitions from Image::ExifTool::FLIR
var FLIRMeasInfoTags = TagTable{
	ModuleName: "FLIR",
	Tags: map[string]TagDef{
		"Meas1Label": {
			ID:          "Meas1Label",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int16u",
		},
	},
}
