// Code generated by gen-tags. DO NOT EDIT.

package tags

// FLIRMeterLinkTags contains tag definitions from Image::ExifTool::FLIR
var FLIRMeterLinkTags = TagTable{
	ModuleName: "FLIR",
	Tags: map[string]TagDef{
	},
}
