// Code generated by gen-tags. DO NOT EDIT.

package tags

// FLIRFPFTags contains tag definitions from Image::ExifTool::FLIR
var FLIRFPFTags = TagTable{
	ModuleName: "FLIR",
	Tags: map[string]TagDef{
		"0xB8": {
			ID:          "0xB8",
		},
		"0x1E4": {
			ID:          "0x1E4",
		},
		"0x1F8": {
			ID:          "0x1F8",
		},
		"0x1FC": {
			ID:          "0x1FC",
		},
		"0x2A8": {
			ID:          "0x2A8",
		},
		"0x2AC": {
			ID:          "0x2AC",
		},
		"0x2B0": {
			ID:          "0x2B0",
		},
		"0x24": {
			ID:          "0x24",
		},
		"0x2C": {
			ID:          "0x2C",
		},
		"0x78": {
			ID:          "0x78",
		},
		"0x150": {
			ID:          "0x150",
		},
		"0x1E0": {
			ID:          "0x1E0",
		},
		"0x2B4": {
			ID:          "0x2B4",
		},
		"0x20": {
			ID:          "0x20",
		},
		"0x98": {
			ID:          "0x98",
		},
		"0x1F4": {
			ID:          "0x1F4",
		},
		"0x100": {
			ID:          "0x100",
		},
		"0x140": {
			ID:          "0x140",
		},
		"0x1E8": {
			ID:          "0x1E8",
		},
		"0x1EC": {
			ID:          "0x1EC",
		},
		"0x180": {
			ID:          "0x180",
		},
		"0x2A4": {
			ID:          "0x2A4",
		},
		"0x2E": {
			ID:          "0x2E",
		},
		"0x30": {
			ID:          "0x30",
		},
		"0x34": {
			ID:          "0x34",
		},
		"0xD8": {
			ID:          "0xD8",
		},
		"0x2B8": {
			ID:          "0x2B8",
		},
		"0x200": {
			ID:          "0x200",
		},
		"0x204": {
			ID:          "0x204",
		},
		"0x120": {
			ID:          "0x120",
		},
		"0xDC": {
			ID:          "0xDC",
		},
		"0xE0": {
			ID:          "0xE0",
		},
		"0x1F0": {
			ID:          "0x1F0",
		},
	},
}
