// Code generated by gen-tags. DO NOT EDIT.

package tags

// FLIRFFFTags contains tag definitions from Image::ExifTool::FLIR
var FLIRFFFTags = TagTable{
	ModuleName: "FLIR",
	Tags: map[string]TagDef{
	},
}
