// Code generated by gen-tags. DO NOT EDIT.

package tags

// FLIRParamInfoTags contains tag definitions from Image::ExifTool::FLIR
var FLIRParamInfoTags = TagTable{
	ModuleName: "FLIR",
	Tags: map[string]TagDef{
		"Param2": {
			ID:          "Param2",
		},
		"Param3": {
			ID:          "Param3",
		},
		"Param0": {
			ID:          "Param0",
		},
		"Param1": {
			ID:          "Param1",
		},
	},
}
