// Code generated by gen-tags. DO NOT EDIT.

package tags

// FLIRUserDataTags contains tag definitions from Image::ExifTool::FLIR
var FLIRUserDataTags = TagTable{
	ModuleName: "FLIR",
	Tags: map[string]TagDef{
	},
}
