// Code generated by gen-tags. DO NOT EDIT.

package tags

// FujiFilmIFDTags contains tag definitions from Image::ExifTool::FujiFilm
var FujiFilmIFDTags = TagTable{
	ModuleName: "FujiFilm",
	Tags: map[string]TagDef{
		"0xF00A": {
			ID:          "0xF00A",
		},
		"0xF00B": {
			ID:          "0xF00B",
		},
		"0xF00C": {
			ID:          "0xF00C",
		},
		"0xF010": {
			ID:          "0xF010",
		},
		"0xF001": {
			ID:          "0xF001",
			Name:        "RawImageFullWidth",
		},
		"0xF002": {
			ID:          "0xF002",
			Name:        "RawImageFullHeight",
		},
		"0xF003": {
			ID:          "0xF003",
			Name:        "BitsPerSample",
		},
		"0xF00D": {
			ID:          "0xF00D",
		},
		"0xF00E": {
			ID:          "0xF00E",
			Name:        "WB_GRBLevels",
		},
		"0xF00F": {
			ID:          "0xF00F",
		},
	},
}
