// Code generated by gen-tags. DO NOT EDIT.

package tags

// FujiFilmMOVTags contains tag definitions from Image::ExifTool::FujiFilm
var FujiFilmMOVTags = TagTable{
	ModuleName: "FujiFilm",
	Tags: map[string]TagDef{
	},
}
