// Code generated by gen-tags. DO NOT EDIT.

package tags

// FujiFilmFocusSettingsTags contains tag definitions from Image::ExifTool::FujiFilm
var FujiFilmFocusSettingsTags = TagTable{
	ModuleName: "FujiFilm",
	Tags: map[string]TagDef{
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int32u",
		},
		"WRITABLE": {
			ID:          "WRITABLE",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
	},
}
