// Code generated by gen-tags. DO NOT EDIT.

package tags

// GeoTiffMainTags contains tag definitions from Image::ExifTool::GeoTiff
var GeoTiffMainTags = TagTable{
	ModuleName: "GeoTiff",
	Tags: map[string]TagDef{
		"2049": {
			ID:          "2049",
			Name:        "GeogCitation",
		},
		"2057": {
			ID:          "2057",
			Name:        "GeogSemiMajorAxis",
		},
		"2059": {
			ID:          "2059",
			Name:        "GeogInvFlattening",
		},
		"47017": {
			ID:          "47017",
			Name:        "ChartContourInterval",
		},
		"2055": {
			ID:          "2055",
			Name:        "GeogAngularUnitSize",
		},
		"3079": {
			ID:          "3079",
			Name:        "ProjStdParallel2",
		},
		"47016": {
			ID:          "47016",
			Name:        "InsetNWPixelY",
		},
		"3090": {
			ID:          "3090",
			Name:        "ProjCenterEasting",
		},
		"3092": {
			ID:          "3092",
			Name:        "ProjScaleAtNatOrigin",
		},
		"3094": {
			ID:          "3094",
			Name:        "ProjAzimuthAngle",
		},
		"3080": {
			ID:          "3080",
			Name:        "ProjNatOriginLong",
		},
		"2058": {
			ID:          "2058",
			Name:        "GeogSemiMinorAxis",
		},
		"2061": {
			ID:          "2061",
			Name:        "GeogPrimeMeridianLong",
		},
		"3078": {
			ID:          "3078",
			Name:        "ProjStdParallel1",
		},
		"3084": {
			ID:          "3084",
			Name:        "ProjFalseOriginLong",
		},
		"1026": {
			ID:          "1026",
			Name:        "GTCitation",
		},
		"2062": {
			ID:          "2062",
			Name:        "GeogToWGS84",
		},
		"3082": {
			ID:          "3082",
			Name:        "ProjFalseEasting",
		},
		"3085": {
			ID:          "3085",
			Name:        "ProjFalseOriginLat",
		},
		"3087": {
			ID:          "3087",
			Name:        "ProjFalseOriginNorthing",
		},
		"3096": {
			ID:          "3096",
			Name:        "ProjRectifiedGridAngle",
		},
		"4097": {
			ID:          "4097",
			Name:        "VerticalCitation",
		},
		"47004": {
			ID:          "47004",
			Name:        "ChartSourceDate",
		},
		"3073": {
			ID:          "3073",
			Name:        "PCSCitation",
		},
		"3081": {
			ID:          "3081",
			Name:        "ProjNatOriginLat",
		},
		"3086": {
			ID:          "3086",
			Name:        "ProjFalseOriginEasting",
		},
		"3089": {
			ID:          "3089",
			Name:        "ProjCenterLat",
		},
		"3091": {
			ID:          "3091",
			Name:        "ProjCenterNorthing",
		},
		"47006": {
			ID:          "47006",
			Name:        "ChartCountryOrigin",
		},
		"2053": {
			ID:          "2053",
			Name:        "GeogLinearUnitSize",
		},
		"47010": {
			ID:          "47010",
			Name:        "ChartMagVar",
		},
		"47012": {
			ID:          "47012",
			Name:        "ChartMagVarAnnChange",
		},
		"47013": {
			ID:          "47013",
			Name:        "ChartWGSNSShift",
		},
		"47015": {
			ID:          "47015",
			Name:        "InsetNWPixelX",
		},
		"3088": {
			ID:          "3088",
			Name:        "ProjCenterLong",
		},
		"3093": {
			ID:          "3093",
			Name:        "ProjScaleAtCenter",
		},
		"3077": {
			ID:          "3077",
			Name:        "ProjLinearUnitSize",
		},
		"3083": {
			ID:          "3083",
			Name:        "ProjFalseNorthing",
		},
		"47003": {
			ID:          "47003",
			Name:        "ChartSourceEdition",
		},
		"47005": {
			ID:          "47005",
			Name:        "ChartCorrDate",
		},
		"3095": {
			ID:          "3095",
			Name:        "ProjStraightVertPoleLong",
		},
		"47002": {
			ID:          "47002",
			Name:        "ChartSource",
		},
		"47007": {
			ID:          "47007",
			Name:        "ChartRasterEdition",
		},
		"47011": {
			ID:          "47011",
			Name:        "ChartMagVarYear",
		},
	},
}
