// Code generated by gen-tags. DO NOT EDIT.

package tags

// GIFMainTags contains tag definitions from Image::ExifTool::GIF
var GIFMainTags = TagTable{
	ModuleName: "GIF",
	Tags: map[string]TagDef{
		"GIFVersion": {
			ID:          "GIFVersion",
		},
		"FrameCount": {
			ID:          "FrameCount",
		},
		"Text": {
			ID:          "Text",
		},
		"TransparentColor": {
			ID:          "TransparentColor",
		},
	},
}
