// Code generated by gen-tags. DO NOT EDIT.

package tags

// GIMPMainTags contains tag definitions from Image::ExifTool::GIMP
var GIMPMainTags = TagTable{
	ModuleName: "GIMP",
	Tags: map[string]TagDef{
		"header": {
			ID:          "header",
		},
	},
}
