// Code generated by gen-tags. DO NOT EDIT.

package tags

// GIMPResolutionTags contains tag definitions from Image::ExifTool::GIMP
var GIMPResolutionTags = TagTable{
	ModuleName: "GIMP",
	Tags: map[string]TagDef{
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "float",
		},
		"0": {
			ID:          "0",
			Name:        "XResolution",
		},
		"1": {
			ID:          "1",
			Name:        "YResolution",
		},
	},
}
