// Code generated by gen-tags. DO NOT EDIT.

package tags

// GMmarlTags contains tag definitions from Image::ExifTool::GM
var GMmarlTags = TagTable{
	ModuleName: "GM",
	Tags: map[string]TagDef{
		"Distance": {
			ID:          "Distance",
		},
		"EngineSpeedRequest": {
			ID:          "EngineSpeedRequest",
		},
		"FuelCapacity": {
			ID:          "FuelCapacity",
		},
		"GPSFix": {
			ID:          "GPSFix",
		},
		"LRTyrePressure": {
			ID:          "LRTyrePressure",
		},
		"ValetMode": {
			ID:          "ValetMode",
		},
		"DriverPerformanceMode": {
			ID:          "DriverPerformanceMode",
		},
		"LongitudinalAcceleration": {
			ID:          "LongitudinalAcceleration",
		},
		"SystemBackupPowerEnabled": {
			ID:          "SystemBackupPowerEnabled",
		},
		"BatteryVoltage": {
			ID:          "BatteryVoltage",
		},
		"SystemPowerMode": {
			ID:          "SystemPowerMode",
		},
		"Beacon": {
			ID:          "Beacon",
		},
		"CPUSystem": {
			ID:          "CPUSystem",
		},
		"LFTyrePressure": {
			ID:          "LFTyrePressure",
		},
		"RFTyreTemp": {
			ID:          "RFTyreTemp",
		},
		"RPM": {
			ID:          "RPM",
		},
		"SpeedRequestIntervention": {
			ID:          "SpeedRequestIntervention",
		},
		"TransportStorageMode": {
			ID:          "TransportStorageMode",
		},
		"ABSActive": {
			ID:          "ABSActive",
		},
		"BrakePos": {
			ID:          "BrakePos",
		},
		"DiskReadRate": {
			ID:          "DiskReadRate",
		},
		"CPUIO": {
			ID:          "CPUIO",
		},
		"OilTemp": {
			ID:          "OilTemp",
		},
		"BoostPressureInd": {
			ID:          "BoostPressureInd",
		},
		"OutsideAirTemperature": {
			ID:          "OutsideAirTemperature",
		},
		"Steering2Switch": {
			ID:          "Steering2Switch",
		},
		"SteeringAngle": {
			ID:          "SteeringAngle",
		},
		"SuspensionDisplacementRightRear": {
			ID:          "SuspensionDisplacementRightRear",
		},
		"TractionControlActive": {
			ID:          "TractionControlActive",
		},
		"AccelPos": {
			ID:          "AccelPos",
		},
		"ClutchPos": {
			ID:          "ClutchPos",
		},
		"DiskWriteTime": {
			ID:          "DiskWriteTime",
		},
		"CornerExitSetting": {
			ID:          "CornerExitSetting",
		},
		"CPUFree": {
			ID:          "CPUFree",
		},
		"DiskWriteOperations": {
			ID:          "DiskWriteOperations",
		},
		"Speed": {
			ID:          "Speed",
		},
		"SuspensionDisplacementLeftFront": {
			ID:          "SuspensionDisplacementLeftFront",
		},
		"IntakeAirTemperature": {
			ID:          "IntakeAirTemperature",
		},
		"RRTyreTemp": {
			ID:          "RRTyreTemp",
		},
		"TransOilTemp": {
			ID:          "TransOilTemp",
		},
		"WheelspeedLeftNon-Driven": {
			ID:          "WheelspeedLeftNon-Driven",
		},
		"FuelLevel": {
			ID:          "FuelLevel",
		},
		"Steering1Switch": {
			ID:          "Steering1Switch",
		},
		"SuspensionDisplacementLeftRear": {
			ID:          "SuspensionDisplacementLeftRear",
		},
		"SuspensionDisplacementRightFront": {
			ID:          "SuspensionDisplacementRightFront",
		},
		"WheelspeedLeftDriven": {
			ID:          "WheelspeedLeftDriven",
		},
		"CoolantTemp": {
			ID:          "CoolantTemp",
		},
		"DiskReadTime": {
			ID:          "DiskReadTime",
		},
		"DiskWriteRate": {
			ID:          "DiskWriteRate",
		},
		"LRTyreTemp": {
			ID:          "LRTyreTemp",
		},
		"RFTyrePressure": {
			ID:          "RFTyrePressure",
		},
		"RRTyrePressure": {
			ID:          "RRTyrePressure",
		},
		"WheelspeedRightNon-Driven": {
			ID:          "WheelspeedRightNon-Driven",
		},
		"CPUIRQ": {
			ID:          "CPUIRQ",
		},
		"EngineTorqureReq": {
			ID:          "EngineTorqureReq",
		},
		"OilPressure": {
			ID:          "OilPressure",
		},
		"SpeedControlResponse": {
			ID:          "SpeedControlResponse",
		},
		"VehicleStabilityActive": {
			ID:          "VehicleStabilityActive",
		},
		"CPUUser": {
			ID:          "CPUUser",
		},
		"LateralAcceleration": {
			ID:          "LateralAcceleration",
		},
		"LFTyreTemp": {
			ID:          "LFTyreTemp",
		},
		"SystemBackupPowerMode": {
			ID:          "SystemBackupPowerMode",
		},
		"YawRate": {
			ID:          "YawRate",
		},
		"DiskReadOperations": {
			ID:          "DiskReadOperations",
		},
		"InfotainOpMode": {
			ID:          "InfotainOpMode",
		},
		"IntakeBoostPressure": {
			ID:          "IntakeBoostPressure",
		},
		"RecordingEventOdometer": {
			ID:          "RecordingEventOdometer",
		},
		"VerticalAcceleration": {
			ID:          "VerticalAcceleration",
		},
		"WheelspeedRightDriven": {
			ID:          "WheelspeedRightDriven",
		},
	},
}
