// Code generated by gen-tags. DO NOT EDIT.

package tags

// GMmrlhTags contains tag definitions from Image::ExifTool::GM
var GMmrlhTags = TagTable{
	ModuleName: "GM",
	Tags: map[string]TagDef{
		"0": {
			ID:          "0",
		},
	},
}
