// Code generated by gen-tags. DO NOT EDIT.

package tags

// GoProGLPITags contains tag definitions from Image::ExifTool::GoPro
var GoProGLPITags = TagTable{
	ModuleName: "GoPro",
	Tags: map[string]TagDef{
		"5": {
			ID:          "5",
		},
		"6": {
			ID:          "6",
		},
		"7": {
			ID:          "7",
		},
		"8": {
			ID:          "8",
		},
		"4": {
			ID:          "4",
		},
	},
}
