// Code generated by gen-tags. DO NOT EDIT.

package tags

// GoProGPMFTags contains tag definitions from Image::ExifTool::GoPro
var GoProGPMFTags = TagTable{
	ModuleName: "GoPro",
	Tags: map[string]TagDef{
		"HSGT": {
			ID:          "HSGT",
		},
		"PYCF": {
			ID:          "PYCF",
		},
		"SMTR": {
			ID:          "SMTR",
		},
		"CORI": {
			ID:          "CORI",
		},
		"MWET": {
			ID:          "MWET",
			Name:        "MicrophoneWet",
		},
		"ARWA": {
			ID:          "ARWA",
		},
		"DZST": {
			ID:          "DZST",
		},
		"EMPT": {
			ID:          "EMPT",
		},
		"FMWR": {
			ID:          "FMWR",
		},
		"VRES": {
			ID:          "VRES",
		},
		"AUDO": {
			ID:          "AUDO",
		},
		"AUPT": {
			ID:          "AUPT",
		},
		"CDTM": {
			ID:          "CDTM",
		},
		"MAGN": {
			ID:          "MAGN",
		},
		"PIMD": {
			ID:          "PIMD",
		},
		"PRJT": {
			ID:          "PRJT",
		},
		"WBAL": {
			ID:          "WBAL",
		},
		"AALP": {
			ID:          "AALP",
		},
		"ABSC": {
			ID:          "ABSC",
		},
		"ARUW": {
			ID:          "ARUW",
		},
		"DUST": {
			ID:          "DUST",
		},
		"PIMX": {
			ID:          "PIMX",
		},
		"PTWB": {
			ID:          "PTWB",
		},
		"ORIO": {
			ID:          "ORIO",
			Name:        "OutputOrientation",
		},
		"GPSA": {
			ID:          "GPSA",
		},
		"APTO": {
			ID:          "APTO",
		},
		"MMOD": {
			ID:          "MMOD",
		},
		"PHDR": {
			ID:          "PHDR",
		},
		"VFPS": {
			ID:          "VFPS",
		},
		"DVID": {
			ID:          "DVID",
		},
		"MAPY": {
			ID:          "MAPY",
		},
		"ORIN": {
			ID:          "ORIN",
			Name:        "InputOrientation",
		},
		"UNIF": {
			ID:          "UNIF",
			Name:        "InputUniformity",
		},
		"HDRV": {
			ID:          "HDRV",
		},
		"POLY": {
			ID:          "POLY",
		},
		"PTSH": {
			ID:          "PTSH",
		},
		"SCAP": {
			ID:          "SCAP",
		},
		"SCTM": {
			ID:          "SCTM",
		},
		"SROT": {
			ID:          "SROT",
			Name:        "SensorReadoutTime",
		},
		"TSMP": {
			ID:          "TSMP",
		},
		"ZMPL": {
			ID:          "ZMPL",
		},
		"PTEV": {
			ID:          "PTEV",
		},
		"GRAV": {
			ID:          "GRAV",
		},
		"IORI": {
			ID:          "IORI",
		},
		"DZMX": {
			ID:          "DZMX",
		},
		"FCNM": {
			ID:          "FCNM",
		},
		"MUID": {
			ID:          "MUID",
		},
		"PTCL": {
			ID:          "PTCL",
		},
		"ZFOV": {
			ID:          "ZFOV",
		},
		"HUES": {
			ID:          "HUES",
			Name:        "PrediminantHue",
		},
		"FWVS": {
			ID:          "FWVS",
		},
		"AUBT": {
			ID:          "AUBT",
		},
		"FACE": {
			ID:          "FACE",
		},
		"MYCF": {
			ID:          "MYCF",
		},
		"SCEN": {
			ID:          "SCEN",
		},
		"YAVG": {
			ID:          "YAVG",
			Name:        "LumaAverage",
		},
		"CTRL": {
			ID:          "CTRL",
		},
		"ISOE": {
			ID:          "ISOE",
		},
		"CLDP": {
			ID:          "CLDP",
		},
		"ALLD": {
			ID:          "ALLD",
		},
		"CPIN": {
			ID:          "CPIN",
			Name:        "ChapterNumber",
		},
		"EISE": {
			ID:          "EISE",
		},
		"HCLT": {
			ID:          "HCLT",
		},
		"MXCF": {
			ID:          "MXCF",
		},
		"EXPT": {
			ID:          "EXPT",
		},
		"MAPX": {
			ID:          "MAPX",
		},
		"PRES": {
			ID:          "PRES",
		},
		"RATE": {
			ID:          "RATE",
		},
		"TYPE": {
			ID:          "TYPE",
		},
		"BITR": {
			ID:          "BITR",
		},
		"DVNM": {
			ID:          "DVNM",
		},
		"PIMN": {
			ID:          "PIMN",
		},
		"PWPR": {
			ID:          "PWPR",
		},
		"RAMP": {
			ID:          "RAMP",
		},
		"CASN": {
			ID:          "CASN",
		},
		"ORDP": {
			ID:          "ORDP",
		},
		"MTRX": {
			ID:          "MTRX",
			Name:        "AccelerometerMatrix",
		},
		"WNDM": {
			ID:          "WNDM",
			Name:        "WindProcessing",
		},
	},
}
