// Code generated by gen-tags. DO NOT EDIT.

package tags

// H264RecInfoTags contains tag definitions from Image::ExifTool::H264
var H264RecInfoTags = TagTable{
	ModuleName: "H264",
	Tags: map[string]TagDef{
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int8u",
		},
	},
}
