// Code generated by gen-tags. DO NOT EDIT.

package tags

// H264MakeModelTags contains tag definitions from Image::ExifTool::H264
var H264MakeModelTags = TagTable{
	ModuleName: "H264",
	Tags: map[string]TagDef{
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int16u",
		},
	},
}
