// Code generated by gen-tags. DO NOT EDIT.

package tags

// H264FrameInfoTags contains tag definitions from Image::ExifTool::H264
var H264FrameInfoTags = TagTable{
	ModuleName: "H264",
	Tags: map[string]TagDef{
		"1": {
			ID:          "1",
			Name:        "VideoFrameRate",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int8u",
		},
		"0": {
			ID:          "0",
			Name:        "CaptureFrameRate",
		},
	},
}
