// Code generated by gen-tags. DO NOT EDIT.

package tags

// HPMainTags contains tag definitions from Image::ExifTool::HP
var HPMainTags = TagTable{
	ModuleName: "HP",
	Tags: map[string]TagDef{
	},
}
