// Code generated by gen-tags. DO NOT EDIT.

package tags

// HPType2Tags contains tag definitions from Image::ExifTool::HP
var HPType2Tags = TagTable{
	ModuleName: "HP",
	Tags: map[string]TagDef{
		"Serial Number": {
			ID:          "Serial Number",
			Name:        "SerialNumber",
		},
		"Lens Shading": {
			ID:          "Lens Shading",
			Name:        "LensShading",
		},
	},
}
