// Code generated by gen-tags. DO NOT EDIT.

package tags

// HPType6Tags contains tag definitions from Image::ExifTool::HP
var HPType6Tags = TagTable{
	ModuleName: "HP",
	Tags: map[string]TagDef{
	},
}
