// Code generated by gen-tags. DO NOT EDIT.

package tags

// HPTDHDTags contains tag definitions from Image::ExifTool::HP
var HPTDHDTags = TagTable{
	ModuleName: "HP",
	Tags: map[string]TagDef{
		"FWRV": {
			ID:          "FWRV",
			Name:        "FirmwareVersion",
		},
		"CMSN": {
			ID:          "CMSN",
		},
	},
}
