// Code generated by gen-tags. DO NOT EDIT.

package tags

// HTMLdcTags contains tag definitions from Image::ExifTool::HTML
var HTMLdcTags = TagTable{
	ModuleName: "HTML",
	Tags: map[string]TagDef{
		"publisher": {
			ID:          "publisher",
		},
		"relation": {
			ID:          "relation",
		},
		"subject": {
			ID:          "subject",
		},
		"title": {
			ID:          "title",
		},
		"contributor": {
			ID:          "contributor",
		},
		"format": {
			ID:          "format",
		},
		"language": {
			ID:          "language",
		},
		"rights": {
			ID:          "rights",
		},
		"source": {
			ID:          "source",
		},
		"type": {
			ID:          "type",
		},
		"coverage": {
			ID:          "coverage",
		},
		"creator": {
			ID:          "creator",
		},
		"description": {
			ID:          "description",
		},
		"identifier": {
			ID:          "identifier",
		},
	},
}
