// Code generated by gen-tags. DO NOT EDIT.

package tags

// ICC_ProfileMainTags contains tag definitions from Image::ExifTool::ICC_Profile
var ICC_ProfileMainTags = TagTable{
	ModuleName: "ICC_Profile",
	Tags: map[string]TagDef{
		"scrn": {
			ID:          "scrn",
			Name:        "Screening",
		},
		"D2B1": {
			ID:          "D2B1",
		},
		"bsp1": {
			ID:          "bsp1",
			Name:        "BRDFSpectralParam1",
		},
		"bBA0": {
			ID:          "bBA0",
			Name:        "BRDFBToA0",
		},
		"bkpt": {
			ID:          "bkpt",
			Name:        "MediaBlackPoint",
		},
		"bMB1": {
			ID:          "bMB1",
			Name:        "BRDFMToB1",
		},
		"gdb2": {
			ID:          "gdb2",
			Name:        "GamutBoundaryDescription2",
		},
		"M2B0": {
			ID:          "M2B0",
			Name:        "MToB0",
		},
		"M2B1": {
			ID:          "M2B1",
			Name:        "MToB1",
		},
		"CxF ": {
			ID:          "CxF ",
			Name:        "CXF",
		},
		"s2cp": {
			ID:          "s2cp",
			Name:        "StandardToCustomPcc",
		},
		"wtpt": {
			ID:          "wtpt",
			Name:        "MediaWhitePoint",
		},
		"fpce": {
			ID:          "fpce",
		},
		"rhoc": {
			ID:          "rhoc",
		},
		"B2D0": {
			ID:          "B2D0",
		},
		"bAB2": {
			ID:          "bAB2",
			Name:        "BRDFAToB2",
		},
		"M2S0": {
			ID:          "M2S0",
			Name:        "MToS0",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"mmod": {
			ID:          "mmod",
			Name:        "MakeAndModel",
		},
		"bcp2": {
			ID:          "bcp2",
			Name:        "BRDFColorimetricParam2",
		},
		"bBD2": {
			ID:          "bBD2",
			Name:        "BRDFBToD2",
		},
		"scrd": {
			ID:          "scrd",
			Name:        "ScreeningDesc",
		},
		"bAB0": {
			ID:          "bAB0",
			Name:        "BRDFAToB0",
		},
		"bAB1": {
			ID:          "bAB1",
			Name:        "BRDFAToB1",
		},
		"cloo": {
			ID:          "cloo",
			Name:        "ColorantOrderOut",
		},
		"B2A1": {
			ID:          "B2A1",
			Name:        "BToA1",
		},
		"mcta": {
			ID:          "mcta",
			Name:        "MultiplexTypeArray",
		},
		"M2B2": {
			ID:          "M2B2",
			Name:        "MToB2",
		},
		"B2A3": {
			ID:          "B2A3",
			Name:        "BToA3",
		},
		"bBA1": {
			ID:          "bBA1",
			Name:        "BRDFBToA1",
		},
		"dBA0": {
			ID:          "dBA0",
			Name:        "DirectionalBToA0",
		},
		"gdb1": {
			ID:          "gdb1",
			Name:        "GamutBoundaryDescription1",
		},
		"A2B2": {
			ID:          "A2B2",
			Name:        "AToB2",
		},
		"bsp3": {
			ID:          "bsp3",
			Name:        "BRDFSpectralParam3",
		},
		"psd2": {
			ID:          "psd2",
		},
		"D2B3": {
			ID:          "D2B3",
		},
		"pre1": {
			ID:          "pre1",
			Name:        "Preview1",
		},
		"ps2s": {
			ID:          "ps2s",
		},
		"rXYZ": {
			ID:          "rXYZ",
		},
		"bcp0": {
			ID:          "bcp0",
			Name:        "BRDFColorimetricParam0",
		},
		"dAB2": {
			ID:          "dAB2",
			Name:        "DirectionalAToB2",
		},
		"M2S2": {
			ID:          "M2S2",
			Name:        "MToS2",
		},
		"A2B3": {
			ID:          "A2B3",
			Name:        "AToB3",
		},
		"bBA3": {
			ID:          "bBA3",
			Name:        "BRDFBToA3",
		},
		"bBD0": {
			ID:          "bBD0",
			Name:        "BRDFBToD0",
		},
		"dDB1": {
			ID:          "dDB1",
			Name:        "DirectionalDToB1",
		},
		"vued": {
			ID:          "vued",
			Name:        "ViewingCondDesc",
		},
		"bMB2": {
			ID:          "bMB2",
			Name:        "BRDFMToB2",
		},
		"dAB0": {
			ID:          "dAB0",
			Name:        "DirectionalAToB0",
		},
		"dBD3": {
			ID:          "dBD3",
			Name:        "DirectionalBToD3",
		},
		"c2sp": {
			ID:          "c2sp",
			Name:        "CustomToStandardPcc",
		},
		"A2B0": {
			ID:          "A2B0",
			Name:        "AToB0",
		},
		"pseq": {
			ID:          "pseq",
			Name:        "ProfileSequenceDesc",
		},
		"bMS3": {
			ID:          "bMS3",
			Name:        "BRDFMToS3",
		},
		"dBD1": {
			ID:          "dBD1",
			Name:        "DirectionalBToD1",
		},
		"M2S1": {
			ID:          "M2S1",
			Name:        "MToS1",
		},
		"clro": {
			ID:          "clro",
			Name:        "ColorantOrder",
		},
		"ncol": {
			ID:          "ncol",
		},
		"ps2i": {
			ID:          "ps2i",
		},
		"dBD0": {
			ID:          "dBD0",
			Name:        "DirectionalBToD0",
		},
		"chad": {
			ID:          "chad",
			Name:        "ChromaticAdaptation",
		},
		"bDB1": {
			ID:          "bDB1",
			Name:        "BRDFDToB1",
		},
		"bDB3": {
			ID:          "bDB3",
			Name:        "BRDFDToB3",
		},
		"M2A0": {
			ID:          "M2A0",
			Name:        "MToA0",
		},
		"MS00": {
			ID:          "MS00",
			Name:        "WCSProfiles",
		},
		"bcp3": {
			ID:          "bcp3",
			Name:        "BRDFColorimetricParam3",
		},
		"bMS2": {
			ID:          "bMS2",
			Name:        "BRDFMToS2",
		},
		"dBD2": {
			ID:          "dBD2",
			Name:        "DirectionalBToD2",
		},
		"nmcl": {
			ID:          "nmcl",
			Name:        "NamedColor",
		},
		"bXYZ": {
			ID:          "bXYZ",
		},
		"ncl2": {
			ID:          "ncl2",
			Name:        "NamedColor2",
		},
		"D2B0": {
			ID:          "D2B0",
		},
		"ndin": {
			ID:          "ndin",
			Name:        "NativeDisplayInfo",
		},
		"bDB0": {
			ID:          "bDB0",
			Name:        "BRDFDToB0",
		},
		"dBA2": {
			ID:          "dBA2",
			Name:        "DirectionalBToA2",
		},
		"swpt": {
			ID:          "swpt",
			Name:        "SpectralWhitePoint",
		},
		"desc": {
			ID:          "desc",
			Name:        "ProfileDescription",
		},
		"bAB3": {
			ID:          "bAB3",
			Name:        "BRDFAToB3",
		},
		"bBD3": {
			ID:          "bBD3",
			Name:        "BRDFBToD3",
		},
		"dAB1": {
			ID:          "dAB1",
			Name:        "DirectionalAToB1",
		},
		"minf": {
			ID:          "minf",
			Name:        "MeasurementInfo",
		},
		"miin": {
			ID:          "miin",
			Name:        "MeasurementInputInfo",
		},
		"B2A0": {
			ID:          "B2A0",
			Name:        "BToA0",
		},
		"gamt": {
			ID:          "gamt",
			Name:        "Gamut",
		},
		"psd1": {
			ID:          "psd1",
		},
		"dAB3": {
			ID:          "dAB3",
			Name:        "DirectionalAToB3",
		},
		"dDB0": {
			ID:          "dDB0",
			Name:        "DirectionalDToB0",
		},
		"dDB3": {
			ID:          "dDB3",
			Name:        "DirectionalDToB3",
		},
		"bsp2": {
			ID:          "bsp2",
			Name:        "BRDFSpectralParam2",
		},
		"clio": {
			ID:          "clio",
			Name:        "ColorantInfoOut",
		},
		"bDB2": {
			ID:          "bDB2",
			Name:        "BRDFDToB2",
		},
		"bMB3": {
			ID:          "bMB3",
			Name:        "BRDFMToB3",
		},
		"gdb3": {
			ID:          "gdb3",
			Name:        "GamutBoundaryDescription3",
		},
		"ciis": {
			ID:          "ciis",
		},
		"B2D1": {
			ID:          "B2D1",
		},
		"B2D2": {
			ID:          "B2D2",
		},
		"dscm": {
			ID:          "dscm",
			Name:        "ProfileDescriptionML",
		},
		"bBA2": {
			ID:          "bBA2",
			Name:        "BRDFBToA2",
		},
		"bMB0": {
			ID:          "bMB0",
			Name:        "BRDFMToB0",
		},
		"rfnm": {
			ID:          "rfnm",
			Name:        "ReferenceName",
		},
		"bsp0": {
			ID:          "bsp0",
			Name:        "BRDFSpectralParam0",
		},
		"M2B3": {
			ID:          "M2B3",
			Name:        "MToB3",
		},
		"psd0": {
			ID:          "psd0",
		},
		"B2D3": {
			ID:          "B2D3",
		},
		"bcp1": {
			ID:          "bcp1",
			Name:        "BRDFColorimetricParam1",
		},
		"mdv ": {
			ID:          "mdv ",
			Name:        "MultiplexDefaultValues",
		},
		"cept": {
			ID:          "cept",
			Name:        "ColorEncodingParams",
		},
		"csnm": {
			ID:          "csnm",
			Name:        "ColorSpaceName",
		},
		"scoe": {
			ID:          "scoe",
		},
		"vcgt": {
			ID:          "vcgt",
			Name:        "VideoCardGamma",
		},
		"A2M0": {
			ID:          "A2M0",
			Name:        "AToM0",
		},
		"gdb0": {
			ID:          "gdb0",
			Name:        "GamutBoundaryDescription0",
		},
		"psin": {
			ID:          "psin",
			Name:        "ProfileSequenceInfo",
		},
		"pre0": {
			ID:          "pre0",
			Name:        "Preview0",
		},
		"pre2": {
			ID:          "pre2",
			Name:        "Preview2",
		},
		"dBA1": {
			ID:          "dBA1",
			Name:        "DirectionalBToA1",
		},
		"resp": {
			ID:          "resp",
			Name:        "OutputResponse",
		},
		"bBD1": {
			ID:          "bBD1",
			Name:        "BRDFBToD1",
		},
		"bMS0": {
			ID:          "bMS0",
			Name:        "BRDFMToS0",
		},
		"dDB2": {
			ID:          "dDB2",
			Name:        "DirectionalDToB2",
		},
		"smap": {
			ID:          "smap",
			Name:        "SurfaceMap",
		},
		"D2B2": {
			ID:          "D2B2",
		},
		"hdgm": {
			ID:          "hdgm",
		},
		"svcn": {
			ID:          "svcn",
			Name:        "SpectralViewingConditions",
		},
		"A2B1": {
			ID:          "A2B1",
			Name:        "AToB1",
		},
		"B2A2": {
			ID:          "B2A2",
			Name:        "BToA2",
		},
		"gXYZ": {
			ID:          "gXYZ",
		},
		"lumi": {
			ID:          "lumi",
			Name:        "Luminance",
		},
		"bMS1": {
			ID:          "bMS1",
			Name:        "BRDFMToS1",
		},
		"dBA3": {
			ID:          "dBA3",
			Name:        "DirectionalBToA3",
		},
		"crdi": {
			ID:          "crdi",
		},
		"sape": {
			ID:          "sape",
		},
		"rpoc": {
			ID:          "rpoc",
		},
		"psvm": {
			ID:          "psvm",
			Name:        "PS2CRDVMSize",
		},
		"M2S3": {
			ID:          "M2S3",
			Name:        "MToS3",
		},
	},
}
