// Code generated by gen-tags. DO NOT EDIT.

package tags

// ICC_ProfileViewingConditionsTags contains tag definitions from Image::ExifTool::ICC_Profile
var ICC_ProfileViewingConditionsTags = TagTable{
	ModuleName: "ICC_Profile",
	Tags: map[string]TagDef{
	},
}
