// Code generated by gen-tags. DO NOT EDIT.

package tags

// ICOMainTags contains tag definitions from Image::ExifTool::ICO
var ICOMainTags = TagTable{
	ModuleName: "ICO",
	Tags: map[string]TagDef{
	},
}
