// Code generated by gen-tags. DO NOT EDIT.

package tags

// ID3CompositeTags contains tag definitions from Image::ExifTool::ID3
var ID3CompositeTags = TagTable{
	ModuleName: "ID3",
	Tags: map[string]TagDef{
	},
}
