// Code generated by gen-tags. DO NOT EDIT.

package tags

// ID3MainTags contains tag definitions from Image::ExifTool::ID3
var ID3MainTags = TagTable{
	ModuleName: "ID3",
	Tags: map[string]TagDef{
	},
}
