// Code generated by gen-tags. DO NOT EDIT.

package tags

// ID3v2_4Tags contains tag definitions from Image::ExifTool::ID3
var ID3v2_4Tags = TagTable{
	ModuleName: "ID3",
	Tags: map[string]TagDef{
		"RVA2": {
			ID:          "RVA2",
			Name:        "RelativeVolumeAdjustment",
		},
		"TDEN": {
			ID:          "TDEN",
		},
		"TDRC": {
			ID:          "TDRC",
		},
		"TDTG": {
			ID:          "TDTG",
		},
		"TPRO": {
			ID:          "TPRO",
			Name:        "ProducedNotice",
		},
		"TSOP": {
			ID:          "TSOP",
			Name:        "PerformerSortOrder",
		},
		"TSOT": {
			ID:          "TSOT",
			Name:        "TitleSortOrder",
		},
		"TSST": {
			ID:          "TSST",
			Name:        "SetSubtitle",
		},
		"TDOR": {
			ID:          "TDOR",
		},
		"TDRL": {
			ID:          "TDRL",
		},
		"TIPL": {
			ID:          "TIPL",
			Name:        "InvolvedPeople",
		},
		"TMCL": {
			ID:          "TMCL",
			Name:        "MusicianCredits",
		},
		"TMOO": {
			ID:          "TMOO",
			Name:        "Mood",
		},
		"TSOA": {
			ID:          "TSOA",
			Name:        "AlbumSortOrder",
		},
	},
}
