// Code generated by gen-tags. DO NOT EDIT.

package tags

// ID3v2_2Tags contains tag definitions from Image::ExifTool::ID3
var ID3v2_2Tags = TagTable{
	ModuleName: "ID3",
	Tags: map[string]TagDef{
		"IPL": {
			ID:          "IPL",
			Name:        "InvolvedPeople",
		},
		"TDA": {
			ID:          "TDA",
		},
		"TOR": {
			ID:          "TOR",
			Name:        "OriginalReleaseYear",
		},
		"TSI": {
			ID:          "TSI",
			Name:        "Size",
		},
		"TYE": {
			ID:          "TYE",
		},
		"RVA": {
			ID:          "RVA",
			Name:        "RelativeVolumeAdjustment",
		},
		"TSA": {
			ID:          "TSA",
			Name:        "AlbumSortOrder",
		},
		"GP1": {
			ID:          "GP1",
		},
		"TSS": {
			ID:          "TSS",
			Name:        "EncoderSettings",
		},
		"TDY": {
			ID:          "TDY",
			Name:        "PlaylistDelay",
		},
		"TRC": {
			ID:          "TRC",
		},
		"WAS": {
			ID:          "WAS",
			Name:        "SourceURL",
		},
		"TMT": {
			ID:          "TMT",
			Name:        "Media",
		},
		"TOL": {
			ID:          "TOL",
			Name:        "OriginalLyricist",
		},
		"TP2": {
			ID:          "TP2",
			Name:        "Band",
		},
		"TRD": {
			ID:          "TRD",
			Name:        "RecordingDates",
		},
		"WXX": {
			ID:          "WXX",
			Name:        "UserDefinedURL",
		},
		"COM": {
			ID:          "COM",
			Name:        "Comment",
		},
		"PIC-3": {
			ID:          "PIC-3",
		},
		"TEN": {
			ID:          "TEN",
			Name:        "EncodedBy",
		},
		"TPB": {
			ID:          "TPB",
			Name:        "Publisher",
		},
		"TRK": {
			ID:          "TRK",
			Name:        "Track",
		},
		"WAF": {
			ID:          "WAF",
			Name:        "FileURL",
		},
		"TS2": {
			ID:          "TS2",
			Name:        "AlbumArtistSortOrder",
		},
		"TBP": {
			ID:          "TBP",
			Name:        "BeatsPerMinute",
		},
		"TFT": {
			ID:          "TFT",
			Name:        "FileType",
		},
		"TOT": {
			ID:          "TOT",
			Name:        "OriginalAlbum",
		},
		"TP1": {
			ID:          "TP1",
		},
		"TT1": {
			ID:          "TT1",
			Name:        "Grouping",
		},
		"MVN": {
			ID:          "MVN",
		},
		"TOF": {
			ID:          "TOF",
			Name:        "OriginalFileName",
		},
		"TKE": {
			ID:          "TKE",
			Name:        "InitialKey",
		},
		"TLE": {
			ID:          "TLE",
			Name:        "Length",
		},
		"TPA": {
			ID:          "TPA",
			Name:        "PartOfSet",
		},
		"TIM": {
			ID:          "TIM",
		},
		"TXX": {
			ID:          "TXX",
			Name:        "UserDefinedText",
		},
		"PIC-1": {
			ID:          "PIC-1",
		},
		"TOA": {
			ID:          "TOA",
		},
		"TT2": {
			ID:          "TT2",
			Name:        "Title",
		},
		"ULT": {
			ID:          "ULT",
			Name:        "Lyrics",
		},
		"WAR": {
			ID:          "WAR",
		},
		"WCM": {
			ID:          "WCM",
			Name:        "CommercialURL",
		},
		"WPB": {
			ID:          "WPB",
			Name:        "PublisherURL",
		},
		"TP3": {
			ID:          "TP3",
			Name:        "Conductor",
		},
		"TST": {
			ID:          "TST",
			Name:        "TitleSortOrder",
		},
		"TSP": {
			ID:          "TSP",
			Name:        "PerformerSortOrder",
		},
		"TCP": {
			ID:          "TCP",
		},
		"TSC": {
			ID:          "TSC",
			Name:        "ComposerSortOrder",
		},
		"CNT": {
			ID:          "CNT",
			Name:        "PlayCounter",
		},
		"TCR": {
			ID:          "TCR",
		},
		"TP4": {
			ID:          "TP4",
			Name:        "InterpretedBy",
		},
		"TCM": {
			ID:          "TCM",
			Name:        "Composer",
		},
		"TLA": {
			ID:          "TLA",
			Name:        "Language",
		},
		"TT3": {
			ID:          "TT3",
			Name:        "Subtitle",
		},
		"TXT": {
			ID:          "TXT",
			Name:        "Lyricist",
		},
		"ITU": {
			ID:          "ITU",
		},
		"PCS": {
			ID:          "PCS",
		},
		"TAL": {
			ID:          "TAL",
			Name:        "Album",
		},
		"WCP": {
			ID:          "WCP",
		},
		"MVI": {
			ID:          "MVI",
		},
	},
}
