// Code generated by gen-tags. DO NOT EDIT.

package tags

// ID3v2_3Tags contains tag definitions from Image::ExifTool::ID3
var ID3v2_3Tags = TagTable{
	ModuleName: "ID3",
	Tags: map[string]TagDef{
		"TDAT": {
			ID:          "TDAT",
		},
		"TIME": {
			ID:          "TIME",
		},
		"TORY": {
			ID:          "TORY",
			Name:        "OriginalReleaseYear",
		},
		"TRDA": {
			ID:          "TRDA",
			Name:        "RecordingDates",
		},
		"TSIZ": {
			ID:          "TSIZ",
			Name:        "Size",
		},
		"TYER": {
			ID:          "TYER",
		},
		"IPLS": {
			ID:          "IPLS",
			Name:        "InvolvedPeople",
		},
	},
}
