// Code generated by gen-tags. DO NOT EDIT.

package tags

// InfiRayVersionTags contains tag definitions from Image::ExifTool::InfiRay
var InfiRayVersionTags = TagTable{
	ModuleName: "InfiRay",
	Tags: map[string]TagDef{
		"0x2C": {
			ID:          "0x2C",
		},
		"0x2E": {
			ID:          "0x2E",
		},
		"0x4A": {
			ID:          "0x4A",
		},
		"0x0E": {
			ID:          "0x0E",
		},
		"0x3A": {
			ID:          "0x3A",
		},
		"0x3E": {
			ID:          "0x3E",
		},
		"0x40": {
			ID:          "0x40",
		},
		"0x0D": {
			ID:          "0x0D",
		},
		"0x28": {
			ID:          "0x28",
		},
		"0x38": {
			ID:          "0x38",
		},
		"0x48": {
			ID:          "0x48",
		},
		"0x00": {
			ID:          "0x00",
		},
		"0x11": {
			ID:          "0x11",
		},
		"0x30": {
			ID:          "0x30",
		},
		"0x3C": {
			ID:          "0x3C",
		},
		"0x4C": {
			ID:          "0x4C",
		},
		"0x4E": {
			ID:          "0x4E",
		},
		"0x0C": {
			ID:          "0x0C",
		},
		"0x0F": {
			ID:          "0x0F",
		},
		"0x10": {
			ID:          "0x10",
		},
		"0x20": {
			ID:          "0x20",
		},
		"0x2A": {
			ID:          "0x2A",
		},
	},
}
