// Code generated by gen-tags. DO NOT EDIT.

package tags

// InfiRayMixModeTags contains tag definitions from Image::ExifTool::InfiRay
var InfiRayMixModeTags = TagTable{
	ModuleName: "InfiRay",
	Tags: map[string]TagDef{
		"0x00": {
			ID:          "0x00",
		},
		"0x01": {
			ID:          "0x01",
		},
		"0x05": {
			ID:          "0x05",
		},
		"0x09": {
			ID:          "0x09",
		},
	},
}
