// Code generated by gen-tags. DO NOT EDIT.

package tags

// InfiRaySensorTags contains tag definitions from Image::ExifTool::InfiRay
var InfiRaySensorTags = TagTable{
	ModuleName: "InfiRay",
	Tags: map[string]TagDef{
		"0x100": {
			ID:          "0x100",
		},
		"0x180": {
			ID:          "0x180",
		},
		"0x2C0": {
			ID:          "0x2C0",
		},
		"0x000": {
			ID:          "0x000",
		},
		"0x140": {
			ID:          "0x140",
		},
		"0x144": {
			ID:          "0x144",
		},
		"0x1C0": {
			ID:          "0x1C0",
		},
		"0x200": {
			ID:          "0x200",
		},
		"0x240": {
			ID:          "0x240",
		},
		"0x280": {
			ID:          "0x280",
		},
		"0x2C4": {
			ID:          "0x2C4",
		},
		"0x040": {
			ID:          "0x040",
		},
		"0x080": {
			ID:          "0x080",
		},
		"0x0C0": {
			ID:          "0x0C0",
		},
	},
}
