// Code generated by gen-tags. DO NOT EDIT.

package tags

// IPTCCompositeTags contains tag definitions from Image::ExifTool::IPTC
var IPTCCompositeTags = TagTable{
	ModuleName: "IPTC",
	Tags: map[string]TagDef{
	},
}
