// Code generated by gen-tags. DO NOT EDIT.

package tags

// IPTCEnvelopeRecordTags contains tag definitions from Image::ExifTool::IPTC
var IPTCEnvelopeRecordTags = TagTable{
	ModuleName: "IPTC",
	Tags: map[string]TagDef{
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"WRITABLE": {
			ID:          "WRITABLE",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
	},
}
