// Code generated by gen-tags. DO NOT EDIT.

package tags

// IPTCiptcCharsetTags contains tag definitions from Image::ExifTool::IPTC
var IPTCiptcCharsetTags = TagTable{
	ModuleName: "IPTC",
	Tags: map[string]TagDef{
		"\\x1b%G": {
			ID:          "\\x1b%G",
			Name:        "UTF8",
		},
	},
}
