// Code generated by gen-tags. DO NOT EDIT.

package tags

// IPTCPostObjectDataTags contains tag definitions from Image::ExifTool::IPTC
var IPTCPostObjectDataTags = TagTable{
	ModuleName: "IPTC",
	Tags: map[string]TagDef{
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
	},
}
