// Code generated by gen-tags. DO NOT EDIT.

package tags

// ISOBootRecordTags contains tag definitions from Image::ExifTool::ISO
var ISOBootRecordTags = TagTable{
	ModuleName: "ISO",
	Tags: map[string]TagDef{
		"7": {
			ID:          "7",
		},
		"39": {
			ID:          "39",
		},
	},
}
