// Code generated by gen-tags. DO NOT EDIT.

package tags

// ISOPrimaryVolumeTags contains tag definitions from Image::ExifTool::ISO
var ISOPrimaryVolumeTags = TagTable{
	ModuleName: "ISO",
	Tags: map[string]TagDef{
		"40": {
			ID:          "40",
		},
		"124": {
			ID:          "124",
		},
		"190": {
			ID:          "190",
		},
		"318": {
			ID:          "318",
		},
		"830": {
			ID:          "830",
		},
		"120": {
			ID:          "120",
		},
		"446": {
			ID:          "446",
		},
		"740": {
			ID:          "740",
		},
		"813": {
			ID:          "813",
		},
		"847": {
			ID:          "847",
		},
		"132": {
			ID:          "132",
		},
		"140": {
			ID:          "140",
		},
		"574": {
			ID:          "574",
		},
		"776": {
			ID:          "776",
		},
		"80": {
			ID:          "80",
		},
		"128": {
			ID:          "128",
		},
		"702": {
			ID:          "702",
		},
		"864": {
			ID:          "864",
		},
		"8": {
			ID:          "8",
		},
	},
}
