// Code generated by gen-tags. DO NOT EDIT.

package tags

// ITCHeaderTags contains tag definitions from Image::ExifTool::ITC
var ITCHeaderTags = TagTable{
	ModuleName: "ITC",
	Tags: map[string]TagDef{
	},
}
