// Code generated by gen-tags. DO NOT EDIT.

package tags

// ITCMainTags contains tag definitions from Image::ExifTool::ITC
var ITCMainTags = TagTable{
	ModuleName: "ITC",
	Tags: map[string]TagDef{
		"itch": {
			ID:          "itch",
		},
		"item": {
			ID:          "item",
		},
	},
}
