// Code generated by gen-tags. DO NOT EDIT.

package tags

// ITCItemTags contains tag definitions from Image::ExifTool::ITC
var ITCItemTags = TagTable{
	ModuleName: "ITC",
	Tags: map[string]TagDef{
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int32u",
		},
		"7": {
			ID:          "7",
			Name:        "ImageWidth",
		},
		"8": {
			ID:          "8",
			Name:        "ImageHeight",
		},
	},
}
