// Code generated by gen-tags. DO NOT EDIT.

package tags

// JPEGJPSTags contains tag definitions from Image::ExifTool::JPEG
var JPEGJPSTags = TagTable{
	ModuleName: "JPEG",
	Tags: map[string]TagDef{
	},
}
