// Code generated by gen-tags. DO NOT EDIT.

package tags

// JPEGMediaJukeboxTags contains tag definitions from Image::ExifTool::JPEG
var JPEGMediaJukeboxTags = TagTable{
	ModuleName: "JPEG",
	Tags: map[string]TagDef{
	},
}
