// Code generated by gen-tags. DO NOT EDIT.

package tags

// Jpeg2000DisplayResolutionTags contains tag definitions from Image::ExifTool::Jpeg2000
var Jpeg2000DisplayResolutionTags = TagTable{
	ModuleName: "Jpeg2000",
	Tags: map[string]TagDef{
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int8s",
		},
	},
}
