// Code generated by gen-tags. DO NOT EDIT.

package tags

// JVCTextTags contains tag definitions from Image::ExifTool::JVC
var JVCTextTags = TagTable{
	ModuleName: "JVC",
	Tags: map[string]TagDef{
		"VER": {
			ID:          "VER",
		},
	},
}
