// Code generated by gen-tags. DO NOT EDIT.

package tags

// KodakType10Tags contains tag definitions from Image::ExifTool::Kodak
var KodakType10Tags = TagTable{
	ModuleName: "Kodak",
	Tags: map[string]TagDef{
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"PRIORITY": {
			ID:          "PRIORITY",
		},
	},
}
