// Code generated by gen-tags. DO NOT EDIT.

package tags

// KodakCompositeTags contains tag definitions from Image::ExifTool::Kodak
var KodakCompositeTags = TagTable{
	ModuleName: "Kodak",
	Tags: map[string]TagDef{
	},
}
