// Code generated by gen-tags. DO NOT EDIT.

package tags

// KodakFreeTags contains tag definitions from Image::ExifTool::Kodak
var KodakFreeTags = TagTable{
	ModuleName: "Kodak",
	Tags: map[string]TagDef{
		"ISOS": {
			ID:          "ISOS",
		},
	},
}
