// Code generated by gen-tags. DO NOT EDIT.

package tags

// KodakSubIFD2Tags contains tag definitions from Image::ExifTool::Kodak
var KodakSubIFD2Tags = TagTable{
	ModuleName: "Kodak",
	Tags: map[string]TagDef{
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
	},
}
