// Code generated by gen-tags. DO NOT EDIT.

package tags

// KodakfreaTags contains tag definitions from Image::ExifTool::Kodak
var KodakfreaTags = TagTable{
	ModuleName: "Kodak",
	Tags: map[string]TagDef{
		"ver ": {
			ID:          "ver ",
		},
		"thma": {
			ID:          "thma",
		},
		"scra": {
			ID:          "scra",
		},
	},
}
