// Code generated by gen-tags. DO NOT EDIT.

package tags

// KodakMetaTags contains tag definitions from Image::ExifTool::Kodak
var KodakMetaTags = TagTable{
	ModuleName: "Kodak",
	Tags: map[string]TagDef{
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"0xC350": {
			ID:          "0xC350",
			Name:        "FilmProductCode",
		},
		"0xC355": {
			ID:          "0xC355",
			Name:        "UserSelectGroupTitle",
		},
		"0xC365": {
			ID:          "0xC365",
			Name:        "MetadataNumber",
		},
		"0xC36D": {
			ID:          "0xC36D",
			Name:        "NativeYResolution",
		},
		"0xC419": {
			ID:          "0xC419",
			Name:        "SourceImageFileName",
		},
		"0xC46C": {
			ID:          "0xC46C",
			Name:        "PrintQuality",
		},
		"0xC35B": {
			ID:          "0xC35B",
			Name:        "FilmGencode",
		},
		"0xC35D": {
			ID:          "0xC35D",
			Name:        "FilmSize",
		},
		"0xC363": {
			ID:          "0xC363",
			Name:        "ImageRotationStatus",
		},
		"WRITE_GROUP": {
			ID:          "WRITE_GROUP",
		},
		"0xC358": {
			ID:          "0xC358",
			Name:        "EnvelopeNumber",
		},
		"0xC35F": {
			ID:          "0xC35F",
			Name:        "SBAInputImageColorspace",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"0xC359": {
			ID:          "0xC359",
			Name:        "FrameNumber",
		},
		"0xC418": {
			ID:          "0xC418",
			Name:        "SourceImageDirectory",
		},
		"0xC46E": {
			ID:          "0xC46E",
			Name:        "ImagePrintStatus",
		},
		"0xC351": {
			ID:          "0xC351",
			Name:        "ImageSourceEK",
		},
		"0xC35A": {
			ID:          "0xC35A",
			Name:        "FilmCategory",
		},
		"0xC360": {
			ID:          "0xC360",
			Name:        "SBAInputImageBitDepth",
		},
		"0xC36C": {
			ID:          "0xC36C",
			Name:        "NativeXResolution",
		},
		"0xC366": {
			ID:          "0xC366",
			Name:        "EditTagArray",
		},
		"0xC367": {
			ID:          "0xC367",
			Name:        "Magnification",
		},
		"0xC37A": {
			ID:          "0xC37A",
			Name:        "NativeResolutionUnit",
		},
		"0xC41A": {
			ID:          "0xC41A",
			Name:        "SourceImageVolumeName",
		},
		"0xC352": {
			ID:          "0xC352",
			Name:        "CaptureConditionsPAR",
		},
		"0xC364": {
			ID:          "0xC364",
			Name:        "RollGuidElements",
		},
		"0xC356": {
			ID:          "0xC356",
			Name:        "DealerIDNumber",
		},
		"0xC357": {
			ID:          "0xC357",
			Name:        "CaptureDeviceFID",
		},
		"0xC35C": {
			ID:          "0xC35C",
			Name:        "ModelAndVersion",
		},
		"0xC35E": {
			ID:          "0xC35E",
			Name:        "SBA_RGBShifts",
		},
	},
}
