// Code generated by gen-tags. DO NOT EDIT.

package tags

// Latin2Latin2Tags contains tag definitions from 
var Latin2Latin2Tags = TagTable{
	ModuleName: "Latin2",
	Tags: map[string]TagDef{
		"0x80": {
			ID:          "0x80",
		},
		"0x86": {
			ID:          "0x86",
		},
		"0x8F": {
			ID:          "0x8F",
		},
		"0x9D": {
			ID:          "0x9D",
		},
		"0xC6": {
			ID:          "0xC6",
		},
		"0xDE": {
			ID:          "0xDE",
		},
		"0xFE": {
			ID:          "0xFE",
		},
		"0x8B": {
			ID:          "0x8B",
		},
		"0x94": {
			ID:          "0x94",
		},
		"0x99": {
			ID:          "0x99",
		},
		"0xAF": {
			ID:          "0xAF",
		},
		"0xBF": {
			ID:          "0xBF",
		},
		"0xEF": {
			ID:          "0xEF",
		},
		"0xA2": {
			ID:          "0xA2",
		},
		"0xF5": {
			ID:          "0xF5",
		},
		"0xBA": {
			ID:          "0xBA",
		},
		"0xCF": {
			ID:          "0xCF",
		},
		"0xD5": {
			ID:          "0xD5",
		},
		"0xE6": {
			ID:          "0xE6",
		},
	},
}
