// Code generated by gen-tags. DO NOT EDIT.

package tags

// LeafSubIFDTags contains tag definitions from Image::ExifTool::Leaf
var LeafSubIFDTags = TagTable{
	ModuleName: "Leaf",
	Tags: map[string]TagDef{
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
	},
}
