// Code generated by gen-tags. DO NOT EDIT.

package tags

// LeafColorSetupTags contains tag definitions from Image::ExifTool::Leaf
var LeafColorSetupTags = TagTable{
	ModuleName: "Leaf",
	Tags: map[string]TagDef{
		"ColorObj_type": {
			ID:          "ColorObj_type",
		},
		"ColorObj_has_ICC": {
			ID:          "ColorObj_has_ICC",
		},
		"ColorObj_output_profile": {
			ID:          "ColorObj_output_profile",
		},
		"ColorObj_color_mode": {
			ID:          "ColorObj_color_mode",
		},
		"ColorObj_color_type": {
			ID:          "ColorObj_color_type",
		},
		"ColorObj_version": {
			ID:          "ColorObj_version",
		},
		"ColorObj_name": {
			ID:          "ColorObj_name",
		},
		"ColorObj_back_type": {
			ID:          "ColorObj_back_type",
		},
		"ColorObj_input_profile": {
			ID:          "ColorObj_input_profile",
		},
	},
}
