// Code generated by gen-tags. DO NOT EDIT.

package tags

// LeafSelectionTags contains tag definitions from Image::ExifTool::Leaf
var LeafSelectionTags = TagTable{
	ModuleName: "Leaf",
	Tags: map[string]TagDef{
		"SelObj_version": {
			ID:          "SelObj_version",
		},
		"SelObj_name": {
			ID:          "SelObj_name",
		},
		"SelObj_type": {
			ID:          "SelObj_type",
		},
		"SelObj_resolution": {
			ID:          "SelObj_resolution",
		},
		"SelObj_scale": {
			ID:          "SelObj_scale",
		},
		"SelObj_locks": {
			ID:          "SelObj_locks",
		},
		"SelObj_orientation": {
			ID:          "SelObj_orientation",
		},
		"SelObj_back_type": {
			ID:          "SelObj_back_type",
		},
		"SelObj_rect": {
			ID:          "SelObj_rect",
		},
	},
}
