// Code generated by gen-tags. DO NOT EDIT.

package tags

// LeafToneCurveTags contains tag definitions from Image::ExifTool::Leaf
var LeafToneCurveTags = TagTable{
	ModuleName: "Leaf",
	Tags: map[string]TagDef{
		"ToneObj_version": {
			ID:          "ToneObj_version",
		},
		"ToneObj_name": {
			ID:          "ToneObj_name",
		},
		"ToneObj_type": {
			ID:          "ToneObj_type",
		},
		"ToneObj_back_type": {
			ID:          "ToneObj_back_type",
		},
		"ToneObj_npts": {
			ID:          "ToneObj_npts",
		},
		"ToneObj_tones": {
			ID:          "ToneObj_tones",
		},
		"ToneObj_gamma": {
			ID:          "ToneObj_gamma",
		},
	},
}
