// Code generated by gen-tags. DO NOT EDIT.

package tags

// LeafCameraProfileTags contains tag definitions from Image::ExifTool::Leaf
var LeafCameraProfileTags = TagTable{
	ModuleName: "Leaf",
	Tags: map[string]TagDef{
		"CamProf_version": {
			ID:          "CamProf_version",
			Name:        "CameraProfileVersion",
		},
		"CamProf_name": {
			ID:          "CamProf_name",
			Name:        "CameraName",
		},
		"CamProf_type": {
			ID:          "CamProf_type",
			Name:        "CameraType",
		},
		"CamProf_back_type": {
			ID:          "CamProf_back_type",
			Name:        "CameraBackType",
		},
	},
}
