// Code generated by gen-tags. DO NOT EDIT.

package tags

// LeafCaptureProfileTags contains tag definitions from Image::ExifTool::Leaf
var LeafCaptureProfileTags = TagTable{
	ModuleName: "Leaf",
	Tags: map[string]TagDef{
		"CaptProf_name": {
			ID:          "CaptProf_name",
		},
		"CaptProf_type": {
			ID:          "CaptProf_type",
		},
		"CaptProf_back_type": {
			ID:          "CaptProf_back_type",
		},
		"CaptProf_xy_offset_info": {
			ID:          "CaptProf_xy_offset_info",
			Name:        "XYOffsetInfo",
		},
		"CaptProf_reconstruction_type": {
			ID:          "CaptProf_reconstruction_type",
		},
		"CaptProf_CCD_rect": {
			ID:          "CaptProf_CCD_rect",
		},
		"CaptProf_CCD_valid_rect": {
			ID:          "CaptProf_CCD_valid_rect",
		},
		"CaptProf_luminance_consts": {
			ID:          "CaptProf_luminance_consts",
		},
		"CaptProf_image_fields": {
			ID:          "CaptProf_image_fields",
		},
		"CaptProf_raw_data_rotation": {
			ID:          "CaptProf_raw_data_rotation",
		},
		"CaptProf_left_dark_rect": {
			ID:          "CaptProf_left_dark_rect",
		},
		"CaptProf_color_matrix": {
			ID:          "CaptProf_color_matrix",
		},
		"CaptProf_number_of_planes": {
			ID:          "CaptProf_number_of_planes",
		},
		"CaptProf_color_averages": {
			ID:          "CaptProf_color_averages",
		},
		"CaptProf_right_dark_rect": {
			ID:          "CaptProf_right_dark_rect",
		},
		"CaptProf_center_dark_rect": {
			ID:          "CaptProf_center_dark_rect",
		},
		"CaptProf_version": {
			ID:          "CaptProf_version",
		},
		"CaptProf_image_offset": {
			ID:          "CaptProf_image_offset",
		},
		"CaptProf_image_bounds": {
			ID:          "CaptProf_image_bounds",
		},
		"CaptProf_mosaic_pattern": {
			ID:          "CaptProf_mosaic_pattern",
		},
		"CaptProf_dark_correction_type": {
			ID:          "CaptProf_dark_correction_type",
		},
		"CaptProf_CCD_video_rect": {
			ID:          "CaptProf_CCD_video_rect",
		},
	},
}
