// Code generated by gen-tags. DO NOT EDIT.

package tags

// LeafCaptureSetupTags contains tag definitions from Image::ExifTool::Leaf
var LeafCaptureSetupTags = TagTable{
	ModuleName: "Leaf",
	Tags: map[string]TagDef{
		"CaptureObj_back_type": {
			ID:          "CaptureObj_back_type",
		},
		"CaptureObj_single_quality": {
			ID:          "CaptureObj_single_quality",
		},
		"CaptureObj_Multi_quality": {
			ID:          "CaptureObj_Multi_quality",
		},
		"CaptureObj_version": {
			ID:          "CaptureObj_version",
		},
		"CaptureObj_name": {
			ID:          "CaptureObj_name",
		},
		"CaptureObj_type": {
			ID:          "CaptureObj_type",
		},
	},
}
