// Code generated by gen-tags. DO NOT EDIT.

package tags

// LeafShootSetupTags contains tag definitions from Image::ExifTool::Leaf
var LeafShootSetupTags = TagTable{
	ModuleName: "Leaf",
	Tags: map[string]TagDef{
		"ShootObj_version": {
			ID:          "ShootObj_version",
		},
		"ShootObj_name": {
			ID:          "ShootObj_name",
		},
		"ShootObj_type": {
			ID:          "ShootObj_type",
		},
		"ShootObj_back_type": {
			ID:          "ShootObj_back_type",
		},
	},
}
