// Code generated by gen-tags. DO NOT EDIT.

package tags

// LeafSharpnessTags contains tag definitions from Image::ExifTool::Leaf
var LeafSharpnessTags = TagTable{
	ModuleName: "Leaf",
	Tags: map[string]TagDef{
		"SharpObj_back_type": {
			ID:          "SharpObj_back_type",
		},
		"SharpObj_sharp_method": {
			ID:          "SharpObj_sharp_method",
		},
		"SharpObj_data_len": {
			ID:          "SharpObj_data_len",
		},
		"SharpObj_sharp_info": {
			ID:          "SharpObj_sharp_info",
		},
		"SharpObj_version": {
			ID:          "SharpObj_version",
		},
		"SharpObj_name": {
			ID:          "SharpObj_name",
		},
		"SharpObj_type": {
			ID:          "SharpObj_type",
		},
	},
}
