// Code generated by gen-tags. DO NOT EDIT.

package tags

// LNKMainTags contains tag definitions from Image::ExifTool::LNK
var LNKMainTags = TagTable{
	ModuleName: "LNK",
	Tags: map[string]TagDef{
		"0x30010": {
			ID:          "0x30010",
			Name:        "WorkingDirectory",
		},
		"0x30020": {
			ID:          "0x30020",
			Name:        "CommandLineArguments",
		},
		"0x30040": {
			ID:          "0x30040",
			Name:        "IconFileName",
		},
		"0x30004": {
			ID:          "0x30004",
			Name:        "Description",
		},
		"0x30008": {
			ID:          "0x30008",
			Name:        "RelativePath",
		},
	},
}
