// Code generated by gen-tags. DO NOT EDIT.

package tags

// LNKConsoleFEDataTags contains tag definitions from Image::ExifTool::LNK
var LNKConsoleFEDataTags = TagTable{
	ModuleName: "LNK",
	Tags: map[string]TagDef{
	},
}
