// Code generated by gen-tags. DO NOT EDIT.

package tags

// LNKItem0032Tags contains tag definitions from Image::ExifTool::LNK
var LNKItem0032Tags = TagTable{
	ModuleName: "LNK",
	Tags: map[string]TagDef{
	},
}
