// Code generated by gen-tags. DO NOT EDIT.

package tags

// LytroMainTags contains tag definitions from Image::ExifTool::Lytro
var LytroMainTags = TagTable{
	ModuleName: "Lytro",
	Tags: map[string]TagDef{
		"DevicesAccelerometerSampleArrayX": {
			ID:          "DevicesAccelerometerSampleArrayX",
		},
		"DevicesSensorSensorSerial": {
			ID:          "DevicesSensorSensorSerial",
		},
		"DevicesSensorIso": {
			ID:          "DevicesSensorIso",
		},
		"ImageLimitExposureBias": {
			ID:          "ImageLimitExposureBias",
		},
		"Type": {
			ID:          "Type",
		},
		"CameraModel": {
			ID:          "CameraModel",
		},
		"CameraSerialNumber": {
			ID:          "CameraSerialNumber",
		},
		"DevicesAccelerometerSampleArrayY": {
			ID:          "DevicesAccelerometerSampleArrayY",
		},
		"DevicesAccelerometerSampleArrayZ": {
			ID:          "DevicesAccelerometerSampleArrayZ",
		},
		"ImageModulationExposureBias": {
			ID:          "ImageModulationExposureBias",
		},
		"CameraMake": {
			ID:          "CameraMake",
		},
		"CameraFirmware": {
			ID:          "CameraFirmware",
		},
		"DevicesAccelerometerSampleArrayTime": {
			ID:          "DevicesAccelerometerSampleArrayTime",
		},
	},
}
