// Code generated by gen-tags. DO NOT EDIT.

package tags

// M2TSMainTags contains tag definitions from Image::ExifTool::M2TS
var M2TSMainTags = TagTable{
	ModuleName: "M2TS",
	Tags: map[string]TagDef{
		"_AC3": {
			ID:          "_AC3",
		},
		"_H264": {
			ID:          "_H264",
		},
		"_MISB": {
			ID:          "_MISB",
		},
	},
}
