// Code generated by gen-tags. DO NOT EDIT.

package tags

// MacArabicMacArabicTags contains tag definitions from 
var MacArabicMacArabicTags = TagTable{
	ModuleName: "MacArabic",
	Tags: map[string]TagDef{
		"0x99": {
			ID:          "0x99",
		},
		"0x9E": {
			ID:          "0x9E",
		},
		"0xA8": {
			ID:          "0xA8",
		},
		"0xC0": {
			ID:          "0xC0",
		},
		"0x8F": {
			ID:          "0x8F",
		},
		"0xA3": {
			ID:          "0xA3",
		},
		"0xCC": {
			ID:          "0xCC",
		},
		"0xF6": {
			ID:          "0xF6",
		},
		"0xC8": {
			ID:          "0xC8",
		},
		"0xD8": {
			ID:          "0xD8",
		},
		"0x85": {
			ID:          "0x85",
		},
		"0xF2": {
			ID:          "0xF2",
		},
		"0xFA": {
			ID:          "0xFA",
		},
		"0xB2": {
			ID:          "0xB2",
		},
		"0xB6": {
			ID:          "0xB6",
		},
		"0xD4": {
			ID:          "0xD4",
		},
		"0x94": {
			ID:          "0x94",
		},
		"0xBB": {
			ID:          "0xBB",
		},
		"0xD0": {
			ID:          "0xD0",
		},
		"0xDD": {
			ID:          "0xDD",
		},
		"0xE2": {
			ID:          "0xE2",
		},
		"0xFF": {
			ID:          "0xFF",
		},
		"0x80": {
			ID:          "0x80",
		},
		"0xC4": {
			ID:          "0xC4",
		},
		"0xEA": {
			ID:          "0xEA",
		},
		"0xAD": {
			ID:          "0xAD",
		},
		"0xEE": {
			ID:          "0xEE",
		},
		"0xE6": {
			ID:          "0xE6",
		},
		"0x8A": {
			ID:          "0x8A",
		},
	},
}
