// Code generated by gen-tags. DO NOT EDIT.

package tags

// MacCyrillicMacCyrillicTags contains tag definitions from 
var MacCyrillicMacCyrillicTags = TagTable{
	ModuleName: "MacCyrillic",
	Tags: map[string]TagDef{
		"0xB0": {
			ID:          "0xB0",
		},
		"0x90": {
			ID:          "0x90",
		},
		"0xA0": {
			ID:          "0xA0",
		},
		"0xD5": {
			ID:          "0xD5",
		},
		"0xFE": {
			ID:          "0xFE",
		},
		"0xE2": {
			ID:          "0xE2",
		},
		"0xAC": {
			ID:          "0xAC",
		},
		"0x88": {
			ID:          "0x88",
		},
		"0xA6": {
			ID:          "0xA6",
		},
		"0xBE": {
			ID:          "0xBE",
		},
		"0xC3": {
			ID:          "0xC3",
		},
		"0xC8": {
			ID:          "0xC8",
		},
		"0xCD": {
			ID:          "0xCD",
		},
		"0xF2": {
			ID:          "0xF2",
		},
		"0xFA": {
			ID:          "0xFA",
		},
		"0x8C": {
			ID:          "0x8C",
		},
		"0x94": {
			ID:          "0x94",
		},
		"0x98": {
			ID:          "0x98",
		},
		"0xDA": {
			ID:          "0xDA",
		},
		"0xDE": {
			ID:          "0xDE",
		},
		"0x80": {
			ID:          "0x80",
		},
		"0x84": {
			ID:          "0x84",
		},
		"0xEE": {
			ID:          "0xEE",
		},
		"0xF6": {
			ID:          "0xF6",
		},
		"0xD1": {
			ID:          "0xD1",
		},
		"0xE6": {
			ID:          "0xE6",
		},
		"0xB6": {
			ID:          "0xB6",
		},
		"0x9C": {
			ID:          "0x9C",
		},
		"0xBA": {
			ID:          "0xBA",
		},
		"0xEA": {
			ID:          "0xEA",
		},
	},
}
