// Code generated by gen-tags. DO NOT EDIT.

package tags

// MacCroatianMacCroatianTags contains tag definitions from 
var MacCroatianMacCroatianTags = TagTable{
	ModuleName: "MacCroatian",
	Tags: map[string]TagDef{
		"0x80": {
			ID:          "0x80",
		},
		"0xAA": {
			ID:          "0xAA",
		},
		"0xBF": {
			ID:          "0xBF",
		},
		"0xCE": {
			ID:          "0xCE",
		},
		"0xD7": {
			ID:          "0xD7",
		},
		"0xEB": {
			ID:          "0xEB",
		},
		"0xF5": {
			ID:          "0xF5",
		},
		"0xFF": {
			ID:          "0xFF",
		},
		"0xAF": {
			ID:          "0xAF",
		},
		"0xDC": {
			ID:          "0xDC",
		},
		"0xFA": {
			ID:          "0xFA",
		},
		"0x8A": {
			ID:          "0x8A",
		},
		"0x8F": {
			ID:          "0x8F",
		},
		"0x9E": {
			ID:          "0x9E",
		},
		"0xC4": {
			ID:          "0xC4",
		},
		"0xC9": {
			ID:          "0xC9",
		},
		"0xE6": {
			ID:          "0xE6",
		},
		"0xF0": {
			ID:          "0xF0",
		},
		"0x85": {
			ID:          "0x85",
		},
		"0x94": {
			ID:          "0x94",
		},
		"0x99": {
			ID:          "0x99",
		},
		"0xA5": {
			ID:          "0xA5",
		},
		"0xB6": {
			ID:          "0xB6",
		},
		"0xBA": {
			ID:          "0xBA",
		},
		"0xD2": {
			ID:          "0xD2",
		},
		"0xE1": {
			ID:          "0xE1",
		},
	},
}
