// Code generated by gen-tags. DO NOT EDIT.

package tags

// MacGreekMacGreekTags contains tag definitions from 
var MacGreekMacGreekTags = TagTable{
	ModuleName: "MacGreek",
	Tags: map[string]TagDef{
		"0x99": {
			ID:          "0x99",
		},
		"0xA8": {
			ID:          "0xA8",
		},
		"0xC1": {
			ID:          "0xC1",
		},
		"0xCB": {
			ID:          "0xCB",
		},
		"0xCF": {
			ID:          "0xCF",
		},
		"0xD3": {
			ID:          "0xD3",
		},
		"0x8A": {
			ID:          "0x8A",
		},
		"0x9E": {
			ID:          "0x9E",
		},
		"0xDC": {
			ID:          "0xDC",
		},
		"0xE0": {
			ID:          "0xE0",
		},
		"0xE4": {
			ID:          "0xE4",
		},
		"0xE8": {
			ID:          "0xE8",
		},
		"0xF0": {
			ID:          "0xF0",
		},
		"0xF8": {
			ID:          "0xF8",
		},
		"0xD8": {
			ID:          "0xD8",
		},
		"0xEC": {
			ID:          "0xEC",
		},
		"0xF4": {
			ID:          "0xF4",
		},
		"0xFC": {
			ID:          "0xFC",
		},
		"0xBD": {
			ID:          "0xBD",
		},
		"0x80": {
			ID:          "0x80",
		},
		"0x94": {
			ID:          "0x94",
		},
		"0xA3": {
			ID:          "0xA3",
		},
		"0xAE": {
			ID:          "0xAE",
		},
		"0xB4": {
			ID:          "0xB4",
		},
		"0xB9": {
			ID:          "0xB9",
		},
		"0xC6": {
			ID:          "0xC6",
		},
		"0x85": {
			ID:          "0x85",
		},
		"0x8F": {
			ID:          "0x8F",
		},
	},
}
