// Code generated by gen-tags. DO NOT EDIT.

package tags

// MacJapaneseMacJapaneseTags contains tag definitions from 
var MacJapaneseMacJapaneseTags = TagTable{
	ModuleName: "MacJapanese",
	Tags: map[string]TagDef{
		"0xA4": {
			ID:          "0xA4",
		},
		"0xAC": {
			ID:          "0xAC",
		},
		"0xB0": {
			ID:          "0xB0",
		},
		"0xBC": {
			ID:          "0xBC",
		},
		"0xCC": {
			ID:          "0xCC",
		},
		"0xDC": {
			ID:          "0xDC",
		},
		"0xFE": {
			ID:          "0xFE",
		},
		"0xC8": {
			ID:          "0xC8",
		},
		"0xD0": {
			ID:          "0xD0",
		},
		"0x5C": {
			ID:          "0x5C",
		},
		"0xA8": {
			ID:          "0xA8",
		},
		"0xB8": {
			ID:          "0xB8",
		},
		"0xC0": {
			ID:          "0xC0",
		},
		"0xB4": {
			ID:          "0xB4",
		},
		"0xC4": {
			ID:          "0xC4",
		},
		"0xD4": {
			ID:          "0xD4",
		},
		"0xD8": {
			ID:          "0xD8",
		},
	},
}
