// Code generated by gen-tags. DO NOT EDIT.

package tags

// MacKoreanMacKoreanTags contains tag definitions from 
var MacKoreanMacKoreanTags = TagTable{
	ModuleName: "MacKorean",
	Tags: map[string]TagDef{
		"0x80": {
			ID:          "0x80",
		},
		"0x84": {
			ID:          "0x84",
		},
	},
}
