// Code generated by gen-tags. DO NOT EDIT.

package tags

// MacRomanMacRomanTags contains tag definitions from 
var MacRomanMacRomanTags = TagTable{
	ModuleName: "MacRoman",
	Tags: map[string]TagDef{
		"0x80": {
			ID:          "0x80",
		},
		"0x94": {
			ID:          "0x94",
		},
		"0xA5": {
			ID:          "0xA5",
		},
		"0xAB": {
			ID:          "0xAB",
		},
		"0xEC": {
			ID:          "0xEC",
		},
		"0xFB": {
			ID:          "0xFB",
		},
		"0xB7": {
			ID:          "0xB7",
		},
		"0xC6": {
			ID:          "0xC6",
		},
		"0xD4": {
			ID:          "0xD4",
		},
		"0x85": {
			ID:          "0x85",
		},
		"0x8F": {
			ID:          "0x8F",
		},
		"0xBC": {
			ID:          "0xBC",
		},
		"0xC1": {
			ID:          "0xC1",
		},
		"0xCB": {
			ID:          "0xCB",
		},
		"0xD0": {
			ID:          "0xD0",
		},
		"0xE7": {
			ID:          "0xE7",
		},
		"0xF1": {
			ID:          "0xF1",
		},
		"0x8A": {
			ID:          "0x8A",
		},
		"0x99": {
			ID:          "0x99",
		},
		"0x9E": {
			ID:          "0x9E",
		},
		"0xB0": {
			ID:          "0xB0",
		},
		"0xD9": {
			ID:          "0xD9",
		},
		"0xDD": {
			ID:          "0xDD",
		},
		"0xE2": {
			ID:          "0xE2",
		},
		"0xF6": {
			ID:          "0xF6",
		},
	},
}
