// Code generated by gen-tags. DO NOT EDIT.

package tags

// MatroskaMainTags contains tag definitions from Image::ExifTool::Matroska
var MatroskaMainTags = TagTable{
	ModuleName: "Matroska",
	Tags: map[string]TagDef{
		"0x1EB923": {
			ID:          "0x1EB923",
		},
		"0xD80": {
			ID:          "0xD80",
		},
		"0x1F": {
			ID:          "0x1F",
		},
		"0x1378": {
			ID:          "0x1378",
		},
		"0x598": {
			ID:          "0x598",
		},
		"0x05": {
			ID:          "0x05",
		},
		"0x2B": {
			ID:          "0x2B",
		},
		"0x3446": {
			ID:          "0x3446",
		},
		"0x26FC": {
			ID:          "0x26FC",
		},
		"0x23C5": {
			ID:          "0x23C5",
		},
		"0x4F": {
			ID:          "0x4F",
		},
		"0x08": {
			ID:          "0x08",
		},
		"0x2DF8": {
			ID:          "0x2DF8",
		},
		"0x23CA": {
			ID:          "0x23CA",
		},
		"0x39": {
			ID:          "0x39",
		},
		"0x17": {
			ID:          "0x17",
		},
		"0x135F": {
			ID:          "0x135F",
		},
		"0x5A3": {
			ID:          "0x5A3",
		},
		"0x3BA9": {
			ID:          "0x3BA9",
		},
		"0x21": {
			ID:          "0x21",
		},
		"0x7A": {
			ID:          "0x7A",
		},
		"0x2264": {
			ID:          "0x2264",
		},
		"0x3E8A": {
			ID:          "0x3E8A",
		},
		"0x5BC": {
			ID:          "0x5BC",
		},
		"0x136E": {
			ID:          "0x136E",
		},
		"0x23C9": {
			ID:          "0x23C9",
		},
		"0x286": {
			ID:          "0x286",
		},
		"0x3EA5": {
			ID:          "0x3EA5",
		},
		"0x15AA": {
			ID:          "0x15AA",
		},
		"0x14BA": {
			ID:          "0x14BA",
		},
		"0xEB524": {
			ID:          "0xEB524",
		},
		"0x7E2": {
			ID:          "0x7E2",
		},
		"0x485": {
			ID:          "0x485",
		},
		"0x23A2": {
			ID:          "0x23A2",
		},
		"0x1B4040": {
			ID:          "0x1B4040",
		},
		"0x14AA": {
			ID:          "0x14AA",
		},
		"0x6A": {
			ID:          "0x6A",
		},
		"0x484": {
			ID:          "0x484",
		},
		"0x1E83BB": {
			ID:          "0x1E83BB",
		},
		"0x2F": {
			ID:          "0x2F",
		},
		"0x14BB": {
			ID:          "0x14BB",
		},
		"0x7E3": {
			ID:          "0x7E3",
		},
		"0x5DD": {
			ID:          "0x5DD",
		},
		"0x1C83AB": {
			ID:          "0x1C83AB",
		},
		"0x29FC": {
			ID:          "0x29FC",
		},
		"0x23": {
			ID:          "0x23",
		},
		"0x4C": {
			ID:          "0x4C",
		},
		"0x2FAB": {
			ID:          "0x2FAB",
		},
		"0x67E": {
			ID:          "0x67E",
		},
		"0x287": {
			ID:          "0x287",
		},
		"0x3384": {
			ID:          "0x3384",
		},
		"0x33C4": {
			ID:          "0x33C4",
		},
		"0x28CA": {
			ID:          "0x28CA",
		},
		"0x14CC": {
			ID:          "0x14CC",
		},
		"0x14DD": {
			ID:          "0x14DD",
		},
		"0x65C": {
			ID:          "0x65C",
		},
		"0x09": {
			ID:          "0x09",
		},
		"0x71": {
			ID:          "0x71",
		},
		"0x4E": {
			ID:          "0x4E",
		},
		"0x2DE7": {
			ID:          "0x2DE7",
		},
		"0x2A": {
			ID:          "0x2A",
		},
		"0x5BD": {
			ID:          "0x5BD",
		},
		"0x22": {
			ID:          "0x22",
		},
		"0x33C5": {
			ID:          "0x33C5",
		},
		"0x1A9697": {
			ID:          "0x1A9697",
		},
		"0x2EBC": {
			ID:          "0x2EBC",
		},
		"0x37C": {
			ID:          "0x37C",
		},
		"0x33A4": {
			ID:          "0x33A4",
		},
		"0x1741": {
			ID:          "0x1741",
		},
		"0x6E": {
			ID:          "0x6E",
		},
		"0x57": {
			ID:          "0x57",
		},
		"0x3314F": {
			ID:          "0x3314F",
		},
		"0x14B0": {
			ID:          "0x14B0",
		},
		"0x6B": {
			ID:          "0x6B",
		},
		"0x660": {
			ID:          "0x660",
		},
		"0x29A5": {
			ID:          "0x29A5",
		},
		"0x30": {
			ID:          "0x30",
		},
		"0x77": {
			ID:          "0x77",
		},
		"0x18": {
			ID:          "0x18",
		},
		"0x37E": {
			ID:          "0x37E",
		},
		"0x2532": {
			ID:          "0x2532",
		},
		"0x27": {
			ID:          "0x27",
		},
		"0x7D": {
			ID:          "0x7D",
		},
		"0x1031": {
			ID:          "0x1031",
		},
		"0x5DB": {
			ID:          "0x5DB",
		},
		"0x2933": {
			ID:          "0x2933",
		},
		"0x24": {
			ID:          "0x24",
		},
		"0x4B": {
			ID:          "0x4B",
		},
		"0x26A5": {
			ID:          "0x26A5",
		},
		"0x3A": {
			ID:          "0x3A",
		},
		"0x2F3": {
			ID:          "0x2F3",
		},
		"0x25": {
			ID:          "0x25",
		},
		"0xFB523": {
			ID:          "0xFB523",
		},
		"0x383E3": {
			ID:          "0x383E3",
		},
		"0x255": {
			ID:          "0x255",
		},
		"0x6AE": {
			ID:          "0x6AE",
		},
		"0x2E67": {
			ID:          "0x2E67",
		},
		"0x23C6": {
			ID:          "0x23C6",
		},
		"0x1CB923": {
			ID:          "0x1CB923",
		},
		"0x137F": {
			ID:          "0x137F",
		},
		"0x2B59C": {
			ID:          "0x2B59C",
		},
		"0x487": {
			ID:          "0x487",
		},
		"0x3EB5": {
			ID:          "0x3EB5",
		},
		"0x18D7": {
			ID:          "0x18D7",
		},
		"0x2F2": {
			ID:          "0x2F2",
		},
		"0x15EE": {
			ID:          "0x15EE",
		},
		"0x6B240": {
			ID:          "0x6B240",
		},
		"0x1032": {
			ID:          "0x1032",
		},
		"0x7E4": {
			ID:          "0x7E4",
		},
		"0x66E": {
			ID:          "0x66E",
		},
		"0x675": {
			ID:          "0x675",
		},
		"0x35": {
			ID:          "0x35",
		},
		"0x50D": {
			ID:          "0x50D",
		},
		"0x3F": {
			ID:          "0x3F",
		},
		"0x6C": {
			ID:          "0x6C",
		},
		"0x0444": {
			ID:          "0x0444",
		},
		"0x47A": {
			ID:          "0x47A",
		},
		"0x2F7": {
			ID:          "0x2F7",
		},
		"0x285": {
			ID:          "0x285",
		},
		"0x4D": {
			ID:          "0x4D",
		},
		"0x2B59D": {
			ID:          "0x2B59D",
		},
		"0x38B5": {
			ID:          "0x38B5",
		},
		"0x23C4": {
			ID:          "0x23C4",
		},
		"0x3E9A": {
			ID:          "0x3E9A",
		},
	},
}
