// Code generated by gen-tags. DO NOT EDIT.

package tags

// MatroskaStdTagTags contains tag definitions from Image::ExifTool::Matroska
var MatroskaStdTagTags = TagTable{
	ModuleName: "Matroska",
	Tags: map[string]TagDef{
		"BPM": {
			ID:          "BPM",
			Name:        "BPM",
		},
		"CATALOG_NUMBER": {
			ID:          "CATALOG_NUMBER",
			Name:        "CatalogNumber",
		},
		"SUBTITLE": {
			ID:          "SUBTITLE",
			Name:        "Subtitle",
		},
		"CONTENT_TYPE": {
			ID:          "CONTENT_TYPE",
			Name:        "ContentType",
		},
		"COMPOSER_NATIONALITY": {
			ID:          "COMPOSER_NATIONALITY",
			Name:        "ComposerNationality",
		},
		"LABEL_CODE": {
			ID:          "LABEL_CODE",
			Name:        "LabelCode",
		},
		"PART_NUMBER": {
			ID:          "PART_NUMBER",
			Name:        "PartNumber",
		},
		"EXECUTIVE_PRODUCER": {
			ID:          "EXECUTIVE_PRODUCER",
			Name:        "ExecutiveProducer",
		},
		"PUBLISHER": {
			ID:          "PUBLISHER",
			Name:        "Publisher",
		},
		"REPLAYGAIN_PEAK": {
			ID:          "REPLAYGAIN_PEAK",
			Name:        "ReplaygainPeak",
		},
		"MCDI": {
			ID:          "MCDI",
			Name:        "MCDI",
		},
		"PURCHASE_INFO": {
			ID:          "PURCHASE_INFO",
			Name:        "PurchaseInfo",
		},
		"PURCHASE_OWNER": {
			ID:          "PURCHASE_OWNER",
			Name:        "PurchaseOwner",
		},
		"ORIGINAL": {
			ID:          "ORIGINAL",
		},
		"TITLE": {
			ID:          "TITLE",
			Name:        "Title",
		},
		"LYRICIST": {
			ID:          "LYRICIST",
			Name:        "Lyricist",
		},
		"PRODUCTION_DESIGNER": {
			ID:          "PRODUCTION_DESIGNER",
			Name:        "ProductionDesigner",
		},
		"MASTERED_BY": {
			ID:          "MASTERED_BY",
			Name:        "MasteredBy",
		},
		"BPS": {
			ID:          "BPS",
			Name:        "BPS",
		},
		"COUNTRY": {
			ID:          "COUNTRY",
		},
		"EMAIL": {
			ID:          "EMAIL",
		},
		"SOUND_ENGINEER": {
			ID:          "SOUND_ENGINEER",
			Name:        "SoundEngineer",
		},
		"PRODUCER": {
			ID:          "PRODUCER",
			Name:        "Producer",
		},
		"DISTRIBUTED_BY": {
			ID:          "DISTRIBUTED_BY",
			Name:        "DistributedBy",
		},
		"REMIXED_BY": {
			ID:          "REMIXED_BY",
			Name:        "RemixedBy",
		},
		"ENCODER_SETTINGS": {
			ID:          "ENCODER_SETTINGS",
			Name:        "EncoderSettings",
		},
		"IMDB": {
			ID:          "IMDB",
			Name:        "IMDB",
		},
		"ADDRESS": {
			ID:          "ADDRESS",
		},
		"COSTUME_DESIGNER": {
			ID:          "COSTUME_DESIGNER",
			Name:        "CostumeDesigner",
		},
		"CHARACTER": {
			ID:          "CHARACTER",
			Name:        "Character",
		},
		"ENCODED_BY": {
			ID:          "ENCODED_BY",
			Name:        "EncodedBy",
		},
		"MEASURE": {
			ID:          "MEASURE",
			Name:        "Measure",
		},
		"REPLAYGAIN_GAIN": {
			ID:          "REPLAYGAIN_GAIN",
			Name:        "ReplaygainGain",
		},
		"TOTAL_PARTS": {
			ID:          "TOTAL_PARTS",
			Name:        "TotalParts",
		},
		"ARTIST": {
			ID:          "ARTIST",
			Name:        "Artist",
		},
		"ARRANGER": {
			ID:          "ARRANGER",
			Name:        "Arranger",
		},
		"SCREENPLAY_BY": {
			ID:          "SCREENPLAY_BY",
			Name:        "ScreenplayBy",
		},
		"PRODUCTION_STUDIO": {
			ID:          "PRODUCTION_STUDIO",
			Name:        "ProductionStudio",
		},
		"DATE_RECORDED": {
			ID:          "DATE_RECORDED",
		},
		"TUNING": {
			ID:          "TUNING",
			Name:        "Tuning",
		},
		"PURCHASE_PRICE": {
			ID:          "PURCHASE_PRICE",
			Name:        "PurchasePrice",
		},
		"PHONE": {
			ID:          "PHONE",
		},
		"LEAD_PERFORMER": {
			ID:          "LEAD_PERFORMER",
			Name:        "LeadPerformer",
		},
		"MOOD": {
			ID:          "MOOD",
			Name:        "Mood",
		},
		"INITIAL_KEY": {
			ID:          "INITIAL_KEY",
			Name:        "InitialKey",
		},
		"COPYRIGHT": {
			ID:          "COPYRIGHT",
			Name:        "Copyright",
		},
		"TERMS_OF_USE": {
			ID:          "TERMS_OF_USE",
			Name:        "TermsOfUse",
		},
		"COMPOSER": {
			ID:          "COMPOSER",
			Name:        "Composer",
		},
		"MIXED_BY": {
			ID:          "MIXED_BY",
			Name:        "MixedBy",
		},
		"LABEL": {
			ID:          "LABEL",
			Name:        "Label",
		},
		"SUMMARY": {
			ID:          "SUMMARY",
			Name:        "Summary",
		},
		"SYNOPSIS": {
			ID:          "SYNOPSIS",
			Name:        "Synopsis",
		},
		"ASSISTANT_DIRECTOR": {
			ID:          "ASSISTANT_DIRECTOR",
			Name:        "AssistantDirector",
		},
		"COPRODUCER": {
			ID:          "COPRODUCER",
			Name:        "Coproducer",
		},
		"SUBJECT": {
			ID:          "SUBJECT",
			Name:        "Subject",
		},
		"TMDB": {
			ID:          "TMDB",
			Name:        "TMDB",
		},
		"TVDB": {
			ID:          "TVDB",
			Name:        "TVDB",
		},
		"FAX": {
			ID:          "FAX",
		},
		"DIRECTOR_OF_PHOTOGRAPHY": {
			ID:          "DIRECTOR_OF_PHOTOGRAPHY",
			Name:        "DirectorOfPhotography",
		},
		"WRITTEN_BY": {
			ID:          "WRITTEN_BY",
			Name:        "WrittenBy",
		},
		"COMPOSITION_LOCATION": {
			ID:          "COMPOSITION_LOCATION",
			Name:        "CompositionLocation",
		},
		"COMMENT": {
			ID:          "COMMENT",
			Name:        "Comment",
		},
		"RATING": {
			ID:          "RATING",
			Name:        "Rating",
		},
		"PART_OFFSET": {
			ID:          "PART_OFFSET",
			Name:        "PartOffset",
		},
		"LAW_RATING": {
			ID:          "LAW_RATING",
			Name:        "LawRating",
		},
		"FPS": {
			ID:          "FPS",
			Name:        "FPS",
		},
		"EDITED_BY": {
			ID:          "EDITED_BY",
			Name:        "EditedBy",
		},
		"DATE_DIGITIZED": {
			ID:          "DATE_DIGITIZED",
		},
		"PLAY_COUNTER": {
			ID:          "PLAY_COUNTER",
			Name:        "PlayCounter",
		},
		"BARCODE": {
			ID:          "BARCODE",
			Name:        "Barcode",
		},
		"PURCHASE_CURRENCY": {
			ID:          "PURCHASE_CURRENCY",
			Name:        "PurchaseCurrency",
		},
		"PRODUCTION_COPYRIGHT": {
			ID:          "PRODUCTION_COPYRIGHT",
			Name:        "ProductionCopyright",
		},
		"SAMPLE": {
			ID:          "SAMPLE",
		},
		"DIRECTOR": {
			ID:          "DIRECTOR",
			Name:        "Director",
		},
		"ORIGINAL_MEDIA_TYPE": {
			ID:          "ORIGINAL_MEDIA_TYPE",
			Name:        "OriginalMediaType",
		},
		"PERIOD": {
			ID:          "PERIOD",
			Name:        "Period",
		},
		"DATE_ENCODED": {
			ID:          "DATE_ENCODED",
		},
		"ENCODER": {
			ID:          "ENCODER",
			Name:        "Encoder",
		},
		"LCCN": {
			ID:          "LCCN",
			Name:        "Lccn",
		},
		"LICENSE": {
			ID:          "LICENSE",
			Name:        "License",
		},
		"URL": {
			ID:          "URL",
		},
		"ACCOMPANIMENT": {
			ID:          "ACCOMPANIMENT",
			Name:        "Accompaniment",
		},
		"ART_DIRECTOR": {
			ID:          "ART_DIRECTOR",
			Name:        "ArtDirector",
		},
		"THANKS_TO": {
			ID:          "THANKS_TO",
			Name:        "ThanksTo",
		},
		"DESCRIPTION": {
			ID:          "DESCRIPTION",
			Name:        "Description",
		},
		"PURCHASE_ITEM": {
			ID:          "PURCHASE_ITEM",
			Name:        "PurchaseItem",
		},
		"CHOREGRAPHER": {
			ID:          "CHOREGRAPHER",
			Name:        "Choregrapher",
		},
		"GENRE": {
			ID:          "GENRE",
			Name:        "Genre",
		},
		"DATE_RELEASED": {
			ID:          "DATE_RELEASED",
		},
		"DATE_TAGGED": {
			ID:          "DATE_TAGGED",
		},
		"RECORDING_LOCATION": {
			ID:          "RECORDING_LOCATION",
			Name:        "RecordingLocation",
		},
		"ISRC": {
			ID:          "ISRC",
			Name:        "ISRC",
		},
		"ISBN": {
			ID:          "ISBN",
			Name:        "ISBN",
		},
		"SORT_WITH": {
			ID:          "SORT_WITH",
		},
		"LYRICS": {
			ID:          "LYRICS",
			Name:        "Lyrics",
		},
		"CONDUCTOR": {
			ID:          "CONDUCTOR",
			Name:        "Conductor",
		},
		"ACTOR": {
			ID:          "ACTOR",
			Name:        "Actor",
		},
		"DATE_WRITTEN": {
			ID:          "DATE_WRITTEN",
		},
		"DATE_PURCHASED": {
			ID:          "DATE_PURCHASED",
		},
	},
}
