// Code generated by gen-tags. DO NOT EDIT.

package tags

// MatroskaProjectionTags contains tag definitions from Image::ExifTool::Matroska
var MatroskaProjectionTags = TagTable{
	ModuleName: "Matroska",
	Tags: map[string]TagDef{
		"0x7673": {
			ID:          "0x7673",
		},
		"0x7674": {
			ID:          "0x7674",
		},
		"0x7675": {
			ID:          "0x7675",
		},
	},
}
