// Code generated by gen-tags. DO NOT EDIT.

package tags

// MicrosoftXtraTags contains tag definitions from Image::ExifTool::Microsoft
var MicrosoftXtraTags = TagTable{
	ModuleName: "Microsoft",
	Tags: map[string]TagDef{
		"WM/OriginalArtist": {
			ID:          "WM/OriginalArtist",
		},
		"{64440490-4C8B-11D1-8B70-080036B11A03} 6": {
			ID:          "{64440490-4C8B-11D1-8B70-080036B11A03} 6",
			Name:        "AudioSampleSize",
		},
		"{28636AA6-953D-11D2-B5D6-00C04FD918D0} 11": {
			ID:          "{28636AA6-953D-11D2-B5D6-00C04FD918D0} 11",
			Name:        "Type",
		},
		"ModifiedBy": {
			ID:          "ModifiedBy",
		},
		"PlaylistIndex": {
			ID:          "PlaylistIndex",
		},
		"RecordingTimeYearMonthDay": {
			ID:          "RecordingTimeYearMonthDay",
		},
		"UserPlayCount": {
			ID:          "UserPlayCount",
		},
		"{63C25B20-96BE-488F-8788-C09C407AD812} 100": {
			ID:          "{63C25B20-96BE-488F-8788-C09C407AD812} 100",
			Name:        "Street",
		},
		"AlbumTitleSortOrder": {
			ID:          "AlbumTitleSortOrder",
		},
		"{09429607-582D-437F-84C3-DE93A2B24C3C} 100": {
			ID:          "{09429607-582D-437F-84C3-DE93A2B24C3C} 100",
			Name:        "OptionalAttendees",
		},
		"{6A15E5A0-0A1E-4CD7-BB8C-D2F1B0C929BC} 100": {
			ID:          "{6A15E5A0-0A1E-4CD7-BB8C-D2F1B0C929BC} 100",
			Name:        "BusinessPhone",
		},
		"{E3E0584C-B788-4A5A-BB20-7F5A44C9ACDD} 16": {
			ID:          "{E3E0584C-B788-4A5A-BB20-7F5A44C9ACDD} 16",
			Name:        "ToAddresses",
		},
		"{6D748DE2-8D38-4CC3-AC60-F009B057C557} 13": {
			ID:          "{6D748DE2-8D38-4CC3-AC60-F009B057C557} 13",
			Name:        "Rerun",
		},
		"{F8D3F6AC-4874-42CB-BE59-AB454B30716A} 100": {
			ID:          "{F8D3F6AC-4874-42CB-BE59-AB454B30716A} 100",
			Name:        "Sensitivity",
		},
		"{08C7CC5F-60F2-4494-AD75-55E3E0B5ADD0} 100": {
			ID:          "{08C7CC5F-60F2-4494-AD75-55E3E0B5ADD0} 100",
			Name:        "TaskOwner",
		},
		"{28636AA6-953D-11D2-B5D6-00C04FD918D0} 14": {
			ID:          "{28636AA6-953D-11D2-B5D6-00C04FD918D0} 14",
			Name:        "TotalFileSize",
		},
		"AcquisitionTime": {
			ID:          "AcquisitionTime",
		},
		"WM/VideoWidth": {
			ID:          "WM/VideoWidth",
			Name:        "VideoWidth",
		},
		"{C89A23D0-7D6D-4EB8-87D4-776A82D493E5} 100": {
			ID:          "{C89A23D0-7D6D-4EB8-87D4-776A82D493E5} 100",
			Name:        "HomeStateOrProvince",
		},
		"{C8EA94F0-A9E3-4969-A94B-9C62A95324E0} 100": {
			ID:          "{C8EA94F0-A9E3-4969-A94B-9C62A95324E0} 100",
			Name:        "City",
		},
		"{41CF5AE0-F75A-4806-BD87-59C7D9248EB9} 100": {
			ID:          "{41CF5AE0-F75A-4806-BD87-59C7D9248EB9} 100",
			Name:        "WindowsFileName",
		},
		"{9B174B35-40FF-11D2-A27E-00C04FC30871} 5": {
			ID:          "{9B174B35-40FF-11D2-A27E-00C04FC30871} 5",
			Name:        "SpaceUsed",
		},
		"{14B81DA1-0135-4D31-96D9-6CBFC9671A99} 37383": {
			ID:          "{14B81DA1-0135-4D31-96D9-6CBFC9671A99} 37383",
			Name:        "MeteringMode",
		},
		"Sync11": {
			ID:          "Sync11",
		},
		"VideoFormat": {
			ID:          "VideoFormat",
		},
		"{6444048F-4C8B-11D1-8B70-080036B11A03} 13": {
			ID:          "{6444048F-4C8B-11D1-8B70-080036B11A03} 13",
			Name:        "Dimensions",
		},
		"{64440492-4C8B-11D1-8B70-080036B11A03} 9": {
			ID:          "{64440492-4C8B-11D1-8B70-080036B11A03} 9",
			Name:        "Rating",
		},
		"{0BA7D6C3-568D-4159-AB91-781A91FB71E5} 100": {
			ID:          "{0BA7D6C3-568D-4159-AB91-781A91FB71E5} 100",
			Name:        "RequiredAttendeeAddresses",
		},
		"{F1A24AA7-9CA7-40F6-89EC-97DEF9FFE8DB} 100": {
			ID:          "{F1A24AA7-9CA7-40F6-89EC-97DEF9FFE8DB} 100",
			Name:        "FileAs",
		},
		"{9B174B35-40FF-11D2-A27E-00C04FC30871} 2": {
			ID:          "{9B174B35-40FF-11D2-A27E-00C04FC30871} 2",
			Name:        "SpaceFree",
		},
		"{64440492-4C8B-11D1-8B70-080036B11A03} 22": {
			ID:          "{64440492-4C8B-11D1-8B70-080036B11A03} 22",
			Name:        "Producers",
		},
		"ContentDistributorDuration": {
			ID:          "ContentDistributorDuration",
		},
		"UserLastPlayedTime": {
			ID:          "UserLastPlayedTime",
		},
		"UserPlaycountNight": {
			ID:          "UserPlaycountNight",
		},
		"WM/MediaOriginalChannel": {
			ID:          "WM/MediaOriginalChannel",
			Name:        "MediaOriginalChannel",
		},
		"WM/WMShadowFileSourceDRMType": {
			ID:          "WM/WMShadowFileSourceDRMType",
			Name:        "WMShadowFileSourceDRMType",
		},
		"{F29F85E0-4FF9-1068-AB91-08002B27B3D9} 5": {
			ID:          "{F29F85E0-4FF9-1068-AB91-08002B27B3D9} 5",
			Name:        "Keywords",
		},
		"{64440491-4C8B-11D1-8B70-080036B11A03} 3": {
			ID:          "{64440491-4C8B-11D1-8B70-080036B11A03} 3",
			Name:        "FrameWidth",
		},
		"Sync02": {
			ID:          "Sync02",
		},
		"Sync05": {
			ID:          "Sync05",
		},
		"UserEffectiveRating": {
			ID:          "UserEffectiveRating",
		},
		"UserPlaycountWeekend": {
			ID:          "UserPlaycountWeekend",
		},
		"{28636AA6-953D-11D2-B5D6-00C04FD918D0} 5": {
			ID:          "{28636AA6-953D-11D2-B5D6-00C04FD918D0} 5",
			Name:        "Computer",
		},
		"{6D748DE2-8D38-4CC3-AC60-F009B057C557} 14": {
			ID:          "{6D748DE2-8D38-4CC3-AC60-F009B057C557} 14",
			Name:        "SAP",
		},
		"PeakValue": {
			ID:          "PeakValue",
		},
		"Sync06": {
			ID:          "Sync06",
		},
		"{BFEE9149-E3E2-49A7-A862-C05988145CEC} 100": {
			ID:          "{BFEE9149-E3E2-49A7-A862-C05988145CEC} 100",
			Name:        "IsOnline",
		},
		"{3F8472B5-E0AF-4DB2-8071-C53FE76AE7CE} 100": {
			ID:          "{3F8472B5-E0AF-4DB2-8071-C53FE76AE7CE} 100",
			Name:        "DueDate",
		},
		"{635E9051-50A5-4BA2-B9DB-4ED056C77296} 100": {
			ID:          "{635E9051-50A5-4BA2-B9DB-4ED056C77296} 100",
			Name:        "FullName",
		},
		"{64440492-4C8B-11D1-8B70-080036B11A03} 23": {
			ID:          "{64440492-4C8B-11D1-8B70-080036B11A03} 23",
			Name:        "Writers",
		},
		"{E3E0584C-B788-4A5A-BB20-7F5A44C9ACDD} 21": {
			ID:          "{E3E0584C-B788-4A5A-BB20-7F5A44C9ACDD} 21",
			Name:        "Attachments",
		},
		"{9C1FCF74-2D97-41BA-B4AE-CB2E3661A6E4} 8": {
			ID:          "{9C1FCF74-2D97-41BA-B4AE-CB2E3661A6E4} 8",
			Name:        "HasAttachments",
		},
		"{56A3372E-CE9C-11D2-9F0E-006097C686F6} 37": {
			ID:          "{56A3372E-CE9C-11D2-9F0E-006097C686F6} 37",
			Name:        "PartOfSet",
		},
		"{084D8A0A-E6D5-40DE-BF1F-C8820E7C877C} 100": {
			ID:          "{084D8A0A-E6D5-40DE-BF1F-C8820E7C877C} 100",
			Name:        "Complete",
		},
		"CDTrackEnabled": {
			ID:          "CDTrackEnabled",
		},
		"{56A3372E-CE9C-11D2-9F0E-006097C686F6} 36": {
			ID:          "{56A3372E-CE9C-11D2-9F0E-006097C686F6} 36",
			Name:        "Conductors",
		},
		"{14B81DA1-0135-4D31-96D9-6CBFC9671A99} 271": {
			ID:          "{14B81DA1-0135-4D31-96D9-6CBFC9671A99} 271",
			Name:        "CameraMaker",
		},
		"{276D7BB0-5B34-4FB0-AA4B-158ED12A1809} 100": {
			ID:          "{276D7BB0-5B34-4FB0-AA4B-158ED12A1809} 100",
			Name:        "ClientID",
		},
		"{5DA84765-E3FF-4278-86B0-A27967FBDD03} 100": {
			ID:          "{5DA84765-E3FF-4278-86B0-A27967FBDD03} 100",
			Name:        "HasFlag",
		},
		"FileType": {
			ID:          "FileType",
		},
		"WM/Language": {
			ID:          "WM/Language",
			Name:        "Language",
		},
		"{402B5934-EC5A-48C3-93E6-85E86A2D934E} 100": {
			ID:          "{402B5934-EC5A-48C3-93E6-85E86A2D934E} 100",
			Name:        "BusinessCity",
		},
		"{346C8BD1-2E6A-4C45-89A4-61B78E8E700F} 100": {
			ID:          "{346C8BD1-2E6A-4C45-89A4-61B78E8E700F} 100",
			Name:        "Incomplete",
		},
		"{10984E0A-F9F2-4321-B7EF-BAF195AF4319} 100": {
			ID:          "{10984E0A-F9F2-4321-B7EF-BAF195AF4319} 100",
			Name:        "ParentalRatingReason",
		},
		"PixelAspectRatioY": {
			ID:          "PixelAspectRatioY",
		},
		"RecordingTime": {
			ID:          "RecordingTime",
		},
		"Subject": {
			ID:          "Subject",
		},
		"WM/Composer": {
			ID:          "WM/Composer",
		},
		"{176DC63C-2688-4E89-8143-A347800F25E9} 47": {
			ID:          "{176DC63C-2688-4E89-8143-A347800F25E9} 47",
			Name:        "Birthday",
		},
		"{8AFCC170-8A46-4B53-9EEE-90BAE7151E62} 100": {
			ID:          "{8AFCC170-8A46-4B53-9EEE-90BAE7151E62} 100",
			Name:        "HomePostalCode",
		},
		"{FF962609-B7D6-4999-862D-95180D529AEA} 100": {
			ID:          "{FF962609-B7D6-4999-862D-95180D529AEA} 100",
			Name:        "OtherStreet",
		},
		"{B725F130-47EF-101A-A5F1-02608C9EEBAC} 2": {
			ID:          "{B725F130-47EF-101A-A5F1-02608C9EEBAC} 2",
			Name:        "FolderName",
		},
		"DVDID": {
			ID:          "DVDID",
		},
		"Location": {
			ID:          "Location",
		},
		"Sync09": {
			ID:          "Sync09",
		},
		"{E3E0584C-B788-4A5A-BB20-7F5A44C9ACDD} 10": {
			ID:          "{E3E0584C-B788-4A5A-BB20-7F5A44C9ACDD} 10",
			Name:        "ReadStatus",
		},
		"{DABD30ED-0043-4789-A7F8-D013A4736622} 100": {
			ID:          "{DABD30ED-0043-4789-A7F8-D013A4736622} 100",
			Name:        "Folder",
		},
		"{D4D0AA16-9948-41A4-AA85-D97FF9646993} 100": {
			ID:          "{D4D0AA16-9948-41A4-AA85-D97FF9646993} 100",
			Name:        "Participants",
		},
		"{2E4B640D-5019-46D8-8881-55414CC5CAA0} 100": {
			ID:          "{2E4B640D-5019-46D8-8881-55414CC5CAA0} 100",
			Name:        "MediaCreated",
		},
		"{E3E0584C-B788-4A5A-BB20-7F5A44C9ACDD} 17": {
			ID:          "{E3E0584C-B788-4A5A-BB20-7F5A44C9ACDD} 17",
			Name:        "ToNames",
		},
		"Comment": {
			ID:          "Comment",
		},
		"RadioBand": {
			ID:          "RadioBand",
		},
		"ReleaseDateYearMonthDay": {
			ID:          "ReleaseDateYearMonthDay",
		},
		"TrackingID": {
			ID:          "TrackingID",
		},
		"WM/Mood": {
			ID:          "WM/Mood",
		},
		"{B725F130-47EF-101A-A5F1-02608C9EEBAC} 4": {
			ID:          "{B725F130-47EF-101A-A5F1-02608C9EEBAC} 4",
			Name:        "Type",
		},
		"{7B9F6399-0A3F-4B12-89BD-4ADC51C918AF} 100": {
			ID:          "{7B9F6399-0A3F-4B12-89BD-4ADC51C918AF} 100",
			Name:        "HomePOBox",
		},
		"{56A3372E-CE9C-11D2-9F0E-006097C686F6} 38": {
			ID:          "{56A3372E-CE9C-11D2-9F0E-006097C686F6} 38",
			Name:        "Subtitle",
		},
		"ShadowFilePath": {
			ID:          "ShadowFilePath",
		},
		"Sync10": {
			ID:          "Sync10",
		},
		"{F29F85E0-4FF9-1068-AB91-08002B27B3D9} 6": {
			ID:          "{F29F85E0-4FF9-1068-AB91-08002B27B3D9} 6",
			Name:        "Comments",
		},
		"{C0AC206A-827E-4650-95AE-77E2BB74FCC9} 100": {
			ID:          "{C0AC206A-827E-4650-95AE-77E2BB74FCC9} 100",
			Name:        "MailingAddress",
		},
		"{FDF84370-031A-4ADD-9E91-0D775F1C6605} 100": {
			ID:          "{FDF84370-031A-4ADD-9E91-0D775F1C6605} 100",
			Name:        "Mileage",
		},
		"{14B81DA1-0135-4D31-96D9-6CBFC9671A99} 34850": {
			ID:          "{14B81DA1-0135-4D31-96D9-6CBFC9671A99} 34850",
			Name:        "ExposureProgram",
		},
		"{0CEF7D53-FA64-11D1-A203-0000F81FEDEE} 9": {
			ID:          "{0CEF7D53-FA64-11D1-A203-0000F81FEDEE} 9",
			Name:        "LegalTrademarks",
		},
		"Provider": {
			ID:          "Provider",
		},
		"ReleaseDateYear": {
			ID:          "ReleaseDateYear",
		},
		"Sync04": {
			ID:          "Sync04",
		},
		"Sync08": {
			ID:          "Sync08",
		},
		"UserPlaycountWeekday": {
			ID:          "UserPlaycountWeekday",
		},
		"WM/Genre": {
			ID:          "WM/Genre",
			Name:        "Genre",
		},
		"WM/PartOfSet": {
			ID:          "WM/PartOfSet",
			Name:        "PartOfSet",
		},
		"{64440491-4C8B-11D1-8B70-080036B11A03} 43": {
			ID:          "{64440491-4C8B-11D1-8B70-080036B11A03} 43",
			Name:        "TotalBitrate",
		},
		"Event": {
			ID:          "Event",
		},
		"Is_Protected": {
			ID:          "Is_Protected",
			Name:        "IsProtected",
		},
		"ReleaseDateMonth": {
			ID:          "ReleaseDateMonth",
		},
		"VideoBitrate": {
			ID:          "VideoBitrate",
		},
		"WM/AlbumCoverURL": {
			ID:          "WM/AlbumCoverURL",
		},
		"WM/Producer": {
			ID:          "WM/Producer",
		},
		"{56A3372E-CE9C-11D2-9F0E-006097C686F6} 4": {
			ID:          "{56A3372E-CE9C-11D2-9F0E-006097C686F6} 4",
			Name:        "AlbumTitle",
		},
		"{D6304E01-F8F5-4F45-8B15-D024A6296789} 100": {
			ID:          "{D6304E01-F8F5-4F45-8B15-D024A6296789} 100",
			Name:        "Pager",
		},
		"CameraModel": {
			ID:          "CameraModel",
		},
		"Copyright": {
			ID:          "Copyright",
		},
		"{D5CDD502-2E9C-101B-9397-08002B2CF9AE} 2": {
			ID:          "{D5CDD502-2E9C-101B-9397-08002B2CF9AE} 2",
			Name:        "Category",
		},
		"{56310920-2491-4919-99CE-EADB06FAFDB2} 100": {
			ID:          "{56310920-2491-4919-99CE-EADB06FAFDB2} 100",
			Name:        "BusinessHomePage",
		},
		"{CC6F4F24-6083-4BD4-8754-674D0DE87AB8} 100": {
			ID:          "{CC6F4F24-6083-4BD4-8754-674D0DE87AB8} 100",
			Name:        "E-mailDisplayName",
		},
		"{6444048F-4C8B-11D1-8B70-080036B11A03} 6": {
			ID:          "{6444048F-4C8B-11D1-8B70-080036B11A03} 6",
			Name:        "VerticalResolution",
		},
		"{F23F425C-71A1-4FA8-922F-678EA4A60408} 100": {
			ID:          "{F23F425C-71A1-4FA8-922F-678EA4A60408} 100",
			Name:        "IsAttachment",
		},
		"{E3E0584C-B788-4A5A-BB20-7F5A44C9ACDD} 14": {
			ID:          "{E3E0584C-B788-4A5A-BB20-7F5A44C9ACDD} 14",
			Name:        "FromNames",
		},
		"DRMKeyID": {
			ID:          "DRMKeyID",
		},
		"Sync01": {
			ID:          "Sync01",
		},
		"WM/Writer": {
			ID:          "WM/Writer",
		},
		"{98F98354-617A-46B8-8560-5B1B64BF1F89} 100": {
			ID:          "{98F98354-617A-46B8-8560-5B1B64BF1F89} 100",
			Name:        "HomeAddress",
		},
		"{14B81DA1-0135-4D31-96D9-6CBFC9671A99} 37385": {
			ID:          "{14B81DA1-0135-4D31-96D9-6CBFC9671A99} 37385",
			Name:        "FlashMode",
		},
		"{E6DDCAF7-29C5-4F0A-9A68-D19412EC7090} 100": {
			ID:          "{E6DDCAF7-29C5-4F0A-9A68-D19412EC7090} 100",
			Name:        "LensMaker",
		},
		"{EE3D3D8A-5381-4CFA-B13B-AAF66B5F4EC9} 100": {
			ID:          "{EE3D3D8A-5381-4CFA-B13B-AAF66B5F4EC9} 100",
			Name:        "WhiteBalance",
		},
		"Sync12": {
			ID:          "Sync12",
		},
		"{446F787F-10C4-41CB-A6C4-4D0343551597} 100": {
			ID:          "{446F787F-10C4-41CB-A6C4-4D0343551597} 100",
			Name:        "BusinessStateOrProvince",
		},
		"{08F6D7C2-E3F2-44FC-AF1E-5AA5C81A2D3E} 100": {
			ID:          "{08F6D7C2-E3F2-44FC-AF1E-5AA5C81A2D3E} 100",
			Name:        "MaxAperture",
		},
		"{6D748DE2-8D38-4CC3-AC60-F009B057C557} 12": {
			ID:          "{6D748DE2-8D38-4CC3-AC60-F009B057C557} 12",
			Name:        "ClosedCaptioning",
		},
		"{48FD6EC8-8A12-4CDF-A03E-4EC5A511EDDE} 100": {
			ID:          "{48FD6EC8-8A12-4CDF-A03E-4EC5A511EDDE} 100",
			Name:        "StartDate",
		},
		"titleNum": {
			ID:          "titleNum",
		},
		"WM/Year": {
			ID:          "WM/Year",
		},
		"{56A3372E-CE9C-11D2-9F0E-006097C686F6} 2": {
			ID:          "{56A3372E-CE9C-11D2-9F0E-006097C686F6} 2",
			Name:        "Artist",
		},
		"{B0B87314-FCF6-4FEB-8DFF-A50DA6AF561C} 100": {
			ID:          "{B0B87314-FCF6-4FEB-8DFF-A50DA6AF561C} 100",
			Name:        "BusinessCountry-Region",
		},
		"{176DC63C-2688-4E89-8143-A347800F25E9} 7": {
			ID:          "{176DC63C-2688-4E89-8143-A347800F25E9} 7",
			Name:        "OfficeLocation",
		},
		"{95C656C1-2ABF-4148-9ED3-9EC602E3B7CD} 100": {
			ID:          "{95C656C1-2ABF-4148-9ED3-9EC602E3B7CD} 100",
			Name:        "OtherPostalCode",
		},
		"{E3E0584C-B788-4A5A-BB20-7F5A44C9ACDD} 15": {
			ID:          "{E3E0584C-B788-4A5A-BB20-7F5A44C9ACDD} 15",
			Name:        "Store",
		},
		"{4776CAFA-BCE4-4CB1-A23E-265E76D8EB11} 100": {
			ID:          "{4776CAFA-BCE4-4CB1-A23E-265E76D8EB11} 100",
			Name:        "Color",
		},
		"BuyNow": {
			ID:          "BuyNow",
		},
		"{64440490-4C8B-11D1-8B70-080036B11A03} 3": {
			ID:          "{64440490-4C8B-11D1-8B70-080036B11A03} 3",
			Name:        "Duration",
		},
		"{6D748DE2-8D38-4CC3-AC60-F009B057C557} 2": {
			ID:          "{6D748DE2-8D38-4CC3-AC60-F009B057C557} 2",
			Name:        "EpisodeName",
		},
		"{D5CDD502-2E9C-101B-9397-08002B2CF9AE} 15": {
			ID:          "{D5CDD502-2E9C-101B-9397-08002B2CF9AE} 15",
			Name:        "Company",
		},
		"{293CA35A-09AA-4DD2-B180-1FE245728A52} 100": {
			ID:          "{293CA35A-09AA-4DD2-B180-1FE245728A52} 100",
			Name:        "Duration",
		},
		"{D55BAE5A-3892-417A-A649-C6AC5AAAEAB3} 100": {
			ID:          "{D55BAE5A-3892-417A-A649-C6AC5AAAEAB3} 100",
			Name:        "OptionalAttendeeAddresses",
		},
		"RecordingTimeMonth": {
			ID:          "RecordingTimeMonth",
		},
		"WM/SharedUserRating": {
			ID:          "WM/SharedUserRating",
		},
		"{6E682923-7F7B-4F0C-A337-CFCA296687BF} 100": {
			ID:          "{6E682923-7F7B-4F0C-A337-CFCA296687BF} 100",
			Name:        "OtherCity",
		},
		"{F334115E-DA1B-4509-9B3D-119504DC7ABB} 100": {
			ID:          "{F334115E-DA1B-4509-9B3D-119504DC7ABB} 100",
			Name:        "Contributors",
		},
		"{5CBF2787-48CF-4208-B90E-EE5E5D420294} 2": {
			ID:          "{5CBF2787-48CF-4208-B90E-EE5E5D420294} 2",
			Name:        "URL",
		},
		"{64440491-4C8B-11D1-8B70-080036B11A03} 8": {
			ID:          "{64440491-4C8B-11D1-8B70-080036B11A03} 8",
			Name:        "DataRate",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"{64440490-4C8B-11D1-8B70-080036B11A03} 7": {
			ID:          "{64440490-4C8B-11D1-8B70-080036B11A03} 7",
			Name:        "Channels",
		},
		"{A94688B6-7D9F-4570-A648-E3DFC0AB2B3F} 100": {
			ID:          "{A94688B6-7D9F-4570-A648-E3DFC0AB2B3F} 100",
			Name:        "OfflineAvailability",
		},
		"{E53D799D-0F3F-466E-B2FF-74634A3CB7A4} 100": {
			ID:          "{E53D799D-0F3F-466E-B2FF-74634A3CB7A4} 100",
			Name:        "Country-Region",
		},
		"{B9B4B3FC-2B51-4A42-B5D8-324146AFCF25} 3": {
			ID:          "{B9B4B3FC-2B51-4A42-B5D8-324146AFCF25} 3",
			Name:        "LinkStatus",
		},
		"{0DA41CFA-D224-4A18-AE2F-596158DB4B3A} 100": {
			ID:          "{0DA41CFA-D224-4A18-AE2F-596158DB4B3A} 100",
			Name:        "SenderName",
		},
		"{E1277516-2B5F-4869-89B1-2E585BD38B7A} 100": {
			ID:          "{E1277516-2B5F-4869-89B1-2E585BD38B7A} 100",
			Name:        "LensModel",
		},
		"{6D217F6D-3F6A-4825-B470-5F03CA2FBE9B} 100": {
			ID:          "{6D217F6D-3F6A-4825-B470-5F03CA2FBE9B} 100",
			Name:        "ProgramMode",
		},
		"WM/ParentalRating": {
			ID:          "WM/ParentalRating",
		},
		"{00F58A38-C54B-4C40-8696-97235980EAE1} 100": {
			ID:          "{00F58A38-C54B-4C40-8696-97235980EAE1} 100",
			Name:        "Resources",
		},
		"{DE5EF3C7-46E1-484E-9999-62C5308394C1} 100": {
			ID:          "{DE5EF3C7-46E1-484E-9999-62C5308394C1} 100",
			Name:        "POBox",
		},
		"{176DC63C-2688-4E89-8143-A347800F25E9} 73": {
			ID:          "{176DC63C-2688-4E89-8143-A347800F25E9} 73",
			Name:        "Suffix",
		},
		"{14B81DA1-0135-4D31-96D9-6CBFC9671A99} 34855": {
			ID:          "{14B81DA1-0135-4D31-96D9-6CBFC9671A99} 34855",
			Name:        "ISOSpeed",
		},
		"{14B81DA1-0135-4D31-96D9-6CBFC9671A99} 37382": {
			ID:          "{14B81DA1-0135-4D31-96D9-6CBFC9671A99} 37382",
			Name:        "SubjectDistance",
		},
		"{EF884C5B-2BFE-41BB-AAE5-76EEDF4F9902} 200": {
			ID:          "{EF884C5B-2BFE-41BB-AAE5-76EEDF4F9902} 200",
			Name:        "SharedWith",
		},
		"ProviderURL": {
			ID:          "ProviderURL",
		},
		"RecordingTimeYear": {
			ID:          "RecordingTimeYear",
		},
		"RequestState": {
			ID:          "RequestState",
		},
		"{F29F85E0-4FF9-1068-AB91-08002B27B3D9} 14": {
			ID:          "{F29F85E0-4FF9-1068-AB91-08002B27B3D9} 14",
			Name:        "Pages",
		},
		"{E3E0584C-B788-4A5A-BB20-7F5A44C9ACDD} 12": {
			ID:          "{E3E0584C-B788-4A5A-BB20-7F5A44C9ACDD} 12",
			Name:        "FlagStatus",
		},
		"{560C36C0-503A-11CF-BAA1-00004C752A9A} 3": {
			ID:          "{560C36C0-503A-11CF-BAA1-00004C752A9A} 3",
			Name:        "Summary",
		},
		"WM/Category": {
			ID:          "WM/Category",
		},
		"{E08805C8-E395-40DF-80D2-54F0D6C43154} 100": {
			ID:          "{E08805C8-E395-40DF-80D2-54F0D6C43154} 100",
			Name:        "DocumentID",
		},
		"{14B81DA1-0135-4D31-96D9-6CBFC9671A99} 18248": {
			ID:          "{14B81DA1-0135-4D31-96D9-6CBFC9671A99} 18248",
			Name:        "Event",
		},
		"{49237325-A95A-4F67-B211-816B2D45D2E0} 100": {
			ID:          "{49237325-A95A-4F67-B211-816B2D45D2E0} 100",
			Name:        "Saturation",
		},
		"{64440491-4C8B-11D1-8B70-080036B11A03} 10": {
			ID:          "{64440491-4C8B-11D1-8B70-080036B11A03} 10",
			Name:        "VideoCompression",
		},
		"LibraryName": {
			ID:          "LibraryName",
		},
		"RecordingTimeDay": {
			ID:          "RecordingTimeDay",
		},
		"SyncState": {
			ID:          "SyncState",
		},
		"WM/BeatsPerMinute": {
			ID:          "WM/BeatsPerMinute",
			Name:        "BeatsPerMinute",
		},
		"WM/Publisher": {
			ID:          "WM/Publisher",
		},
		"WM/TrackNumber": {
			ID:          "WM/TrackNumber",
			Name:        "TrackNumber",
		},
		"WM/PromotionURL": {
			ID:          "WM/PromotionURL",
		},
		"{176DC63C-2688-4E89-8143-A347800F25E9} 74": {
			ID:          "{176DC63C-2688-4E89-8143-A347800F25E9} 74",
			Name:        "Nickname",
		},
		"CallLetters": {
			ID:          "CallLetters",
		},
		"{18BBD425-ECFD-46EF-B612-7B4A6034EDA0} 100": {
			ID:          "{18BBD425-ECFD-46EF-B612-7B4A6034EDA0} 100",
			Name:        "PostalCode",
		},
		"{C554493C-C1F7-40C1-A76C-EF8C0614003E} 100": {
			ID:          "{C554493C-C1F7-40C1-A76C-EF8C0614003E} 100",
			Name:        "Telex",
		},
		"{E3E0584C-B788-4A5A-BB20-7F5A44C9ACDD} 7": {
			ID:          "{E3E0584C-B788-4A5A-BB20-7F5A44C9ACDD} 7",
			Name:        "Path",
		},
		"{E3E0584C-B788-4A5A-BB20-7F5A44C9ACDD} 13": {
			ID:          "{E3E0584C-B788-4A5A-BB20-7F5A44C9ACDD} 13",
			Name:        "FromAddresses",
		},
		"{14B81DA1-0135-4D31-96D9-6CBFC9671A99} 37380": {
			ID:          "{14B81DA1-0135-4D31-96D9-6CBFC9671A99} 37380",
			Name:        "ExposureBias",
		},
		"Title": {
			ID:          "Title",
		},
		"Bitrate": {
			ID:          "Bitrate",
		},
		"UserPlaycountEvening": {
			ID:          "UserPlaycountEvening",
		},
		"WM/Director": {
			ID:          "WM/Director",
		},
		"{D8C3986F-813B-449C-845D-87B95D674ADE} 2": {
			ID:          "{D8C3986F-813B-449C-845D-87B95D674ADE} 2",
			Name:        "Status",
		},
		"{6444048F-4C8B-11D1-8B70-080036B11A03} 4": {
			ID:          "{6444048F-4C8B-11D1-8B70-080036B11A03} 4",
			Name:        "Untitled1",
		},
		"{0CEF7D53-FA64-11D1-A203-0000F81FEDEE} 3": {
			ID:          "{0CEF7D53-FA64-11D1-A203-0000F81FEDEE} 3",
			Name:        "Description",
		},
		"{F29F85E0-4FF9-1068-AB91-08002B27B3D9} 15": {
			ID:          "{F29F85E0-4FF9-1068-AB91-08002B27B3D9} 15",
			Name:        "WordCount",
		},
		"LibraryID": {
			ID:          "LibraryID",
		},
		"Sync03": {
			ID:          "Sync03",
		},
		"UserPlaycountMorning": {
			ID:          "UserPlaycountMorning",
		},
		"WM/MCDI": {
			ID:          "WM/MCDI",
			Name:        "MCDI",
		},
		"WM/WMShadowFileSourceFileType": {
			ID:          "WM/WMShadowFileSourceFileType",
			Name:        "WMShadowFileSourceFileType",
		},
		"{BC4E71CE-17F9-48D5-BEE9-021DF0EA5409} 100": {
			ID:          "{BC4E71CE-17F9-48D5-BEE9-021DF0EA5409} 100",
			Name:        "BusinessPOBox",
		},
		"{8F367200-C270-457C-B1D4-E07C5BCD90C7} 100": {
			ID:          "{8F367200-C270-457C-B1D4-E07C5BCD90C7} 100",
			Name:        "LastName",
		},
		"{6444048F-4C8B-11D1-8B70-080036B11A03} 5": {
			ID:          "{6444048F-4C8B-11D1-8B70-080036B11A03} 5",
			Name:        "HorizontalResolution",
		},
		"TitleSortOrder": {
			ID:          "TitleSortOrder",
		},
		"AverageLevel": {
			ID:          "AverageLevel",
		},
		"LeadPerformer": {
			ID:          "LeadPerformer",
		},
		"Sync16": {
			ID:          "Sync16",
		},
		"{0ADEF160-DB3F-4308-9A21-06237B16FA2A} 100": {
			ID:          "{0ADEF160-DB3F-4308-9A21-06237B16FA2A} 100",
			Name:        "HomeStreet",
		},
		"{AAF16BAC-2B55-45E6-9F6D-415EB94910DF} 100": {
			ID:          "{AAF16BAC-2B55-45E6-9F6D-415EB94910DF} 100",
			Name:        "TTY-TTDPhone",
		},
		"{D5CDD502-2E9C-101B-9397-08002B2CF9AE} 27": {
			ID:          "{D5CDD502-2E9C-101B-9397-08002B2CF9AE} 27",
			Name:        "Status",
		},
		"{64440492-4C8B-11D1-8B70-080036B11A03} 36": {
			ID:          "{64440492-4C8B-11D1-8B70-080036B11A03} 36",
			Name:        "EncodedBy",
		},
		"UserRating": {
			ID:          "UserRating",
		},
		"WM/AuthorURL": {
			ID:          "WM/AuthorURL",
		},
		"{6D748DE2-8D38-4CC3-AC60-F009B057C557} 5": {
			ID:          "{6D748DE2-8D38-4CC3-AC60-F009B057C557} 5",
			Name:        "StationCallSign",
		},
		"WM/Provider": {
			ID:          "WM/Provider",
		},
		"AcquisitionTimeMonth": {
			ID:          "AcquisitionTimeMonth",
		},
		"ProviderLogoURL": {
			ID:          "ProviderLogoURL",
		},
		"WM/AlbumArtist": {
			ID:          "WM/AlbumArtist",
		},
		"WM/MediaStationName": {
			ID:          "WM/MediaStationName",
			Name:        "MediaStationName",
		},
		"{E3E0584C-B788-4A5A-BB20-7F5A44C9ACDD} 9": {
			ID:          "{E3E0584C-B788-4A5A-BB20-7F5A44C9ACDD} 9",
			Name:        "AccountName",
		},
		"Count": {
			ID:          "Count",
		},
		"DRMIndividualizedVersion": {
			ID:          "DRMIndividualizedVersion",
		},
		"MoreInfo": {
			ID:          "MoreInfo",
		},
		"{F29F85E0-4FF9-1068-AB91-08002B27B3D9} 2": {
			ID:          "{F29F85E0-4FF9-1068-AB91-08002B27B3D9} 2",
			Name:        "Title",
		},
		"{5BF396D4-5EB2-466F-BDE9-2FB3F2361D6E} 100": {
			ID:          "{5BF396D4-5EB2-466F-BDE9-2FB3F2361D6E} 100",
			Name:        "Free-busyStatus",
		},
		"{660E04D6-81AB-4977-A09F-82313113AB26} 100": {
			ID:          "{660E04D6-81AB-4977-A09F-82313113AB26} 100",
			Name:        "HomeFax",
		},
		"DTCPIPHost": {
			ID:          "DTCPIPHost",
		},
		"DTCPIPPort": {
			ID:          "DTCPIPPort",
		},
		"Frequency": {
			ID:          "Frequency",
		},
		"ReleaseDateDay": {
			ID:          "ReleaseDateDay",
		},
		"WM/Lyrics": {
			ID:          "WM/Lyrics",
			Name:        "Lyrics",
		},
		"{176DC63C-2688-4E89-8143-A347800F25E9} 69": {
			ID:          "{176DC63C-2688-4E89-8143-A347800F25E9} 69",
			Name:        "PersonalTitle",
		},
		"{C75FAA05-96FD-49E7-9CB4-9F601082D553} 100": {
			ID:          "{C75FAA05-96FD-49E7-9CB4-9F601082D553} 100",
			Name:        "EndDate",
		},
		"AcquisitionTimeDay": {
			ID:          "AcquisitionTimeDay",
		},
		"RatingOrg": {
			ID:          "RatingOrg",
		},
		"RecordingTimeYearMonth": {
			ID:          "RecordingTimeYearMonth",
		},
		"SourceURL": {
			ID:          "SourceURL",
		},
		"{B725F130-47EF-101A-A5F1-02608C9EEBAC} 13": {
			ID:          "{B725F130-47EF-101A-A5F1-02608C9EEBAC} 13",
			Name:        "Attributes",
		},
		"{1E3EE840-BC2B-476C-8237-2ACD1A839B22} 3": {
			ID:          "{1E3EE840-BC2B-476C-8237-2ACD1A839B22} 3",
			Name:        "Kinds",
		},
		"{F29F85E0-4FF9-1068-AB91-08002B27B3D9} 11": {
			ID:          "{F29F85E0-4FF9-1068-AB91-08002B27B3D9} 11",
			Name:        "LastPrinted",
		},
		"WRITE_GROUP": {
			ID:          "WRITE_GROUP",
			Name:        "Microsoft",
		},
		"AcquisitionTimeYearMonth": {
			ID:          "AcquisitionTimeYearMonth",
		},
		"AcquisitionTimeYearMonthDay": {
			ID:          "AcquisitionTimeYearMonthDay",
		},
		"Sync15": {
			ID:          "Sync15",
		},
		"{6444048F-4C8B-11D1-8B70-080036B11A03} 3": {
			ID:          "{6444048F-4C8B-11D1-8B70-080036B11A03} 3",
			Name:        "Untitled0",
		},
		"{176DC63C-2688-4E89-8143-A347800F25E9} 35": {
			ID:          "{176DC63C-2688-4E89-8143-A347800F25E9} 35",
			Name:        "CellPhone",
		},
		"{64440492-4C8B-11D1-8B70-080036B11A03} 30": {
			ID:          "{64440492-4C8B-11D1-8B70-080036B11A03} 30",
			Name:        "Publisher",
		},
		"{0BE1C8E7-1981-4676-AE14-FDD78F05A6E7} 100": {
			ID:          "{0BE1C8E7-1981-4676-AE14-FDD78F05A6E7} 100",
			Name:        "SenderAddress",
		},
		"AVOID": {
			ID:          "AVOID",
		},
		"Temporary": {
			ID:          "Temporary",
		},
		"{D5CDD502-2E9C-101B-9397-08002B2CF9AE} 28": {
			ID:          "{D5CDD502-2E9C-101B-9397-08002B2CF9AE} 28",
			Name:        "Language",
		},
		"{49691C90-7E17-101A-A91C-08002B2ECDA9} 3": {
			ID:          "{49691C90-7E17-101A-A91C-08002B2ECDA9} 3",
			Name:        "SearchRanking",
		},
		"DLNAServerUDN": {
			ID:          "DLNAServerUDN",
		},
		"MediaType": {
			ID:          "MediaType",
		},
		"WM/SubscriptionContentID": {
			ID:          "WM/SubscriptionContentID",
			Name:        "SubscriptionContentID",
		},
		"{E3E0584C-B788-4A5A-BB20-7F5A44C9ACDD} 18": {
			ID:          "{E3E0584C-B788-4A5A-BB20-7F5A44C9ACDD} 18",
			Name:        "Webpage",
		},
		"{6444048F-4C8B-11D1-8B70-080036B11A03} 7": {
			ID:          "{6444048F-4C8B-11D1-8B70-080036B11A03} 7",
			Name:        "BitDepth",
		},
		"{E3E0584C-B788-4A5A-BB20-7F5A44C9ACDD} 6": {
			ID:          "{E3E0584C-B788-4A5A-BB20-7F5A44C9ACDD} 6",
			Name:        "FolderPath",
		},
		"{14B81DA1-0135-4D31-96D9-6CBFC9671A99} 37386": {
			ID:          "{14B81DA1-0135-4D31-96D9-6CBFC9671A99} 37386",
			Name:        "FocalLength",
		},
		"{9C1FCF74-2D97-41BA-B4AE-CB2E3661A6E4} 5": {
			ID:          "{9C1FCF74-2D97-41BA-B4AE-CB2E3661A6E4} 5",
			Name:        "Priority",
		},
		"ReleaseDateYearMonth": {
			ID:          "ReleaseDateYearMonth",
		},
		"WM/ContentDistributor": {
			ID:          "WM/ContentDistributor",
		},
		"WM/OriginalAlbumTitle": {
			ID:          "WM/OriginalAlbumTitle",
		},
		"WM/WMCollectionID": {
			ID:          "WM/WMCollectionID",
			Name:        "WMCollectionID",
		},
		"{730FB6DD-CF7C-426B-A03F-BD166CC9EE24} 100": {
			ID:          "{730FB6DD-CF7C-426B-A03F-BD166CC9EE24} 100",
			Name:        "BusinessAddress",
		},
		"{38965063-EDC8-4268-8491-B7723172CF29} 100": {
			ID:          "{38965063-EDC8-4268-8491-B7723172CF29} 100",
			Name:        "E-mail2",
		},
		"{3C8CEE58-D4F0-4CF9-B756-4E5D24447BCD} 100": {
			ID:          "{3C8CEE58-D4F0-4CF9-B756-4E5D24447BCD} 100",
			Name:        "Gender",
		},
		"{9D2408B6-3167-422B-82B0-F583B7A7CFE3} 100": {
			ID:          "{9D2408B6-3167-422B-82B0-F583B7A7CFE3} 100",
			Name:        "Spouse",
		},
		"AlbumArtistSortOrder": {
			ID:          "AlbumArtistSortOrder",
		},
		"AuthorSortOrder": {
			ID:          "AuthorSortOrder",
		},
		"{644D37B4-E1B3-4BAD-B099-7E7C04966ACA} 100": {
			ID:          "{644D37B4-E1B3-4BAD-B099-7E7C04966ACA} 100",
			Name:        "E-mail3",
		},
		"{E3E0584C-B788-4A5A-BB20-7F5A44C9ACDD} 5": {
			ID:          "{E3E0584C-B788-4A5A-BB20-7F5A44C9ACDD} 5",
			Name:        "CcNames",
		},
		"{56A3372E-CE9C-11D2-9F0E-006097C686F6} 34": {
			ID:          "{56A3372E-CE9C-11D2-9F0E-006097C686F6} 34",
			Name:        "InitialKey",
		},
		"{64440492-4C8B-11D1-8B70-080036B11A03} 31": {
			ID:          "{64440492-4C8B-11D1-8B70-080036B11A03} 31",
			Name:        "Period",
		},
		"Duration": {
			ID:          "Duration",
		},
		"UserServiceRating": {
			ID:          "UserServiceRating",
		},
		"WM/GenreID": {
			ID:          "WM/GenreID",
			Name:        "GenreID",
		},
		"WM/VideoFrameRate": {
			ID:          "WM/VideoFrameRate",
			Name:        "VideoFrameRate",
		},
		"{B725F130-47EF-101A-A5F1-02608C9EEBAC} 12": {
			ID:          "{B725F130-47EF-101A-A5F1-02608C9EEBAC} 12",
			Name:        "Size",
		},
		"{315B9C8D-80A9-4EF9-AE16-8E746DA51D70} 100": {
			ID:          "{315B9C8D-80A9-4EF9-AE16-8E746DA51D70} 100",
			Name:        "IsRecurring",
		},
		"{F3D8F40D-50CB-44A2-9718-40CB9119495D} 100": {
			ID:          "{F3D8F40D-50CB-44A2-9718-40CB9119495D} 100",
			Name:        "Initials",
		},
		"{E3E0584C-B788-4A5A-BB20-7F5A44C9ACDD} 11": {
			ID:          "{E3E0584C-B788-4A5A-BB20-7F5A44C9ACDD} 11",
			Name:        "Importance",
		},
		"AlbumID": {
			ID:          "AlbumID",
		},
		"AlbumIDAlbumArtist": {
			ID:          "AlbumIDAlbumArtist",
		},
		"FourCC": {
			ID:          "FourCC",
		},
		"{8589E481-6040-473D-B171-7FA89C2708ED} 100": {
			ID:          "{8589E481-6040-473D-B171-7FA89C2708ED} 100",
			Name:        "CompanyMainPhone",
		},
		"{7268AF55-1CE4-4F6E-A41F-B6E4EF10E4A9} 100": {
			ID:          "{7268AF55-1CE4-4F6E-A41F-B6E4EF10E4A9} 100",
			Name:        "Profession",
		},
		"{E3E0584C-B788-4A5A-BB20-7F5A44C9ACDD} 2": {
			ID:          "{E3E0584C-B788-4A5A-BB20-7F5A44C9ACDD} 2",
			Name:        "BccAddresses",
		},
		"{56A3372E-CE9C-11D2-9F0E-006097C686F6} 13": {
			ID:          "{56A3372E-CE9C-11D2-9F0E-006097C686F6} 13",
			Name:        "AlbumArtist",
		},
		"{560C36C0-503A-11CF-BAA1-00004C752A9A} 2": {
			ID:          "{560C36C0-503A-11CF-BAA1-00004C752A9A} 2",
			Name:        "AutoSummary",
		},
		"{0CEF7D53-FA64-11D1-A203-0000F81FEDEE} 7": {
			ID:          "{0CEF7D53-FA64-11D1-A203-0000F81FEDEE} 7",
			Name:        "ProductName",
		},
		"{28636AA6-953D-11D2-B5D6-00C04FD918D0} 9": {
			ID:          "{28636AA6-953D-11D2-B5D6-00C04FD918D0} 9",
			Name:        "PerceivedType",
		},
		"{DDD1460F-C0BF-4553-8CE4-10433C908FB0} 100": {
			ID:          "{DDD1460F-C0BF-4553-8CE4-10433C908FB0} 100",
			Name:        "BusinessStreet",
		},
		"{D5CDD502-2E9C-101B-9397-08002B2CF9AE} 26": {
			ID:          "{D5CDD502-2E9C-101B-9397-08002B2CF9AE} 26",
			Name:        "ContentType",
		},
		"{BCCC8A3C-8CEF-42E5-9B1C-C69079398BC7} 100": {
			ID:          "{BCCC8A3C-8CEF-42E5-9B1C-C69079398BC7} 100",
			Name:        "ToDoTitle",
		},
		"AlternateSourceURL": {
			ID:          "AlternateSourceURL",
		},
		"AudioBitrate": {
			ID:          "AudioBitrate",
		},
		"FileSize": {
			ID:          "FileSize",
		},
		"MediaContentTypes": {
			ID:          "MediaContentTypes",
		},
		"SyncOnly": {
			ID:          "SyncOnly",
		},
		"UserPlaycountAfternoon": {
			ID:          "UserPlaycountAfternoon",
		},
		"{56A3372E-CE9C-11D2-9F0E-006097C686F6} 11": {
			ID:          "{56A3372E-CE9C-11D2-9F0E-006097C686F6} 11",
			Name:        "Genre",
		},
		"{64440490-4C8B-11D1-8B70-080036B11A03} 4": {
			ID:          "{64440490-4C8B-11D1-8B70-080036B11A03} 4",
			Name:        "Bitrate",
		},
		"FormatTag": {
			ID:          "FormatTag",
		},
		"{0CEF7D53-FA64-11D1-A203-0000F81FEDEE} 8": {
			ID:          "{0CEF7D53-FA64-11D1-A203-0000F81FEDEE} 8",
			Name:        "ProductVersion",
		},
		"{64440490-4C8B-11D1-8B70-080036B11A03} 5": {
			ID:          "{64440490-4C8B-11D1-8B70-080036B11A03} 5",
			Name:        "AudioSampleRate",
		},
		"{F6272D18-CECC-40B1-B26A-3911717AA7BD} 100": {
			ID:          "{F6272D18-CECC-40B1-B26A-3911717AA7BD} 100",
			Name:        "Location",
		},
		"{FC9F7306-FF8F-4D49-9FB6-3FFE5C0951EC} 100": {
			ID:          "{FC9F7306-FF8F-4D49-9FB6-3FFE5C0951EC} 100",
			Name:        "Department",
		},
		"{56A3372E-CE9C-11D2-9F0E-006097C686F6} 35": {
			ID:          "{56A3372E-CE9C-11D2-9F0E-006097C686F6} 35",
			Name:        "Beats-per-minute",
		},
		"{668CDFA5-7A1B-4323-AE4B-E527393A1D81} 100": {
			ID:          "{668CDFA5-7A1B-4323-AE4B-E527393A1D81} 100",
			Name:        "Source",
		},
		"{D37D52C6-261C-4303-82B3-08B926AC6F12} 100": {
			ID:          "{D37D52C6-261C-4303-82B3-08B926AC6F12} 100",
			Name:        "BillingInformation",
		},
		"Sync13": {
			ID:          "Sync13",
		},
		"WM/ContentDistributorType": {
			ID:          "WM/ContentDistributorType",
			Name:        "ContentDistributorType",
		},
		"WM/ProviderStyle": {
			ID:          "WM/ProviderStyle",
			Name:        "ProviderStyle",
		},
		"WM/WMCollectionGroupID": {
			ID:          "WM/WMCollectionGroupID",
			Name:        "WMCollectionGroupID",
		},
		"WM/WMContentID": {
			ID:          "WM/WMContentID",
			Name:        "WMContentID",
		},
		"{6D24888F-4718-4BDA-AFED-EA0FB4386CD8} 100": {
			ID:          "{6D24888F-4718-4BDA-AFED-EA0FB4386CD8} 100",
			Name:        "OfflineStatus",
		},
		"{176DC63C-2688-4E89-8143-A347800F25E9} 20": {
			ID:          "{176DC63C-2688-4E89-8143-A347800F25E9} 20",
			Name:        "HomePhone",
		},
		"{71B377D6-E570-425F-A170-809FAE73E54E} 100": {
			ID:          "{71B377D6-E570-425F-A170-809FAE73E54E} 100",
			Name:        "OtherStateOrProvince",
		},
		"chapterNum": {
			ID:          "chapterNum",
		},
		"PixelAspectRatioX": {
			ID:          "PixelAspectRatioX",
		},
		"{176DC63C-2688-4E89-8143-A347800F25E9} 48": {
			ID:          "{176DC63C-2688-4E89-8143-A347800F25E9} 48",
			Name:        "PrimaryE-mail",
		},
		"{EF884C5B-2BFE-41BB-AAE5-76EEDF4F9902} 100": {
			ID:          "{EF884C5B-2BFE-41BB-AAE5-76EEDF4F9902} 100",
			Name:        "Shared",
		},
		"{56A3372E-CE9C-11D2-9F0E-006097C686F6} 39": {
			ID:          "{56A3372E-CE9C-11D2-9F0E-006097C686F6} 39",
			Name:        "Mood",
		},
		"{14B81DA1-0135-4D31-96D9-6CBFC9671A99} 33434": {
			ID:          "{14B81DA1-0135-4D31-96D9-6CBFC9671A99} 33434",
			Name:        "ExposureTime",
		},
		"{64440491-4C8B-11D1-8B70-080036B11A03} 6": {
			ID:          "{64440491-4C8B-11D1-8B70-080036B11A03} 6",
			Name:        "FrameRate",
		},
		"WM/Period": {
			ID:          "WM/Period",
		},
		"WM/VideoHeight": {
			ID:          "WM/VideoHeight",
			Name:        "VideoHeight",
		},
		"{6D748DE2-8D38-4CC3-AC60-F009B057C557} 3": {
			ID:          "{6D748DE2-8D38-4CC3-AC60-F009B057C557} 3",
			Name:        "ProgramDescription",
		},
		"{AAA660F9-9865-458E-B484-01BC7FE3973E} 100": {
			ID:          "{AAA660F9-9865-458E-B484-01BC7FE3973E} 100",
			Name:        "OrganizerName",
		},
		"{14977844-6B49-4AAD-A714-A4513BF60460} 100": {
			ID:          "{14977844-6B49-4AAD-A714-A4513BF60460} 100",
			Name:        "FirstName",
		},
		"{8F167568-0AAE-4322-8ED9-6055B7B0E398} 100": {
			ID:          "{8F167568-0AAE-4322-8ED9-6055B7B0E398} 100",
			Name:        "OtherCountry-Region",
		},
		"{6D748DE2-8D38-4CC3-AC60-F009B057C557} 7": {
			ID:          "{6D748DE2-8D38-4CC3-AC60-F009B057C557} 7",
			Name:        "ChannelNumber",
		},
		"{64440492-4C8B-11D1-8B70-080036B11A03} 20": {
			ID:          "{64440492-4C8B-11D1-8B70-080036B11A03} 20",
			Name:        "Directors",
		},
		"AcquisitionTimeYear": {
			ID:          "AcquisitionTimeYear",
		},
		"AudioFormat": {
			ID:          "AudioFormat",
		},
		"Description": {
			ID:          "Description",
		},
		"Sync07": {
			ID:          "Sync07",
		},
		"{E1D4A09E-D758-4CD1-B6EC-34A8B5A73F80} 100": {
			ID:          "{E1D4A09E-D758-4CD1-B6EC-34A8B5A73F80} 100",
			Name:        "BusinessPostalCode",
		},
		"{E3E0584C-B788-4A5A-BB20-7F5A44C9ACDD} 3": {
			ID:          "{E3E0584C-B788-4A5A-BB20-7F5A44C9ACDD} 3",
			Name:        "BccNames",
		},
		"{D35F743A-EB2E-47F2-A286-844132CB1427} 100": {
			ID:          "{D35F743A-EB2E-47F2-A286-844132CB1427} 100",
			Name:        "ExifVersion",
		},
		"Sync14": {
			ID:          "Sync14",
		},
		"{91EFF6F3-2E27-42CA-933E-7C999FBE310B} 100": {
			ID:          "{91EFF6F3-2E27-42CA-933E-7C999FBE310B} 100",
			Name:        "BusinessFax",
		},
		"{8FDC6DEA-B929-412B-BA90-397A257465FE} 100": {
			ID:          "{8FDC6DEA-B929-412B-BA90-397A257465FE} 100",
			Name:        "CarPhone",
		},
		"{14B81DA1-0135-4D31-96D9-6CBFC9671A99} 274": {
			ID:          "{14B81DA1-0135-4D31-96D9-6CBFC9671A99} 274",
			Name:        "Orientation",
		},
		"TotalDuration": {
			ID:          "TotalDuration",
		},
		"WM/InitialKey": {
			ID:          "WM/InitialKey",
		},
		"{B725F130-47EF-101A-A5F1-02608C9EEBAC} 10": {
			ID:          "{B725F130-47EF-101A-A5F1-02608C9EEBAC} 10",
			Name:        "Name",
		},
		"{9AD5BADB-CEA7-4470-A03D-B84E51B9949E} 100": {
			ID:          "{9AD5BADB-CEA7-4470-A03D-B84E51B9949E} 100",
			Name:        "Anniversary",
		},
		"{5DC2253F-5E11-4ADF-9CFE-910DD01E3E70} 100": {
			ID:          "{5DC2253F-5E11-4ADF-9CFE-910DD01E3E70} 100",
			Name:        "Hobbies",
		},
		"{176DC63C-2688-4E89-8143-A347800F25E9} 6": {
			ID:          "{176DC63C-2688-4E89-8143-A347800F25E9} 6",
			Name:        "JobTitle",
		},
		"PartOfSet": {
			ID:          "PartOfSet",
		},
		"{F29F85E0-4FF9-1068-AB91-08002B27B3D9} 12": {
			ID:          "{F29F85E0-4FF9-1068-AB91-08002B27B3D9} 12",
			Name:        "Untitled2",
		},
		"{9A93244D-A7AD-4FF8-9B99-45EE4CC09AF6} 100": {
			ID:          "{9A93244D-A7AD-4FF8-9B99-45EE4CC09AF6} 100",
			Name:        "AssistantsPhone",
		},
		"{84D8F337-981D-44B3-9615-C7596DBA17E3} 100": {
			ID:          "{84D8F337-981D-44B3-9615-C7596DBA17E3} 100",
			Name:        "E-mailList",
		},
		"{176DC63C-2688-4E89-8143-A347800F25E9} 25": {
			ID:          "{176DC63C-2688-4E89-8143-A347800F25E9} 25",
			Name:        "PrimaryPhone",
		},
		"{5CBF2787-48CF-4208-B90E-EE5E5D420294} 21": {
			ID:          "{5CBF2787-48CF-4208-B90E-EE5E5D420294} 21",
			Name:        "Description",
		},
		"{14B81DA1-0135-4D31-96D9-6CBFC9671A99} 37384": {
			ID:          "{14B81DA1-0135-4D31-96D9-6CBFC9671A99} 37384",
			Name:        "LightSource",
		},
		"IsVBR": {
			ID:          "IsVBR",
		},
		"UserCustom1": {
			ID:          "UserCustom1",
		},
		"{BF53D1C3-49E0-4F7F-8567-5A821D8AC542} 100": {
			ID:          "{BF53D1C3-49E0-4F7F-8567-5A821D8AC542} 100",
			Name:        "CallbackNumber",
		},
		"{D4729704-8EF1-43EF-9024-2BD381187FD5} 100": {
			ID:          "{D4729704-8EF1-43EF-9024-2BD381187FD5} 100",
			Name:        "Children",
		},
		"{8B26EA41-058F-43F6-AECC-4035681CE977} 100": {
			ID:          "{8B26EA41-058F-43F6-AECC-4035681CE977} 100",
			Name:        "OtherPOBox",
		},
		"{39A7F922-477C-48DE-8BC8-B28441E342E3} 100": {
			ID:          "{39A7F922-477C-48DE-8BC8-B28441E342E3} 100",
			Name:        "Project",
		},
		"Author": {
			ID:          "Author",
		},
		"DLNASourceURI": {
			ID:          "DLNASourceURI",
		},
		"ReleaseDate": {
			ID:          "ReleaseDate",
		},
		"WM/AlbumTitle": {
			ID:          "WM/AlbumTitle",
		},
		"WM/ContentGroupDescription": {
			ID:          "WM/ContentGroupDescription",
			Name:        "ContentGroupDescription",
		},
		"WM/ProviderRating": {
			ID:          "WM/ProviderRating",
			Name:        "ProviderRating",
		},
		"{176DC63C-2688-4E89-8143-A347800F25E9} 70": {
			ID:          "{176DC63C-2688-4E89-8143-A347800F25E9} 70",
			Name:        "GivenName",
		},
		"{508161FA-313B-43D5-83A1-C1ACCF68622C} 100": {
			ID:          "{508161FA-313B-43D5-83A1-C1ACCF68622C} 100",
			Name:        "OtherAddress",
		},
		"DisplayArtist": {
			ID:          "DisplayArtist",
		},
		"WM/SubTitle": {
			ID:          "WM/SubTitle",
		},
		"{0CEF7D53-FA64-11D1-A203-0000F81FEDEE} 4": {
			ID:          "{0CEF7D53-FA64-11D1-A203-0000F81FEDEE} 4",
			Name:        "FileVersion",
		},
		"{D5CDD502-2E9C-101B-9397-08002B2CF9AE} 7": {
			ID:          "{D5CDD502-2E9C-101B-9397-08002B2CF9AE} 7",
			Name:        "Slides",
		},
		"{64440492-4C8B-11D1-8B70-080036B11A03} 34": {
			ID:          "{64440492-4C8B-11D1-8B70-080036B11A03} 34",
			Name:        "UserWebURL",
		},
		"{E3E0584C-B788-4A5A-BB20-7F5A44C9ACDD} 4": {
			ID:          "{E3E0584C-B788-4A5A-BB20-7F5A44C9ACDD} 4",
			Name:        "CcAddresses",
		},
		"{DC8F80BD-AF1E-4289-85B6-3DFC1B493992} 100": {
			ID:          "{DC8F80BD-AF1E-4289-85B6-3DFC1B493992} 100",
			Name:        "ConversationID",
		},
		"RadioFormat": {
			ID:          "RadioFormat",
		},
		"{F29F85E0-4FF9-1068-AB91-08002B27B3D9} 3": {
			ID:          "{F29F85E0-4FF9-1068-AB91-08002B27B3D9} 3",
			Name:        "Subject",
		},
		"{56A3372E-CE9C-11D2-9F0E-006097C686F6} 7": {
			ID:          "{56A3372E-CE9C-11D2-9F0E-006097C686F6} 7",
			Name:        "TrackNumber",
		},
		"UserCustom2": {
			ID:          "UserCustom2",
		},
		"{14B81DA1-0135-4D31-96D9-6CBFC9671A99} 272": {
			ID:          "{14B81DA1-0135-4D31-96D9-6CBFC9671A99} 272",
			Name:        "CameraModel",
		},
		"{F29F85E0-4FF9-1068-AB91-08002B27B3D9} 18": {
			ID:          "{F29F85E0-4FF9-1068-AB91-08002B27B3D9} 18",
			Name:        "ProgramName",
		},
		"{F1176DFE-7138-4640-8B4C-AE375DC70A6D} 100": {
			ID:          "{F1176DFE-7138-4640-8B4C-AE375DC70A6D} 100",
			Name:        "StateOrProvince",
		},
		"{A0E74609-B84D-4F49-B860-462BD9971F98} 100": {
			ID:          "{A0E74609-B84D-4F49-B860-462BD9971F98} 100",
			Name:        "FocalLength35mm",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"CameraManufacturer": {
			ID:          "CameraManufacturer",
		},
		"FrameRate": {
			ID:          "FrameRate",
		},
		"WM/OriginalLyricist": {
			ID:          "WM/OriginalLyricist",
		},
		"WM/UniqueFileIdentifier": {
			ID:          "WM/UniqueFileIdentifier",
			Name:        "UniqueFileIdentifier",
		},
		"{9B174B35-40FF-11D2-A27E-00C04FC30871} 3": {
			ID:          "{9B174B35-40FF-11D2-A27E-00C04FC30871} 3",
			Name:        "TotalSize",
		},
		"{176DC63C-2688-4E89-8143-A347800F25E9} 71": {
			ID:          "{176DC63C-2688-4E89-8143-A347800F25E9} 71",
			Name:        "MiddleName",
		},
		"{B9B4B3FC-2B51-4A42-B5D8-324146AFCF25} 2": {
			ID:          "{B9B4B3FC-2B51-4A42-B5D8-324146AFCF25} 2",
			Name:        "LinkTarget",
		},
		"{72FC5BA4-24F9-4011-9F3F-ADD27AFAD818} 100": {
			ID:          "{72FC5BA4-24F9-4011-9F3F-ADD27AFAD818} 100",
			Name:        "ReminderTime",
		},
		"{D68DBD8A-3374-4B81-9972-3EC30682DB3D} 100": {
			ID:          "{D68DBD8A-3374-4B81-9972-3EC30682DB3D} 100",
			Name:        "IMAddresses",
		},
		"{1E005EE6-BF27-428B-B01C-79676ACD2870} 100": {
			ID:          "{1E005EE6-BF27-428B-B01C-79676ACD2870} 100",
			Name:        "Division",
		},
		"{F29F85E0-4FF9-1068-AB91-08002B27B3D9} 10": {
			ID:          "{F29F85E0-4FF9-1068-AB91-08002B27B3D9} 10",
			Name:        "TotalEditingTime",
		},
		"{28636AA6-953D-11D2-B5D6-00C04FD918D0} 12": {
			ID:          "{28636AA6-953D-11D2-B5D6-00C04FD918D0} 12",
			Name:        "FileCount",
		},
		"{4684FE97-8765-4842-9C13-F006447B178C} 100": {
			ID:          "{4684FE97-8765-4842-9C13-F006447B178C} 100",
			Name:        "BroadcastDate",
		},
		"{64440491-4C8B-11D1-8B70-080036B11A03} 4": {
			ID:          "{64440491-4C8B-11D1-8B70-080036B11A03} 4",
			Name:        "FrameHeight",
		},
		"CurrentBitrate": {
			ID:          "CurrentBitrate",
		},
		"WM/ProtectionType": {
			ID:          "WM/ProtectionType",
			Name:        "ProtectionType",
		},
		"{95BEB1FC-326D-4644-B396-CD3ED90E6DDF} 100": {
			ID:          "{95BEB1FC-326D-4644-B396-CD3ED90E6DDF} 100",
			Name:        "EntryType",
		},
		"{64440492-4C8B-11D1-8B70-080036B11A03} 21": {
			ID:          "{64440492-4C8B-11D1-8B70-080036B11A03} 21",
			Name:        "ParentalRating",
		},
		"{A5477F61-7A82-4ECA-9DDE-98B69B2479B3} 100": {
			ID:          "{A5477F61-7A82-4ECA-9DDE-98B69B2479B3} 100",
			Name:        "RecordingTime",
		},
		"IsNetworkFeed": {
			ID:          "IsNetworkFeed",
		},
		"WM/Conductor": {
			ID:          "WM/Conductor",
		},
		"WM/SubTitleDescription": {
			ID:          "WM/SubTitleDescription",
			Name:        "SubtitleDescription",
		},
		"{744C8242-4DF5-456C-AB9E-014EFB9021E3} 100": {
			ID:          "{744C8242-4DF5-456C-AB9E-014EFB9021E3} 100",
			Name:        "OrganizerAddress",
		},
		"{B33AF30B-F552-4584-936C-CB93E5CDA29F} 100": {
			ID:          "{B33AF30B-F552-4584-936C-CB93E5CDA29F} 100",
			Name:        "RequiredAttendees",
		},
		"{CD102C9C-5540-4A88-A6F6-64E4981C8CD1} 100": {
			ID:          "{CD102C9C-5540-4A88-A6F6-64E4981C8CD1} 100",
			Name:        "AssistantsName",
		},
		"{08A65AA1-F4C9-43DD-9DDF-A33D8E7EAD85} 100": {
			ID:          "{08A65AA1-F4C9-43DD-9DDF-A33D8E7EAD85} 100",
			Name:        "HomeCountry-Region",
		},
		"{5CDA5FC8-33EE-4FF3-9094-AE7BD8868C4D} 100": {
			ID:          "{5CDA5FC8-33EE-4FF3-9094-AE7BD8868C4D} 100",
			Name:        "IsDeleted",
		},
		"Abstract": {
			ID:          "Abstract",
		},
		"BuyTickets": {
			ID:          "BuyTickets",
		},
		"Channels": {
			ID:          "Channels",
		},
		"{AEAC19E4-89AE-4508-B9B7-BB867ABEE2ED} 2": {
			ID:          "{AEAC19E4-89AE-4508-B9B7-BB867ABEE2ED} 2",
			Name:        "Protected",
		},
		"{176DC63C-2688-4E89-8143-A347800F25E9} 65": {
			ID:          "{176DC63C-2688-4E89-8143-A347800F25E9} 65",
			Name:        "HomeCity",
		},
		"{67DF94DE-0CA7-4D6F-B792-053A3E4F03CF} 100": {
			ID:          "{67DF94DE-0CA7-4D6F-B792-053A3E4F03CF} 100",
			Name:        "FlagColor",
		},
		"{A6F360D2-55F9-48DE-B909-620E090A647C} 100": {
			ID:          "{A6F360D2-55F9-48DE-B909-620E090A647C} 100",
			Name:        "IsCompleted",
		},
		"{DEA7C82C-1D89-4A66-9427-A4E3DEBABCB1} 100": {
			ID:          "{DEA7C82C-1D89-4A66-9427-A4E3DEBABCB1} 100",
			Name:        "ContactNames",
		},
		"{9B174B34-40FF-11D2-A27E-00C04FC30871} 4": {
			ID:          "{9B174B34-40FF-11D2-A27E-00C04FC30871} 4",
			Name:        "Owner",
		},
		"{F8FA7FA3-D12B-4785-8A4E-691A94F7A3E7} 100": {
			ID:          "{F8FA7FA3-D12B-4785-8A4E-691A94F7A3E7} 100",
			Name:        "E-mailAddress",
		},
		"{97B0AD89-DF49-49CC-834E-660974FD755B} 100": {
			ID:          "{97B0AD89-DF49-49CC-834E-660974FD755B} 100",
			Name:        "Label",
		},
		"{64440492-4C8B-11D1-8B70-080036B11A03} 19": {
			ID:          "{64440492-4C8B-11D1-8B70-080036B11A03} 19",
			Name:        "Composers",
		},
		"{14B81DA1-0135-4D31-96D9-6CBFC9671A99} 33437": {
			ID:          "{14B81DA1-0135-4D31-96D9-6CBFC9671A99} 33437",
			Name:        "F-stop",
		},
		"{1B5439E7-EBA1-4AF8-BDD7-7AF1D4549493} 100": {
			ID:          "{1B5439E7-EBA1-4AF8-BDD7-7AF1D4549493} 100",
			Name:        "StationName",
		},
	},
}
