// Code generated by gen-tags. DO NOT EDIT.

package tags

// MIEPreviewTags contains tag definitions from Image::ExifTool::MIE
var MIEPreviewTags = TagTable{
	ModuleName: "MIE",
	Tags: map[string]TagDef{
		"WRITE_GROUP": {
			ID:          "WRITE_GROUP",
			Name:        "MIE-Preview",
		},
		"0Type": {
			ID:          "0Type",
		},
		"1Name": {
			ID:          "1Name",
		},
	},
}
