// Code generated by gen-tags. DO NOT EDIT.

package tags

// MIELensTags contains tag definitions from Image::ExifTool::MIE
var MIELensTags = TagTable{
	ModuleName: "MIE",
	Tags: map[string]TagDef{
		"WRITE_GROUP": {
			ID:          "WRITE_GROUP",
			Name:        "MIE-Lens",
		},
		"Make": {
			ID:          "Make",
		},
		"MaxAperture": {
			ID:          "MaxAperture",
		},
		"MaxFocalLength": {
			ID:          "MaxFocalLength",
		},
		"MinFocalLength": {
			ID:          "MinFocalLength",
		},
		"OpticalZoom": {
			ID:          "OpticalZoom",
		},
		"FNumber": {
			ID:          "FNumber",
		},
		"FocalLength": {
			ID:          "FocalLength",
		},
		"MaxApertureAtMaxFocal": {
			ID:          "MaxApertureAtMaxFocal",
		},
		"MinAperture": {
			ID:          "MinAperture",
		},
		"Model": {
			ID:          "Model",
		},
		"SerialNumber": {
			ID:          "SerialNumber",
		},
	},
}
