// Code generated by gen-tags. DO NOT EDIT.

package tags

// MIEMakerNotesTags contains tag definitions from Image::ExifTool::MIE
var MIEMakerNotesTags = TagTable{
	ModuleName: "MIE",
	Tags: map[string]TagDef{
		"WRITE_GROUP": {
			ID:          "WRITE_GROUP",
			Name:        "MIE-MakerNotes",
		},
		"Kodak": {
			ID:          "Kodak",
		},
		"KonicaMinolta": {
			ID:          "KonicaMinolta",
		},
		"Nikon": {
			ID:          "Nikon",
		},
		"Olympus": {
			ID:          "Olympus",
		},
		"Panasonic": {
			ID:          "Panasonic",
		},
		"Ricoh": {
			ID:          "Ricoh",
		},
		"Sony": {
			ID:          "Sony",
		},
		"Casio": {
			ID:          "Casio",
		},
		"FujiFilm": {
			ID:          "FujiFilm",
		},
		"Pentax": {
			ID:          "Pentax",
		},
		"Sigma": {
			ID:          "Sigma",
		},
	},
}
