// Code generated by gen-tags. DO NOT EDIT.

package tags

// MIECanonTags contains tag definitions from Image::ExifTool::MIE
var MIECanonTags = TagTable{
	ModuleName: "MIE",
	Tags: map[string]TagDef{
		"WRITE_GROUP": {
			ID:          "WRITE_GROUP",
			Name:        "MIE-Canon",
		},
	},
}
