// Code generated by gen-tags. DO NOT EDIT.

package tags

// MIFFMainTags contains tag definitions from Image::ExifTool::MIFF
var MIFFMainTags = TagTable{
	ModuleName: "MIFF",
	Tags: map[string]TagDef{
		"colorspace": {
			ID:          "colorspace",
			Name:        "ColorSpace",
		},
		"scene": {
			ID:          "scene",
			Name:        "Scene",
		},
		"border-color": {
			ID:          "border-color",
			Name:        "BorderColor",
		},
		"matt-color": {
			ID:          "matt-color",
			Name:        "MattColor",
		},
		"compression": {
			ID:          "compression",
			Name:        "Compression",
		},
		"packets": {
			ID:          "packets",
			Name:        "Packets",
		},
		"red-primary": {
			ID:          "red-primary",
			Name:        "RedPrimary",
		},
		"resolution": {
			ID:          "resolution",
			Name:        "Resolution",
		},
		"units": {
			ID:          "units",
			Name:        "Units",
		},
		"colors": {
			ID:          "colors",
			Name:        "Colors",
		},
		"green-primary": {
			ID:          "green-primary",
			Name:        "GreenPrimary",
		},
		"label": {
			ID:          "label",
			Name:        "Label",
		},
		"matte": {
			ID:          "matte",
			Name:        "Matte",
		},
		"dispose": {
			ID:          "dispose",
			Name:        "Dispose",
		},
		"montage": {
			ID:          "montage",
			Name:        "Montage",
		},
		"rows": {
			ID:          "rows",
			Name:        "ImageHeight",
		},
		"blue-primary": {
			ID:          "blue-primary",
			Name:        "BluePrimary",
		},
		"depth": {
			ID:          "depth",
			Name:        "Depth",
		},
		"page": {
			ID:          "page",
			Name:        "Page",
		},
		"rendering-intent": {
			ID:          "rendering-intent",
			Name:        "RenderingIntent",
		},
		"white-point": {
			ID:          "white-point",
			Name:        "WhitePoint",
		},
		"class": {
			ID:          "class",
			Name:        "Class",
		},
		"columns": {
			ID:          "columns",
			Name:        "ImageWidth",
		},
		"gamma": {
			ID:          "gamma",
			Name:        "Gamma",
		},
		"id": {
			ID:          "id",
			Name:        "ID",
		},
		"signature": {
			ID:          "signature",
			Name:        "Signature",
		},
		"background-color": {
			ID:          "background-color",
			Name:        "BackgroundColor",
		},
		"delay": {
			ID:          "delay",
			Name:        "Delay",
		},
		"iterations": {
			ID:          "iterations",
			Name:        "Iterations",
		},
	},
}
