// Code generated by gen-tags. DO NOT EDIT.

package tags

// MinoltaISInfoA100Tags contains tag definitions from Image::ExifTool::Minolta
var MinoltaISInfoA100Tags = TagTable{
	ModuleName: "Minolta",
	Tags: map[string]TagDef{
		"WRITABLE": {
			ID:          "WRITABLE",
		},
		"PRIORITY": {
			ID:          "PRIORITY",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
	},
}
