// Code generated by gen-tags. DO NOT EDIT.

package tags

// MinoltaCameraSettings5DTags contains tag definitions from Image::ExifTool::Minolta
var MinoltaCameraSettings5DTags = TagTable{
	ModuleName: "Minolta",
	Tags: map[string]TagDef{
		"0x37": {
			ID:          "0x37",
			Name:        "FreeMemoryCardImages",
		},
		"0x54": {
			ID:          "0x54",
			Name:        "FreeMemoryCardImages",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"WRITABLE": {
			ID:          "WRITABLE",
		},
		"PRIORITY": {
			ID:          "PRIORITY",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int16u",
		},
	},
}
