// Code generated by gen-tags. DO NOT EDIT.

package tags

// MinoltaminoltaSceneModeTags contains tag definitions from Image::ExifTool::Minolta
var MinoltaminoltaSceneModeTags = TagTable{
	ModuleName: "Minolta",
	Tags: map[string]TagDef{
		"27": {
			ID:          "27",
		},
		"0xFFFF": {
			ID:          "0xFFFF",
		},
		"8": {
			ID:          "8",
			Name:        "Macro",
		},
		"18": {
			ID:          "18",
		},
		"19": {
			ID:          "19",
		},
		"20": {
			ID:          "20",
		},
		"24": {
			ID:          "24",
		},
		"26": {
			ID:          "26",
		},
		"33": {
			ID:          "33",
		},
		"3": {
			ID:          "3",
			Name:        "Night Scene",
		},
		"4": {
			ID:          "4",
			Name:        "Sunset",
		},
		"9": {
			ID:          "9",
			Name:        "Super Macro",
		},
		"17": {
			ID:          "17",
			Name:        "Night View/Portrait",
		},
		"21": {
			ID:          "21",
		},
		"25": {
			ID:          "25",
		},
		"28": {
			ID:          "28",
		},
		"2": {
			ID:          "2",
			Name:        "Text",
		},
		"6": {
			ID:          "6",
			Name:        "Landscape",
		},
		"16": {
			ID:          "16",
		},
		"23": {
			ID:          "23",
		},
		"0": {
			ID:          "0",
			Name:        "Standard",
		},
		"1": {
			ID:          "1",
			Name:        "Portrait",
		},
		"5": {
			ID:          "5",
			Name:        "Sports",
		},
		"7": {
			ID:          "7",
		},
		"22": {
			ID:          "22",
			Name:        "Auto+",
		},
	},
}
