// Code generated by gen-tags. DO NOT EDIT.

package tags

// MinoltaminoltaColorModeTags contains tag definitions from Image::ExifTool::Minolta
var MinoltaminoltaColorModeTags = TagTable{
	ModuleName: "Minolta",
	Tags: map[string]TagDef{
		"1": {
			ID:          "1",
			Name:        "Black & White",
		},
		"9": {
			ID:          "9",
		},
		"17": {
			ID:          "17",
		},
		"0x84": {
			ID:          "0x84",
			Name:        "Embed Adobe RGB",
		},
		"13": {
			ID:          "13",
			Name:        "Natural sRGB",
		},
		"14": {
			ID:          "14",
			Name:        "Natural+ sRGB",
		},
		"15": {
			ID:          "15",
		},
		"2": {
			ID:          "2",
			Name:        "Vivid color",
		},
		"3": {
			ID:          "3",
			Name:        "Solarization",
		},
		"4": {
			ID:          "4",
			Name:        "Adobe RGB",
		},
		"5": {
			ID:          "5",
		},
		"12": {
			ID:          "12",
		},
		"16": {
			ID:          "16",
		},
		"18": {
			ID:          "18",
		},
		"0": {
			ID:          "0",
			Name:        "Natural color",
		},
	},
}
