// Code generated by gen-tags. DO NOT EDIT.

package tags

// MinoltaMOV1Tags contains tag definitions from Image::ExifTool::Minolta
var MinoltaMOV1Tags = TagTable{
	ModuleName: "Minolta",
	Tags: map[string]TagDef{
	},
}
