// Code generated by gen-tags. DO NOT EDIT.

package tags

// MinoltaCameraSettingsA100Tags contains tag definitions from Image::ExifTool::Minolta
var MinoltaCameraSettingsA100Tags = TagTable{
	ModuleName: "Minolta",
	Tags: map[string]TagDef{
		"WRITABLE": {
			ID:          "WRITABLE",
		},
		"PRIORITY": {
			ID:          "PRIORITY",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int16u",
		},
		"0x32": {
			ID:          "0x32",
		},
		"0x36": {
			ID:          "0x36",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"0x34": {
			ID:          "0x34",
		},
		"0x35": {
			ID:          "0x35",
		},
	},
}
