// Code generated by gen-tags. DO NOT EDIT.

package tags

// MinoltaminoltaTeleconvertersTags contains tag definitions from Image::ExifTool::Minolta
var MinoltaminoltaTeleconvertersTags = TagTable{
	ModuleName: "Minolta",
	Tags: map[string]TagDef{
		"0x05": {
			ID:          "0x05",
		},
		"0x50": {
			ID:          "0x50",
			Name:        "Minolta AF 2x APO II",
		},
		"0x60": {
			ID:          "0x60",
		},
		"0x88": {
			ID:          "0x88",
			Name:        "Minolta/Sony AF 1.4x APO (D)",
		},
		"0x00": {
			ID:          "0x00",
			Name:        "None",
		},
		"0x04": {
			ID:          "0x04",
		},
		"0x48": {
			ID:          "0x48",
			Name:        "Minolta/Sony AF 2x APO (D)",
		},
		"0x90": {
			ID:          "0x90",
			Name:        "Minolta AF 1.4x APO II",
		},
		"0xA0": {
			ID:          "0xA0",
		},
	},
}
