// Code generated by gen-tags. DO NOT EDIT.

package tags

// MinoltametabonesIDTags contains tag definitions from Image::ExifTool::Minolta
var MinoltametabonesIDTags = TagTable{
	ModuleName: "Minolta",
	Tags: map[string]TagDef{
		"0xEF00": {
			ID:          "0xEF00",
		},
		"0x7700": {
			ID:          "0x7700",
		},
		"0x7900": {
			ID:          "0x7900",
		},
		"0xBC00": {
			ID:          "0xBC00",
		},
		"0xBD00": {
			ID:          "0xBD00",
		},
		"0xBE00": {
			ID:          "0xBE00",
		},
		"0xCC00": {
			ID:          "0xCC00",
		},
		"0xF000": {
			ID:          "0xF000",
		},
		"0xF100": {
			ID:          "0xF100",
		},
		"0xFF00": {
			ID:          "0xFF00",
		},
		"0x7800": {
			ID:          "0x7800",
		},
		"0x8700": {
			ID:          "0x8700",
		},
	},
}
