// Code generated by gen-tags. DO NOT EDIT.

package tags

// MISBSecurityTags contains tag definitions from Image::ExifTool::MISB
var MISBSecurityTags = TagTable{
	ModuleName: "MISB",
	Tags: map[string]TagDef{
		"8": {
			ID:          "8",
		},
		"11": {
			ID:          "11",
			Name:        "ClassificationAndMarkingSystem",
		},
		"14": {
			ID:          "14",
		},
		"15": {
			ID:          "15",
			Name:        "UMID",
		},
		"6": {
			ID:          "6",
		},
		"9": {
			ID:          "9",
		},
		"17": {
			ID:          "17",
			Name:        "TransportStreamID",
		},
		"22": {
			ID:          "22",
		},
		"3": {
			ID:          "3",
		},
		"4": {
			ID:          "4",
			Name:        "SecuritySCI-SHIInformation",
		},
		"7": {
			ID:          "7",
		},
		"13": {
			ID:          "13",
		},
		"16": {
			ID:          "16",
			Name:        "StreamID",
		},
		"5": {
			ID:          "5",
		},
		"21": {
			ID:          "21",
			Name:        "ItemDesignatorID",
		},
	},
}
