// Code generated by gen-tags. DO NOT EDIT.

package tags

// MNGClipObjectsTags contains tag definitions from Image::ExifTool::MNG
var MNGClipObjectsTags = TagTable{
	ModuleName: "MNG",
	Tags: map[string]TagDef{
	},
}
