// Code generated by gen-tags. DO NOT EDIT.

package tags

// MNGJNGHeaderTags contains tag definitions from Image::ExifTool::MNG
var MNGJNGHeaderTags = TagTable{
	ModuleName: "MNG",
	Tags: map[string]TagDef{
		"9": {
			ID:          "9",
			Name:        "BitDepth",
		},
		"12": {
			ID:          "12",
			Name:        "AlphaBitDepth",
		},
	},
}
