// Code generated by gen-tags. DO NOT EDIT.

package tags

// MNGFramePriorityTags contains tag definitions from Image::ExifTool::MNG
var MNGFramePriorityTags = TagTable{
	ModuleName: "MNG",
	Tags: map[string]TagDef{
		"2": {
			ID:          "2",
			Name:        "Priority",
		},
	},
}
