// Code generated by gen-tags. DO NOT EDIT.

package tags

// MNGExportImageTags contains tag definitions from Image::ExifTool::MNG
var MNGExportImageTags = TagTable{
	ModuleName: "MNG",
	Tags: map[string]TagDef{
	},
}
