// Code generated by gen-tags. DO NOT EDIT.

package tags

// MNGBasisObjectTags contains tag definitions from Image::ExifTool::MNG
var MNGBasisObjectTags = TagTable{
	ModuleName: "MNG",
	Tags: map[string]TagDef{
		"8": {
			ID:          "8",
			Name:        "BitDepth",
		},
		"26": {
			ID:          "26",
			Name:        "Viewable",
		},
	},
}
