// Code generated by gen-tags. DO NOT EDIT.

package tags

// MotorolaMainTags contains tag definitions from Image::ExifTool::Motorola
var MotorolaMainTags = TagTable{
	ModuleName: "Motorola",
	Tags: map[string]TagDef{
		"0x5501": {
			ID:          "0x5501",
		},
		"0x64D0": {
			ID:          "0x64D0",
		},
		"0x665E": {
			ID:          "0x665E",
		},
		"0x6705": {
			ID:          "0x6705",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"WRITABLE": {
			ID:          "WRITABLE",
		},
		"0x5500": {
			ID:          "0x5500",
		},
	},
}
