// Code generated by gen-tags. DO NOT EDIT.

package tags

// MPEGCompositeTags contains tag definitions from Image::ExifTool::MPEG
var MPEGCompositeTags = TagTable{
	ModuleName: "MPEG",
	Tags: map[string]TagDef{
	},
}
