// Code generated by gen-tags. DO NOT EDIT.

package tags

// MPFCompositeTags contains tag definitions from Image::ExifTool::MPF
var MPFCompositeTags = TagTable{
	ModuleName: "MPF",
	Tags: map[string]TagDef{
	},
}
