// Code generated by gen-tags. DO NOT EDIT.

package tags

// MWGCollectionsTags contains tag definitions from Image::ExifTool::MWG
var MWGCollectionsTags = TagTable{
	ModuleName: "MWG",
	Tags: map[string]TagDef{
		"NAMESPACE": {
			ID:          "NAMESPACE",
			Name:        "mwg-coll",
		},
	},
}
