// Code generated by gen-tags. DO NOT EDIT.

package tags

// MXFHeaderTags contains tag definitions from Image::ExifTool::MXF
var MXFHeaderTags = TagTable{
	ModuleName: "MXF",
	Tags: map[string]TagDef{
	},
}
