// Code generated by gen-tags. DO NOT EDIT.

package tags

// NikonMenuInfoZ8Tags contains tag definitions from Image::ExifTool::Nikon
var NikonMenuInfoZ8Tags = TagTable{
	ModuleName: "Nikon",
	Tags: map[string]TagDef{
		"IS_SUBDIR": {
			ID:          "IS_SUBDIR",
		},
	},
}
