// Code generated by gen-tags. DO NOT EDIT.

package tags

// NikonNEFInfoTags contains tag definitions from Image::ExifTool::Nikon
var NikonNEFInfoTags = TagTable{
	ModuleName: "Nikon",
	Tags: map[string]TagDef{
	},
}
