// Code generated by gen-tags. DO NOT EDIT.

package tags

// NikonShotInfoD4Tags contains tag definitions from Image::ExifTool::Nikon
var NikonShotInfoD4Tags = TagTable{
	ModuleName: "Nikon",
	Tags: map[string]TagDef{
		"IS_SUBDIR": {
			ID:          "IS_SUBDIR",
		},
		"WRITABLE": {
			ID:          "WRITABLE",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
	},
}
