// Code generated by gen-tags. DO NOT EDIT.

package tags

// NikonBracketingInfoD810Tags contains tag definitions from Image::ExifTool::Nikon
var NikonBracketingInfoD810Tags = TagTable{
	ModuleName: "Nikon",
	Tags: map[string]TagDef{
	},
}
