// Code generated by gen-tags. DO NOT EDIT.

package tags

// NikonIntervalInfoZ7IITags contains tag definitions from Image::ExifTool::Nikon
var NikonIntervalInfoZ7IITags = TagTable{
	ModuleName: "Nikon",
	Tags: map[string]TagDef{
		"DATAMEMBER": {
			ID:          "DATAMEMBER",
		},
	},
}
