// Code generated by gen-tags. DO NOT EDIT.

package tags

// NikonMakerNotes0x51Tags contains tag definitions from Image::ExifTool::Nikon
var NikonMakerNotes0x51Tags = TagTable{
	ModuleName: "Nikon",
	Tags: map[string]TagDef{
	},
}
