// Code generated by gen-tags. DO NOT EDIT.

package tags

// NikonLensData0800Tags contains tag definitions from Image::ExifTool::Nikon
var NikonLensData0800Tags = TagTable{
	ModuleName: "Nikon",
	Tags: map[string]TagDef{
		"DATAMEMBER": {
			ID:          "DATAMEMBER",
		},
	},
}
