// Code generated by gen-tags. DO NOT EDIT.

package tags

// NikonCaptureDLightingHQTags contains tag definitions from Image::ExifTool::NikonCapture
var NikonCaptureDLightingHQTags = TagTable{
	ModuleName: "NikonCapture",
	Tags: map[string]TagDef{
		"1": {
			ID:          "1",
			Name:        "D-LightingHQHighlight",
		},
		"2": {
			ID:          "2",
			Name:        "D-LightingHQColorBoost",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"WRITABLE": {
			ID:          "WRITABLE",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int32u",
		},
		"0": {
			ID:          "0",
			Name:        "D-LightingHQShadow",
		},
	},
}
