// Code generated by gen-tags. DO NOT EDIT.

package tags

// NikonLensData01Tags contains tag definitions from Image::ExifTool::Nikon
var NikonLensData01Tags = TagTable{
	ModuleName: "Nikon",
	Tags: map[string]TagDef{
		"0x11": {
			ID:          "0x11",
		},
	},
}
