// Code generated by gen-tags. DO NOT EDIT.

package tags

// NikonCaptureDLightingHSTags contains tag definitions from Image::ExifTool::NikonCapture
var NikonCaptureDLightingHSTags = TagTable{
	ModuleName: "NikonCapture",
	Tags: map[string]TagDef{
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"WRITABLE": {
			ID:          "WRITABLE",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int32u",
		},
		"0": {
			ID:          "0",
			Name:        "D-LightingHSAdjustment",
		},
		"1": {
			ID:          "1",
			Name:        "D-LightingHSColorBoost",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
	},
}
