// Code generated by gen-tags. DO NOT EDIT.

package tags

// NikonAVITags contains tag definitions from Image::ExifTool::Nikon
var NikonAVITags = TagTable{
	ModuleName: "Nikon",
	Tags: map[string]TagDef{
	},
}
