// Code generated by gen-tags. DO NOT EDIT.

package tags

// NikonMenuSettingsD850Tags contains tag definitions from Image::ExifTool::Nikon
var NikonMenuSettingsD850Tags = TagTable{
	ModuleName: "Nikon",
	Tags: map[string]TagDef{
	},
}
