// Code generated by gen-tags. DO NOT EDIT.

package tags

// NikonastTags contains tag definitions from Image::ExifTool::Nikon
var NikonastTags = TagTable{
	ModuleName: "Nikon",
	Tags: map[string]TagDef{
		"GPSLatitude": {
			ID:          "GPSLatitude",
		},
		"GPSLongitude": {
			ID:          "GPSLongitude",
		},
		"GPSMapDatum": {
			ID:          "GPSMapDatum",
		},
		"NAMESPACE": {
			ID:          "NAMESPACE",
			Name:        "ast",
		},
		"about": {
			ID:          "about",
		},
		"version": {
			ID:          "version",
		},
		"GPSVersionID": {
			ID:          "GPSVersionID",
		},
	},
}
