// Code generated by gen-tags. DO NOT EDIT.

package tags

// NikonHDRInfoTags contains tag definitions from Image::ExifTool::Nikon
var NikonHDRInfoTags = TagTable{
	ModuleName: "Nikon",
	Tags: map[string]TagDef{
	},
}
