// Code generated by gen-tags. DO NOT EDIT.

package tags

// NikonOrientationInfoTags contains tag definitions from Image::ExifTool::Nikon
var NikonOrientationInfoTags = TagTable{
	ModuleName: "Nikon",
	Tags: map[string]TagDef{
	},
}
