// Code generated by gen-tags. DO NOT EDIT.

package tags

// NikonCustomSettingsD700Tags contains tag definitions from Image::ExifTool::NikonCustom
var NikonCustomSettingsD700Tags = TagTable{
	ModuleName: "NikonCustom",
	Tags: map[string]TagDef{
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"WRITABLE": {
			ID:          "WRITABLE",
		},
		"DATAMEMBER": {
			ID:          "DATAMEMBER",
		},
	},
}
