// Code generated by gen-tags. DO NOT EDIT.

package tags

// NikonNCDBTags contains tag definitions from Image::ExifTool::Nikon
var NikonNCDBTags = TagTable{
	ModuleName: "Nikon",
	Tags: map[string]TagDef{
	},
}
