// Code generated by gen-tags. DO NOT EDIT.

package tags

// NikonROCTags contains tag definitions from Image::ExifTool::Nikon
var NikonROCTags = TagTable{
	ModuleName: "Nikon",
	Tags: map[string]TagDef{
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int32u",
		},
	},
}
