// Code generated by gen-tags. DO NOT EDIT.

package tags

// NikonMenuInfoZ7IITags contains tag definitions from Image::ExifTool::Nikon
var NikonMenuInfoZ7IITags = TagTable{
	ModuleName: "Nikon",
	Tags: map[string]TagDef{
		"IS_SUBDIR": {
			ID:          "IS_SUBDIR",
		},
	},
}
