// Code generated by gen-tags. DO NOT EDIT.

package tags

// NikonISOAutoInfoD810Tags contains tag definitions from Image::ExifTool::Nikon
var NikonISOAutoInfoD810Tags = TagTable{
	ModuleName: "Nikon",
	Tags: map[string]TagDef{
	},
}
