// Code generated by gen-tags. DO NOT EDIT.

package tags

// NikonType2Tags contains tag definitions from Image::ExifTool::Nikon
var NikonType2Tags = TagTable{
	ModuleName: "Nikon",
	Tags: map[string]TagDef{
		"0x0008": {
			ID:          "0x0008",
			Name:        "Focus",
		},
		"0x000B": {
			ID:          "0x000B",
			Name:        "Converter",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"WRITABLE": {
			ID:          "WRITABLE",
		},
		"0x0003": {
			ID:          "0x0003",
			Name:        "Quality",
		},
		"0x0005": {
			ID:          "0x0005",
			Name:        "ImageAdjustment",
		},
		"0x000A": {
			ID:          "0x000A",
			Name:        "DigitalZoom",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"0x0004": {
			ID:          "0x0004",
			Name:        "ColorMode",
		},
		"0x0006": {
			ID:          "0x0006",
			Name:        "CCDSensitivity",
		},
		"0x0007": {
			ID:          "0x0007",
			Name:        "WhiteBalance",
		},
	},
}
