// Code generated by gen-tags. DO NOT EDIT.

package tags

// NikonCaptureCropDataTags contains tag definitions from Image::ExifTool::NikonCapture
var NikonCaptureCropDataTags = TagTable{
	ModuleName: "NikonCapture",
	Tags: map[string]TagDef{
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int8u",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"WRITABLE": {
			ID:          "WRITABLE",
		},
	},
}
