// Code generated by gen-tags. DO NOT EDIT.

package tags

// NikonPreviewIFDTags contains tag definitions from Image::ExifTool::Nikon
var NikonPreviewIFDTags = TagTable{
	ModuleName: "Nikon",
	Tags: map[string]TagDef{
		"PrintConv": {
			ID:          "PrintConv",
			Name:        "sprintf(\"%.1f mm\",$val)",
		},
		"PrintConvInv": {
			ID:          "PrintConvInv",
			Name:        "$val=~s/\\s*mm$//;$val",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"0x11A": {
			ID:          "0x11A",
			Name:        "XResolution",
		},
		"0x11B": {
			ID:          "0x11B",
			Name:        "YResolution",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"ValueConv": {
			ID:          "ValueConv",
			Name:        "5 * 2**($val/24)",
		},
		"ValueConvInv": {
			ID:          "ValueConvInv",
			Name:        "$val>0 ? 24*log($val/5)/log(2) : 0",
		},
	},
}
