// Code generated by gen-tags. DO NOT EDIT.

package tags

// NikonIntervalInfoD6Tags contains tag definitions from Image::ExifTool::Nikon
var NikonIntervalInfoD6Tags = TagTable{
	ModuleName: "Nikon",
	Tags: map[string]TagDef{
		"DATAMEMBER": {
			ID:          "DATAMEMBER",
		},
	},
}
