// Code generated by gen-tags. DO NOT EDIT.

package tags

// NikonFaceDetectTags contains tag definitions from Image::ExifTool::Nikon
var NikonFaceDetectTags = TagTable{
	ModuleName: "Nikon",
	Tags: map[string]TagDef{
		"DATAMEMBER": {
			ID:          "DATAMEMBER",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int16u",
		},
	},
}
