// Code generated by gen-tags. DO NOT EDIT.

package tags

// NikonCustomSettingsD500Tags contains tag definitions from Image::ExifTool::Nikon
var NikonCustomSettingsD500Tags = TagTable{
	ModuleName: "Nikon",
	Tags: map[string]TagDef{
		"IS_SUBDIR": {
			ID:          "IS_SUBDIR",
		},
	},
}
