// Code generated by gen-tags. DO NOT EDIT.

package tags

// NikonMenuSettingsZ7IITags contains tag definitions from Image::ExifTool::Nikon
var NikonMenuSettingsZ7IITags = TagTable{
	ModuleName: "Nikon",
	Tags: map[string]TagDef{
		"584": {
			ID:          "584",
		},
		"326": {
			ID:          "326",
		},
		"348": {
			ID:          "348",
		},
		"502": {
			ID:          "502",
		},
		"506": {
			ID:          "506",
		},
		"DATAMEMBER": {
			ID:          "DATAMEMBER",
		},
		"346": {
			ID:          "346",
		},
		"504": {
			ID:          "504",
		},
		"568": {
			ID:          "568",
		},
		"572": {
			ID:          "572",
		},
		"574": {
			ID:          "574",
		},
	},
}
