// Code generated by gen-tags. DO NOT EDIT.

package tags

// NikonPictureControl2Tags contains tag definitions from Image::ExifTool::Nikon
var NikonPictureControl2Tags = TagTable{
	ModuleName: "Nikon",
	Tags: map[string]TagDef{
	},
}
