// Code generated by gen-tags. DO NOT EDIT.

package tags

// NikonLensData0402Tags contains tag definitions from Image::ExifTool::Nikon
var NikonLensData0402Tags = TagTable{
	ModuleName: "Nikon",
	Tags: map[string]TagDef{
	},
}
