// Code generated by gen-tags. DO NOT EDIT.

package tags

// NikonVignetteInfoTags contains tag definitions from Image::ExifTool::Nikon
var NikonVignetteInfoTags = TagTable{
	ModuleName: "Nikon",
	Tags: map[string]TagDef{
	},
}
