// Code generated by gen-tags. DO NOT EDIT.

package tags

// NikonCaptureUnsharpDataTags contains tag definitions from Image::ExifTool::NikonCapture
var NikonCaptureUnsharpDataTags = TagTable{
	ModuleName: "NikonCapture",
	Tags: map[string]TagDef{
		"79": {
			ID:          "79",
		},
		"106": {
			ID:          "106",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"WRITABLE": {
			ID:          "WRITABLE",
		},
		"54": {
			ID:          "54",
			Name:        "Unsharp2Threshold",
		},
		"104": {
			ID:          "104",
		},
		"0": {
			ID:          "0",
			Name:        "UnsharpCount",
		},
		"19": {
			ID:          "19",
		},
		"25": {
			ID:          "25",
		},
		"27": {
			ID:          "27",
			Name:        "Unsharp1Threshold",
		},
		"50": {
			ID:          "50",
		},
		"73": {
			ID:          "73",
		},
		"77": {
			ID:          "77",
		},
		"81": {
			ID:          "81",
			Name:        "Unsharp3Threshold",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int8u",
		},
		"23": {
			ID:          "23",
		},
		"46": {
			ID:          "46",
		},
		"100": {
			ID:          "100",
		},
		"108": {
			ID:          "108",
			Name:        "Unsharp4Threshold",
		},
		"52": {
			ID:          "52",
		},
	},
}
