// Code generated by gen-tags. DO NOT EDIT.

package tags

// NikonCompositeTags contains tag definitions from Image::ExifTool::Nikon
var NikonCompositeTags = TagTable{
	ModuleName: "Nikon",
	Tags: map[string]TagDef{
	},
}
