// Code generated by gen-tags. DO NOT EDIT.

package tags

// NikonFileInfoTags contains tag definitions from Image::ExifTool::Nikon
var NikonFileInfoTags = TagTable{
	ModuleName: "Nikon",
	Tags: map[string]TagDef{
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int16u",
		},
		"2": {
			ID:          "2",
			Name:        "MemoryCardNumber",
		},
	},
}
