// Code generated by gen-tags. DO NOT EDIT.

package tags

// NikonColorBalanceBTags contains tag definitions from Image::ExifTool::Nikon
var NikonColorBalanceBTags = TagTable{
	ModuleName: "Nikon",
	Tags: map[string]TagDef{
		"0x13F8": {
			ID:          "0x13F8",
		},
		"0x1408": {
			ID:          "0x1408",
		},
		"0x1428": {
			ID:          "0x1428",
		},
		"0x1438": {
			ID:          "0x1438",
		},
		"0x1448": {
			ID:          "0x1448",
		},
		"0x1468": {
			ID:          "0x1468",
		},
		"0x1478": {
			ID:          "0x1478",
		},
		"0x13E8": {
			ID:          "0x13E8",
		},
	},
}
