// Code generated by gen-tags. DO NOT EDIT.

package tags

// NikonsdcTags contains tag definitions from Image::ExifTool::Nikon
var NikonsdcTags = TagTable{
	ModuleName: "Nikon",
	Tags: map[string]TagDef{
		"NAMESPACE": {
			ID:          "NAMESPACE",
			Name:        "sdc",
		},
		"about": {
			ID:          "about",
		},
		"version": {
			ID:          "version",
		},
		"appversion": {
			ID:          "appversion",
		},
		"appname": {
			ID:          "appname",
		},
	},
}
