// Code generated by gen-tags. DO NOT EDIT.

package tags

// NikonLocationInfoTags contains tag definitions from Image::ExifTool::Nikon
var NikonLocationInfoTags = TagTable{
	ModuleName: "Nikon",
	Tags: map[string]TagDef{
		"DATAMEMBER": {
			ID:          "DATAMEMBER",
		},
		"8": {
			ID:          "8",
		},
	},
}
