// Code generated by gen-tags. DO NOT EDIT.

package tags

// NikonHDRInfo2Tags contains tag definitions from Image::ExifTool::Nikon
var NikonHDRInfo2Tags = TagTable{
	ModuleName: "Nikon",
	Tags: map[string]TagDef{
	},
}
