// Code generated by gen-tags. DO NOT EDIT.

package tags

// OggMainTags contains tag definitions from Image::ExifTool::Ogg
var OggMainTags = TagTable{
	ModuleName: "Ogg",
	Tags: map[string]TagDef{
		"vorbis": {
			ID:          "vorbis",
		},
		"theora": {
			ID:          "theora",
		},
		"Opus": {
			ID:          "Opus",
		},
		"FLAC": {
			ID:          "FLAC",
		},
		"ID3": {
			ID:          "ID3",
		},
	},
}
