// Code generated by gen-tags. DO NOT EDIT.

package tags

// OlympusThumbnailTags contains tag definitions from Image::ExifTool::Olympus
var OlympusThumbnailTags = TagTable{
	ModuleName: "Olympus",
	Tags: map[string]TagDef{
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int32u",
		},
		"1": {
			ID:          "1",
			Name:        "ThumbnailWidth",
		},
		"2": {
			ID:          "2",
			Name:        "ThumbnailHeight",
		},
		"3": {
			ID:          "3",
			Name:        "ThumbnailLength",
		},
		"4": {
			ID:          "4",
		},
	},
}
