// Code generated by gen-tags. DO NOT EDIT.

package tags

// OlympusRawDevelopment2Tags contains tag definitions from Image::ExifTool::Olympus
var OlympusRawDevelopment2Tags = TagTable{
	ModuleName: "Olympus",
	Tags: map[string]TagDef{
		"WRITABLE": {
			ID:          "WRITABLE",
		},
		"0x100": {
			ID:          "0x100",
		},
		"0x102": {
			ID:          "0x102",
		},
		"0x105": {
			ID:          "0x105",
		},
		"0x10E": {
			ID:          "0x10E",
		},
		"0x10F": {
			ID:          "0x10F",
		},
		"0x113": {
			ID:          "0x113",
		},
		"0x119": {
			ID:          "0x119",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"0x104": {
			ID:          "0x104",
		},
		"0x107": {
			ID:          "0x107",
		},
		"0x108": {
			ID:          "0x108",
		},
		"0x106": {
			ID:          "0x106",
		},
		"0x10D": {
			ID:          "0x10D",
		},
		"0x120": {
			ID:          "0x120",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"0x103": {
			ID:          "0x103",
		},
		"0x112": {
			ID:          "0x112",
		},
	},
}
