// Code generated by gen-tags. DO NOT EDIT.

package tags

// OlympusscrnTags contains tag definitions from Image::ExifTool::Olympus
var OlympusscrnTags = TagTable{
	ModuleName: "Olympus",
	Tags: map[string]TagDef{
	},
}
