// Code generated by gen-tags. DO NOT EDIT.

package tags

// OlympusTextInfoTags contains tag definitions from Image::ExifTool::Olympus
var OlympusTextInfoTags = TagTable{
	ModuleName: "Olympus",
	Tags: map[string]TagDef{
		"Resolution": {
			ID:          "Resolution",
		},
	},
}
