// Code generated by gen-tags. DO NOT EDIT.

package tags

// OlympusCameraSettingsTags contains tag definitions from Image::ExifTool::Olympus
var OlympusCameraSettingsTags = TagTable{
	ModuleName: "Olympus",
	Tags: map[string]TagDef{
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"WRITABLE": {
			ID:          "WRITABLE",
		},
		"0x203": {
			ID:          "0x203",
		},
		"0x401": {
			ID:          "0x401",
		},
		"0x50D": {
			ID:          "0x50D",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
	},
}
