// Code generated by gen-tags. DO NOT EDIT.

package tags

// OlympusOLYM2Tags contains tag definitions from Image::ExifTool::Olympus
var OlympusOLYM2Tags = TagTable{
	ModuleName: "Olympus",
	Tags: map[string]TagDef{
	},
}
