// Code generated by gen-tags. DO NOT EDIT.

package tags

// OlympusFETagsTags contains tag definitions from Image::ExifTool::Olympus
var OlympusFETagsTags = TagTable{
	ModuleName: "Olympus",
	Tags: map[string]TagDef{
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
	},
}
