// Code generated by gen-tags. DO NOT EDIT.

package tags

// OlympusEquipmentTags contains tag definitions from Image::ExifTool::Olympus
var OlympusEquipmentTags = TagTable{
	ModuleName: "Olympus",
	Tags: map[string]TagDef{
		"0x1003": {
			ID:          "0x1003",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"0x203": {
			ID:          "0x203",
		},
		"0x207": {
			ID:          "0x207",
		},
		"0x303": {
			ID:          "0x303",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"WRITABLE": {
			ID:          "WRITABLE",
		},
		"0x208": {
			ID:          "0x208",
		},
		"0x302": {
			ID:          "0x302",
		},
	},
}
