// Code generated by gen-tags. DO NOT EDIT.

package tags

// OlympusDSSTags contains tag definitions from Image::ExifTool::Olympus
var OlympusDSSTags = TagTable{
	ModuleName: "Olympus",
	Tags: map[string]TagDef{
		"12": {
			ID:          "12",
		},
	},
}
