// Code generated by gen-tags. DO NOT EDIT.

package tags

// OlympusRawInfoTags contains tag definitions from Image::ExifTool::Olympus
var OlympusRawInfoTags = TagTable{
	ModuleName: "Olympus",
	Tags: map[string]TagDef{
		"0x2000": {
			ID:          "0x2000",
		},
		"0x110": {
			ID:          "0x110",
		},
		"0x120": {
			ID:          "0x120",
		},
		"0x123": {
			ID:          "0x123",
		},
		"0x2002": {
			ID:          "0x2002",
		},
		"0x100": {
			ID:          "0x100",
		},
		"0x310": {
			ID:          "0x310",
		},
		"0x612": {
			ID:          "0x612",
		},
		"0x1013": {
			ID:          "0x1013",
		},
		"0x2023": {
			ID:          "0x2023",
		},
		"0x124": {
			ID:          "0x124",
		},
		"0x132": {
			ID:          "0x132",
		},
		"0x614": {
			ID:          "0x614",
		},
		"0x2022": {
			ID:          "0x2022",
		},
		"0x121": {
			ID:          "0x121",
		},
		"0x131": {
			ID:          "0x131",
		},
		"0x133": {
			ID:          "0x133",
		},
		"0x613": {
			ID:          "0x613",
		},
		"0x1010": {
			ID:          "0x1010",
		},
		"0x1011": {
			ID:          "0x1011",
		},
		"0x1012": {
			ID:          "0x1012",
		},
		"0x2021": {
			ID:          "0x2021",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"0x615": {
			ID:          "0x615",
		},
		"0x1001": {
			ID:          "0x1001",
		},
		"0x2001": {
			ID:          "0x2001",
		},
		"0x130": {
			ID:          "0x130",
		},
		"0x600": {
			ID:          "0x600",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"0x122": {
			ID:          "0x122",
		},
		"0x311": {
			ID:          "0x311",
		},
		"0x611": {
			ID:          "0x611",
		},
		"0x2010": {
			ID:          "0x2010",
		},
		"0x2020": {
			ID:          "0x2020",
		},
	},
}
