// Code generated by gen-tags. DO NOT EDIT.

package tags

// OlympusMP4Tags contains tag definitions from Image::ExifTool::Olympus
var OlympusMP4Tags = TagTable{
	ModuleName: "Olympus",
	Tags: map[string]TagDef{
	},
}
