// Code generated by gen-tags. DO NOT EDIT.

package tags

// OlympusMovableInfoTags contains tag definitions from Image::ExifTool::Olympus
var OlympusMovableInfoTags = TagTable{
	ModuleName: "Olympus",
	Tags: map[string]TagDef{
	},
}
