// Code generated by gen-tags. DO NOT EDIT.

package tags

// Olympusthmb2Tags contains tag definitions from Image::ExifTool::Olympus
var Olympusthmb2Tags = TagTable{
	ModuleName: "Olympus",
	Tags: map[string]TagDef{
	},
}
