// Code generated by gen-tags. DO NOT EDIT.

package tags

// OlympusMOV3Tags contains tag definitions from Image::ExifTool::Olympus
var OlympusMOV3Tags = TagTable{
	ModuleName: "Olympus",
	Tags: map[string]TagDef{
	},
}
