// Code generated by gen-tags. DO NOT EDIT.

package tags

// OpenEXRMainTags contains tag definitions from Image::ExifTool::OpenEXR
var OpenEXRMainTags = TagTable{
	ModuleName: "OpenEXR",
	Tags: map[string]TagDef{
		"lookModTransform": {
			ID:          "lookModTransform",
		},
		"wrapmodes": {
			ID:          "wrapmodes",
		},
		"displayWindow": {
			ID:          "displayWindow",
		},
		"screenWindowCenter": {
			ID:          "screenWindowCenter",
		},
		"tiles": {
			ID:          "tiles",
		},
		"worldToCamera": {
			ID:          "worldToCamera",
		},
		"comments": {
			ID:          "comments",
		},
		"isoSpeed": {
			ID:          "isoSpeed",
		},
		"owner": {
			ID:          "owner",
		},
		"preview": {
			ID:          "preview",
		},
		"screenWindowWidth": {
			ID:          "screenWindowWidth",
		},
		"timeCode": {
			ID:          "timeCode",
		},
		"type": {
			ID:          "type",
		},
		"version": {
			ID:          "version",
		},
		"aperture": {
			ID:          "aperture",
		},
		"chunkCount": {
			ID:          "chunkCount",
		},
		"adoptedNeutral": {
			ID:          "adoptedNeutral",
		},
		"channels": {
			ID:          "channels",
		},
		"dataWindow": {
			ID:          "dataWindow",
		},
		"keyCode": {
			ID:          "keyCode",
		},
		"multiView": {
			ID:          "multiView",
		},
		"renderingTransform": {
			ID:          "renderingTransform",
		},
		"xDensity": {
			ID:          "xDensity",
		},
		"framesPerSecond": {
			ID:          "framesPerSecond",
		},
		"whiteLuminance": {
			ID:          "whiteLuminance",
		},
		"worldToNDC": {
			ID:          "worldToNDC",
		},
		"name": {
			ID:          "name",
		},
		"_ver": {
			ID:          "_ver",
		},
		"pixelAspectRatio": {
			ID:          "pixelAspectRatio",
		},
		"chromaticities": {
			ID:          "chromaticities",
		},
	},
}
