// Code generated by gen-tags. DO NOT EDIT.

package tags

// OpusMainTags contains tag definitions from Image::ExifTool::Opus
var OpusMainTags = TagTable{
	ModuleName: "Opus",
	Tags: map[string]TagDef{
	},
}
