// Code generated by gen-tags. DO NOT EDIT.

package tags

// PalmEXTHTags contains tag definitions from Image::ExifTool::Palm
var PalmEXTHTags = TagTable{
	ModuleName: "Palm",
	Tags: map[string]TagDef{
		"129": {
			ID:          "129",
			Name:        "KF8CoverURI",
		},
		"200": {
			ID:          "200",
			Name:        "DictionaryShortName",
		},
		"402": {
			ID:          "402",
			Name:        "PublisherLimit",
		},
		"100": {
			ID:          "100",
		},
		"116": {
			ID:          "116",
		},
		"119": {
			ID:          "119",
			Name:        "RetailPriceCurrency",
		},
		"207": {
			ID:          "207",
		},
		"208": {
			ID:          "208",
			Name:        "Watermark",
		},
		"504": {
			ID:          "504",
			Name:        "ASIN2",
		},
		"524": {
			ID:          "524",
			Name:        "Language",
		},
		"2": {
			ID:          "2",
			Name:        "DRMCommerceID",
		},
		"103": {
			ID:          "103",
			Name:        "Description",
		},
		"104": {
			ID:          "104",
			Name:        "ISBN",
		},
		"111": {
			ID:          "111",
			Name:        "BookType",
		},
		"206": {
			ID:          "206",
		},
		"406": {
			ID:          "406",
			Name:        "RentalExpirationDate",
		},
		"1": {
			ID:          "1",
			Name:        "DRMServerID",
		},
		"109": {
			ID:          "109",
		},
		"113": {
			ID:          "113",
			Name:        "ASIN",
		},
		"501": {
			ID:          "501",
		},
		"209": {
			ID:          "209",
			Name:        "Tamper-proofKeys",
		},
		"401": {
			ID:          "401",
		},
		"502": {
			ID:          "502",
			Name:        "LastUpdateTime",
		},
		"503": {
			ID:          "503",
			Name:        "UpdatedTitle",
		},
		"525": {
			ID:          "525",
			Name:        "Alignment",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "string",
		},
		"3": {
			ID:          "3",
			Name:        "DRM_E-BookBaseID",
		},
		"105": {
			ID:          "105",
		},
		"112": {
			ID:          "112",
			Name:        "Source",
		},
		"115": {
			ID:          "115",
		},
		"101": {
			ID:          "101",
			Name:        "Publisher",
		},
		"118": {
			ID:          "118",
			Name:        "RetailPrice",
		},
		"125": {
			ID:          "125",
		},
		"405": {
			ID:          "405",
		},
		"102": {
			ID:          "102",
			Name:        "Imprint",
		},
		"205": {
			ID:          "205",
		},
		"535": {
			ID:          "535",
			Name:        "CreatorBuildNumber2",
		},
		"107": {
			ID:          "107",
			Name:        "Review",
		},
		"108": {
			ID:          "108",
			Name:        "Contributor",
		},
		"110": {
			ID:          "110",
			Name:        "SubjectCode",
		},
		"114": {
			ID:          "114",
			Name:        "BookVersion",
		},
		"117": {
			ID:          "117",
			Name:        "Adult",
		},
	},
}
