// Code generated by gen-tags. DO NOT EDIT.

package tags

// PalmMainTags contains tag definitions from Image::ExifTool::Palm
var PalmMainTags = TagTable{
	ModuleName: "Palm",
	Tags: map[string]TagDef{
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int32u",
		},
		"0": {
			ID:          "0",
		},
		"12": {
			ID:          "12",
			Name:        "ModificationNumber",
		},
	},
}
