// Code generated by gen-tags. DO NOT EDIT.

package tags

// PanasonicLeica4Tags contains tag definitions from Image::ExifTool::Panasonic
var PanasonicLeica4Tags = TagTable{
	ModuleName: "Panasonic",
	Tags: map[string]TagDef{
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"WRITABLE": {
			ID:          "WRITABLE",
		},
	},
}
