// Code generated by gen-tags. DO NOT EDIT.

package tags

// PanasonicLeica2Tags contains tag definitions from Image::ExifTool::Panasonic
var PanasonicLeica2Tags = TagTable{
	ModuleName: "Panasonic",
	Tags: map[string]TagDef{
		"0x331": {
			ID:          "0x331",
		},
		"0x321": {
			ID:          "0x321",
		},
		"0x332": {
			ID:          "0x332",
		},
		"0x333": {
			ID:          "0x333",
		},
		"0x340": {
			ID:          "0x340",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"WRITABLE": {
			ID:          "WRITABLE",
		},
		"0x322": {
			ID:          "0x322",
		},
		"0x323": {
			ID:          "0x323",
		},
		"0x324": {
			ID:          "0x324",
		},
		"0x330": {
			ID:          "0x330",
		},
	},
}
