// Code generated by gen-tags. DO NOT EDIT.

package tags

// PanasonicleicaLensTypesTags contains tag definitions from Image::ExifTool::Panasonic
var PanasonicleicaLensTypesTags = TagTable{
	ModuleName: "Panasonic",
	Tags: map[string]TagDef{
		"39": {
			ID:          "39",
		},
		"32": {
			ID:          "32",
		},
		"33": {
			ID:          "33",
		},
		"43": {
			ID:          "43",
		},
		"48": {
			ID:          "48",
		},
		"9 0": {
			ID:          "9 0",
		},
		"29": {
			ID:          "29",
		},
		"0 0": {
			ID:          "0 0",
			Name:        "Uncoded lens",
		},
		"1": {
			ID:          "1",
		},
		"4": {
			ID:          "4",
		},
		"11": {
			ID:          "11",
		},
		"37": {
			ID:          "37",
		},
		"46": {
			ID:          "46",
		},
		"16 2": {
			ID:          "16 2",
			Name:        "Tri-Elmar-M 16-18-21mm f/4 ASPH. (at 18mm)",
		},
		"26": {
			ID:          "26",
		},
		"29 0": {
			ID:          "29 0",
		},
		"39 0": {
			ID:          "39 0",
		},
		"40": {
			ID:          "40",
		},
		"42 2": {
			ID:          "42 2",
			Name:        "Tri-Elmar-M 28-35-50mm f/4 ASPH. (at 35mm)",
		},
		"7": {
			ID:          "7",
		},
		"47": {
			ID:          "47",
		},
		"51 2": {
			ID:          "51 2",
		},
		"52": {
			ID:          "52",
		},
		"6 0": {
			ID:          "6 0",
		},
		"9": {
			ID:          "9",
		},
		"31 0": {
			ID:          "31 0",
		},
		"51": {
			ID:          "51",
		},
		"31": {
			ID:          "31",
		},
		"5": {
			ID:          "5",
		},
		"6": {
			ID:          "6",
		},
		"24": {
			ID:          "24",
		},
		"25": {
			ID:          "25",
		},
		"36": {
			ID:          "36",
		},
		"23": {
			ID:          "23",
		},
		"34": {
			ID:          "34",
		},
		"49": {
			ID:          "49",
		},
		"53 2": {
			ID:          "53 2",
		},
		"16 3": {
			ID:          "16 3",
			Name:        "Tri-Elmar-M 16-18-21mm f/4 ASPH. (at 21mm)",
		},
		"28": {
			ID:          "28",
		},
		"41": {
			ID:          "41",
		},
		"53 3": {
			ID:          "53 3",
		},
		"42": {
			ID:          "42",
		},
		"42 3": {
			ID:          "42 3",
			Name:        "Tri-Elmar-M 28-35-50mm f/4 ASPH. (at 50mm)",
		},
		"44": {
			ID:          "44",
		},
		"16": {
			ID:          "16",
		},
		"16 1": {
			ID:          "16 1",
			Name:        "Tri-Elmar-M 16-18-21mm f/4 ASPH. (at 16mm)",
		},
		"35": {
			ID:          "35",
		},
		"38": {
			ID:          "38",
		},
		"41 3": {
			ID:          "41 3",
		},
		"45": {
			ID:          "45",
		},
		"30": {
			ID:          "30",
		},
		"42 1": {
			ID:          "42 1",
			Name:        "Tri-Elmar-M 28-35-50mm f/4 ASPH. (at 28mm)",
		},
		"50": {
			ID:          "50",
		},
		"53": {
			ID:          "53",
		},
		"12": {
			ID:          "12",
		},
		"27": {
			ID:          "27",
		},
		"58": {
			ID:          "58",
		},
		"3": {
			ID:          "3",
		},
	},
}
