// Code generated by gen-tags. DO NOT EDIT.

package tags

// PanasonicDSATags contains tag definitions from Image::ExifTool::Panasonic
var PanasonicDSATags = TagTable{
	ModuleName: "Panasonic",
	Tags: map[string]TagDef{
		"NAMESPACE": {
			ID:          "NAMESPACE",
			Name:        "xmpDSA",
		},
		"WRITABLE": {
			ID:          "WRITABLE",
			Name:        "string",
		},
		"AVOID": {
			ID:          "AVOID",
		},
		"Version": {
			ID:          "Version",
		},
		"CorrectionAlreadyApplied": {
			ID:          "CorrectionAlreadyApplied",
		},
		"PitchAngle": {
			ID:          "PitchAngle",
		},
		"RollAngle": {
			ID:          "RollAngle",
		},
		"TargetAspectRatio": {
			ID:          "TargetAspectRatio",
		},
		"FocalLength35mm": {
			ID:          "FocalLength35mm",
		},
		"ScalingFactorHeight": {
			ID:          "ScalingFactorHeight",
		},
		"ValidCropCorners": {
			ID:          "ValidCropCorners",
		},
		"ApplyAutomatically": {
			ID:          "ApplyAutomatically",
		},
		"NormalizedCropCorners": {
			ID:          "NormalizedCropCorners",
		},
	},
}
