// Code generated by gen-tags. DO NOT EDIT.

package tags

// PanasonicPANATags contains tag definitions from Image::ExifTool::Panasonic
var PanasonicPANATags = TagTable{
	ModuleName: "Panasonic",
	Tags: map[string]TagDef{
	},
}
