// Code generated by gen-tags. DO NOT EDIT.

package tags

// PanasonicData2Tags contains tag definitions from Image::ExifTool::Panasonic
var PanasonicData2Tags = TagTable{
	ModuleName: "Panasonic",
	Tags: map[string]TagDef{
	},
}
