// Code generated by gen-tags. DO NOT EDIT.

package tags

// PanasonicLeica5Tags contains tag definitions from Image::ExifTool::Panasonic
var PanasonicLeica5Tags = TagTable{
	ModuleName: "Panasonic",
	Tags: map[string]TagDef{
		"WRITABLE": {
			ID:          "WRITABLE",
		},
		"PRIORITY": {
			ID:          "PRIORITY",
		},
		"0x0407": {
			ID:          "0x0407",
		},
		"0x0408": {
			ID:          "0x0408",
		},
		"0x0412": {
			ID:          "0x0412",
		},
		"0x0413": {
			ID:          "0x0413",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
	},
}
