// Code generated by gen-tags. DO NOT EDIT.

package tags

// PanasonicSerialInfoTags contains tag definitions from Image::ExifTool::Panasonic
var PanasonicSerialInfoTags = TagTable{
	ModuleName: "Panasonic",
	Tags: map[string]TagDef{
	},
}
