// Code generated by gen-tags. DO NOT EDIT.

package tags

// PanasonicType2Tags contains tag definitions from Image::ExifTool::Panasonic
var PanasonicType2Tags = TagTable{
	ModuleName: "Panasonic",
	Tags: map[string]TagDef{
		"3": {
			ID:          "3",
			Name:        "Gain",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int16u",
		},
	},
}
