// Code generated by gen-tags. DO NOT EDIT.

package tags

// ParrotCompositeTags contains tag definitions from Image::ExifTool::Parrot
var ParrotCompositeTags = TagTable{
	ModuleName: "Parrot",
	Tags: map[string]TagDef{
	},
}
