// Code generated by gen-tags. DO NOT EDIT.

package tags

// ParrotARCoreCustomTags contains tag definitions from Image::ExifTool::Parrot
var ParrotARCoreCustomTags = TagTable{
	ModuleName: "Parrot",
	Tags: map[string]TagDef{
	},
}
