// Code generated by gen-tags. DO NOT EDIT.

package tags

// ParrotAutomationTags contains tag definitions from Image::ExifTool::Parrot
var ParrotAutomationTags = TagTable{
	ModuleName: "Parrot",
	Tags: map[string]TagDef{
	},
}
