// Code generated by gen-tags. DO NOT EDIT.

package tags

// PCAPMainTags contains tag definitions from Image::ExifTool::PCAP
var PCAPMainTags = TagTable{
	ModuleName: "PCAP",
	Tags: map[string]TagDef{
		"PCAPVersion": {
			ID:          "PCAPVersion",
		},
		"1": {
			ID:          "1",
			Name:        "Comment",
		},
		"SHB-2": {
			ID:          "SHB-2",
			Name:        "Hardware",
		},
		"SHB-3": {
			ID:          "SHB-3",
			Name:        "OperatingSytem",
		},
		"SHB-4": {
			ID:          "SHB-4",
			Name:        "UserApplication",
		},
		"IDB-2": {
			ID:          "IDB-2",
			Name:        "DeviceName",
		},
		"IDB-3": {
			ID:          "IDB-3",
			Name:        "Description",
		},
	},
}
