// Code generated by gen-tags. DO NOT EDIT.

package tags

// PDFColorSpaceTags contains tag definitions from Image::ExifTool::PDF
var PDFColorSpaceTags = TagTable{
	ModuleName: "PDF",
	Tags: map[string]TagDef{
	},
}
