// Code generated by gen-tags. DO NOT EDIT.

package tags

// PDFPagesTags contains tag definitions from Image::ExifTool::PDF
var PDFPagesTags = TagTable{
	ModuleName: "PDF",
	Tags: map[string]TagDef{
		"Count": {
			ID:          "Count",
			Name:        "PageCount",
		},
	},
}
