// Code generated by gen-tags. DO NOT EDIT.

package tags

// PDFReferenceTags contains tag definitions from Image::ExifTool::PDF
var PDFReferenceTags = TagTable{
	ModuleName: "PDF",
	Tags: map[string]TagDef{
	},
}
