// Code generated by gen-tags. DO NOT EDIT.

package tags

// PDFAdobePhotoshopTags contains tag definitions from Image::ExifTool::PDF
var PDFAdobePhotoshopTags = TagTable{
	ModuleName: "PDF",
	Tags: map[string]TagDef{
	},
}
