// Code generated by gen-tags. DO NOT EDIT.

package tags

// PDFPropertiesTags contains tag definitions from Image::ExifTool::PDF
var PDFPropertiesTags = TagTable{
	ModuleName: "PDF",
	Tags: map[string]TagDef{
		"EXTRACT_UNKNOWN": {
			ID:          "EXTRACT_UNKNOWN",
		},
	},
}
