// Code generated by gen-tags. DO NOT EDIT.

package tags

// PDFMCTags contains tag definitions from Image::ExifTool::PDF
var PDFMCTags = TagTable{
	ModuleName: "PDF",
	Tags: map[string]TagDef{
	},
}
