// Code generated by gen-tags. DO NOT EDIT.

package tags

// PDFTransformParamsTags contains tag definitions from Image::ExifTool::PDF
var PDFTransformParamsTags = TagTable{
	ModuleName: "PDF",
	Tags: map[string]TagDef{
		"Msg": {
			ID:          "Msg",
			Name:        "UsageRightsMessage",
		},
	},
}
