// Code generated by gen-tags. DO NOT EDIT.

package tags

// PDFAFTags contains tag definitions from Image::ExifTool::PDF
var PDFAFTags = TagTable{
	ModuleName: "PDF",
	Tags: map[string]TagDef{
	},
}
