// Code generated by gen-tags. DO NOT EDIT.

package tags

// PDFSignatureTags contains tag definitions from Image::ExifTool::PDF
var PDFSignatureTags = TagTable{
	ModuleName: "PDF",
	Tags: map[string]TagDef{
		"ContactInfo": {
			ID:          "ContactInfo",
			Name:        "SignerContactInfo",
		},
		"Location": {
			ID:          "Location",
			Name:        "SigningLocation",
		},
		"Name": {
			ID:          "Name",
			Name:        "SigningAuthority",
		},
		"Reason": {
			ID:          "Reason",
			Name:        "SigningReason",
		},
		"Prop_AuthType": {
			ID:          "Prop_AuthType",
			Name:        "AuthenticationType",
		},
	},
}
