// Code generated by gen-tags. DO NOT EDIT.

package tags

// PDFDocPDFDocTags contains tag definitions from 
var PDFDocPDFDocTags = TagTable{
	ModuleName: "PDFDoc",
	Tags: map[string]TagDef{
		"0x1C": {
			ID:          "0x1C",
		},
		"0x1F": {
			ID:          "0x1F",
		},
		"0x1D": {
			ID:          "0x1D",
		},
		"0x1E": {
			ID:          "0x1E",
		},
		"0x80": {
			ID:          "0x80",
		},
		"0x81": {
			ID:          "0x81",
		},
		"0x18": {
			ID:          "0x18",
		},
		"0x19": {
			ID:          "0x19",
		},
		"0x1A": {
			ID:          "0x1A",
		},
		"0x1B": {
			ID:          "0x1B",
		},
	},
}
