// Code generated by gen-tags. DO NOT EDIT.

package tags

// PentaxLensInfo2Tags contains tag definitions from Image::ExifTool::Pentax
var PentaxLensInfo2Tags = TagTable{
	ModuleName: "Pentax",
	Tags: map[string]TagDef{
		"IS_SUBDIR": {
			ID:          "IS_SUBDIR",
		},
	},
}
