// Code generated by gen-tags. DO NOT EDIT.

package tags

// PentaxAWBInfoTags contains tag definitions from Image::ExifTool::Pentax
var PentaxAWBInfoTags = TagTable{
	ModuleName: "Pentax",
	Tags: map[string]TagDef{
	},
}
