// Code generated by gen-tags. DO NOT EDIT.

package tags

// PentaxTimeInfoTags contains tag definitions from Image::ExifTool::Pentax
var PentaxTimeInfoTags = TagTable{
	ModuleName: "Pentax",
	Tags: map[string]TagDef{
	},
}
