// Code generated by gen-tags. DO NOT EDIT.

package tags

// PentaxLevelInfoK3IIITags contains tag definitions from Image::ExifTool::Pentax
var PentaxLevelInfoK3IIITags = TagTable{
	ModuleName: "Pentax",
	Tags: map[string]TagDef{
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int8s",
		},
	},
}
