// Code generated by gen-tags. DO NOT EDIT.

package tags

// PentaxCameraInfoTags contains tag definitions from Image::ExifTool::Pentax
var PentaxCameraInfoTags = TagTable{
	ModuleName: "Pentax",
	Tags: map[string]TagDef{
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int32u",
		},
		"4": {
			ID:          "4",
			Name:        "InternalSerialNumber",
		},
	},
}
