// Code generated by gen-tags. DO NOT EDIT.

package tags

// PentaxJunk2Tags contains tag definitions from Image::ExifTool::Pentax
var PentaxJunk2Tags = TagTable{
	ModuleName: "Pentax",
	Tags: map[string]TagDef{
	},
}
