// Code generated by gen-tags. DO NOT EDIT.

package tags

// PentaxJunkTags contains tag definitions from Image::ExifTool::Pentax
var PentaxJunkTags = TagTable{
	ModuleName: "Pentax",
	Tags: map[string]TagDef{
	},
}
