// Code generated by gen-tags. DO NOT EDIT.

package tags

// PentaxShotInfoTags contains tag definitions from Image::ExifTool::Pentax
var PentaxShotInfoTags = TagTable{
	ModuleName: "Pentax",
	Tags: map[string]TagDef{
	},
}
