// Code generated by gen-tags. DO NOT EDIT.

package tags

// PentaxType4Tags contains tag definitions from Image::ExifTool::Pentax
var PentaxType4Tags = TagTable{
	ModuleName: "Pentax",
	Tags: map[string]TagDef{
		"F/W Version": {
			ID:          "F/W Version",
			Name:        "FirmwareVersion",
		},
	},
}
