// Code generated by gen-tags. DO NOT EDIT.

package tags

// PentaxFilterInfoTags contains tag definitions from Image::ExifTool::Pentax
var PentaxFilterInfoTags = TagTable{
	ModuleName: "Pentax",
	Tags: map[string]TagDef{
		"0x0E2": {
			ID:          "0x0E2",
		},
		"0x0F3": {
			ID:          "0x0F3",
		},
		"0x0D1": {
			ID:          "0x0D1",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int8u",
		},
		"0x06B": {
			ID:          "0x06B",
		},
		"0x115": {
			ID:          "0x115",
		},
		"0x016": {
			ID:          "0x016",
		},
		"0x038": {
			ID:          "0x038",
		},
		"0x09E": {
			ID:          "0x09E",
		},
		"0x0C0": {
			ID:          "0x0C0",
		},
		"0x104": {
			ID:          "0x104",
		},
		"0x126": {
			ID:          "0x126",
		},
		"0x137": {
			ID:          "0x137",
		},
		"0x148": {
			ID:          "0x148",
		},
		"0x005": {
			ID:          "0x005",
		},
		"0x027": {
			ID:          "0x027",
		},
		"0x049": {
			ID:          "0x049",
		},
		"0x05A": {
			ID:          "0x05A",
		},
		"0x08D": {
			ID:          "0x08D",
		},
		"0x0AF": {
			ID:          "0x0AF",
		},
		"0x07C": {
			ID:          "0x07C",
		},
	},
}
