// Code generated by gen-tags. DO NOT EDIT.

package tags

// PentaxSRInfo2Tags contains tag definitions from Image::ExifTool::Pentax
var PentaxSRInfo2Tags = TagTable{
	ModuleName: "Pentax",
	Tags: map[string]TagDef{
	},
}
