// Code generated by gen-tags. DO NOT EDIT.

package tags

// PentaxAEInfoTags contains tag definitions from Image::ExifTool::Pentax
var PentaxAEInfoTags = TagTable{
	ModuleName: "Pentax",
	Tags: map[string]TagDef{
		"DATAMEMBER": {
			ID:          "DATAMEMBER",
		},
	},
}
