// Code generated by gen-tags. DO NOT EDIT.

package tags

// PentaxAFPointInfoTags contains tag definitions from Image::ExifTool::Pentax
var PentaxAFPointInfoTags = TagTable{
	ModuleName: "Pentax",
	Tags: map[string]TagDef{
	},
}
