// Code generated by gen-tags. DO NOT EDIT.

package tags

// PentaxAEInfoUnknownTags contains tag definitions from Image::ExifTool::Pentax
var PentaxAEInfoUnknownTags = TagTable{
	ModuleName: "Pentax",
	Tags: map[string]TagDef{
	},
}
