// Code generated by gen-tags. DO NOT EDIT.

package tags

// PentaxWBLevelsTags contains tag definitions from Image::ExifTool::Pentax
var PentaxWBLevelsTags = TagTable{
	ModuleName: "Pentax",
	Tags: map[string]TagDef{
	},
}
