// Code generated by gen-tags. DO NOT EDIT.

package tags

// PentaxAEInfo3Tags contains tag definitions from Image::ExifTool::Pentax
var PentaxAEInfo3Tags = TagTable{
	ModuleName: "Pentax",
	Tags: map[string]TagDef{
	},
}
