// Code generated by gen-tags. DO NOT EDIT.

package tags

// PentaxType2Tags contains tag definitions from Image::ExifTool::Pentax
var PentaxType2Tags = TagTable{
	ModuleName: "Pentax",
	Tags: map[string]TagDef{
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"WRITABLE": {
			ID:          "WRITABLE",
			Name:        "int16u",
		},
	},
}
