// Code generated by gen-tags. DO NOT EDIT.

package tags

// PentaxAVITags contains tag definitions from Image::ExifTool::Pentax
var PentaxAVITags = TagTable{
	ModuleName: "Pentax",
	Tags: map[string]TagDef{
	},
}
