// Code generated by gen-tags. DO NOT EDIT.

package tags

// PhaseOneSensorCalibrationTags contains tag definitions from Image::ExifTool::PhaseOne
var PhaseOneSensorCalibrationTags = TagTable{
	ModuleName: "PhaseOne",
	Tags: map[string]TagDef{
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"WRITE_GROUP": {
			ID:          "WRITE_GROUP",
			Name:        "PhaseOne",
		},
	},
}
