// Code generated by gen-tags. DO NOT EDIT.

package tags

// PhaseOneMainTags contains tag definitions from Image::ExifTool::PhaseOne
var PhaseOneMainTags = TagTable{
	ModuleName: "PhaseOne",
	Tags: map[string]TagDef{
		"0x0105": {
			ID:          "0x0105",
			Name:        "ISO",
		},
		"0x0109": {
			ID:          "0x0109",
			Name:        "SensorHeight",
		},
		"0x0204": {
			ID:          "0x0204",
		},
		"0x021C": {
			ID:          "0x021C",
		},
		"0x0301": {
			ID:          "0x0301",
		},
		"0x010A": {
			ID:          "0x010A",
		},
		"0x010B": {
			ID:          "0x010B",
		},
		"0x010C": {
			ID:          "0x010C",
			Name:        "ImageWidth",
		},
		"0x0412": {
			ID:          "0x0412",
		},
		"WRITABLE": {
			ID:          "WRITABLE",
			Name:        "1",
		},
		"0x0107": {
			ID:          "0x0107",
		},
		"0x0108": {
			ID:          "0x0108",
			Name:        "SensorWidth",
		},
		"0x0203": {
			ID:          "0x0203",
		},
		"0x0222": {
			ID:          "0x0222",
		},
		"0x0223": {
			ID:          "0x0223",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"0x010D": {
			ID:          "0x010D",
			Name:        "ImageHeight",
		},
		"0x0113": {
			ID:          "0x0113",
		},
		"0x021D": {
			ID:          "0x021D",
		},
		"0x0410": {
			ID:          "0x0410",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int32s",
		},
		"0x0102": {
			ID:          "0x0102",
		},
	},
}
