// Code generated by gen-tags. DO NOT EDIT.

package tags

// PhotoshopSliceInfoTags contains tag definitions from Image::ExifTool::Photoshop
var PhotoshopSliceInfoTags = TagTable{
	ModuleName: "Photoshop",
	Tags: map[string]TagDef{
		"24": {
			ID:          "24",
		},
		"20": {
			ID:          "20",
		},
	},
}
