// Code generated by gen-tags. DO NOT EDIT.

package tags

// PhotoshopprintFlagsTags contains tag definitions from Image::ExifTool::Photoshop
var PhotoshopprintFlagsTags = TagTable{
	ModuleName: "Photoshop",
	Tags: map[string]TagDef{
		"2": {
			ID:          "2",
		},
		"5": {
			ID:          "5",
			Name:        "Emulsion down",
		},
		"7": {
			ID:          "7",
			Name:        "Description",
		},
		"8": {
			ID:          "8",
			Name:        "Print flags",
		},
		"3": {
			ID:          "3",
			Name:        "Registration marks",
		},
		"4": {
			ID:          "4",
			Name:        "Negative",
		},
		"6": {
			ID:          "6",
		},
		"0": {
			ID:          "0",
			Name:        "Labels",
		},
		"1": {
			ID:          "1",
			Name:        "Corner crop marks",
		},
	},
}
