// Code generated by gen-tags. DO NOT EDIT.

package tags

// PhotoshopPixelInfoTags contains tag definitions from Image::ExifTool::Photoshop
var PhotoshopPixelInfoTags = TagTable{
	ModuleName: "Photoshop",
	Tags: map[string]TagDef{
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"4": {
			ID:          "4",
		},
	},
}
