// Code generated by gen-tags. DO NOT EDIT.

package tags

// PhotoMechanicSoftEditTags contains tag definitions from Image::ExifTool::PhotoMechanic
var PhotoMechanicSoftEditTags = TagTable{
	ModuleName: "PhotoMechanic",
	Tags: map[string]TagDef{
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"213": {
			ID:          "213",
			Name:        "ConstrainedCropWidth",
		},
		"215": {
			ID:          "215",
			Name:        "FrameNum",
		},
		"217": {
			ID:          "217",
			Name:        "CropLeft",
		},
		"223": {
			ID:          "223",
			Name:        "Rating",
		},
		"237": {
			ID:          "237",
		},
		"238": {
			ID:          "238",
		},
		"WRITABLE": {
			ID:          "WRITABLE",
		},
		"209": {
			ID:          "209",
		},
		"211": {
			ID:          "211",
		},
		"218": {
			ID:          "218",
			Name:        "CropTop",
		},
		"219": {
			ID:          "219",
			Name:        "CropRight",
		},
		"220": {
			ID:          "220",
			Name:        "CropBottom",
		},
		"239": {
			ID:          "239",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int32s",
		},
		"210": {
			ID:          "210",
		},
		"212": {
			ID:          "212",
		},
		"214": {
			ID:          "214",
			Name:        "ConstrainedCropHeight",
		},
		"236": {
			ID:          "236",
		},
	},
}
