// Code generated by gen-tags. DO NOT EDIT.

package tags

// PhotoCDMainTags contains tag definitions from Image::ExifTool::PhotoCD
var PhotoCDMainTags = TagTable{
	ModuleName: "PhotoCD",
	Tags: map[string]TagDef{
	},
}
