// Code generated by gen-tags. DO NOT EDIT.

package tags

// PhotoshopMainTags contains tag definitions from Image::ExifTool::Photoshop
var PhotoshopMainTags = TagTable{
	ModuleName: "Photoshop",
	Tags: map[string]TagDef{
		"0x0400": {
			ID:          "0x0400",
		},
		"0x0413": {
			ID:          "0x0413",
		},
		"0x0415": {
			ID:          "0x0415",
		},
		"0x03EF": {
			ID:          "0x03EF",
		},
		"0x03FC": {
			ID:          "0x03FC",
		},
		"0x0423": {
			ID:          "0x0423",
		},
		"0x0BB8": {
			ID:          "0x0BB8",
		},
		"0x03E9": {
			ID:          "0x03E9",
		},
		"0x03F9": {
			ID:          "0x03F9",
		},
		"0x0411": {
			ID:          "0x0411",
		},
		"0x0416": {
			ID:          "0x0416",
		},
		"0x041B": {
			ID:          "0x041B",
		},
		"0x043E": {
			ID:          "0x043E",
		},
		"0x03F4": {
			ID:          "0x03F4",
		},
		"0x0433": {
			ID:          "0x0433",
		},
		"0x1B59": {
			ID:          "0x1B59",
		},
		"0x0408": {
			ID:          "0x0408",
		},
		"0x042B": {
			ID:          "0x042B",
		},
		"0x042F": {
			ID:          "0x042F",
		},
		"0x0402": {
			ID:          "0x0402",
		},
		"0x03FB": {
			ID:          "0x03FB",
		},
		"0x0410": {
			ID:          "0x0410",
		},
		"0x0412": {
			ID:          "0x0412",
		},
		"0x0432": {
			ID:          "0x0432",
		},
		"0x043B": {
			ID:          "0x043B",
		},
		"0x043C": {
			ID:          "0x043C",
		},
		"0x043A": {
			ID:          "0x043A",
		},
		"0x03F8": {
			ID:          "0x03F8",
		},
		"0x040E": {
			ID:          "0x040E",
		},
		"0x042A": {
			ID:          "0x042A",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"0x0430": {
			ID:          "0x0430",
		},
		"0x0431": {
			ID:          "0x0431",
		},
		"0x0436": {
			ID:          "0x0436",
		},
		"0x03F0": {
			ID:          "0x03F0",
		},
		"0x03F1": {
			ID:          "0x03F1",
		},
		"0x03F5": {
			ID:          "0x03F5",
		},
		"0x03F7": {
			ID:          "0x03F7",
		},
		"0x03FD": {
			ID:          "0x03FD",
		},
		"0x03FE": {
			ID:          "0x03FE",
		},
		"0x0417": {
			ID:          "0x0417",
		},
		"0x0405": {
			ID:          "0x0405",
		},
		"0x042E": {
			ID:          "0x042E",
		},
		"0x043D": {
			ID:          "0x043D",
		},
		"0x1F40": {
			ID:          "0x1F40",
		},
		"0x2710": {
			ID:          "0x2710",
		},
		"0x0401": {
			ID:          "0x0401",
		},
		"0x0429": {
			ID:          "0x0429",
		},
		"0x0440": {
			ID:          "0x0440",
		},
		"0x03EB": {
			ID:          "0x03EB",
		},
		"0x03F6": {
			ID:          "0x03F6",
		},
		"0x0403": {
			ID:          "0x0403",
		},
		"0x0414": {
			ID:          "0x0414",
		},
		"0x1B58": {
			ID:          "0x1B58",
		},
		"0x03E8": {
			ID:          "0x03E8",
		},
		"0x03EA": {
			ID:          "0x03EA",
		},
		"0x041D": {
			ID:          "0x041D",
		},
		"0x0434": {
			ID:          "0x0434",
		},
		"0x0438": {
			ID:          "0x0438",
		},
		"0x043F": {
			ID:          "0x043F",
		},
		"0x03F2": {
			ID:          "0x03F2",
		},
		"0x03FA": {
			ID:          "0x03FA",
		},
		"0x03FF": {
			ID:          "0x03FF",
		},
		"0x041C": {
			ID:          "0x041C",
		},
	},
}
