// Code generated by gen-tags. DO NOT EDIT.

package tags

// PhotoshopUnknownTags contains tag definitions from Image::ExifTool::Photoshop
var PhotoshopUnknownTags = TagTable{
	ModuleName: "Photoshop",
	Tags: map[string]TagDef{
	},
}
