// Code generated by gen-tags. DO NOT EDIT.

package tags

// PICTMainTags contains tag definitions from Image::ExifTool::PICT
var PICTMainTags = TagTable{
	ModuleName: "PICT",
	Tags: map[string]TagDef{
	},
}
