// Code generated by gen-tags. DO NOT EDIT.

package tags

// PLUSXMPTags contains tag definitions from Image::ExifTool::PLUS
var PLUSXMPTags = TagTable{
	ModuleName: "PLUS",
	Tags: map[string]TagDef{
		"OtherLicenseRequirements": {
			ID:          "OtherLicenseRequirements",
		},
		"ImageSupplierImageID": {
			ID:          "ImageSupplierImageID",
		},
		"LicenseID": {
			ID:          "LicenseID",
		},
		"Custom2": {
			ID:          "Custom2",
		},
		"LicensorNotes": {
			ID:          "LicensorNotes",
		},
		"PropertyReleaseID": {
			ID:          "PropertyReleaseID",
		},
		"CopyrightRegistrationNumber": {
			ID:          "CopyrightRegistrationNumber",
		},
		"Custom1": {
			ID:          "Custom1",
		},
		"NAMESPACE": {
			ID:          "NAMESPACE",
			Name:        "plus",
		},
		"OtherConditions": {
			ID:          "OtherConditions",
		},
		"FirstPublicationDate": {
			ID:          "FirstPublicationDate",
		},
		"CopyrightOwnerImageID": {
			ID:          "CopyrightOwnerImageID",
		},
		"LicensorTransactionID": {
			ID:          "LicensorTransactionID",
		},
		"Custom3": {
			ID:          "Custom3",
		},
		"Custom5": {
			ID:          "Custom5",
		},
		"Custom7": {
			ID:          "Custom7",
		},
		"ModelReleaseID": {
			ID:          "ModelReleaseID",
		},
		"ImageCreatorImageID": {
			ID:          "ImageCreatorImageID",
		},
		"LicenseeImageID": {
			ID:          "LicenseeImageID",
		},
		"LicenseeImageNotes": {
			ID:          "LicenseeImageNotes",
		},
		"LicenseTransactionDate": {
			ID:          "LicenseTransactionDate",
		},
		"Custom8": {
			ID:          "Custom8",
		},
		"LicenseEndDate": {
			ID:          "LicenseEndDate",
		},
		"FileNameAsDelivered": {
			ID:          "FileNameAsDelivered",
		},
		"OtherImageInfo": {
			ID:          "OtherImageInfo",
		},
		"LicenseeTransactionID": {
			ID:          "LicenseeTransactionID",
		},
		"LicenseeProjectReference": {
			ID:          "LicenseeProjectReference",
		},
		"OtherLicenseInfo": {
			ID:          "OtherLicenseInfo",
		},
		"Custom4": {
			ID:          "Custom4",
		},
		"Custom9": {
			ID:          "Custom9",
		},
		"Version": {
			ID:          "Version",
		},
		"LicenseStartDate": {
			ID:          "LicenseStartDate",
		},
		"ProductOrServiceConstraints": {
			ID:          "ProductOrServiceConstraints",
		},
		"Custom6": {
			ID:          "Custom6",
		},
		"RegionConstraints": {
			ID:          "RegionConstraints",
		},
		"TermsAndConditionsURL": {
			ID:          "TermsAndConditionsURL",
		},
		"LicensorImageID": {
			ID:          "LicensorImageID",
		},
		"OtherLicenseDocuments": {
			ID:          "OtherLicenseDocuments",
		},
		"MediaConstraints": {
			ID:          "MediaConstraints",
		},
		"OtherConstraints": {
			ID:          "OtherConstraints",
		},
		"TermsAndConditionsText": {
			ID:          "TermsAndConditionsText",
		},
		"Custom10": {
			ID:          "Custom10",
		},
	},
}
