// Code generated by gen-tags. DO NOT EDIT.

package tags

// PNGImageHeaderTags contains tag definitions from Image::ExifTool::PNG
var PNGImageHeaderTags = TagTable{
	ModuleName: "PNG",
	Tags: map[string]TagDef{
		"8": {
			ID:          "8",
			Name:        "BitDepth",
		},
	},
}
