// Code generated by gen-tags. DO NOT EDIT.

package tags

// PNGMainTags contains tag definitions from Image::ExifTool::PNG
var PNGMainTags = TagTable{
	ModuleName: "PNG",
	Tags: map[string]TagDef{
		"PREFERRED": {
			ID:          "PREFERRED",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
	},
}
