// Code generated by gen-tags. DO NOT EDIT.

package tags

// PNGStereoImageTags contains tag definitions from Image::ExifTool::PNG
var PNGStereoImageTags = TagTable{
	ModuleName: "PNG",
	Tags: map[string]TagDef{
	},
}
