// Code generated by gen-tags. DO NOT EDIT.

package tags

// PSPMainTags contains tag definitions from Image::ExifTool::PSP
var PSPMainTags = TagTable{
	ModuleName: "PSP",
	Tags: map[string]TagDef{
		"FileVersion": {
			ID:          "FileVersion",
		},
	},
}
