// Code generated by gen-tags. DO NOT EDIT.

package tags

// PSPCreatorTags contains tag definitions from Image::ExifTool::PSP
var PSPCreatorTags = TagTable{
	ModuleName: "PSP",
	Tags: map[string]TagDef{
		"PRIORITY": {
			ID:          "PRIORITY",
		},
		"0": {
			ID:          "0",
			Name:        "Title",
		},
		"5": {
			ID:          "5",
			Name:        "Description",
		},
	},
}
