// Code generated by gen-tags. DO NOT EDIT.

package tags

// PSPExtTags contains tag definitions from Image::ExifTool::PSP
var PSPExtTags = TagTable{
	ModuleName: "PSP",
	Tags: map[string]TagDef{
	},
}
