// Code generated by gen-tags. DO NOT EDIT.

package tags

// QuickTimeHandlerTags contains tag definitions from Image::ExifTool::QuickTime
var QuickTimeHandlerTags = TagTable{
	ModuleName: "QuickTime",
	Tags: map[string]TagDef{
	},
}
