// Code generated by gen-tags. DO NOT EDIT.

package tags

// QuickTimeMediaTags contains tag definitions from Image::ExifTool::QuickTime
var QuickTimeMediaTags = TagTable{
	ModuleName: "QuickTime",
	Tags: map[string]TagDef{
	},
}
