// Code generated by gen-tags. DO NOT EDIT.

package tags

// QuickTimeTrackRefTags contains tag definitions from Image::ExifTool::QuickTime
var QuickTimeTrackRefTags = TagTable{
	ModuleName: "QuickTime",
	Tags: map[string]TagDef{
	},
}
