// Code generated by gen-tags. DO NOT EDIT.

package tags

// QuickTimeGenMediaHeaderTags contains tag definitions from Image::ExifTool::QuickTime
var QuickTimeGenMediaHeaderTags = TagTable{
	ModuleName: "QuickTime",
	Tags: map[string]TagDef{
	},
}
