// Code generated by gen-tags. DO NOT EDIT.

package tags

// QuickTimecbmpTags contains tag definitions from Image::ExifTool::QuickTime
var QuickTimecbmpTags = TagTable{
	ModuleName: "QuickTime",
	Tags: map[string]TagDef{
	},
}
