// Code generated by gen-tags. DO NOT EDIT.

package tags

// QuickTimeColorRepTags contains tag definitions from Image::ExifTool::QuickTime
var QuickTimeColorRepTags = TagTable{
	ModuleName: "QuickTime",
	Tags: map[string]TagDef{
	},
}
