// Code generated by gen-tags. DO NOT EDIT.

package tags

// QuickTimeVideoProfTags contains tag definitions from Image::ExifTool::QuickTime
var QuickTimeVideoProfTags = TagTable{
	ModuleName: "QuickTime",
	Tags: map[string]TagDef{
	},
}
