// Code generated by gen-tags. DO NOT EDIT.

package tags

// QuickTimestringEncodingTags contains tag definitions from Image::ExifTool::QuickTime
var QuickTimestringEncodingTags = TagTable{
	ModuleName: "QuickTime",
	Tags: map[string]TagDef{
		"2": {
			ID:          "2",
			Name:        "UTF16",
		},
		"3": {
			ID:          "3",
			Name:        "ShiftJIS",
		},
		"4": {
			ID:          "4",
			Name:        "UTF8",
		},
		"5": {
			ID:          "5",
			Name:        "UTF16",
		},
		"1": {
			ID:          "1",
			Name:        "UTF8",
		},
	},
}
