// Code generated by gen-tags. DO NOT EDIT.

package tags

// QuickTimeSpatialAudioTags contains tag definitions from Image::ExifTool::QuickTime
var QuickTimeSpatialAudioTags = TagTable{
	ModuleName: "QuickTime",
	Tags: map[string]TagDef{
	},
}
