// Code generated by gen-tags. DO NOT EDIT.

package tags

// QuickTimeHTCBinaryTags contains tag definitions from Image::ExifTool::QuickTime
var QuickTimeHTCBinaryTags = TagTable{
	ModuleName: "QuickTime",
	Tags: map[string]TagDef{
	},
}
