// Code generated by gen-tags. DO NOT EDIT.

package tags

// QuickTimeMovieTags contains tag definitions from Image::ExifTool::QuickTime
var QuickTimeMovieTags = TagTable{
	ModuleName: "QuickTime",
	Tags: map[string]TagDef{
	},
}
