// Code generated by gen-tags. DO NOT EDIT.

package tags

// QuickTimedontInheritTags contains tag definitions from Image::ExifTool::QuickTime
var QuickTimedontInheritTags = TagTable{
	ModuleName: "QuickTime",
	Tags: map[string]TagDef{
		"ispe": {
			ID:          "ispe",
		},
		"pixi": {
			ID:          "pixi",
		},
		"irot": {
			ID:          "irot",
		},
		"pasp": {
			ID:          "pasp",
		},
		"hvcC": {
			ID:          "hvcC",
		},
		"colr": {
			ID:          "colr",
		},
	},
}
