// Code generated by gen-tags. DO NOT EDIT.

package tags

// QuickTimePreviewTags contains tag definitions from Image::ExifTool::QuickTime
var QuickTimePreviewTags = TagTable{
	ModuleName: "QuickTime",
	Tags: map[string]TagDef{
	},
}
