// Code generated by gen-tags. DO NOT EDIT.

package tags

// QuickTimeHintTrackInfoTags contains tag definitions from Image::ExifTool::QuickTime
var QuickTimeHintTrackInfoTags = TagTable{
	ModuleName: "QuickTime",
	Tags: map[string]TagDef{
	},
}
