// Code generated by gen-tags. DO NOT EDIT.

package tags

// QuickTimeSampleTableTags contains tag definitions from Image::ExifTool::QuickTime
var QuickTimeSampleTableTags = TagTable{
	ModuleName: "QuickTime",
	Tags: map[string]TagDef{
	},
}
