// Code generated by gen-tags. DO NOT EDIT.

package tags

// QuickTimeTrackFragmentTags contains tag definitions from Image::ExifTool::QuickTime
var QuickTimeTrackFragmentTags = TagTable{
	ModuleName: "QuickTime",
	Tags: map[string]TagDef{
	},
}
