// Code generated by gen-tags. DO NOT EDIT.

package tags

// QuickTimeBitrateTags contains tag definitions from Image::ExifTool::QuickTime
var QuickTimeBitrateTags = TagTable{
	ModuleName: "QuickTime",
	Tags: map[string]TagDef{
	},
}
