// Code generated by gen-tags. DO NOT EDIT.

package tags

// QuickTimeMovieHeaderTags contains tag definitions from Image::ExifTool::QuickTime
var QuickTimeMovieHeaderTags = TagTable{
	ModuleName: "QuickTime",
	Tags: map[string]TagDef{
	},
}
