// Code generated by gen-tags. DO NOT EDIT.

package tags

// QuickTimeequiTags contains tag definitions from Image::ExifTool::QuickTime
var QuickTimeequiTags = TagTable{
	ModuleName: "QuickTime",
	Tags: map[string]TagDef{
	},
}
