// Code generated by gen-tags. DO NOT EDIT.

package tags

// QuickTimeUserMediaTags contains tag definitions from Image::ExifTool::QuickTime
var QuickTimeUserMediaTags = TagTable{
	ModuleName: "QuickTime",
	Tags: map[string]TagDef{
	},
}
