// Code generated by gen-tags. DO NOT EDIT.

package tags

// QuickTimeCompositeTags contains tag definitions from Image::ExifTool::QuickTime
var QuickTimeCompositeTags = TagTable{
	ModuleName: "QuickTime",
	Tags: map[string]TagDef{
	},
}
