// Code generated by gen-tags. DO NOT EDIT.

package tags

// QuickTimeOtherSampleDescTags contains tag definitions from Image::ExifTool::QuickTime
var QuickTimeOtherSampleDescTags = TagTable{
	ModuleName: "QuickTime",
	Tags: map[string]TagDef{
	},
}
