// Code generated by gen-tags. DO NOT EDIT.

package tags

// QuickTimeeeBoxTags contains tag definitions from Image::ExifTool::QuickTime
var QuickTimeeeBoxTags = TagTable{
	ModuleName: "QuickTime",
	Tags: map[string]TagDef{
		"ctbx": {
			ID:          "ctbx",
		},
		"vide": {
			ID:          "vide",
		},
		"text": {
			ID:          "text",
		},
		"meta": {
			ID:          "meta",
		},
		"sbtl": {
			ID:          "sbtl",
		},
		"data": {
			ID:          "data",
		},
		"camm": {
			ID:          "camm",
		},
	},
}
