// Code generated by gen-tags. DO NOT EDIT.

package tags

// QuickTimeMainTags contains tag definitions from Image::ExifTool::QuickTime
var QuickTimeMainTags = TagTable{
	ModuleName: "QuickTime",
	Tags: map[string]TagDef{
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"wide": {
			ID:          "wide",
		},
		"mdat": {
			ID:          "mdat",
		},
		"junk": {
			ID:          "junk",
		},
	},
}
