// Code generated by gen-tags. DO NOT EDIT.

package tags

// QuickTimeTimeCodeTags contains tag definitions from Image::ExifTool::QuickTime
var QuickTimeTimeCodeTags = TagTable{
	ModuleName: "QuickTime",
	Tags: map[string]TagDef{
	},
}
