// Code generated by gen-tags. DO NOT EDIT.

package tags

// QuickTimeTrackApertureTags contains tag definitions from Image::ExifTool::QuickTime
var QuickTimeTrackApertureTags = TagTable{
	ModuleName: "QuickTime",
	Tags: map[string]TagDef{
	},
}
