// Code generated by gen-tags. DO NOT EDIT.

package tags

// QuickTimeHTCInfoTags contains tag definitions from Image::ExifTool::QuickTime
var QuickTimeHTCInfoTags = TagTable{
	ModuleName: "QuickTime",
	Tags: map[string]TagDef{
	},
}
