// Code generated by gen-tags. DO NOT EDIT.

package tags

// QuickTimeVideoHeaderTags contains tag definitions from Image::ExifTool::QuickTime
var QuickTimeVideoHeaderTags = TagTable{
	ModuleName: "QuickTime",
	Tags: map[string]TagDef{
	},
}
