// Code generated by gen-tags. DO NOT EDIT.

package tags

// QuickTimesv3dTags contains tag definitions from Image::ExifTool::QuickTime
var QuickTimesv3dTags = TagTable{
	ModuleName: "QuickTime",
	Tags: map[string]TagDef{
	},
}
