// Code generated by gen-tags. DO NOT EDIT.

package tags

// QuickTimeMetaRelationTags contains tag definitions from Image::ExifTool::QuickTime
var QuickTimeMetaRelationTags = TagTable{
	ModuleName: "QuickTime",
	Tags: map[string]TagDef{
	},
}
