// Code generated by gen-tags. DO NOT EDIT.

package tags

// QuickTimeVideoKeysTags contains tag definitions from Image::ExifTool::QuickTime
var QuickTimeVideoKeysTags = TagTable{
	ModuleName: "QuickTime",
	Tags: map[string]TagDef{
	},
}
