// Code generated by gen-tags. DO NOT EDIT.

package tags

// QuickTimeDataInfoTags contains tag definitions from Image::ExifTool::QuickTime
var QuickTimeDataInfoTags = TagTable{
	ModuleName: "QuickTime",
	Tags: map[string]TagDef{
	},
}
