// Code generated by gen-tags. DO NOT EDIT.

package tags

// QuickTimePittasoftTags contains tag definitions from Image::ExifTool::QuickTime
var QuickTimePittasoftTags = TagTable{
	ModuleName: "QuickTime",
	Tags: map[string]TagDef{
	},
}
