// Code generated by gen-tags. DO NOT EDIT.

package tags

// RealPropertiesTags contains tag definitions from Image::ExifTool::Real
var RealPropertiesTags = TagTable{
	ModuleName: "Real",
	Tags: map[string]TagDef{
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int32u",
		},
		"0": {
			ID:          "0",
		},
		"1": {
			ID:          "1",
		},
		"2": {
			ID:          "2",
			Name:        "MaxPacketSize",
		},
		"3": {
			ID:          "3",
			Name:        "AvgPacketSize",
		},
		"5": {
			ID:          "5",
		},
		"6": {
			ID:          "6",
		},
		"9": {
			ID:          "9",
		},
		"4": {
			ID:          "4",
			Name:        "NumPackets",
		},
		"7": {
			ID:          "7",
		},
		"8": {
			ID:          "8",
		},
	},
}
