// Code generated by gen-tags. DO NOT EDIT.

package tags

// RealAudioV4Tags contains tag definitions from Image::ExifTool::Real
var RealAudioV4Tags = TagTable{
	ModuleName: "Real",
	Tags: map[string]TagDef{
		"2": {
			ID:          "2",
		},
		"5": {
			ID:          "5",
		},
		"7": {
			ID:          "7",
		},
		"12": {
			ID:          "12",
		},
		"16": {
			ID:          "16",
			Name:        "Channels",
		},
		"21": {
			ID:          "21",
		},
		"27": {
			ID:          "27",
		},
		"29": {
			ID:          "29",
		},
		"25": {
			ID:          "25",
		},
		"1": {
			ID:          "1",
		},
		"9": {
			ID:          "9",
		},
		"10": {
			ID:          "10",
			Name:        "AudioFrameSize",
		},
		"13": {
			ID:          "13",
			Name:        "SampleRate",
		},
		"14": {
			ID:          "14",
		},
		"20": {
			ID:          "20",
		},
		"30": {
			ID:          "30",
		},
		"0": {
			ID:          "0",
		},
		"3": {
			ID:          "3",
		},
		"8": {
			ID:          "8",
		},
		"18": {
			ID:          "18",
		},
		"19": {
			ID:          "19",
		},
		"24": {
			ID:          "24",
		},
		"22": {
			ID:          "22",
		},
		"28": {
			ID:          "28",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int16u",
		},
		"4": {
			ID:          "4",
		},
		"11": {
			ID:          "11",
		},
		"17": {
			ID:          "17",
		},
		"6": {
			ID:          "6",
		},
		"15": {
			ID:          "15",
			Name:        "BitsPerSample",
		},
		"23": {
			ID:          "23",
		},
		"26": {
			ID:          "26",
		},
	},
}
