// Code generated by gen-tags. DO NOT EDIT.

package tags

// RealContentDescrTags contains tag definitions from Image::ExifTool::Real
var RealContentDescrTags = TagTable{
	ModuleName: "Real",
	Tags: map[string]TagDef{
		"0": {
			ID:          "0",
		},
		"3": {
			ID:          "3",
		},
		"4": {
			ID:          "4",
		},
		"6": {
			ID:          "6",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int16u",
		},
		"1": {
			ID:          "1",
		},
		"2": {
			ID:          "2",
		},
		"5": {
			ID:          "5",
		},
		"7": {
			ID:          "7",
		},
	},
}
