// Code generated by gen-tags. DO NOT EDIT.

package tags

// RedRED1Tags contains tag definitions from Image::ExifTool::Red
var RedRED1Tags = TagTable{
	ModuleName: "Red",
	Tags: map[string]TagDef{
		"0x07": {
			ID:          "0x07",
		},
		"0x36": {
			ID:          "0x36",
		},
		"0x3A": {
			ID:          "0x3A",
		},
		"0x43": {
			ID:          "0x43",
		},
	},
}
