// Code generated by gen-tags. DO NOT EDIT.

package tags

// RicohCompositeTags contains tag definitions from Image::ExifTool::Ricoh
var RicohCompositeTags = TagTable{
	ModuleName: "Ricoh",
	Tags: map[string]TagDef{
	},
}
