// Code generated by gen-tags. DO NOT EDIT.

package tags

// RicohAVITags contains tag definitions from Image::ExifTool::Ricoh
var RicohAVITags = TagTable{
	ModuleName: "Ricoh",
	Tags: map[string]TagDef{
	},
}
