// Code generated by gen-tags. DO NOT EDIT.

package tags

// RicohThetaSubdirTags contains tag definitions from Image::ExifTool::Ricoh
var RicohThetaSubdirTags = TagTable{
	ModuleName: "Ricoh",
	Tags: map[string]TagDef{
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
	},
}
