// Code generated by gen-tags. DO NOT EDIT.

package tags

// RicohFirmwareInfoTags contains tag definitions from Image::ExifTool::Ricoh
var RicohFirmwareInfoTags = TagTable{
	ModuleName: "Ricoh",
	Tags: map[string]TagDef{
		"WRITABLE": {
			ID:          "WRITABLE",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
	},
}
