// Code generated by gen-tags. DO NOT EDIT.

package tags

// RicohRDTCTags contains tag definitions from Image::ExifTool::Ricoh
var RicohRDTCTags = TagTable{
	ModuleName: "Ricoh",
	Tags: map[string]TagDef{
		"0": {
			ID:          "0",
		},
		"16": {
			ID:          "16",
		},
	},
}
