// Code generated by gen-tags. DO NOT EDIT.

package tags

// RicohdatParmsTags contains tag definitions from Image::ExifTool::Ricoh
var RicohdatParmsTags = TagTable{
	ModuleName: "Ricoh",
	Tags: map[string]TagDef{
	},
}
