// Code generated by gen-tags. DO NOT EDIT.

package tags

// RIFFJunkTags contains tag definitions from Image::ExifTool::RIFF
var RIFFJunkTags = TagTable{
	ModuleName: "RIFF",
	Tags: map[string]TagDef{
	},
}
