// Code generated by gen-tags. DO NOT EDIT.

package tags

// RIFFDS64Tags contains tag definitions from Image::ExifTool::RIFF
var RIFFDS64Tags = TagTable{
	ModuleName: "RIFF",
	Tags: map[string]TagDef{
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int64u",
		},
		"2": {
			ID:          "2",
			Name:        "NumberOfSamples64",
		},
	},
}
