// Code generated by gen-tags. DO NOT EDIT.

package tags

// RIFFVP8LTags contains tag definitions from Image::ExifTool::RIFF
var RIFFVP8LTags = TagTable{
	ModuleName: "RIFF",
	Tags: map[string]TagDef{
	},
}
