// Code generated by gen-tags. DO NOT EDIT.

package tags

// RIFFCompositeTags contains tag definitions from Image::ExifTool::RIFF
var RIFFCompositeTags = TagTable{
	ModuleName: "RIFF",
	Tags: map[string]TagDef{
	},
}
