// Code generated by gen-tags. DO NOT EDIT.

package tags

// RIFFStreamHeaderTags contains tag definitions from Image::ExifTool::RIFF
var RIFFStreamHeaderTags = TagTable{
	ModuleName: "RIFF",
	Tags: map[string]TagDef{
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int32u",
		},
		"PRIORITY": {
			ID:          "PRIORITY",
		},
	},
}
