// Code generated by gen-tags. DO NOT EDIT.

package tags

// RIFFInfoTags contains tag definitions from Image::ExifTool::RIFF
var RIFFInfoTags = TagTable{
	ModuleName: "RIFF",
	Tags: map[string]TagDef{
		"ICMT": {
			ID:          "ICMT",
			Name:        "Comment",
		},
		"ICDS": {
			ID:          "ICDS",
			Name:        "CostumeDesigner",
		},
		"IMUS": {
			ID:          "IMUS",
			Name:        "MusicBy",
		},
		"IAS4": {
			ID:          "IAS4",
			Name:        "FourthLanguage",
		},
		"IKEY": {
			ID:          "IKEY",
			Name:        "Keywords",
		},
		"ISRF": {
			ID:          "ISRF",
			Name:        "SourceForm",
		},
		"CODE": {
			ID:          "CODE",
			Name:        "EncodedBy",
		},
		"IMIT": {
			ID:          "IMIT",
			Name:        "MoreInfoText",
		},
		"ISMP": {
			ID:          "ISMP",
			Name:        "TimeCode",
		},
		"IPRD": {
			ID:          "IPRD",
			Name:        "Product",
		},
		"IEDT": {
			ID:          "IEDT",
			Name:        "EditedBy",
		},
		"IAS2": {
			ID:          "IAS2",
			Name:        "SecondLanguage",
		},
		"IAS6": {
			ID:          "IAS6",
			Name:        "SixthLanguage",
		},
		"IMIU": {
			ID:          "IMIU",
			Name:        "MoreInfoURL",
		},
		"IWRI": {
			ID:          "IWRI",
			Name:        "WrittenBy",
		},
		"IAS9": {
			ID:          "IAS9",
			Name:        "NinthLanguage",
		},
		"IBSU": {
			ID:          "IBSU",
			Name:        "BaseURL",
		},
		"IPRO": {
			ID:          "IPRO",
			Name:        "ProducedBy",
		},
		"ISTR": {
			ID:          "ISTR",
			Name:        "Starring",
		},
		"TITL": {
			ID:          "TITL",
			Name:        "Title",
		},
		"LANG": {
			ID:          "LANG",
			Name:        "Language",
		},
		"DISP": {
			ID:          "DISP",
			Name:        "SoundSchemeTitle",
		},
		"TLEN": {
			ID:          "TLEN",
		},
		"TVER": {
			ID:          "TVER",
			Name:        "Version",
		},
		"IENG": {
			ID:          "IENG",
			Name:        "Engineer",
		},
		"ISRC": {
			ID:          "ISRC",
			Name:        "Source",
		},
		"TRCK": {
			ID:          "TRCK",
			Name:        "TrackNumber",
		},
		"ITRK": {
			ID:          "ITRK",
			Name:        "TrackNumber",
		},
		"COMM": {
			ID:          "COMM",
			Name:        "Comments",
		},
		"ICNM": {
			ID:          "ICNM",
			Name:        "Cinematographer",
		},
		"ICMS": {
			ID:          "ICMS",
			Name:        "Commissioned",
		},
		"ICRP": {
			ID:          "ICRP",
			Name:        "Cropped",
		},
		"IDPI": {
			ID:          "IDPI",
			Name:        "DotsPerInch",
		},
		"IGNR": {
			ID:          "IGNR",
			Name:        "Genre",
		},
		"ISHP": {
			ID:          "ISHP",
			Name:        "Sharpness",
		},
		"AGES": {
			ID:          "AGES",
			Name:        "Rated",
		},
		"IAS3": {
			ID:          "IAS3",
			Name:        "ThirdLanguage",
		},
		"IMED": {
			ID:          "IMED",
			Name:        "Medium",
		},
		"IPLT": {
			ID:          "IPLT",
			Name:        "NumColors",
		},
		"IPDS": {
			ID:          "IPDS",
			Name:        "ProductionDesigner",
		},
		"IAS5": {
			ID:          "IAS5",
			Name:        "FifthLanguage",
		},
		"ISTD": {
			ID:          "ISTD",
			Name:        "ProductionStudio",
		},
		"ICNT": {
			ID:          "ICNT",
			Name:        "Country",
		},
		"IRTD": {
			ID:          "IRTD",
			Name:        "Rating",
		},
		"IAS7": {
			ID:          "IAS7",
			Name:        "SeventhLanguage",
		},
		"LOCA": {
			ID:          "LOCA",
			Name:        "Location",
		},
		"ITCH": {
			ID:          "ITCH",
			Name:        "Technician",
		},
		"ILNG": {
			ID:          "ILNG",
			Name:        "Language",
		},
		"ILGU": {
			ID:          "ILGU",
			Name:        "LogoURL",
		},
		"ILGT": {
			ID:          "ILGT",
			Name:        "Lightness",
		},
		"IART": {
			ID:          "IART",
		},
		"ICOP": {
			ID:          "ICOP",
		},
		"INAM": {
			ID:          "INAM",
			Name:        "Title",
		},
		"ISBJ": {
			ID:          "ISBJ",
			Name:        "Subject",
		},
		"IDST": {
			ID:          "IDST",
			Name:        "DistributedBy",
		},
		"ICAS": {
			ID:          "ICAS",
			Name:        "DefaultAudioStream",
		},
		"ILIU": {
			ID:          "ILIU",
			Name:        "LogoIconURL",
		},
		"ISGN": {
			ID:          "ISGN",
			Name:        "SecondaryGenre",
		},
		"YEAR": {
			ID:          "YEAR",
			Name:        "Year",
		},
		"GENR": {
			ID:          "GENR",
			Name:        "Genre",
		},
		"IAS1": {
			ID:          "IAS1",
			Name:        "FirstLanguage",
		},
		"TURL": {
			ID:          "TURL",
			Name:        "URL",
		},
		"TORG": {
			ID:          "TORG",
			Name:        "Organization",
		},
		"DIRC": {
			ID:          "DIRC",
			Name:        "Directory",
		},
		"STAR": {
			ID:          "STAR",
			Name:        "Starring",
		},
		"PRT1": {
			ID:          "PRT1",
			Name:        "Part",
		},
		"IAS8": {
			ID:          "IAS8",
			Name:        "EighthLanguage",
		},
		"IMBI": {
			ID:          "IMBI",
			Name:        "MoreInfoBannerImage",
		},
		"IMBU": {
			ID:          "IMBU",
			Name:        "MoreInfoBannerURL",
		},
		"IENC": {
			ID:          "IENC",
			Name:        "EncodedBy",
		},
		"IARL": {
			ID:          "IARL",
			Name:        "ArchivalLocation",
		},
		"IDIM": {
			ID:          "IDIM",
			Name:        "Dimensions",
		},
		"IWMU": {
			ID:          "IWMU",
			Name:        "WatermarkURL",
		},
		"IRIP": {
			ID:          "IRIP",
			Name:        "RippedBy",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "string",
		},
		"PRT2": {
			ID:          "PRT2",
			Name:        "NumberOfParts",
		},
	},
}
