// Code generated by gen-tags. DO NOT EDIT.

package tags

// RIFFTdatTags contains tag definitions from Image::ExifTool::RIFF
var RIFFTdatTags = TagTable{
	ModuleName: "RIFF",
	Tags: map[string]TagDef{
	},
}
