// Code generated by gen-tags. DO NOT EDIT.

package tags

// RSRCMainTags contains tag definitions from Image::ExifTool::RSRC
var RSRCMainTags = TagTable{
	ModuleName: "RSRC",
	Tags: map[string]TagDef{
		"usro_0x0000": {
			ID:          "usro_0x0000",
			Name:        "OpenWithApplication",
		},
		"vers_0x0001": {
			ID:          "vers_0x0001",
			Name:        "ApplicationVersion",
		},
		"STR _0xbff3": {
			ID:          "STR _0xbff3",
			Name:        "ApplicationMissingMsg",
		},
		"STR _0xbff4": {
			ID:          "STR _0xbff4",
			Name:        "CreatorApplication",
		},
		"STR#_0x0080": {
			ID:          "STR#_0x0080",
			Name:        "Keywords",
		},
		"TEXT_0x0080": {
			ID:          "TEXT_0x0080",
			Name:        "Description",
		},
	},
}
