// Code generated by gen-tags. DO NOT EDIT.

package tags

// SamsungOrientationInfoTags contains tag definitions from Image::ExifTool::Samsung
var SamsungOrientationInfoTags = TagTable{
	ModuleName: "Samsung",
	Tags: map[string]TagDef{
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"WRITABLE": {
			ID:          "WRITABLE",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "rational64s",
		},
	},
}
