// Code generated by gen-tags. DO NOT EDIT.

package tags

// SamsungMainTags contains tag definitions from Image::ExifTool::Samsung
var SamsungMainTags = TagTable{
	ModuleName: "Samsung",
	Tags: map[string]TagDef{
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"WRITABLE": {
			ID:          "WRITABLE",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int32u",
		},
		"IS_OFFSET": {
			ID:          "IS_OFFSET",
		},
		"IS_SUBDIR": {
			ID:          "IS_SUBDIR",
		},
	},
}
