// Code generated by gen-tags. DO NOT EDIT.

package tags

// SamsungMP4Tags contains tag definitions from Image::ExifTool::Samsung
var SamsungMP4Tags = TagTable{
	ModuleName: "Samsung",
	Tags: map[string]TagDef{
	},
}
