// Code generated by gen-tags. DO NOT EDIT.

package tags

// SamsungIFDTags contains tag definitions from Image::ExifTool::Samsung
var SamsungIFDTags = TagTable{
	ModuleName: "Samsung",
	Tags: map[string]TagDef{
	},
}
