// Code generated by gen-tags. DO NOT EDIT.

package tags

// SamsungsmtaTags contains tag definitions from Image::ExifTool::Samsung
var SamsungsmtaTags = TagTable{
	ModuleName: "Samsung",
	Tags: map[string]TagDef{
		"mdln": {
			ID:          "mdln",
		},
	},
}
