// Code generated by gen-tags. DO NOT EDIT.

package tags

// SanyoFaceInfoTags contains tag definitions from Image::ExifTool::Sanyo
var SanyoFaceInfoTags = TagTable{
	ModuleName: "Sanyo",
	Tags: map[string]TagDef{
		"WRITABLE": {
			ID:          "WRITABLE",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int32u",
		},
		"0": {
			ID:          "0",
			Name:        "FacesDetected",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
	},
}
