// Code generated by gen-tags. DO NOT EDIT.

package tags

// SanyoMOVTags contains tag definitions from Image::ExifTool::Sanyo
var SanyoMOVTags = TagTable{
	ModuleName: "Sanyo",
	Tags: map[string]TagDef{
	},
}
