// Code generated by gen-tags. DO NOT EDIT.

package tags

// ShiftJISShiftJISTags contains tag definitions from 
var ShiftJISShiftJISTags = TagTable{
	ModuleName: "ShiftJIS",
	Tags: map[string]TagDef{
		"0xA1": {
			ID:          "0xA1",
		},
		"0xA5": {
			ID:          "0xA5",
		},
		"0xAD": {
			ID:          "0xAD",
		},
		"0xBD": {
			ID:          "0xBD",
		},
		"0xD1": {
			ID:          "0xD1",
		},
		"0xDD": {
			ID:          "0xDD",
		},
		"0xB5": {
			ID:          "0xB5",
		},
		"0xB9": {
			ID:          "0xB9",
		},
		"0xC1": {
			ID:          "0xC1",
		},
		"0xD5": {
			ID:          "0xD5",
		},
		"0x5C": {
			ID:          "0x5C",
		},
		"0xB1": {
			ID:          "0xB1",
		},
		"0xC5": {
			ID:          "0xC5",
		},
		"0xA9": {
			ID:          "0xA9",
		},
		"0xC9": {
			ID:          "0xC9",
		},
		"0xCD": {
			ID:          "0xCD",
		},
		"0xD9": {
			ID:          "0xD9",
		},
	},
}
