// Code generated by gen-tags. DO NOT EDIT.

package tags

// ShortcutsShortcutsTags contains tag definitions from Image::ExifTool::Shortcuts
var ShortcutsShortcutsTags = TagTable{
	ModuleName: "Shortcuts",
	Tags: map[string]TagDef{
		"MyShortcut": {
			ID:          "MyShortcut",
		},
		"MyAlias": {
			ID:          "MyAlias",
			Name:        "FocalLengthIn35mmFormat",
		},
	},
}
