// Code generated by gen-tags. DO NOT EDIT.

package tags

// SigmaRawHeaderExtTags contains tag definitions from Image::ExifTool::SigmaRaw
var SigmaRawHeaderExtTags = TagTable{
	ModuleName: "SigmaRaw",
	Tags: map[string]TagDef{
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "float",
		},
		"0": {
			ID:          "0",
			Name:        "Unused",
		},
		"1": {
			ID:          "1",
		},
		"3": {
			ID:          "3",
		},
		"6": {
			ID:          "6",
		},
		"8": {
			ID:          "8",
		},
		"2": {
			ID:          "2",
		},
		"4": {
			ID:          "4",
		},
		"5": {
			ID:          "5",
		},
		"7": {
			ID:          "7",
		},
		"9": {
			ID:          "9",
		},
		"10": {
			ID:          "10",
		},
	},
}
