// Code generated by gen-tags. DO NOT EDIT.

package tags

// SigmaMainTags contains tag definitions from Image::ExifTool::Sigma
var SigmaMainTags = TagTable{
	ModuleName: "Sigma",
	Tags: map[string]TagDef{
		"0x0004": {
			ID:          "0x0004",
			Name:        "ResolutionMode",
		},
		"0x000B": {
			ID:          "0x000B",
			Name:        "ColorSpace",
		},
		"0x0017": {
			ID:          "0x0017",
			Name:        "Firmware",
		},
		"0x008C": {
			ID:          "0x008C",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"0x0002": {
			ID:          "0x0002",
			Name:        "SerialNumber",
		},
		"0x0007": {
			ID:          "0x0007",
			Name:        "WhiteBalance",
		},
		"0x000A": {
			ID:          "0x000A",
			Name:        "LensFocalRange",
		},
		"0x0015": {
			ID:          "0x0015",
			Name:        "AdjustmentMode",
		},
		"WRITABLE": {
			ID:          "WRITABLE",
			Name:        "string",
		},
		"0x0003": {
			ID:          "0x0003",
			Name:        "DriveMode",
		},
		"0x0019": {
			ID:          "0x0019",
			Name:        "AutoBracket",
		},
		"0x0087": {
			ID:          "0x0087",
		},
		"0x0088": {
			ID:          "0x0088",
		},
		"0x0005": {
			ID:          "0x0005",
			Name:        "AFMode",
		},
		"0x0006": {
			ID:          "0x0006",
			Name:        "FocusSetting",
		},
	},
}
