// Code generated by gen-tags. DO NOT EDIT.

package tags

// SigmaWBSettingsTags contains tag definitions from Image::ExifTool::Sigma
var SigmaWBSettingsTags = TagTable{
	ModuleName: "Sigma",
	Tags: map[string]TagDef{
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"0": {
			ID:          "0",
		},
		"6": {
			ID:          "6",
		},
		"9": {
			ID:          "9",
		},
		"12": {
			ID:          "12",
		},
		"15": {
			ID:          "15",
		},
		"18": {
			ID:          "18",
		},
		"27": {
			ID:          "27",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"WRITABLE": {
			ID:          "WRITABLE",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "float",
		},
		"3": {
			ID:          "3",
		},
		"21": {
			ID:          "21",
		},
		"24": {
			ID:          "24",
		},
	},
}
