// Code generated by gen-tags. DO NOT EDIT.

package tags

// SigmaRawMainTags contains tag definitions from Image::ExifTool::SigmaRaw
var SigmaRawMainTags = TagTable{
	ModuleName: "SigmaRaw",
	Tags: map[string]TagDef{
	},
}
