// Code generated by gen-tags. DO NOT EDIT.

package tags

// SonyFaceInfoATags contains tag definitions from Image::ExifTool::Sony
var SonyFaceInfoATags = TagTable{
	ModuleName: "Sony",
	Tags: map[string]TagDef{
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int16u",
		},
		"DATAMEMBER": {
			ID:          "DATAMEMBER",
		},
	},
}
