// Code generated by gen-tags. DO NOT EDIT.

package tags

// SonySR2SubIFDTags contains tag definitions from Image::ExifTool::Sony
var SonySR2SubIFDTags = TagTable{
	ModuleName: "Sony",
	Tags: map[string]TagDef{
		"0x7482": {
			ID:          "0x7482",
		},
		"0x7481": {
			ID:          "0x7481",
		},
		"0x7828": {
			ID:          "0x7828",
		},
		"0x7310": {
			ID:          "0x7310",
		},
		"0x7486": {
			ID:          "0x7486",
		},
		"0x7822": {
			ID:          "0x7822",
		},
		"0x7823": {
			ID:          "0x7823",
		},
		"0x7825": {
			ID:          "0x7825",
		},
		"0x7824": {
			ID:          "0x7824",
		},
		"WRITE_GROUP": {
			ID:          "WRITE_GROUP",
			Name:        "SR2SubIFD",
		},
		"SET_GROUP1": {
			ID:          "SET_GROUP1",
		},
		"0x7303": {
			ID:          "0x7303",
		},
		"0x7313": {
			ID:          "0x7313",
		},
		"0x7480": {
			ID:          "0x7480",
		},
		"0x74A0": {
			ID:          "0x74A0",
		},
		"0x7820": {
			ID:          "0x7820",
		},
		"0x7302": {
			ID:          "0x7302",
		},
		"0x7312": {
			ID:          "0x7312",
		},
		"0x74A1": {
			ID:          "0x74A1",
		},
		"0x7800": {
			ID:          "0x7800",
		},
		"0x7827": {
			ID:          "0x7827",
		},
		"0x782C": {
			ID:          "0x782C",
		},
		"0x787F": {
			ID:          "0x787F",
		},
		"0x797D": {
			ID:          "0x797D",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"0x7484": {
			ID:          "0x7484",
		},
		"0x7829": {
			ID:          "0x7829",
		},
		"0x782B": {
			ID:          "0x782B",
		},
		"0x7980": {
			ID:          "0x7980",
		},
		"0x7826": {
			ID:          "0x7826",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"PERMANENT": {
			ID:          "PERMANENT",
		},
		"0x7483": {
			ID:          "0x7483",
		},
		"0x7821": {
			ID:          "0x7821",
		},
		"0x7300": {
			ID:          "0x7300",
		},
		"0x782A": {
			ID:          "0x782A",
		},
		"0x7982": {
			ID:          "0x7982",
		},
		"0x782D": {
			ID:          "0x782D",
		},
	},
}
