// Code generated by gen-tags. DO NOT EDIT.

package tags

// SonyTag9401Tags contains tag definitions from Image::ExifTool::Sony
var SonyTag9401Tags = TagTable{
	ModuleName: "Sony",
	Tags: map[string]TagDef{
		"0x0678": {
			ID:          "0x0678",
		},
		"IS_SUBDIR": {
			ID:          "IS_SUBDIR",
		},
		"0x0498": {
			ID:          "0x0498",
		},
		"0x0636": {
			ID:          "0x0636",
		},
		"0x0653": {
			ID:          "0x0653",
		},
		"0x06DE": {
			ID:          "0x06DE",
		},
		"0x06E7": {
			ID:          "0x06E7",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int8u",
		},
		"DATAMEMBER": {
			ID:          "DATAMEMBER",
		},
		"0x044E": {
			ID:          "0x044E",
		},
		"0x0634": {
			ID:          "0x0634",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"0x0000": {
			ID:          "0x0000",
		},
		"0x049D": {
			ID:          "0x049D",
		},
		"0x04A1": {
			ID:          "0x04A1",
		},
		"0x04A2": {
			ID:          "0x04A2",
		},
		"0x04BA": {
			ID:          "0x04BA",
		},
		"0x06B8": {
			ID:          "0x06B8",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"WRITABLE": {
			ID:          "WRITABLE",
		},
		"0x03E2": {
			ID:          "0x03E2",
		},
		"0x03F4": {
			ID:          "0x03F4",
		},
		"0x049E": {
			ID:          "0x049E",
		},
		"0x059D": {
			ID:          "0x059D",
		},
		"0x064C": {
			ID:          "0x064C",
		},
	},
}
