// Code generated by gen-tags. DO NOT EDIT.

package tags

// SonyAFStatus15Tags contains tag definitions from Image::ExifTool::Sony
var SonyAFStatus15Tags = TagTable{
	ModuleName: "Sony",
	Tags: map[string]TagDef{
		"0x06": {
			ID:          "0x06",
		},
		"0x08": {
			ID:          "0x08",
		},
		"0x12": {
			ID:          "0x12",
		},
		"0x16": {
			ID:          "0x16",
		},
		"0x1E": {
			ID:          "0x1E",
		},
		"0x22": {
			ID:          "0x22",
		},
		"0x00": {
			ID:          "0x00",
		},
		"0x1A": {
			ID:          "0x1A",
		},
		"0x1C": {
			ID:          "0x1C",
		},
		"0x0C": {
			ID:          "0x0C",
		},
		"0x0E": {
			ID:          "0x0E",
		},
		"0x14": {
			ID:          "0x14",
		},
		"0x20": {
			ID:          "0x20",
		},
		"0x0A": {
			ID:          "0x0A",
		},
		"0x10": {
			ID:          "0x10",
		},
		"0x18": {
			ID:          "0x18",
		},
		"0x02": {
			ID:          "0x02",
		},
		"0x04": {
			ID:          "0x04",
		},
	},
}
