// Code generated by gen-tags. DO NOT EDIT.

package tags

// SonyTag2010eTags contains tag definitions from Image::ExifTool::Sony
var SonyTag2010eTags = TagTable{
	ModuleName: "Sony",
	Tags: map[string]TagDef{
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"DATAMEMBER": {
			ID:          "DATAMEMBER",
		},
		"0x115C": {
			ID:          "0x115C",
		},
		"0x116C": {
			ID:          "0x116C",
		},
		"0x117C": {
			ID:          "0x117C",
		},
		"0x11A8": {
			ID:          "0x11A8",
		},
		"0x11AD": {
			ID:          "0x11AD",
		},
		"0x1160": {
			ID:          "0x1160",
		},
		"0x1178": {
			ID:          "0x1178",
		},
		"0x1180": {
			ID:          "0x1180",
		},
		"0x1197": {
			ID:          "0x1197",
		},
		"WRITABLE": {
			ID:          "WRITABLE",
		},
		"PRIORITY": {
			ID:          "PRIORITY",
		},
		"0x0008": {
			ID:          "0x0008",
		},
		"0x021C": {
			ID:          "0x021C",
		},
		"0x11AC": {
			ID:          "0x11AC",
		},
		"0x022C": {
			ID:          "0x022C",
		},
		"0x1168": {
			ID:          "0x1168",
		},
		"0x1174": {
			ID:          "0x1174",
		},
		"0x119B": {
			ID:          "0x119B",
		},
		"0x11B4": {
			ID:          "0x11B4",
		},
		"0x1172": {
			ID:          "0x1172",
		},
		"IS_SUBDIR": {
			ID:          "IS_SUBDIR",
		},
		"0x0004": {
			ID:          "0x0004",
		},
		"0x0328": {
			ID:          "0x0328",
		},
		"0x1196": {
			ID:          "0x1196",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int8u",
		},
		"0x0000": {
			ID:          "0x0000",
		},
	},
}
