// Code generated by gen-tags. DO NOT EDIT.

package tags

// SonyTag2010aTags contains tag definitions from Image::ExifTool::Sony
var SonyTag2010aTags = TagTable{
	ModuleName: "Sony",
	Tags: map[string]TagDef{
		"0x1134": {
			ID:          "0x1134",
		},
		"0x1140": {
			ID:          "0x1140",
		},
		"0x1170": {
			ID:          "0x1170",
		},
		"0x1148": {
			ID:          "0x1148",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int8u",
		},
		"0x113E": {
			ID:          "0x113E",
		},
		"0x1144": {
			ID:          "0x1144",
		},
		"0x115E": {
			ID:          "0x115E",
		},
		"0x1163": {
			ID:          "0x1163",
		},
		"WRITABLE": {
			ID:          "WRITABLE",
		},
		"IS_SUBDIR": {
			ID:          "IS_SUBDIR",
		},
		"0x1128": {
			ID:          "0x1128",
		},
		"0x1174": {
			ID:          "0x1174",
		},
		"0x117C": {
			ID:          "0x117C",
		},
		"PRIORITY": {
			ID:          "PRIORITY",
		},
		"0x112C": {
			ID:          "0x112C",
		},
		"0x1138": {
			ID:          "0x1138",
		},
		"0x114C": {
			ID:          "0x114C",
		},
		"0x115F": {
			ID:          "0x115F",
		},
		"0x1175": {
			ID:          "0x1175",
		},
	},
}
