// Code generated by gen-tags. DO NOT EDIT.

package tags

// SonyTag9050dTags contains tag definitions from Image::ExifTool::Sony
var SonyTag9050dTags = TagTable{
	ModuleName: "Sony",
	Tags: map[string]TagDef{
		"WRITABLE": {
			ID:          "WRITABLE",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int8u",
		},
	},
}
