// Code generated by gen-tags. DO NOT EDIT.

package tags

// SonyIDCCompositeTags contains tag definitions from Image::ExifTool::SonyIDC
var SonyIDCCompositeTags = TagTable{
	ModuleName: "SonyIDC",
	Tags: map[string]TagDef{
	},
}
