// Code generated by gen-tags. DO NOT EDIT.

package tags

// SonyAFStatus19Tags contains tag definitions from Image::ExifTool::Sony
var SonyAFStatus19Tags = TagTable{
	ModuleName: "Sony",
	Tags: map[string]TagDef{
		"0x00": {
			ID:          "0x00",
		},
		"0x06": {
			ID:          "0x06",
		},
		"0x10": {
			ID:          "0x10",
		},
		"0x1A": {
			ID:          "0x1A",
		},
		"0x20": {
			ID:          "0x20",
		},
		"0x34": {
			ID:          "0x34",
		},
		"0x36": {
			ID:          "0x36",
		},
		"0x08": {
			ID:          "0x08",
		},
		"0x16": {
			ID:          "0x16",
		},
		"0x18": {
			ID:          "0x18",
		},
		"0x1E": {
			ID:          "0x1E",
		},
		"0x24": {
			ID:          "0x24",
		},
		"0x30": {
			ID:          "0x30",
		},
		"0x1C": {
			ID:          "0x1C",
		},
		"0x22": {
			ID:          "0x22",
		},
		"0x02": {
			ID:          "0x02",
		},
		"0x04": {
			ID:          "0x04",
		},
		"0x12": {
			ID:          "0x12",
		},
		"0x2A": {
			ID:          "0x2A",
		},
		"0x2E": {
			ID:          "0x2E",
		},
		"0x32": {
			ID:          "0x32",
		},
		"0x0A": {
			ID:          "0x0A",
		},
		"0x28": {
			ID:          "0x28",
		},
		"0x38": {
			ID:          "0x38",
		},
		"0x0C": {
			ID:          "0x0C",
		},
		"0x0E": {
			ID:          "0x0E",
		},
		"0x14": {
			ID:          "0x14",
		},
		"0x26": {
			ID:          "0x26",
		},
		"0x2C": {
			ID:          "0x2C",
		},
		"0x3A": {
			ID:          "0x3A",
		},
	},
}
