// Code generated by gen-tags. DO NOT EDIT.

package tags

// SonyCameraInfo3Tags contains tag definitions from Image::ExifTool::Sony
var SonyCameraInfo3Tags = TagTable{
	ModuleName: "Sony",
	Tags: map[string]TagDef{
		"0x2B": {
			ID:          "0x2B",
		},
		"0x2D": {
			ID:          "0x2D",
		},
		"0x2F": {
			ID:          "0x2F",
		},
		"0x31": {
			ID:          "0x31",
		},
		"IS_SUBDIR": {
			ID:          "IS_SUBDIR",
		},
		"0x25": {
			ID:          "0x25",
		},
		"0x27": {
			ID:          "0x27",
		},
		"0x29": {
			ID:          "0x29",
		},
	},
}
