// Code generated by gen-tags. DO NOT EDIT.

package tags

// SonyTag2010bTags contains tag definitions from Image::ExifTool::Sony
var SonyTag2010bTags = TagTable{
	ModuleName: "Sony",
	Tags: map[string]TagDef{
		"0x01B6": {
			ID:          "0x01B6",
		},
		"0x1162": {
			ID:          "0x1162",
		},
		"0x1178": {
			ID:          "0x1178",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int8u",
		},
		"PRIORITY": {
			ID:          "PRIORITY",
		},
		"0x0000": {
			ID:          "0x0000",
		},
		"0x1134": {
			ID:          "0x1134",
		},
		"0x113E": {
			ID:          "0x113E",
		},
		"0x1140": {
			ID:          "0x1140",
		},
		"0x1163": {
			ID:          "0x1163",
		},
		"IS_SUBDIR": {
			ID:          "IS_SUBDIR",
		},
		"0x0004": {
			ID:          "0x0004",
		},
		"0x1128": {
			ID:          "0x1128",
		},
		"0x112C": {
			ID:          "0x112C",
		},
		"0x1138": {
			ID:          "0x1138",
		},
		"0x1144": {
			ID:          "0x1144",
		},
		"0x1148": {
			ID:          "0x1148",
		},
		"0x114C": {
			ID:          "0x114C",
		},
		"WRITABLE": {
			ID:          "WRITABLE",
		},
		"0x0008": {
			ID:          "0x0008",
		},
		"0x0324": {
			ID:          "0x0324",
		},
		"0x1167": {
			ID:          "0x1167",
		},
		"0x1174": {
			ID:          "0x1174",
		},
		"0x1179": {
			ID:          "0x1179",
		},
		"0x1180": {
			ID:          "0x1180",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
	},
}
