// Code generated by gen-tags. DO NOT EDIT.

package tags

// SonyCameraSettingsTags contains tag definitions from Image::ExifTool::Sony
var SonyCameraSettingsTags = TagTable{
	ModuleName: "Sony",
	Tags: map[string]TagDef{
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int16u",
		},
		"PRIORITY": {
			ID:          "PRIORITY",
		},
	},
}
