// Code generated by gen-tags. DO NOT EDIT.

package tags

// SonyShotInfoTags contains tag definitions from Image::ExifTool::Sony
var SonyShotInfoTags = TagTable{
	ModuleName: "Sony",
	Tags: map[string]TagDef{
		"IS_SUBDIR": {
			ID:          "IS_SUBDIR",
		},
		"0x1A": {
			ID:          "0x1A",
		},
		"0x1C": {
			ID:          "0x1C",
		},
		"DATAMEMBER": {
			ID:          "DATAMEMBER",
		},
	},
}
