// Code generated by gen-tags. DO NOT EDIT.

package tags

// SonyMoreInfo0401Tags contains tag definitions from Image::ExifTool::Sony
var SonyMoreInfo0401Tags = TagTable{
	ModuleName: "Sony",
	Tags: map[string]TagDef{
		"PRIORITY": {
			ID:          "PRIORITY",
		},
	},
}
