// Code generated by gen-tags. DO NOT EDIT.

package tags

// SonyCompositeTags contains tag definitions from Image::ExifTool::Sony
var SonyCompositeTags = TagTable{
	ModuleName: "Sony",
	Tags: map[string]TagDef{
	},
}
