// Code generated by gen-tags. DO NOT EDIT.

package tags

// SonyFaceInfo2Tags contains tag definitions from Image::ExifTool::Sony
var SonyFaceInfo2Tags = TagTable{
	ModuleName: "Sony",
	Tags: map[string]TagDef{
	},
}
