// Code generated by gen-tags. DO NOT EDIT.

package tags

// SonyTag9416Tags contains tag definitions from Image::ExifTool::Sony
var SonyTag9416Tags = TagTable{
	ModuleName: "Sony",
	Tags: map[string]TagDef{
		"0x0006": {
			ID:          "0x0006",
		},
		"0x001D": {
			ID:          "0x001D",
		},
		"0x002B": {
			ID:          "0x002B",
		},
		"0x0070": {
			ID:          "0x0070",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int8u",
		},
		"0x0000": {
			ID:          "0x0000",
		},
	},
}
