// Code generated by gen-tags. DO NOT EDIT.

package tags

// SonyTag9050aTags contains tag definitions from Image::ExifTool::Sony
var SonyTag9050aTags = TagTable{
	ModuleName: "Sony",
	Tags: map[string]TagDef{
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int8u",
		},
		"WRITABLE": {
			ID:          "WRITABLE",
		},
		"DATAMEMBER": {
			ID:          "DATAMEMBER",
		},
	},
}
