// Code generated by gen-tags. DO NOT EDIT.

package tags

// SonyTag9404aTags contains tag definitions from Image::ExifTool::Sony
var SonyTag9404aTags = TagTable{
	ModuleName: "Sony",
	Tags: map[string]TagDef{
		"0x000D": {
			ID:          "0x000D",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int8u",
		},
		"WRITABLE": {
			ID:          "WRITABLE",
		},
		"0x000B": {
			ID:          "0x000B",
		},
	},
}
