// Code generated by gen-tags. DO NOT EDIT.

package tags

// SonyTag9405bTags contains tag definitions from Image::ExifTool::Sony
var SonyTag9405bTags = TagTable{
	ModuleName: "Sony",
	Tags: map[string]TagDef{
		"0x0046": {
			ID:          "0x0046",
		},
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"WRITABLE": {
			ID:          "WRITABLE",
		},
		"DATAMEMBER": {
			ID:          "DATAMEMBER",
		},
		"0x000A": {
			ID:          "0x000A",
		},
		"0x0024": {
			ID:          "0x0024",
		},
		"0x0048": {
			ID:          "0x0048",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"FORMAT": {
			ID:          "FORMAT",
			Name:        "int8u",
		},
		"PRIORITY": {
			ID:          "PRIORITY",
		},
		"0x0034": {
			ID:          "0x0034",
		},
		"0x003E": {
			ID:          "0x003E",
		},
		"0x0040": {
			ID:          "0x0040",
		},
	},
}
