// Code generated by gen-tags. DO NOT EDIT.

package tags

// SonySR2DataIFDTags contains tag definitions from Image::ExifTool::Sony
var SonySR2DataIFDTags = TagTable{
	ModuleName: "Sony",
	Tags: map[string]TagDef{
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"SET_GROUP1": {
			ID:          "SET_GROUP1",
		},
	},
}
