// Code generated by gen-tags. DO NOT EDIT.

package tags

// SonyrtmdTags contains tag definitions from Image::ExifTool::Sony
var SonyrtmdTags = TagTable{
	ModuleName: "Sony",
	Tags: map[string]TagDef{
		"0xE300": {
			ID:          "0xE300",
		},
		"0xE445": {
			ID:          "0xE445",
		},
		"0x060E": {
			ID:          "0x060E",
		},
		"0x3219": {
			ID:          "0x3219",
		},
		"0x321A": {
			ID:          "0x321A",
		},
		"0x800A": {
			ID:          "0x800A",
		},
		"0x800B": {
			ID:          "0x800B",
		},
		"0x8100": {
			ID:          "0x8100",
		},
		"0x8101": {
			ID:          "0x8101",
		},
		"0x8104": {
			ID:          "0x8104",
		},
		"0x8004": {
			ID:          "0x8004",
		},
		"0x8005": {
			ID:          "0x8005",
		},
		"0x8105": {
			ID:          "0x8105",
		},
		"0x8115": {
			ID:          "0x8115",
		},
		"0xE301": {
			ID:          "0xE301",
		},
		"0xE302": {
			ID:          "0xE302",
		},
		"0xE435": {
			ID:          "0xE435",
		},
		"0xE437": {
			ID:          "0xE437",
		},
		"0x8106": {
			ID:          "0x8106",
		},
		"0x810B": {
			ID:          "0x810B",
		},
		"0x810D": {
			ID:          "0x810D",
		},
		"0xE000": {
			ID:          "0xE000",
		},
		"0x3210": {
			ID:          "0x3210",
		},
		"0x8001": {
			ID:          "0x8001",
		},
	},
}
