// Code generated by gen-tags. DO NOT EDIT.

package tags

// svTranslateTags contains tag definitions from Image::ExifTool::Lang::sv
var svTranslateTags = TagTable{
	ModuleName: "sv",
	Tags: map[string]TagDef{
		"ShootingMode": {
			ID:          "ShootingMode",
			Name:        "Fotograferingsläge",
		},
		"YCbCrSubSampling": {
			ID:          "YCbCrSubSampling",
			Name:        "Subsampling ratio of Y to C",
		},
		"GPSDestLatitudeRef": {
			ID:          "GPSDestLatitudeRef",
			Name:        "Referens för destionationsbredd",
		},
		"GPSDestLongitude": {
			ID:          "GPSDestLongitude",
			Name:        "Destionationslängd",
		},
		"SamplesPerPixel": {
			ID:          "SamplesPerPixel",
			Name:        "Antal komponenter",
		},
		"SerialNumber": {
			ID:          "SerialNumber",
			Name:        "Kamera-ID",
		},
		"CreateDate": {
			ID:          "CreateDate",
			Name:        "Skapat datum",
		},
		"FileSize": {
			ID:          "FileSize",
			Name:        "Filstorlek",
		},
		"Filename": {
			ID:          "Filename",
			Name:        "Filnamn",
		},
		"MaxAperture": {
			ID:          "MaxAperture",
			Name:        "Största bländare",
		},
		"PrimaryChromaticities": {
			ID:          "PrimaryChromaticities",
			Name:        "Kromaticitet för primärfärger",
		},
		"StripByteCounts": {
			ID:          "StripByteCounts",
			Name:        "Byte komprimerade",
		},
		"SubjectLocation": {
			ID:          "SubjectLocation",
			Name:        "Motivets placering",
		},
		"SupplementalCategories": {
			ID:          "SupplementalCategories",
			Name:        "Tilläggskategorier",
		},
		"DeviceSettingDescription": {
			ID:          "DeviceSettingDescription",
			Name:        "Beskrivning av enhetsinställning",
		},
		"FocalLength35efl": {
			ID:          "FocalLength35efl",
			Name:        "Brännvidd (i 35 mm format)",
		},
		"GPSLongitude": {
			ID:          "GPSLongitude",
			Name:        "Längd",
		},
		"Keywords": {
			ID:          "Keywords",
			Name:        "Nyckelord",
		},
		"NoiseReduction": {
			ID:          "NoiseReduction",
			Name:        "Brusreducering",
		},
		"ThumbnailImage": {
			ID:          "ThumbnailImage",
			Name:        "Miniatyr",
		},
		"TransmissionReference": {
			ID:          "TransmissionReference",
			Name:        "Sändningsreferens",
		},
		"WhitePoint": {
			ID:          "WhitePoint",
			Name:        "Vitpunktskromaticitet",
		},
		"ExposureTime": {
			ID:          "ExposureTime",
			Name:        "Exponeringstid",
		},
		"ModifyDate": {
			ID:          "ModifyDate",
			Name:        "Filändringsdatum och -tid",
		},
		"PhotometricInterpretation": {
			ID:          "PhotometricInterpretation",
			Name:        "Pixelsammansättning",
		},
		"SubjectDistance": {
			ID:          "SubjectDistance",
			Name:        "Motivavstånd",
		},
		"Aperture": {
			ID:          "Aperture",
			Name:        "Bländare",
		},
		"Artist": {
			ID:          "Artist",
			Name:        "Upphovsman",
		},
		"Categories": {
			ID:          "Categories",
			Name:        "Kategorier",
		},
		"GPSDateStamp": {
			ID:          "GPSDateStamp",
			Name:        "GPS-datum",
		},
		"SpatialFrequencyResponse": {
			ID:          "SpatialFrequencyResponse",
			Name:        "Frekvensomfång",
		},
		"SubSecTime": {
			ID:          "SubSecTime",
			Name:        "DateTime subseconds",
		},
		"Caption-Abstract": {
			ID:          "Caption-Abstract",
			Name:        "Bildtext",
		},
		"InteropIndex": {
			ID:          "InteropIndex",
			Name:        "Interoperability Identification",
		},
		"CaptionWriter": {
			ID:          "CaptionWriter",
			Name:        "Bildtextredigerare",
		},
		"ComponentsConfiguration": {
			ID:          "ComponentsConfiguration",
			Name:        "Enskilda komponenters betydelse",
		},
		"GPSLatitude": {
			ID:          "GPSLatitude",
			Name:        "Bredd",
		},
		"ExifVersion": {
			ID:          "ExifVersion",
			Name:        "Exif-version",
		},
		"GPSProcessingMethod": {
			ID:          "GPSProcessingMethod",
			Name:        "Namn på GPS-bearbetningsmetod",
		},
		"RowsPerStrip": {
			ID:          "RowsPerStrip",
			Name:        "Antal rader",
		},
		"DateTimeOriginal": {
			ID:          "DateTimeOriginal",
			Name:        "Ursprungligt datum & tid",
		},
		"CFAPattern": {
			ID:          "CFAPattern",
			Name:        "CFA-mönster",
		},
		"DriveMode": {
			ID:          "DriveMode",
			Name:        "Enhetsläge",
		},
		"ExposureIndex": {
			ID:          "ExposureIndex",
			Name:        "Exponeringsindex",
		},
		"FocalLengthIn35mmFormat": {
			ID:          "FocalLengthIn35mmFormat",
			Name:        "Brännvidd för 35 mm-film",
		},
		"GPSDestDistance": {
			ID:          "GPSDestDistance",
			Name:        "Avstånd till destination",
		},
		"Software": {
			ID:          "Software",
			Name:        "Programvara",
		},
		"GPSDestBearingRef": {
			ID:          "GPSDestBearingRef",
			Name:        "Referens för destination",
		},
		"GPSDestLatitude": {
			ID:          "GPSDestLatitude",
			Name:        "Destinationsbredd",
		},
		"UserComment": {
			ID:          "UserComment",
			Name:        "Användarkommentarer",
		},
		"ApertureValue": {
			ID:          "ApertureValue",
			Name:        "Bländare",
		},
		"Country": {
			ID:          "Country",
			Name:        "Land",
		},
		"ExposureCompensation": {
			ID:          "ExposureCompensation",
			Name:        "Exponeringsförskjutning",
		},
		"ImageHeight": {
			ID:          "ImageHeight",
			Name:        "Bildhöjd",
		},
		"InteropVersion": {
			ID:          "InteropVersion",
			Name:        "Interoperability Version",
		},
		"SubSecTimeOriginal": {
			ID:          "SubSecTimeOriginal",
			Name:        "DateTimeOriginal subseconds",
		},
		"GPSImgDirection": {
			ID:          "GPSImgDirection",
			Name:        "Bildriktning",
		},
		"GPSSatellites": {
			ID:          "GPSSatellites",
			Name:        "GPS-satelliter använda för mätning",
		},
		"ShadingCompensation": {
			ID:          "ShadingCompensation",
			Name:        "Skuggkompensering",
		},
		"SubSecTimeDigitized": {
			ID:          "SubSecTimeDigitized",
			Name:        "DateTimeDigitized subseconds",
		},
		"DigitalZoomRatio": {
			ID:          "DigitalZoomRatio",
			Name:        "Digitalt zoomomfång",
		},
		"Author": {
			ID:          "Author",
			Name:        "Upphovsman",
		},
		"CompressedBitsPerPixel": {
			ID:          "CompressedBitsPerPixel",
			Name:        "Bildkomprimeringsläge",
		},
		"GPSTimeStamp": {
			ID:          "GPSTimeStamp",
			Name:        "GPS-tid (atomur)",
		},
		"RecordMode": {
			ID:          "RecordMode",
			Name:        "Inspelningsläge",
		},
		"BitsPerSample": {
			ID:          "BitsPerSample",
			Name:        "Antal bitar per komponent",
		},
		"Lens": {
			ID:          "Lens",
			Name:        "Objektiv",
		},
		"RelatedImageWidth": {
			ID:          "RelatedImageWidth",
			Name:        "Tillhörande bildbredd",
		},
		"State": {
			ID:          "State",
			Name:        "Län",
		},
		"Brightness": {
			ID:          "Brightness",
			Name:        "Ljusstyrka",
		},
		"DateCreated": {
			ID:          "DateCreated",
			Name:        "Skapat datum",
		},
		"Directory": {
			ID:          "Directory",
			Name:        "Filplats",
		},
		"ExifImageWidth": {
			ID:          "ExifImageWidth",
			Name:        "Giltig bildbredd",
		},
		"FileType": {
			ID:          "FileType",
			Name:        "Filtyp",
		},
		"GPSAltitude": {
			ID:          "GPSAltitude",
			Name:        "Höjd",
		},
		"Hue": {
			ID:          "Hue",
			Name:        "Nyans",
		},
		"Instructions": {
			ID:          "Instructions",
			Name:        "Instruktioner",
		},
		"By-line": {
			ID:          "By-line",
			Name:        "Upphovsman",
		},
		"Location": {
			ID:          "Location",
			Name:        "Plats",
		},
		"InteropOffset": {
			ID:          "InteropOffset",
			Name:        "Interoperability tag",
		},
		"StripOffsets": {
			ID:          "StripOffsets",
			Name:        "Plats för bilddata",
		},
		"Writer-Editor": {
			ID:          "Writer-Editor",
			Name:        "Bildtextredigerare",
		},
		"ImageSize": {
			ID:          "ImageSize",
			Name:        "Bildstorlek",
		},
		"Index": {
			ID:          "Index",
			Name:        "Småbilder",
		},
		"LensInfo": {
			ID:          "LensInfo",
			Name:        "Objektivinformation",
		},
		"FNumber": {
			ID:          "FNumber",
			Name:        "Bländare",
		},
		"FileName": {
			ID:          "FileName",
			Name:        "Filnamn",
		},
		"GPSDestBearing": {
			ID:          "GPSDestBearing",
			Name:        "Destination",
		},
		"GPSTrack": {
			ID:          "GPSTrack",
			Name:        "Rörelseriktning",
		},
		"Lightness": {
			ID:          "Lightness",
			Name:        "Ljushet",
		},
		"CopyrightNotice": {
			ID:          "CopyrightNotice",
			Name:        "Copyrightmeddelande",
		},
		"CreationDate": {
			ID:          "CreationDate",
			Name:        "Skapad datum",
		},
		"FileFormat": {
			ID:          "FileFormat",
			Name:        "Format",
		},
		"Opto-ElectricConvFactor": {
			ID:          "Opto-ElectricConvFactor",
			Name:        "Optoelektrisk konverteringsfaktor",
		},
		"FlashpixVersion": {
			ID:          "FlashpixVersion",
			Name:        "Flashpix-version som stöds",
		},
		"Urgency": {
			ID:          "Urgency",
			Name:        "Prioritet",
		},
		"Credit": {
			ID:          "Credit",
			Name:        "Medverkande",
		},
		"GPSVersionID": {
			ID:          "GPSVersionID",
			Name:        "GPS tag version",
		},
		"ISO": {
			ID:          "ISO",
			Name:        "ISO värde",
		},
		"ColorTemperature": {
			ID:          "ColorTemperature",
			Name:        "Färgtemperatur",
		},
		"Gradation": {
			ID:          "Gradation",
			Name:        "Effektfull",
		},
		"Model": {
			ID:          "Model",
			Name:        "Kamera",
		},
		"FlashExposureComp": {
			ID:          "FlashExposureComp",
			Name:        "Blixtkompensering",
		},
		"ExifImageHeight": {
			ID:          "ExifImageHeight",
			Name:        "Giltig bildhöjd",
		},
		"FocusMode": {
			ID:          "FocusMode",
			Name:        "Fokustyp",
		},
		"GPSAreaInformation": {
			ID:          "GPSAreaInformation",
			Name:        "Namn på GPS-område",
		},
		"GPSDOP": {
			ID:          "GPSDOP",
			Name:        "Måttprecision",
		},
		"Headline": {
			ID:          "Headline",
			Name:        "Rubrik",
		},
		"RelatedImageFileFormat": {
			ID:          "RelatedImageFileFormat",
			Name:        "Tillhörande bildfilsformat",
		},
		"Comment": {
			ID:          "Comment",
			Name:        "Kommentar",
		},
		"FrameRate": {
			ID:          "FrameRate",
			Name:        "Bildfrekvens",
		},
		"FrameSize": {
			ID:          "FrameSize",
			Name:        "Bildstorlek",
		},
		"ShutterSpeed": {
			ID:          "ShutterSpeed",
			Name:        "Exponeringstid",
		},
		"SpectralSensitivity": {
			ID:          "SpectralSensitivity",
			Name:        "Spektral känslighet",
		},
		"GPSDestDistanceRef": {
			ID:          "GPSDestDistanceRef",
			Name:        "Referens för avstånd till destination",
		},
		"Province-State": {
			ID:          "Province-State",
			Name:        "Län/provins",
		},
		"SubjectArea": {
			ID:          "SubjectArea",
			Name:        "Motivyta",
		},
		"TransferFunction": {
			ID:          "TransferFunction",
			Name:        "Överföringsfunktion",
		},
		"FocalLength": {
			ID:          "FocalLength",
			Name:        "Brännvidd",
		},
		"Source": {
			ID:          "Source",
			Name:        "Källa",
		},
		"YCbCrCoefficients": {
			ID:          "YCbCrCoefficients",
			Name:        "Koefficienter för färgområdesomvandling",
		},
		"FlashEnergy": {
			ID:          "FlashEnergy",
			Name:        "Blixtenergi",
		},
		"RelatedSoundFile": {
			ID:          "RelatedSoundFile",
			Name:        "Tillhörande ljudfil",
		},
		"RelatedImageHeight": {
			ID:          "RelatedImageHeight",
			Name:        "Tillhörande bildlängd",
		},
		"Copyright": {
			ID:          "Copyright",
			Name:        "Copyright-innehavare",
		},
		"City": {
			ID:          "City",
			Name:        "Ort",
		},
		"ReferenceBlackWhite": {
			ID:          "ReferenceBlackWhite",
			Name:        "Par av svartvita referensvärden",
		},
		"ThumbnailImageSize": {
			ID:          "ThumbnailImageSize",
			Name:        "Miniatyrstorlek",
		},
		"AuthorsPosition": {
			ID:          "AuthorsPosition",
			Name:        "Författarens befattning",
		},
		"Category": {
			ID:          "Category",
			Name:        "Kategorier",
		},
		"ColorFilter": {
			ID:          "ColorFilter",
			Name:        "Färgfilter",
		},
		"GPSMapDatum": {
			ID:          "GPSMapDatum",
			Name:        "Geodetiska mätningsdata använda",
		},
		"ImageUniqueID": {
			ID:          "ImageUniqueID",
			Name:        "Unikt bild-ID",
		},
		"Make": {
			ID:          "Make",
			Name:        "Tillverkare",
		},
		"ShutterSpeedValue": {
			ID:          "ShutterSpeedValue",
			Name:        "Slutartid",
		},
		"Title": {
			ID:          "Title",
			Name:        "Titel",
		},
		"ExifOffset": {
			ID:          "ExifOffset",
			Name:        "IFD-pekare för Exif",
		},
		"FileModifyDate": {
			ID:          "FileModifyDate",
			Name:        "Uppdateringsdatum",
		},
		"GPSImgDirectionRef": {
			ID:          "GPSImgDirectionRef",
			Name:        "Referens för bildriktning",
		},
		"GPSSpeed": {
			ID:          "GPSSpeed",
			Name:        "Hastighet på GPS-mottagare",
		},
		"Country-PrimaryLocationName": {
			ID:          "Country-PrimaryLocationName",
			Name:        "Land",
		},
		"GPSDestLongitudeRef": {
			ID:          "GPSDestLongitudeRef",
			Name:        "Referens för destinationslängd",
		},
		"GPSInfo": {
			ID:          "GPSInfo",
			Name:        "IFD-pekare för GPS-information",
		},
		"ICCProfile": {
			ID:          "ICCProfile",
			Name:        "ICC profil",
		},
		"ImageWidth": {
			ID:          "ImageWidth",
			Name:        "Bildbredd",
		},
		"MakerNotes": {
			ID:          "MakerNotes",
			Name:        "Tillverkare",
		},
	},
}
