// Code generated by gen-tags. DO NOT EDIT.

package tags

// SymbolSymbolTags contains tag definitions from 
var SymbolSymbolTags = TagTable{
	ModuleName: "Symbol",
	Tags: map[string]TagDef{
		"0xC8": {
			ID:          "0xC8",
		},
		"0xCC": {
			ID:          "0xCC",
		},
		"0xD8": {
			ID:          "0xD8",
		},
		"0xF0": {
			ID:          "0xF0",
		},
		"0xA8": {
			ID:          "0xA8",
		},
		"0xB8": {
			ID:          "0xB8",
		},
		"0xE8": {
			ID:          "0xE8",
		},
		"0x88": {
			ID:          "0x88",
		},
		"0xA4": {
			ID:          "0xA4",
		},
		"0xF4": {
			ID:          "0xF4",
		},
		"0x80": {
			ID:          "0x80",
		},
		"0x90": {
			ID:          "0x90",
		},
		"0x9C": {
			ID:          "0x9C",
		},
		"0xA0": {
			ID:          "0xA0",
		},
		"0xC0": {
			ID:          "0xC0",
		},
		"0xD0": {
			ID:          "0xD0",
		},
		"0x8C": {
			ID:          "0x8C",
		},
		"0x94": {
			ID:          "0x94",
		},
		"0xD4": {
			ID:          "0xD4",
		},
		"0xE0": {
			ID:          "0xE0",
		},
		"0xFC": {
			ID:          "0xFC",
		},
		"0xB4": {
			ID:          "0xB4",
		},
		"0x84": {
			ID:          "0x84",
		},
		"0xB0": {
			ID:          "0xB0",
		},
		"0xBC": {
			ID:          "0xBC",
		},
		"0xC4": {
			ID:          "0xC4",
		},
		"0xF8": {
			ID:          "0xF8",
		},
		"0xEC": {
			ID:          "0xEC",
		},
		"0xE4": {
			ID:          "0xE4",
		},
		"0x98": {
			ID:          "0x98",
		},
		"0xDC": {
			ID:          "0xDC",
		},
		"0xAC": {
			ID:          "0xAC",
		},
	},
}
