// Code generated by gen-tags. DO NOT EDIT.

package tags

// TagInfoXMLlangInfoTags contains tag definitions from Image::ExifTool::TagInfoXML
var TagInfoXMLlangInfoTags = TagTable{
	ModuleName: "TagInfoXML",
	Tags: map[string]TagDef{
	},
}
