// Code generated by gen-tags. DO NOT EDIT.

package tags

// TextMainTags contains tag definitions from Image::ExifTool::Text
var TextMainTags = TagTable{
	ModuleName: "Text",
	Tags: map[string]TagDef{
		"Delimiter": {
			ID:          "Delimiter",
		},
		"Quoting": {
			ID:          "Quoting",
		},
		"RowCount": {
			ID:          "RowCount",
		},
		"ColumnCount": {
			ID:          "ColumnCount",
		},
		"MIMEEncoding": {
			ID:          "MIMEEncoding",
		},
		"ByteOrderMark": {
			ID:          "ByteOrderMark",
		},
		"LineCount": {
			ID:          "LineCount",
		},
		"WordCount": {
			ID:          "WordCount",
		},
	},
}
