// Code generated by gen-tags. DO NOT EDIT.

package tags

// TheoraMainTags contains tag definitions from Image::ExifTool::Theora
var TheoraMainTags = TagTable{
	ModuleName: "Theora",
	Tags: map[string]TagDef{
	},
}
