// Code generated by gen-tags. DO NOT EDIT.

package tags

// TorrentInfoTags contains tag definitions from Image::ExifTool::Torrent
var TorrentInfoTags = TagTable{
	ModuleName: "Torrent",
	Tags: map[string]TagDef{
		"name.utf-8": {
			ID:          "name.utf-8",
		},
		"piece length": {
			ID:          "piece length",
		},
		"private": {
			ID:          "private",
		},
		"profiles": {
			ID:          "profiles",
		},
		"file-media": {
			ID:          "file-media",
		},
		"files": {
			ID:          "files",
		},
		"md5sum": {
			ID:          "md5sum",
		},
		"name": {
			ID:          "name",
		},
		"file-duration": {
			ID:          "file-duration",
		},
		"length": {
			ID:          "length",
		},
	},
}
