// Code generated by gen-tags. DO NOT EDIT.

package tags

// TrailerGoogleTags contains tag definitions from Image::ExifTool::Trailer
var TrailerGoogleTags = TagTable{
	ModuleName: "Trailer",
	Tags: map[string]TagDef{
		"MotionPhoto": {
			ID:          "MotionPhoto",
		},
		"GainMap": {
			ID:          "GainMap",
		},
		"Depth": {
			ID:          "Depth",
		},
		"Confidence": {
			ID:          "Confidence",
		},
		"android/depthmap": {
			ID:          "android/depthmap",
		},
		"android/confidencemap": {
			ID:          "android/confidencemap",
		},
	},
}
