// Code generated by gen-tags. DO NOT EDIT.

package tags

// TurkishTurkishTags contains tag definitions from 
var TurkishTurkishTags = TagTable{
	ModuleName: "Turkish",
	Tags: map[string]TagDef{
		"0x95": {
			ID:          "0x95",
		},
		"0x99": {
			ID:          "0x99",
		},
		"0x9F": {
			ID:          "0x9F",
		},
		"0xF0": {
			ID:          "0xF0",
		},
		"0x80": {
			ID:          "0x80",
		},
		"0x85": {
			ID:          "0x85",
		},
		"0x89": {
			ID:          "0x89",
		},
		"0x91": {
			ID:          "0x91",
		},
	},
}
