// Code generated by gen-tags. DO NOT EDIT.

package tags

// ValidateexifSpecTags contains tag definitions from Image::ExifTool::Validate
var ValidateexifSpecTags = TagTable{
	ModuleName: "Validate",
	Tags: map[string]TagDef{
		"0xA438": {
			ID:          "0xA438",
		},
		"0xA439": {
			ID:          "0xA439",
		},
		"0x110": {
			ID:          "0x110",
		},
		"0x116": {
			ID:          "0x116",
		},
		"0x11C": {
			ID:          "0x11C",
		},
		"0x128": {
			ID:          "0x128",
		},
		"0x132": {
			ID:          "0x132",
		},
		"0x13F": {
			ID:          "0x13F",
		},
		"0x202": {
			ID:          "0x202",
		},
		"0x212": {
			ID:          "0x212",
		},
		"0x201": {
			ID:          "0x201",
		},
		"0xA437": {
			ID:          "0xA437",
		},
		"0xA43A": {
			ID:          "0xA43A",
		},
		"0xA43C": {
			ID:          "0xA43C",
		},
		"0x106": {
			ID:          "0x106",
		},
		"0x112": {
			ID:          "0x112",
		},
		"0x11A": {
			ID:          "0x11A",
		},
		"0x12D": {
			ID:          "0x12D",
		},
		"0x13B": {
			ID:          "0x13B",
		},
		"0x13E": {
			ID:          "0x13E",
		},
		"0x213": {
			ID:          "0x213",
		},
		"0x101": {
			ID:          "0x101",
		},
		"0x131": {
			ID:          "0x131",
		},
		"0x214": {
			ID:          "0x214",
		},
		"0x115": {
			ID:          "0x115",
		},
		"0x1": {
			ID:          "0x1",
		},
		"0x102": {
			ID:          "0x102",
		},
		"0x10E": {
			ID:          "0x10E",
		},
		"0x117": {
			ID:          "0x117",
		},
		"0x10F": {
			ID:          "0x10F",
		},
		"0x111": {
			ID:          "0x111",
		},
		"0x11B": {
			ID:          "0x11B",
		},
		"0xA43B": {
			ID:          "0xA43B",
		},
		"0x100": {
			ID:          "0x100",
		},
		"0x103": {
			ID:          "0x103",
		},
		"0x211": {
			ID:          "0x211",
		},
		"0xA436": {
			ID:          "0xA436",
		},
	},
}
