// Code generated by gen-tags. DO NOT EDIT.

package tags

// WPGMainTags contains tag definitions from Image::ExifTool::WPG
var WPGMainTags = TagTable{
	ModuleName: "WPG",
	Tags: map[string]TagDef{
		"WPGVersion": {
			ID:          "WPGVersion",
		},
		"ImageWidthInches": {
			ID:          "ImageWidthInches",
		},
		"ImageHeightInches": {
			ID:          "ImageHeightInches",
		},
	},
}
