// Code generated by gen-tags. DO NOT EDIT.

package tags

// XMPexifEXTags contains tag definitions from Image::ExifTool::XMP
var XMPexifEXTags = TagTable{
	ModuleName: "XMP",
	Tags: map[string]TagDef{
		"StandardOutputSensitivity": {
			ID:          "StandardOutputSensitivity",
		},
		"ISOSpeed": {
			ID:          "ISOSpeed",
		},
		"CameraOwnerName": {
			ID:          "CameraOwnerName",
		},
		"WaterDepth": {
			ID:          "WaterDepth",
		},
		"Acceleration": {
			ID:          "Acceleration",
		},
		"ImageUniqueID": {
			ID:          "ImageUniqueID",
		},
		"NAMESPACE": {
			ID:          "NAMESPACE",
			Name:        "exifEX",
		},
		"PhotographicSensitivity": {
			ID:          "PhotographicSensitivity",
		},
		"LensSerialNumber": {
			ID:          "LensSerialNumber",
		},
		"Temperature": {
			ID:          "Temperature",
		},
		"ImageTitle": {
			ID:          "ImageTitle",
		},
		"ImageEditor": {
			ID:          "ImageEditor",
		},
		"Photographer": {
			ID:          "Photographer",
		},
		"CameraFirmware": {
			ID:          "CameraFirmware",
		},
		"RecommendedExposureIndex": {
			ID:          "RecommendedExposureIndex",
		},
		"BodySerialNumber": {
			ID:          "BodySerialNumber",
		},
		"LensMake": {
			ID:          "LensMake",
		},
		"LensModel": {
			ID:          "LensModel",
		},
		"Humidity": {
			ID:          "Humidity",
		},
		"Pressure": {
			ID:          "Pressure",
		},
		"CompositeImageCount": {
			ID:          "CompositeImageCount",
		},
		"CameraElevationAngle": {
			ID:          "CameraElevationAngle",
		},
		"RAWDevelopingSoftware": {
			ID:          "RAWDevelopingSoftware",
		},
		"ImageEditingSoftware": {
			ID:          "ImageEditingSoftware",
		},
		"MetadataEditingSoftware": {
			ID:          "MetadataEditingSoftware",
		},
		"PRIORITY": {
			ID:          "PRIORITY",
		},
		"Gamma": {
			ID:          "Gamma",
		},
	},
}
