// Code generated by gen-tags. DO NOT EDIT.

package tags

// XMPxTags contains tag definitions from Image::ExifTool::XMP
var XMPxTags = TagTable{
	ModuleName: "XMP",
	Tags: map[string]TagDef{
		"NAMESPACE": {
			ID:          "NAMESPACE",
			Name:        "x",
		},
		"xmptk": {
			ID:          "xmptk",
		},
	},
}
