// Code generated by gen-tags. DO NOT EDIT.

package tags

// XMPxmpRightsTags contains tag definitions from Image::ExifTool::XMP
var XMPxmpRightsTags = TagTable{
	ModuleName: "XMP",
	Tags: map[string]TagDef{
		"NAMESPACE": {
			ID:          "NAMESPACE",
			Name:        "xmpRights",
		},
		"Certificate": {
			ID:          "Certificate",
		},
		"Marked": {
			ID:          "Marked",
		},
		"Owner": {
			ID:          "Owner",
		},
		"UsageTerms": {
			ID:          "UsageTerms",
		},
		"WebStatement": {
			ID:          "WebStatement",
		},
	},
}
