// Code generated by gen-tags. DO NOT EDIT.

package tags

// XMPsColorantTags contains tag definitions from Image::ExifTool::XMP
var XMPsColorantTags = TagTable{
	ModuleName: "XMP",
	Tags: map[string]TagDef{
		"yellow": {
			ID:          "yellow",
		},
		"B": {
			ID:          "B",
		},
		"groupType": {
			ID:          "groupType",
		},
		"versionString": {
			ID:          "versionString",
		},
		"LumFeather": {
			ID:          "LumFeather",
		},
		"DepthFeather": {
			ID:          "DepthFeather",
		},
		"Invert": {
			ID:          "Invert",
		},
		"Version": {
			ID:          "Version",
		},
		"L": {
			ID:          "L",
		},
		"swatchName": {
			ID:          "swatchName",
		},
		"mode": {
			ID:          "mode",
		},
		"composite": {
			ID:          "composite",
		},
		"SampleType": {
			ID:          "SampleType",
		},
		"NAMESPACE": {
			ID:          "NAMESPACE",
			Name:        "crs",
		},
		"fontName": {
			ID:          "fontName",
		},
		"fontType": {
			ID:          "fontType",
		},
		"AreaComponents": {
			ID:          "AreaComponents",
		},
		"LumMax": {
			ID:          "LumMax",
		},
		"LuminanceDepthSampleInfo": {
			ID:          "LuminanceDepthSampleInfo",
		},
		"blue": {
			ID:          "blue",
		},
		"gray": {
			ID:          "gray",
		},
		"STRUCT_NAME": {
			ID:          "STRUCT_NAME",
			Name:        "CorrRangeMask",
		},
		"type": {
			ID:          "type",
		},
		"magenta": {
			ID:          "magenta",
		},
		"green": {
			ID:          "green",
		},
		"tint": {
			ID:          "tint",
		},
		"Rows": {
			ID:          "Rows",
		},
		"fontFamily": {
			ID:          "fontFamily",
		},
		"Names": {
			ID:          "Names",
		},
		"Values": {
			ID:          "Values",
		},
		"ColorAmount": {
			ID:          "ColorAmount",
		},
		"DepthMin": {
			ID:          "DepthMin",
		},
		"DepthMax": {
			ID:          "DepthMax",
		},
		"LumRange": {
			ID:          "LumRange",
		},
		"cyan": {
			ID:          "cyan",
		},
		"A": {
			ID:          "A",
		},
		"groupName": {
			ID:          "groupName",
		},
		"childFontFiles": {
			ID:          "childFontFiles",
		},
		"ColorRangeMaskAreaSampleInfo": {
			ID:          "ColorRangeMaskAreaSampleInfo",
		},
		"Type": {
			ID:          "Type",
		},
		"LumMin": {
			ID:          "LumMin",
		},
		"black": {
			ID:          "black",
		},
		"red": {
			ID:          "red",
		},
		"fontFace": {
			ID:          "fontFace",
		},
		"fontFileName": {
			ID:          "fontFileName",
		},
		"Columns": {
			ID:          "Columns",
		},
	},
}
