// Code generated by gen-tags. DO NOT EDIT.

package tags

// XMPMainTags contains tag definitions from Image::ExifTool::XMP
var XMPMainTags = TagTable{
	ModuleName: "XMP",
	Tags: map[string]TagDef{
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
	},
}
