// Code generated by gen-tags. DO NOT EDIT.

package tags

// XMPphotoshopTags contains tag definitions from Image::ExifTool::XMP
var XMPphotoshopTags = TagTable{
	ModuleName: "XMP",
	Tags: map[string]TagDef{
		"NAMESPACE": {
			ID:          "NAMESPACE",
			Name:        "photoshop",
		},
		"AuthorsPosition": {
			ID:          "AuthorsPosition",
		},
		"City": {
			ID:          "City",
		},
		"Credit": {
			ID:          "Credit",
		},
		"History": {
			ID:          "History",
		},
		"Source": {
			ID:          "Source",
		},
		"State": {
			ID:          "State",
		},
		"EmbeddedXMPDigest": {
			ID:          "EmbeddedXMPDigest",
		},
		"DateCreated": {
			ID:          "DateCreated",
		},
		"ICCProfile": {
			ID:          "ICCProfile",
		},
		"Instructions": {
			ID:          "Instructions",
		},
		"SidecarForExtension": {
			ID:          "SidecarForExtension",
		},
		"TransmissionReference": {
			ID:          "TransmissionReference",
		},
		"TABLE_DESC": {
			ID:          "TABLE_DESC",
			Name:        "XMP Photoshop",
		},
		"Category": {
			ID:          "Category",
		},
		"Headline": {
			ID:          "Headline",
		},
		"LegacyIPTCDigest": {
			ID:          "LegacyIPTCDigest",
		},
		"CaptionWriter": {
			ID:          "CaptionWriter",
		},
		"Country": {
			ID:          "Country",
		},
		"SupplementalCategories": {
			ID:          "SupplementalCategories",
		},
	},
}
