// Code generated by gen-tags. DO NOT EDIT.

package tags

// XMPExifToolTags contains tag definitions from Image::ExifTool::XMP
var XMPExifToolTags = TagTable{
	ModuleName: "XMP",
	Tags: map[string]TagDef{
		"OriginalImageHash": {
			ID:          "OriginalImageHash",
		},
		"OriginalImageHashType": {
			ID:          "OriginalImageHashType",
		},
		"OriginalImageMD5": {
			ID:          "OriginalImageMD5",
		},
		"NAMESPACE": {
			ID:          "NAMESPACE",
			Name:        "et",
		},
	},
}
