// Code generated by gen-tags. DO NOT EDIT.

package tags

// XMPlatConvTags contains tag definitions from Image::ExifTool::XMP
var XMPlatConvTags = TagTable{
	ModuleName: "XMP",
	Tags: map[string]TagDef{
		"ValueConv": {
			ID:          "ValueConv",
			Name:        "Image::ExifTool::GPS::ToDegrees($val, 1)",
		},
		"ValueConvInv": {
			ID:          "ValueConvInv",
			Name:        "Image::ExifTool::GPS::ToDMS($self, $val, 2, \"N\")",
		},
		"PrintConv": {
			ID:          "PrintConv",
			Name:        "Image::ExifTool::GPS::ToDMS($self, $val, 1, \"N\")",
		},
		"PrintConvInv": {
			ID:          "PrintConvInv",
			Name:        "Image::ExifTool::GPS::ToDegrees($val, 1, \"lat\")",
		},
	},
}
