// Code generated by gen-tags. DO NOT EDIT.

package tags

// XMPspecialStructTags contains tag definitions from Image::ExifTool::XMP
var XMPspecialStructTags = TagTable{
	ModuleName: "XMP",
	Tags: map[string]TagDef{
		"documentID": {
			ID:          "documentID",
		},
		"manageUI": {
			ID:          "manageUI",
		},
		"comments": {
			ID:          "comments",
		},
		"height": {
			ID:          "height",
		},
		"width": {
			ID:          "width",
		},
		"format": {
			ID:          "format",
		},
		"PageNumber": {
			ID:          "PageNumber",
		},
		"maskMarkers": {
			ID:          "maskMarkers",
		},
		"toPart": {
			ID:          "toPart",
		},
		"placedXResolution": {
			ID:          "placedXResolution",
		},
		"softwareAgent": {
			ID:          "softwareAgent",
		},
		"name": {
			ID:          "name",
		},
		"version": {
			ID:          "version",
		},
		"managerVariant": {
			ID:          "managerVariant",
		},
		"alternatePaths": {
			ID:          "alternatePaths",
		},
		"originalDocumentID": {
			ID:          "originalDocumentID",
		},
		"lastURL": {
			ID:          "lastURL",
		},
		"changed": {
			ID:          "changed",
		},
		"TYPE": {
			ID:          "TYPE",
		},
		"SORT_ORDER": {
			ID:          "SORT_ORDER",
		},
		"lastModifyDate": {
			ID:          "lastModifyDate",
		},
		"action": {
			ID:          "action",
		},
		"NAMESPACE": {
			ID:          "NAMESPACE",
			Name:        "xmpGImg",
		},
		"instanceID": {
			ID:          "instanceID",
		},
		"manageTo": {
			ID:          "manageTo",
		},
		"versionID": {
			ID:          "versionID",
		},
		"linkCategory": {
			ID:          "linkCategory",
		},
		"placedResolutionUnit": {
			ID:          "placedResolutionUnit",
		},
		"id": {
			ID:          "id",
		},
		"NOTES": {
			ID:          "NOTES",
		},
		"manager": {
			ID:          "manager",
		},
		"renditionClass": {
			ID:          "renditionClass",
		},
		"filePath": {
			ID:          "filePath",
		},
		"linkForm": {
			ID:          "linkForm",
		},
		"parameters": {
			ID:          "parameters",
		},
		"modifyDate": {
			ID:          "modifyDate",
		},
		"STRUCT_NAME": {
			ID:          "STRUCT_NAME",
			Name:        "PageInfo",
		},
		"GROUPS": {
			ID:          "GROUPS",
		},
		"renditionParams": {
			ID:          "renditionParams",
		},
		"fromPart": {
			ID:          "fromPart",
		},
		"when": {
			ID:          "when",
		},
		"event": {
			ID:          "event",
		},
		"partMapping": {
			ID:          "partMapping",
		},
		"placedYResolution": {
			ID:          "placedYResolution",
		},
		"url": {
			ID:          "url",
		},
		"modifier": {
			ID:          "modifier",
		},
	},
}
