// Code generated by gen-tags. DO NOT EDIT.

package tags

// XMPxmpTableDefaultsTags contains tag definitions from Image::ExifTool::XMP
var XMPxmpTableDefaultsTags = TagTable{
	ModuleName: "XMP",
	Tags: map[string]TagDef{
		"WRITE_PROC": {
			ID:          "WRITE_PROC",
		},
		"CHECK_PROC": {
			ID:          "CHECK_PROC",
		},
		"WRITABLE": {
			ID:          "WRITABLE",
			Name:        "string",
		},
		"LANG_INFO": {
			ID:          "LANG_INFO",
		},
	},
}
