// Code generated by gen-tags. DO NOT EDIT.

package tags

// XMPdateTimeInfoTags contains tag definitions from Image::ExifTool::XMP
var XMPdateTimeInfoTags = TagTable{
	ModuleName: "XMP",
	Tags: map[string]TagDef{
		"Shift": {
			ID:          "Shift",
			Name:        "Time",
		},
		"Validate": {
			ID:          "Validate",
			Name:        "ValidateXMPDate($val)",
		},
		"PrintConv": {
			ID:          "PrintConv",
			Name:        "$self->ConvertDateTime($val)",
		},
		"PrintConvInv": {
			ID:          "PrintConvInv",
			Name:        "$self->InverseDateTime($val,undef,1)",
		},
		"Writable": {
			ID:          "Writable",
			Name:        "date",
		},
	},
}
