// Code generated by gen-tags. DO NOT EDIT.

package tags

// XMPxmpTags contains tag definitions from Image::ExifTool::XMP
var XMPxmpTags = TagTable{
	ModuleName: "XMP",
	Tags: map[string]TagDef{
		"Identifier": {
			ID:          "Identifier",
		},
		"Label": {
			ID:          "Label",
		},
		"Rating": {
			ID:          "Rating",
		},
		"Title": {
			ID:          "Title",
		},
		"Description": {
			ID:          "Description",
		},
		"NAMESPACE": {
			ID:          "NAMESPACE",
			Name:        "xmp",
		},
		"BaseURL": {
			ID:          "BaseURL",
		},
		"CreatorTool": {
			ID:          "CreatorTool",
		},
		"RatingPercent": {
			ID:          "RatingPercent",
		},
		"Keywords": {
			ID:          "Keywords",
		},
		"Format": {
			ID:          "Format",
		},
		"MetadataDate": {
			ID:          "MetadataDate",
		},
		"ModifyDate": {
			ID:          "ModifyDate",
		},
		"PageInfoImage": {
			ID:          "PageInfoImage",
		},
		"Author": {
			ID:          "Author",
		},
		"Advisory": {
			ID:          "Advisory",
		},
		"Nickname": {
			ID:          "Nickname",
		},
		"CreateDate": {
			ID:          "CreateDate",
		},
	},
}
