// Code generated by gen-tags. DO NOT EDIT.

package tags

// ZIPRARTags contains tag definitions from Image::ExifTool::ZIP
var ZIPRARTags = TagTable{
	ModuleName: "ZIP",
	Tags: map[string]TagDef{
	},
}
